In [1]:
import os
import json
import numpy as np
import polars as pl
import pandas as pd
from ucimlrepo import fetch_ucirepo

import kagglehub
from kagglehub import KaggleDatasetAdapter
# from kaggle.api.kaggle_api_extended import KaggleApi

import mixtabank
from mixtabank.src.utils import dataset_loader,get_df_info_pl, get_df_info_pd

/opt/miniconda3/envs/mixtabank/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## MixTaBank Datasets Loading Walkthrough

Mixtabank datasets dictionary per repository:

In [2]:
# mixtabank.uci_dict
# mixtabank.kaggle_dict

## Kaggle

### Home Credit Default Risk

In [2]:
home_credit_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(name="home-credit", source="kaggle", df_type="polars")

Downloading from https://www.kaggle.com/api/v1/datasets/download/datuman/home-credit-default-risk-train-data-tabular?dataset_version_number=1&file_name=application_train.csv...

100%|██████████| 158M/158M [00:25<00:00, 6.44MB/s]

In [3]:
home_credit_df

shape: (307_511, 122)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ SK_ID_CURR ┆ TARGET ┆ NAME_CONTR ┆ CODE_GEND ┆ … ┆ AMT_REQ_C ┆ AMT_REQ_C ┆ AMT_REQ_C ┆ AMT_REQ_C │
│ ---        ┆ ---    ┆ ACT_TYPE   ┆ ER        ┆   ┆ REDIT_BUR ┆ REDIT_BUR ┆ REDIT_BUR ┆ REDIT_BUR │
│ i64        ┆ i64    ┆ ---        ┆ ---       ┆   ┆ EAU_WEEK  ┆ EAU_MON   ┆ EAU_QRT   ┆ EAU_YEAR  │
│            ┆        ┆ str        ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆        ┆            ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 100002     ┆ 1      ┆ Cash loans ┆ M         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0       │
│ 100003     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 100004     ┆ 0      ┆ Revolving  ┆ M         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│            ┆        ┆ loans      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 100006     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 100007     ┆ 0      ┆ Cash loans ┆ M         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ …          ┆ …      ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 456251     ┆ 0      ┆ Cash loans ┆ M         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 456252     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 456253     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ 0.0       ┆ 1.0       ┆ 0.0       ┆ 1.0       │
│ 456254     ┆ 1      ┆ Cash loans ┆ F         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 456255     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ 0.0       ┆ 2.0       ┆ 0.0       ┆ 1.0       │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [7]:
home_credit_df.select(pl.all().n_unique())

shape: (1, 122)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ SK_ID_CURR ┆ TARGET ┆ NAME_CONTR ┆ CODE_GEND ┆ … ┆ AMT_REQ_C ┆ AMT_REQ_C ┆ AMT_REQ_C ┆ AMT_REQ_C │
│ ---        ┆ ---    ┆ ACT_TYPE   ┆ ER        ┆   ┆ REDIT_BUR ┆ REDIT_BUR ┆ REDIT_BUR ┆ REDIT_BUR │
│ u32        ┆ u32    ┆ ---        ┆ ---       ┆   ┆ EAU_WEEK  ┆ EAU_MON   ┆ EAU_QRT   ┆ EAU_YEAR  │
│            ┆        ┆ u32        ┆ u32       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆        ┆            ┆           ┆   ┆ u32       ┆ u32       ┆ u32       ┆ u32       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 307511     ┆ 2      ┆ 2          ┆ 3         ┆ … ┆ 10        ┆ 25        ┆ 12        ┆ 26        │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [8]:
credit_col_list = [
            "NAME_CONTRACT_TYPE",
            "CODE_GENDER",
            "FLAG_OWN_CAR",
            "FLAG_OWN_REALTY",
            "NAME_TYPE_SUITE",
            "NAME_INCOME_TYPE",
            "NAME_EDUCATION_TYPE",
            "NAME_FAMILY_STATUS",
            "NAME_HOUSING_TYPE",
            "OCCUPATION_TYPE",
            "WEEKDAY_APPR_PROCESS_START",
            "ORGANIZATION_TYPE",
            # 'FONDKAPREMONT_MODE', 'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE',  'EMERGENCYSTATE_MODE', # introduce a lot of nans
            "AMT_INCOME_TOTAL",
            "AMT_CREDIT",
            "AMT_ANNUITY",
            "AMT_GOODS_PRICE",
            "TARGET",
        ]
home_credit_df = home_credit_df[credit_col_list].drop_nulls()
home_credit_df
# home_credit_df = home_credit_df.with_columns(pl.col("TARGET").cast(str))

shape: (210_201, 17)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬────────┐
│ NAME_CONTR ┆ CODE_GENDE ┆ FLAG_OWN_ ┆ FLAG_OWN_ ┆ … ┆ AMT_CREDI ┆ AMT_ANNUI ┆ AMT_GOODS ┆ TARGET │
│ ACT_TYPE   ┆ R          ┆ CAR       ┆ REALTY    ┆   ┆ T         ┆ TY        ┆ _PRICE    ┆ ---    │
│ ---        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ i64    │
│ str        ┆ str        ┆ str       ┆ str       ┆   ┆ f64       ┆ f64       ┆ f64       ┆        │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪════════╡
│ Cash loans ┆ M          ┆ N         ┆ Y         ┆ … ┆ 406597.5  ┆ 24700.5   ┆ 351000.0  ┆ 1      │
│ Cash loans ┆ F          ┆ N         ┆ N         ┆ … ┆ 1293502.5 ┆ 35698.5   ┆ 1.1295e6  ┆ 0      │
│ Revolving  ┆ M          ┆ Y         ┆ Y         ┆ … ┆ 135000.0  ┆ 6750.0    ┆ 135000.0  ┆ 0      │
│ loans      ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆        │
│ Cash loans ┆ F          ┆ N         ┆ Y         ┆ … ┆ 312682.5  ┆ 29686.5   ┆ 297000.0  ┆ 0      │
│ Cash loans ┆ M          ┆ N         ┆ Y         ┆ … ┆ 513000.0  ┆ 21865.5   ┆ 513000.0  ┆ 0      │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …      │
│ Cash loans ┆ F          ┆ N         ┆ Y         ┆ … ┆ 331920.0  ┆ 16096.5   ┆ 225000.0  ┆ 0      │
│ Cash loans ┆ M          ┆ N         ┆ N         ┆ … ┆ 254700.0  ┆ 27558.0   ┆ 225000.0  ┆ 0      │
│ Cash loans ┆ F          ┆ N         ┆ Y         ┆ … ┆ 677664.0  ┆ 29979.0   ┆ 585000.0  ┆ 0      │
│ Cash loans ┆ F          ┆ N         ┆ Y         ┆ … ┆ 370107.0  ┆ 20205.0   ┆ 319500.0  ┆ 1      │
│ Cash loans ┆ F          ┆ N         ┆ N         ┆ … ┆ 675000.0  ┆ 49117.5   ┆ 675000.0  ┆ 0      │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴────────┘

In [10]:
# get_df_info_pl(home_credit_df)

### MIMIC iii

In [2]:
mimic_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(name="mimic-iii", source="kaggle", df_type="polars")

Downloading from https://www.kaggle.com/api/v1/datasets/download/datuman/mimic-iii-tabular-limited-features?dataset_version_number=1&file_name=MIMIC_iii.csv...

100%|██████████| 66.2M/66.2M [00:09<00:00, 7.14MB/s]

In [3]:
mimic_df

shape: (556_617, 11)
┌────────┬─────────────┬─────┬─────────────┬───┬───────────┬─────────────┬─────────────┬───────────┐
│ GENDER ┆ icu_length_ ┆ age ┆ ADMISSION_T ┆ … ┆ ETHNICITY ┆ DIAGNOSIS   ┆ DRUG        ┆ ICD9_CODE │
│ ---    ┆ of_stay     ┆ --- ┆ YPE         ┆   ┆ ---       ┆ ---         ┆ ---         ┆ ---       │
│ str    ┆ ---         ┆ i64 ┆ ---         ┆   ┆ str       ┆ str         ┆ str         ┆ i64       │
│        ┆ i64         ┆     ┆ str         ┆   ┆           ┆             ┆             ┆           │
╞════════╪═════════════╪═════╪═════════════╪═══╪═══════════╪═════════════╪═════════════╪═══════════╡
│ F      ┆ 52          ┆ 74  ┆ EMERGENCY   ┆ … ┆ WHITE     ┆ HUMERAL     ┆ Cefazolin   ┆ 8181      │
│        ┆             ┆     ┆             ┆   ┆           ┆ FRACTURE    ┆             ┆           │
│ F      ┆ 52          ┆ 74  ┆ EMERGENCY   ┆ … ┆ WHITE     ┆ HUMERAL     ┆ Cefazolin   ┆ 9904      │
│        ┆             ┆     ┆             ┆   ┆           ┆ FRACTURE    ┆             ┆           │
│ F      ┆ 52          ┆ 74  ┆ EMERGENCY   ┆ … ┆ WHITE     ┆ HUMERAL     ┆ Magnesium   ┆ 8181      │
│        ┆             ┆     ┆             ┆   ┆           ┆ FRACTURE    ┆ Sulfate     ┆           │
│ F      ┆ 52          ┆ 74  ┆ EMERGENCY   ┆ … ┆ WHITE     ┆ HUMERAL     ┆ Magnesium   ┆ 9904      │
│        ┆             ┆     ┆             ┆   ┆           ┆ FRACTURE    ┆ Sulfate     ┆           │
│ F      ┆ 52          ┆ 74  ┆ EMERGENCY   ┆ … ┆ WHITE     ┆ HUMERAL     ┆ 1/2 NS      ┆ 8181      │
│        ┆             ┆     ┆             ┆   ┆           ┆ FRACTURE    ┆             ┆           │
│ …      ┆ …           ┆ …   ┆ …           ┆ … ┆ …         ┆ …           ┆ …           ┆ …         │
│ F      ┆ 18          ┆ 20  ┆ EMERGENCY   ┆ … ┆ OTHER     ┆ STATUS POST ┆ Morphine    ┆ 8659      │
│        ┆             ┆     ┆             ┆   ┆           ┆ MOTOR       ┆ Sulfate     ┆           │
│        ┆             ┆     ┆             ┆   ┆           ┆ VEHICLE     ┆             ┆           │
│        ┆             ┆     ┆             ┆   ┆           ┆ ACCI…       ┆             ┆           │
│ F      ┆ 18          ┆ 20  ┆ EMERGENCY   ┆ … ┆ OTHER     ┆ STATUS POST ┆ Potassium   ┆ 118       │
│        ┆             ┆     ┆             ┆   ┆           ┆ MOTOR       ┆ Chloride    ┆           │
│        ┆             ┆     ┆             ┆   ┆           ┆ VEHICLE     ┆             ┆           │
│        ┆             ┆     ┆             ┆   ┆           ┆ ACCI…       ┆             ┆           │
│ F      ┆ 18          ┆ 20  ┆ EMERGENCY   ┆ … ┆ OTHER     ┆ STATUS POST ┆ Potassium   ┆ 3891      │
│        ┆             ┆     ┆             ┆   ┆           ┆ MOTOR       ┆ Chloride    ┆           │
│        ┆             ┆     ┆             ┆   ┆           ┆ VEHICLE     ┆             ┆           │
│        ┆             ┆     ┆             ┆   ┆           ┆ ACCI…       ┆             ┆           │
│ F      ┆ 18          ┆ 20  ┆ EMERGENCY   ┆ … ┆ OTHER     ┆ STATUS POST ┆ Potassium   ┆ 3893      │
│        ┆             ┆     ┆             ┆   ┆           ┆ MOTOR       ┆ Chloride    ┆           │
│        ┆             ┆     ┆             ┆   ┆           ┆ VEHICLE     ┆             ┆           │
│        ┆             ┆     ┆             ┆   ┆           ┆ ACCI…       ┆             ┆           │
│ F      ┆ 18          ┆ 20  ┆ EMERGENCY   ┆ … ┆ OTHER     ┆ STATUS POST ┆ Potassium   ┆ 8659      │
│        ┆             ┆     ┆             ┆   ┆           ┆ MOTOR       ┆ Chloride    ┆           │
│        ┆             ┆     ┆             ┆   ┆           ┆ VEHICLE     ┆             ┆           │
│        ┆             ┆     ┆             ┆   ┆           ┆ ACCI…       ┆             ┆           │
└────────┴─────────────┴─────┴─────────────┴───┴───────────┴─────────────┴─────────────┴───────────┘

In [4]:
get_df_info_pl(mimic_df)

DataFrame shape: (556617, 11)
Data types (according to dtypes):
Number of numerical columns: 3:
['icu_length_of_stay', 'age', 'ICD9_CODE']
  - Integer columns: 3: ['icu_length_of_stay', 'age', 'ICD9_CODE']
  - Float columns: 0: []
Number of categorical columns: 8:
['GENDER', 'ADMISSION_TYPE', 'ADMISSION_LOCATION', 'DISCHARGE_LOCATION', 'INSURANCE', 'ETHNICITY', 'DIAGNOSIS', 'DRUG']
  - Multiclass columns: 7: ['ADMISSION_TYPE', 'ADMISSION_LOCATION', 'DISCHARGE_LOCATION', 'INSURANCE', 'ETHNICITY', 'DIAGNOSIS', 'DRUG']
  - Binary columns: 1: ['GENDER']
  - Boolean columns: 0: []
Total categorical cardinality: 693
Total types count:
total numerical: 3 (int: 3, float: 0),
Total categorical: 8 (multi-class: 7, bin_cat: 1, bool_cat: 0):
Columns with missing values: 0

{'dtypes': {'GENDER': 'String',
  'icu_length_of_stay': 'Int64',
  'age': 'Int64',
  'ADMISSION_TYPE': 'String',
  'ADMISSION_LOCATION': 'String',
  'DISCHARGE_LOCATION': 'String',
  'INSURANCE': 'String',
  'ETHNICITY': 'String',
  'DIAGNOSIS': 'String',
  'DRUG': 'String',
  'ICD9_CODE': 'Int64'},
 'shape': (556617, 11),
 'numCols': ['icu_length_of_stay', 'age', 'ICD9_CODE'],
 'numColsTotal': 3,
 'intCols': ['icu_length_of_stay', 'age', 'ICD9_CODE'],
 'intColsTotal': 3,
 'floatCols': [],
 'floatColsTotal': 0,
 'catCols': ['GENDER',
  'ADMISSION_TYPE',
  'ADMISSION_LOCATION',
  'DISCHARGE_LOCATION',
  'INSURANCE',
  'ETHNICITY',
  'DIAGNOSIS',
  'DRUG'],
 'catColsTotal': 8,
 'binCols': ['GENDER'],
 'binColsTotal': 1,
 'boolCols': [],
 'boolColsTotal': 0,
 'cardinality': {'GENDER': 2,
  'ADMISSION_TYPE': 3,
  'ADMISSION_LOCATION': 5,
  'DISCHARGE_LOCATION': 10,
  'INSURANCE': 3,
  'ETHNICITY': 9,
  'DIAGNOSIS': 81,
  'DRUG': 580},
 'total_cardinality': 693,
 'nulls': {'GENDER': 0,
  'icu_length_of_stay': 0,
  'age': 0,
  'ADMISSION_TYPE': 0,
  'ADMISSION_LOCATION': 0,
  'DISCHARGE_LOCATION': 0,
  'INSURANCE': 0,
  'ETHNICITY': 0,
  'DIAGNOSIS': 0,
  'DRUG': 0,
  'ICD9_CODE': 0},
 'missing_pct': {'GENDER': 0.0,
  'icu_length_of_stay': 0.0,
  'age': 0.0,
  'ADMISSION_TYPE': 0.0,
  'ADMISSION_LOCATION': 0.0,
  'DISCHARGE_LOCATION': 0.0,
  'INSURANCE': 0.0,
  'ETHNICITY': 0.0,
  'DIAGNOSIS': 0.0,
  'DRUG': 0.0,
  'ICD9_CODE': 0.0},
 'numeric_stats': {'icu_length_of_stay': {'mean': 88.94343507294963,
   'std': 101.15031488687545,
   'min': 4.0,
   'median': 50.0,
   'max': 849.0,
   'missing': 0},
  'age': {'mean': 64.72196321707746,
   'std': 9.78100819647147,
   'min': 17.0,
   'median': 65.0,
   'max': 300.0,
   'missing': 0},
  'ICD9_CODE': {'mean': 5556.379287732858,
   'std': 3190.606373084053,
   'min': 12.0,
   'median': 4513.0,
   'max': 9962.0,
   'missing': 0}},
 'top_unique': {'GENDER': ['F', 'M'],
  'ADMISSION_TYPE': ['ELECTIVE', 'URGENT', 'EMERGENCY'],
  'ADMISSION_LOCATION': ['EMERGENCY ROOM ADMIT',
   'CLINIC REFERRAL/PREMATURE',
   'PHYS REFERRAL/NORMAL DELI',
   'TRANSFER FROM HOSP/EXTRAM',
   'TRANSFER FROM SKILLED NUR'],
  'DISCHARGE_LOCATION': ['SNF',
   'HOME WITH HOME IV PROVIDR',
   'DEAD/EXPIRED',
   'REHAB/DISTINCT PART HOSP',
   'DISCH-TRAN TO PSYCH HOSP',
   'HOME',
   'ICF',
   'HOSPICE-HOME',
   'LONG TERM CARE HOSPITAL',
   'HOME HEALTH CARE'],
  'INSURANCE': ['Medicaid', 'Private', 'Medicare'],
  'ETHNICITY': ['WHITE',
   'BLACK/AFRICAN AMERICAN',
   'HISPANIC OR LATINO',
   'ASIAN',
   'AMERICAN INDIAN/ALASKA NATIVE FEDERALLY RECOGNIZED TRIBE',
   'UNABLE TO OBTAIN',
   'OTHER',
   'HISPANIC/LATINO - PUERTO RICAN',
   'UNKNOWN/NOT SPECIFIED'],
  'DIAGNOSIS': ['CORONARY ARTERY DISEASE\\CORONARY ARTERY BYPASS GRAFT /SDA',
   'ACUTE RESPIRATORY DISTRESS SYNDROME;ACUTE RENAL FAILURE',
   'STROKE/TIA',
   'SEPSIS',
   'ALCOHOLIC HEPATITIS',
   'PULMONARY EDEMA\\CATH',
   'URINARY TRACT INFECTION;PYELONEPHRITIS',
   'UPPER GI BLEED',
   'TRACHEAL STENOSIS',
   'FACIAL NUMBNESS'],
  'DRUG': ['Folic Acid',
   'Sirolimus',
   'Loperamide HCl',
   'Fluticasone-Salmeterol (100/50)',
   'Sterile Diluent for Flolan',
   'Bacitracin/Polymyxin B Sulfate Opht. Oint',
   'Capsaicin 0.025%',
   'Sterile Water',
   'Nafcillin',
   'Lactated Ringers']}}

### Petfinder_Tab

In [20]:
dataset_path = "datuman/petfinder-adoption-tabular-only-tables"
file_name = "petfinder_tab_processed.csv"

# Load the file directly into a Polars DataFrame
df = kagglehub.dataset_load(KaggleDatasetAdapter.POLARS, dataset_path, file_name).collect()
# get_df_info_pl(df)

Petfinder preprocessing

In [21]:
get_df_info_pl(df)

DataFrame shape: (14993, 18)
Data types (according to dtypes):
Number of numerical columns: 12:
['Age', 'MaturitySize', 'FurLength', 'Vaccinated', 'Dewormed', 'Sterilized', 'Health', 'Quantity', 'Fee', 'VideoAmt', 'PhotoAmt', 'is_adopted']
  - Integer columns: 12: ['Age', 'MaturitySize', 'FurLength', 'Vaccinated', 'Dewormed', 'Sterilized', 'Health', 'Quantity', 'Fee', 'VideoAmt', 'PhotoAmt', 'is_adopted']
  - Float columns: 0: []
Number of categorical columns: 6:
['Type', 'Gender', 'Breed1', 'Color1', 'Color2', 'State']
  - Multiclass columns: 5: ['Gender', 'Breed1', 'Color1', 'Color2', 'State']
  - Binary columns: 1: ['Type']
  - Boolean columns: 0: []
Total categorical cardinality: 208
Total types count:
total numerical: 12 (int: 12, float: 0),
Total categorical: 6 (multi-class: 5, bin_cat: 1, bool_cat: 0):
Columns with missing values: 1

{'dtypes': {'Type': 'String',
  'Gender': 'String',
  'Breed1': 'String',
  'Color1': 'String',
  'Color2': 'String',
  'State': 'String',
  'Age': 'Int64',
  'MaturitySize': 'Int64',
  'FurLength': 'Int64',
  'Vaccinated': 'Int64',
  'Dewormed': 'Int64',
  'Sterilized': 'Int64',
  'Health': 'Int64',
  'Quantity': 'Int64',
  'Fee': 'Int64',
  'VideoAmt': 'Int64',
  'PhotoAmt': 'Int64',
  'is_adopted': 'Int64'},
 'shape': (14993, 18),
 'numCols': ['Age',
  'MaturitySize',
  'FurLength',
  'Vaccinated',
  'Dewormed',
  'Sterilized',
  'Health',
  'Quantity',
  'Fee',
  'VideoAmt',
  'PhotoAmt',
  'is_adopted'],
 'numColsTotal': 12,
 'intCols': ['Age',
  'MaturitySize',
  'FurLength',
  'Vaccinated',
  'Dewormed',
  'Sterilized',
  'Health',
  'Quantity',
  'Fee',
  'VideoAmt',
  'PhotoAmt',
  'is_adopted'],
 'intColsTotal': 12,
 'floatCols': [],
 'floatColsTotal': 0,
 'catCols': ['Type', 'Gender', 'Breed1', 'Color1', 'Color2', 'State'],
 'catColsTotal': 6,
 'binCols': ['Type'],
 'binColsTotal': 1,
 'boolCols': [],
 'boolColsTotal': 0,
 'cardinality': {'Type': 2,
  'Gender': 3,
  'Breed1': 175,
  'Color1': 7,
  'Color2': 7,
  'State': 14},
 'total_cardinality': 208,
 'nulls': {'Type': 0,
  'Gender': 0,
  'Breed1': 17,
  'Color1': 0,
  'Color2': 0,
  'State': 0,
  'Age': 0,
  'MaturitySize': 0,
  'FurLength': 0,
  'Vaccinated': 0,
  'Dewormed': 0,
  'Sterilized': 0,
  'Health': 0,
  'Quantity': 0,
  'Fee': 0,
  'VideoAmt': 0,
  'PhotoAmt': 0,
  'is_adopted': 0},
 'missing_pct': {'Type': 0.0,
  'Gender': 0.0,
  'Breed1': 0.1134,
  'Color1': 0.0,
  'Color2': 0.0,
  'State': 0.0,
  'Age': 0.0,
  'MaturitySize': 0.0,
  'FurLength': 0.0,
  'Vaccinated': 0.0,
  'Dewormed': 0.0,
  'Sterilized': 0.0,
  'Health': 0.0,
  'Quantity': 0.0,
  'Fee': 0.0,
  'VideoAmt': 0.0,
  'PhotoAmt': 0.0,
  'is_adopted': 0.0},
 'numeric_stats': {'Age': {'mean': 10.452077636230241,
   'std': 18.155790407074136,
   'min': 0.0,
   'median': 3.0,
   'max': 255.0,
   'missing': 0},
  'MaturitySize': {'mean': 1.8620022677249384,
   'std': 0.5479589256989323,
   'min': 1.0,
   'median': 2.0,
   'max': 4.0,
   'missing': 0},
  'FurLength': {'mean': 1.467484826252251,
   'std': 0.5990698306593882,
   'min': 1.0,
   'median': 1.0,
   'max': 3.0,
   'missing': 0},
  'Vaccinated': {'mean': 1.7312078970186087,
   'std': 0.6676493026390181,
   'min': 1.0,
   'median': 2.0,
   'max': 3.0,
   'missing': 0},
  'Dewormed': {'mean': 1.5587274061228573,
   'std': 0.6958167290444696,
   'min': 1.0,
   'median': 1.0,
   'max': 3.0,
   'missing': 0},
  'Sterilized': {'mean': 1.9142266390982459,
   'std': 0.5661719328461209,
   'min': 1.0,
   'median': 2.0,
   'max': 3.0,
   'missing': 0},
  'Health': {'mean': 1.0366170879743881,
   'std': 0.19953541603101715,
   'min': 1.0,
   'median': 1.0,
   'max': 3.0,
   'missing': 0},
  'Quantity': {'mean': 1.5760688321216567,
   'std': 1.472477255310576,
   'min': 1.0,
   'median': 1.0,
   'max': 20.0,
   'missing': 0},
  'Fee': {'mean': 21.259987994397385,
   'std': 78.41454767116008,
   'min': 0.0,
   'median': 0.0,
   'max': 3000.0,
   'missing': 0},
  'VideoAmt': {'mean': 0.05675982124991663,
   'std': 0.34618455020973543,
   'min': 0.0,
   'median': 0.0,
   'max': 8.0,
   'missing': 0},
  'PhotoAmt': {'mean': 3.889214966984593,
   'std': 3.487810245436974,
   'min': 0.0,
   'median': 3.0,
   'max': 30.0,
   'missing': 0},
  'is_adopted': {'mean': 0.7200693657039952,
   'std': 0.44897986526606304,
   'min': 0.0,
   'median': 1.0,
   'max': 1.0,
   'missing': 0}},
 'top_unique': {'Type': ['Cat', 'Dog'],
  'Gender': ['Mixed', 'Male', 'Female'],
  'Breed1': ['Wheaten Terrier',
   'Jack Russell Terrier (Parson Russell Terrier)',
   'Snowshoe',
   'Cattle Dog',
   'Sphynx (hairless cat)',
   'Shepherd',
   'Chow Chow',
   'Pug',
   'Greyhound',
   'Akita'],
  'Color1': ['Black', 'Cream', 'Yellow', 'Gray', 'White', 'Brown', 'Golden'],
  'Color2': ['NoColor', 'Gray', 'Yellow', 'Cream', 'White', 'Brown', 'Golden'],
  'State': ['Terengganu',
   'Kelantan',
   'Sarawak',
   'Kuala Lumpur',
   'Pahang',
   'Negeri Sembilan',
   'Pulau Pinang',
   'Sabah',
   'Melaka',
   'Selangor']}}

### Clickstream

In [137]:
 "clickstream":{"uci_id":553,
        "name": "Clickstream Data for Online Retail",
        "repository_url": "https://archive.ics.uci.edu/dataset/553/clickstream+data+for+online+retail",
        "data_url": "https://archive.ics.uci.edu/static/public/553/clickstream+data+for+online+retail.data",
        'target_col': 'buy',
        'prediction_task': 'binary_classification',
        "shape": (287, 13),
    },

SyntaxError: illegal target for annotation (3019678334.py, line 1)

In [ ]:
clickstream_data = fetch_ucirepo(id=NAME_URL_DICT_UCI["clickstream"]["uci_id"])
# target_col_name = "buy"
# prediction_task = "binary_classification"
X = pl.from_pandas(clickstream_data.data.features)
Y = pl.from_pandas(clickstream_data.data.targets)
clickstream = pl.concat([X, Y], how="horizontal")
clickstream

## UCI

In [ ]:
# NAME_URL_DICT_UCI = {
#     "bank-marketing": {
#         "uci_id": 222,
#         "name": "Bank Marketing",
#         "repository_url": "https://archive.ics.uci.edu/dataset/222/bank+marketing",
#         "data_url": "https://archive.ics.uci.edu/static/public/222/data.csv",
#         "target_col": "y",
#         "prediction_task": "binary_classification",
#         "shape": (45211, 17),
#         "types": {"intCols": 7, "floatCols": 10, "boolCols": 1, "catCols": 10},
#     },
#     "adult-census": {
#         "uci_id": 2,
#         "name": "Adult",
#         "repository_url": "https://archive.ics.uci.edu/dataset/2/adult",
#         "data_url": "https://archive.ics.uci.edu/static/public/2/adult.data",
#         "target_col": "income",
#         "prediction_task": "binary_classification",
#         "shape": (48842, 15),
#     },
#     "credit-defualt-taiwan": {
#         "uci_id": 350,
#         "name": "Default of Credit Card Clients",
#         "repository_url": "https://archive.ics.uci.edu/dataset/350/default+of+credit+card+clients",
#         "data_url": "https://archive.ics.uci.edu/static/public/350/default+of+credit+card+clients.data",
#         "target_col": "default payment next month",
#         "prediction_task": "binary_classification",
#         "shape": (30000, 24),
#     },
#     "cdc_diabetes": {
#         "uci_id": 891,
#         "name": "CDC Diabetes Health Indicators",
#         "repository_url": "https://archive.ics.uci.edu/dataset/891/diabetes",
#         "data_url": "https://archive.ics.uci.edu/static/public/891/diabetes.data",
#         "target_col": "Diabetes_binary",
#         "prediction_task": "binary_classification",
#         "shape": (253, 680, 21),
#     },
#     "census-income_full": {
#         "uci_id": 117,
#         "name": "Census Income (KDD)",
#         "repository_url": "https://archive.ics.uci.edu/dataset/117/census+income+kdd",
#         "data_url": "https://archive.ics.uci.edu/static/public/117/census+income+kdd.data",
#         "target_col": "income",
#         "prediction_task": "binary_classification",
#         "shape": (299285, 41),
#     },
#     "support2": {
#         "uci_id": 880,
#         "name": "SUPPORT2",
#         "repository_url": "https://archive.ics.uci.edu/dataset/880/support2",
#         "data_url": "https://archive.ics.uci.edu/static/public/880/support2.data",
#         "target_col": "death",
#         "prediction_task": "binary_classification",
#         "shape": (9105, 21),
#     },
#     "diabetes_130us": {
#         "uci_id": 296,
#         "name": "Diabetes 130-US hospitals for years 1999-2008",
#         "repository_url": "https://archive.ics.uci.edu/dataset/296/diabetes+130-us+hospitals+for+years+1999-2008",
#         "data_url": "https://archive.ics.uci.edu/static/public/296/diabetes+130-us+hospitals+for+years+1999-2008.data",
#         "target_col": "readmitted",
#         "prediction_task": "binary_classification",
#         "shape": (130, 50),
#         "types": {"numCols": 27, "catCols": 23},
#     },
#     "nursery": {
#         "uci_id": 76,
#         "name": "Nursery",
#         "repository_url": "https://archive.ics.uci.edu/dataset/76/nursery",
#         "data_url": "https://archive.ics.uci.edu/dataset/76/nursery.data",
#         "target_col": "class",
#         "prediction_task": "multi_class_classification",
#         "shape": (12960, 8),
#     },
#     "taiwanese_bankruptcy": {
#         "uci_id": 572,
#         "name": "Taiwanese Bankruptcy",
#         "repository_url": "https://archive.ics.uci.edu/dataset/572/taiwanese+bankruptcy+prediction",
#         "data_url": "https://archive.ics.uci.edu/dataset/572/taiwanese+bankruptcy+prediction.data",
#         "target_col": "Bankrupt?",
#         "prediction_task": "binary_classification",
#         "shape": (6819, 96),
#     },
#     "apartment_rent_classified": {
#         "uci_id": 555,
#         "name": "Apartment Rent Classified",
#         "repository_url": "https://archive.ics.uci.edu/dataset/555/apartment+for+rent+classified",
#         "data_url": "https://archive.ics.uci.edu/dataset/555/apartment+for+rent+classified.data",
#         "target_col": ["square_feet", "price"],
#         "prediction_task": "regression",
#         "shape": (99826, 21),
#     },
#     "covertype": {
#         "uci_id": 31,
#         "name": "Covertype",
#         "repository_url": "https://archive.ics.uci.edu/dataset/31/covertype",
#         "data_url": "https://archive.ics.uci.edu/dataset/31/covertype.data",
#         "target_col": "Cover_Type",
#         "prediction_task": "multi_class_classification",
#         "shape": (581012, 55),
#     },
#     # "adult": "https://archive.ics.uci.edu/static/public/2/adult.zip",
#     # "default": "https://archive.ics.uci.edu/static/public/350/default+of+credit+card+clients.zip",
#     # "magic": "https://archive.ics.uci.edu/static/public/159/magic+gamma+telescope.zip",
#     # "shoppers": "https://archive.ics.uci.edu/static/public/468/online+shoppers+purchasing+intention+dataset.zip",
#     # "beijing": "https://archive.ics.uci.edu/static/public/381/beijing+pm2+5+data.zip",
#     # "news": "https://archive.ics.uci.edu/static/public/332/online+news+popularity.zip",
# }

### Bank-Marketing

In [4]:
bank_marketing_df, var_types, target_col_name, prediction_task = dataset_loader(name="bank-marketing", source="uci", df_type="polars")

In [7]:
target_col_name, prediction_task

('y', 'binary_classification')

In [5]:
bank_marketing_df

shape: (45_211, 17)
┌─────┬──────────────┬──────────┬───────────┬───┬───────┬──────────┬──────────┬─────┐
│ age ┆ job          ┆ marital  ┆ education ┆ … ┆ pdays ┆ previous ┆ poutcome ┆ y   │
│ --- ┆ ---          ┆ ---      ┆ ---       ┆   ┆ ---   ┆ ---      ┆ ---      ┆ --- │
│ i64 ┆ str          ┆ str      ┆ str       ┆   ┆ i64   ┆ i64      ┆ str      ┆ str │
╞═════╪══════════════╪══════════╪═══════════╪═══╪═══════╪══════════╪══════════╪═════╡
│ 58  ┆ management   ┆ married  ┆ tertiary  ┆ … ┆ -1    ┆ 0        ┆ null     ┆ no  │
│ 44  ┆ technician   ┆ single   ┆ secondary ┆ … ┆ -1    ┆ 0        ┆ null     ┆ no  │
│ 33  ┆ entrepreneur ┆ married  ┆ secondary ┆ … ┆ -1    ┆ 0        ┆ null     ┆ no  │
│ 47  ┆ blue-collar  ┆ married  ┆ null      ┆ … ┆ -1    ┆ 0        ┆ null     ┆ no  │
│ 33  ┆ null         ┆ single   ┆ null      ┆ … ┆ -1    ┆ 0        ┆ null     ┆ no  │
│ …   ┆ …            ┆ …        ┆ …         ┆ … ┆ …     ┆ …        ┆ …        ┆ …   │
│ 51  ┆ technician   ┆ married  ┆ tertiary  ┆ … ┆ -1    ┆ 0        ┆ null     ┆ yes │
│ 71  ┆ retired      ┆ divorced ┆ primary   ┆ … ┆ -1    ┆ 0        ┆ null     ┆ yes │
│ 72  ┆ retired      ┆ married  ┆ secondary ┆ … ┆ 184   ┆ 3        ┆ success  ┆ yes │
│ 57  ┆ blue-collar  ┆ married  ┆ secondary ┆ … ┆ -1    ┆ 0        ┆ null     ┆ no  │
│ 37  ┆ entrepreneur ┆ married  ┆ secondary ┆ … ┆ 188   ┆ 11       ┆ other    ┆ no  │
└─────┴──────────────┴──────────┴───────────┴───┴───────┴──────────┴──────────┴─────┘

In [6]:
bank_info = get_df_info_pl(bank_marketing_df)

DataFrame shape: (45211, 17)
Data types (according to dtypes):
Number of numerical columns: 7:
['age', 'balance', 'day_of_week', 'duration', 'campaign', 'pdays', 'previous']
  - Integer columns: 7: ['age', 'balance', 'day_of_week', 'duration', 'campaign', 'pdays', 'previous']
  - Float columns: 0: []
Number of categorical columns: 10:
['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome', 'y']
  - Multiclass columns: 6: ['job', 'marital', 'education', 'contact', 'month', 'poutcome']
  - Binary columns: 4: ['default', 'housing', 'loan', 'y']
  - Boolean columns: 0: []
Total categorical cardinality: 46
Total types count:
total numerical: 7 (int: 7, float: 0),
Total categorical: 10 (multi-class: 6, bin_cat: 4, bool_cat: 0):
Columns with missing values: 4

In [51]:
bank_marketing_df.select(bank_info["intCols"]).with_columns(pl.all().unique().count())

shape: (45_211, 7)
┌─────┬─────────┬─────────────┬──────────┬──────────┬───────┬──────────┐
│ age ┆ balance ┆ day_of_week ┆ duration ┆ campaign ┆ pdays ┆ previous │
│ --- ┆ ---     ┆ ---         ┆ ---      ┆ ---      ┆ ---   ┆ ---      │
│ u32 ┆ u32     ┆ u32         ┆ u32      ┆ u32      ┆ u32   ┆ u32      │
╞═════╪═════════╪═════════════╪══════════╪══════════╪═══════╪══════════╡
│ 77  ┆ 7168    ┆ 31          ┆ 1573     ┆ 48       ┆ 559   ┆ 41       │
│ 77  ┆ 7168    ┆ 31          ┆ 1573     ┆ 48       ┆ 559   ┆ 41       │
│ 77  ┆ 7168    ┆ 31          ┆ 1573     ┆ 48       ┆ 559   ┆ 41       │
│ 77  ┆ 7168    ┆ 31          ┆ 1573     ┆ 48       ┆ 559   ┆ 41       │
│ 77  ┆ 7168    ┆ 31          ┆ 1573     ┆ 48       ┆ 559   ┆ 41       │
│ …   ┆ …       ┆ …           ┆ …        ┆ …        ┆ …     ┆ …        │
│ 77  ┆ 7168    ┆ 31          ┆ 1573     ┆ 48       ┆ 559   ┆ 41       │
│ 77  ┆ 7168    ┆ 31          ┆ 1573     ┆ 48       ┆ 559   ┆ 41       │
│ 77  ┆ 7168    ┆ 31          ┆ 1573     ┆ 48       ┆ 559   ┆ 41       │
│ 77  ┆ 7168    ┆ 31          ┆ 1573     ┆ 48       ┆ 559   ┆ 41       │
│ 77  ┆ 7168    ┆ 31          ┆ 1573     ┆ 48       ┆ 559   ┆ 41       │
└─────┴─────────┴─────────────┴──────────┴──────────┴───────┴──────────┘

### Adult

In [8]:
# adult_data = fetch_ucirepo(id=mixtabank.uci_dict["adult-census"]["uci_id"])
# target_col_name = "is_high_income"
# prediction_task = "binary_classification"
# X = pl.from_pandas(adult_data.data.features)
# Y = pl.from_pandas(adult_data.data.targets)
# adult = pl.concat([X, Y], how="horizontal")
adult_census_df, var_types, target_col_name, prediction_task = dataset_loader(name="adult-census", source="uci", df_type="polars")
var_types, target_col_name, prediction_task

({'age': 'Integer',
  'workclass': 'Categorical',
  'fnlwgt': 'Integer',
  'education': 'Categorical',
  'education-num': 'Integer',
  'marital-status': 'Categorical',
  'occupation': 'Categorical',
  'relationship': 'Categorical',
  'race': 'Categorical',
  'sex': 'Binary',
  'capital-gain': 'Integer',
  'capital-loss': 'Integer',
  'hours-per-week': 'Integer',
  'native-country': 'Categorical',
  'income': 'Binary'},
 'income',
 'binary_classification')

In [9]:
adult_census_df

shape: (48_842, 15)
┌─────┬──────────────┬────────┬───────────┬───┬──────────────┬──────────────┬─────────────┬────────┐
│ age ┆ workclass    ┆ fnlwgt ┆ education ┆ … ┆ capital-loss ┆ hours-per-we ┆ native-coun ┆ income │
│ --- ┆ ---          ┆ ---    ┆ ---       ┆   ┆ ---          ┆ ek           ┆ try         ┆ ---    │
│ i64 ┆ str          ┆ i64    ┆ str       ┆   ┆ i64          ┆ ---          ┆ ---         ┆ str    │
│     ┆              ┆        ┆           ┆   ┆              ┆ i64          ┆ str         ┆        │
╞═════╪══════════════╪════════╪═══════════╪═══╪══════════════╪══════════════╪═════════════╪════════╡
│ 39  ┆ State-gov    ┆ 77516  ┆ Bachelors ┆ … ┆ 0            ┆ 40           ┆ United-Stat ┆ <=50K  │
│     ┆              ┆        ┆           ┆   ┆              ┆              ┆ es          ┆        │
│ 50  ┆ Self-emp-not ┆ 83311  ┆ Bachelors ┆ … ┆ 0            ┆ 13           ┆ United-Stat ┆ <=50K  │
│     ┆ -inc         ┆        ┆           ┆   ┆              ┆              ┆ es          ┆        │
│ 38  ┆ Private      ┆ 215646 ┆ HS-grad   ┆ … ┆ 0            ┆ 40           ┆ United-Stat ┆ <=50K  │
│     ┆              ┆        ┆           ┆   ┆              ┆              ┆ es          ┆        │
│ 53  ┆ Private      ┆ 234721 ┆ 11th      ┆ … ┆ 0            ┆ 40           ┆ United-Stat ┆ <=50K  │
│     ┆              ┆        ┆           ┆   ┆              ┆              ┆ es          ┆        │
│ 28  ┆ Private      ┆ 338409 ┆ Bachelors ┆ … ┆ 0            ┆ 40           ┆ Cuba        ┆ <=50K  │
│ …   ┆ …            ┆ …      ┆ …         ┆ … ┆ …            ┆ …            ┆ …           ┆ …      │
│ 39  ┆ Private      ┆ 215419 ┆ Bachelors ┆ … ┆ 0            ┆ 36           ┆ United-Stat ┆ <=50K. │
│     ┆              ┆        ┆           ┆   ┆              ┆              ┆ es          ┆        │
│ 64  ┆ null         ┆ 321403 ┆ HS-grad   ┆ … ┆ 0            ┆ 40           ┆ United-Stat ┆ <=50K. │
│     ┆              ┆        ┆           ┆   ┆              ┆              ┆ es          ┆        │
│ 38  ┆ Private      ┆ 374983 ┆ Bachelors ┆ … ┆ 0            ┆ 50           ┆ United-Stat ┆ <=50K. │
│     ┆              ┆        ┆           ┆   ┆              ┆              ┆ es          ┆        │
│ 44  ┆ Private      ┆ 83891  ┆ Bachelors ┆ … ┆ 0            ┆ 40           ┆ United-Stat ┆ <=50K. │
│     ┆              ┆        ┆           ┆   ┆              ┆              ┆ es          ┆        │
│ 35  ┆ Self-emp-inc ┆ 182148 ┆ Bachelors ┆ … ┆ 0            ┆ 60           ┆ United-Stat ┆ >50K.  │
│     ┆              ┆        ┆           ┆   ┆              ┆              ┆ es          ┆        │
└─────┴──────────────┴────────┴───────────┴───┴──────────────┴──────────────┴─────────────┴────────┘

In [10]:

adult_census_df = adult_census_df.with_columns(pl.when(pl.col("income") == ">50K.").then(1).otherwise(0).alias("is_high_income").cast(str))
adult_census_df = adult_census_df.drop(["income"])  # Drop un-used columns
adult_census_df

shape: (48_842, 15)
┌─────┬─────────────┬────────┬───────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ age ┆ workclass   ┆ fnlwgt ┆ education ┆ … ┆ capital-los ┆ hours-per-w ┆ native-cou ┆ is_high_in │
│ --- ┆ ---         ┆ ---    ┆ ---       ┆   ┆ s           ┆ eek         ┆ ntry       ┆ come       │
│ i64 ┆ str         ┆ i64    ┆ str       ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│     ┆             ┆        ┆           ┆   ┆ i64         ┆ i64         ┆ str        ┆ str        │
╞═════╪═════════════╪════════╪═══════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ 39  ┆ State-gov   ┆ 77516  ┆ Bachelors ┆ … ┆ 0           ┆ 40          ┆ United-Sta ┆ 0          │
│     ┆             ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 50  ┆ Self-emp-no ┆ 83311  ┆ Bachelors ┆ … ┆ 0           ┆ 13          ┆ United-Sta ┆ 0          │
│     ┆ t-inc       ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 38  ┆ Private     ┆ 215646 ┆ HS-grad   ┆ … ┆ 0           ┆ 40          ┆ United-Sta ┆ 0          │
│     ┆             ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 53  ┆ Private     ┆ 234721 ┆ 11th      ┆ … ┆ 0           ┆ 40          ┆ United-Sta ┆ 0          │
│     ┆             ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 28  ┆ Private     ┆ 338409 ┆ Bachelors ┆ … ┆ 0           ┆ 40          ┆ Cuba       ┆ 0          │
│ …   ┆ …           ┆ …      ┆ …         ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ 39  ┆ Private     ┆ 215419 ┆ Bachelors ┆ … ┆ 0           ┆ 36          ┆ United-Sta ┆ 0          │
│     ┆             ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 64  ┆ null        ┆ 321403 ┆ HS-grad   ┆ … ┆ 0           ┆ 40          ┆ United-Sta ┆ 0          │
│     ┆             ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 38  ┆ Private     ┆ 374983 ┆ Bachelors ┆ … ┆ 0           ┆ 50          ┆ United-Sta ┆ 0          │
│     ┆             ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 44  ┆ Private     ┆ 83891  ┆ Bachelors ┆ … ┆ 0           ┆ 40          ┆ United-Sta ┆ 0          │
│     ┆             ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 35  ┆ Self-emp-in ┆ 182148 ┆ Bachelors ┆ … ┆ 0           ┆ 60          ┆ United-Sta ┆ 1          │
│     ┆ c           ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
└─────┴─────────────┴────────┴───────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [14]:
df_info = get_df_info_pl(adult_census_df)
# df_info

DataFrame shape: (48842, 15)
Data types (according to dtypes):
Number of numerical columns: 6:
['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week']
  - Integer columns: 6: ['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week']
  - Float columns: 0: []
Number of categorical columns: 9:
['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country', 'is_high_income']
  - Multiclass columns: 7: ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'native-country']
  - Binary columns: 2: ['sex', 'is_high_income']
  - Boolean columns: 0: []
Total categorical cardinality: 107
Total types count:
total numerical: 6 (int: 6, float: 0),
Total categorical: 9 (multi-class: 7, bin_cat: 2, bool_cat: 0):
Columns with missing values: 3

### Credit-default Taiwan

In [15]:
credit_taiwan_df, var_types, target_col_name, prediction_task = dataset_loader(name="credit-defualt-taiwan", source="uci", df_type="polars")
var_types, target_col_name, prediction_task

({'ID': 'Integer',
  'X1': 'Integer',
  'X2': 'Integer',
  'X3': 'Integer',
  'X4': 'Integer',
  'X5': 'Integer',
  'X6': 'Integer',
  'X7': 'Integer',
  'X8': 'Integer',
  'X9': 'Integer',
  'X10': 'Integer',
  'X11': 'Integer',
  'X12': 'Integer',
  'X13': 'Integer',
  'X14': 'Integer',
  'X15': 'Integer',
  'X16': 'Integer',
  'X17': 'Integer',
  'X18': 'Integer',
  'X19': 'Integer',
  'X20': 'Integer',
  'X21': 'Integer',
  'X22': 'Integer',
  'X23': 'Integer',
  'Y': 'Binary'},
 'default payment next month',
 'binary_classification')

In [16]:
credit_taiwan_df

shape: (30_000, 24)
┌────────┬─────┬─────┬─────┬───┬──────┬───────┬──────┬─────┐
│ X1     ┆ X2  ┆ X3  ┆ X4  ┆ … ┆ X21  ┆ X22   ┆ X23  ┆ Y   │
│ ---    ┆ --- ┆ --- ┆ --- ┆   ┆ ---  ┆ ---   ┆ ---  ┆ --- │
│ i64    ┆ i64 ┆ i64 ┆ i64 ┆   ┆ i64  ┆ i64   ┆ i64  ┆ i64 │
╞════════╪═════╪═════╪═════╪═══╪══════╪═══════╪══════╪═════╡
│ 20000  ┆ 2   ┆ 2   ┆ 1   ┆ … ┆ 0    ┆ 0     ┆ 0    ┆ 1   │
│ 120000 ┆ 2   ┆ 2   ┆ 2   ┆ … ┆ 1000 ┆ 0     ┆ 2000 ┆ 1   │
│ 90000  ┆ 2   ┆ 2   ┆ 2   ┆ … ┆ 1000 ┆ 1000  ┆ 5000 ┆ 0   │
│ 50000  ┆ 2   ┆ 2   ┆ 1   ┆ … ┆ 1100 ┆ 1069  ┆ 1000 ┆ 0   │
│ 50000  ┆ 1   ┆ 2   ┆ 1   ┆ … ┆ 9000 ┆ 689   ┆ 679  ┆ 0   │
│ …      ┆ …   ┆ …   ┆ …   ┆ … ┆ …    ┆ …     ┆ …    ┆ …   │
│ 220000 ┆ 1   ┆ 3   ┆ 1   ┆ … ┆ 3047 ┆ 5000  ┆ 1000 ┆ 0   │
│ 150000 ┆ 1   ┆ 3   ┆ 2   ┆ … ┆ 129  ┆ 0     ┆ 0    ┆ 0   │
│ 30000  ┆ 1   ┆ 2   ┆ 2   ┆ … ┆ 4200 ┆ 2000  ┆ 3100 ┆ 1   │
│ 80000  ┆ 1   ┆ 3   ┆ 1   ┆ … ┆ 1926 ┆ 52964 ┆ 1804 ┆ 1   │
│ 50000  ┆ 1   ┆ 2   ┆ 1   ┆ … ┆ 1000 ┆ 1000  ┆ 1000 ┆ 1   │
└────────┴─────┴─────┴─────┴───┴──────┴───────┴──────┴─────┘

In [18]:
# get_df_info_pl(credit_taiwan_df)

In [84]:
credit_data.metadata["additional_info"]["variable_info"].split("\r\n")

['This research employed a binary variable, default payment (Yes = 1, No = 0), as the response variable. This study reviewed the literature and used the following 23 variables as explanatory variables:',
 'X1: Amount of the given credit (NT dollar): it includes both the individual consumer credit and his/her family (supplementary) credit.',
 'X2: Gender (1 = male; 2 = female).',
 'X3: Education (1 = graduate school; 2 = university; 3 = high school; 4 = others).',
 'X4: Marital status (1 = married; 2 = single; 3 = others).',
 'X5: Age (year).',
 'X6 - X11: History of past payment. We tracked the past monthly payment records (from April to September, 2005) as follows: X6 = the repayment status in September, 2005; X7 = the repayment status in August, 2005; . . .;X11 = the repayment status in April, 2005. The measurement scale for the repayment status is: -1 = pay duly; 1 = payment delay for one month; 2 = payment delay for two months; . . .; 8 = payment delay for eight months; 9 = payment delay for nine months and above.',
 'X12-X17: Amount of bill statement (NT dollar). X12 = amount of bill statement in September, 2005; X13 = amount of bill statement in August, 2005; . . .; X17 = amount of bill statement in April, 2005. ',
 'X18-X23: Amount of previous payment (NT dollar). X18 = amount paid in September, 2005; X19 = amount paid in August, 2005; . . .;X23 = amount paid in April, 2005.',
 '']

In [19]:
col_mapping = {
    "X1": "Credit_Amount",
    "X2": "Gender",
    "X3": "Education_Level",
    "X4": "Marital_Status",
    "X5": "Age",
    "X6": "Pay_0",
    "X7": "Pay_2",
    "X8": "Pay_3",
    "X9": "Pay_4",
    "X10": "Pay_5",
    "X11": "Pay_6",
    "X12": "Bill_Amount1",
    "X13": "Bill_Amount2",
    "X14": "Bill_Amount3",
    "X15": "Bill_Amount4",
    "X16": "Bill_Amount5",
    "X17": "Bill_Amount6",
    "X18": "Pay_Amount1",
    "X19": "Pay_Amount2",
    "X20": "Pay_Amount3",
    "X21": "Pay_Amount4",
    "X22": "Pay_Amount5",
    "X23": "Pay_Amount6",
    "Y": "default",
}

catCols = [
    "Gender",
    "Education_Level",
    "Marital_Status",
    "default",
]


credit_taiwan_df = credit_taiwan_df.rename(col_mapping)
credit_taiwan_df = credit_taiwan_df.with_columns(pl.col(catCols).cast(pl.Utf8))
credit_taiwan_df

shape: (30_000, 24)
┌────────────┬────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬─────────┐
│ Credit_Amo ┆ Gender ┆ Education_ ┆ Marital_St ┆ … ┆ Pay_Amount ┆ Pay_Amoun ┆ Pay_Amoun ┆ default │
│ unt        ┆ ---    ┆ Level      ┆ atus       ┆   ┆ 4          ┆ t5        ┆ t6        ┆ ---     │
│ ---        ┆ str    ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ str     │
│ i64        ┆        ┆ str        ┆ str        ┆   ┆ i64        ┆ i64       ┆ i64       ┆         │
╞════════════╪════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═════════╡
│ 20000      ┆ 2      ┆ 2          ┆ 1          ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 1       │
│ 120000     ┆ 2      ┆ 2          ┆ 2          ┆ … ┆ 1000       ┆ 0         ┆ 2000      ┆ 1       │
│ 90000      ┆ 2      ┆ 2          ┆ 2          ┆ … ┆ 1000       ┆ 1000      ┆ 5000      ┆ 0       │
│ 50000      ┆ 2      ┆ 2          ┆ 1          ┆ … ┆ 1100       ┆ 1069      ┆ 1000      ┆ 0       │
│ 50000      ┆ 1      ┆ 2          ┆ 1          ┆ … ┆ 9000       ┆ 689       ┆ 679       ┆ 0       │
│ …          ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …       │
│ 220000     ┆ 1      ┆ 3          ┆ 1          ┆ … ┆ 3047       ┆ 5000      ┆ 1000      ┆ 0       │
│ 150000     ┆ 1      ┆ 3          ┆ 2          ┆ … ┆ 129        ┆ 0         ┆ 0         ┆ 0       │
│ 30000      ┆ 1      ┆ 2          ┆ 2          ┆ … ┆ 4200       ┆ 2000      ┆ 3100      ┆ 1       │
│ 80000      ┆ 1      ┆ 3          ┆ 1          ┆ … ┆ 1926       ┆ 52964     ┆ 1804      ┆ 1       │
│ 50000      ┆ 1      ┆ 2          ┆ 1          ┆ … ┆ 1000       ┆ 1000      ┆ 1000      ┆ 1       │
└────────────┴────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴─────────┘

In [20]:
get_df_info_pl(credit_taiwan_df)

DataFrame shape: (30000, 24)
Data types (according to dtypes):
Number of numerical columns: 20:
['Credit_Amount', 'Age', 'Pay_0', 'Pay_2', 'Pay_3', 'Pay_4', 'Pay_5', 'Pay_6', 'Bill_Amount1', 'Bill_Amount2', 'Bill_Amount3', 'Bill_Amount4', 'Bill_Amount5', 'Bill_Amount6', 'Pay_Amount1', 'Pay_Amount2', 'Pay_Amount3', 'Pay_Amount4', 'Pay_Amount5', 'Pay_Amount6']
  - Integer columns: 20: ['Credit_Amount', 'Age', 'Pay_0', 'Pay_2', 'Pay_3', 'Pay_4', 'Pay_5', 'Pay_6', 'Bill_Amount1', 'Bill_Amount2', 'Bill_Amount3', 'Bill_Amount4', 'Bill_Amount5', 'Bill_Amount6', 'Pay_Amount1', 'Pay_Amount2', 'Pay_Amount3', 'Pay_Amount4', 'Pay_Amount5', 'Pay_Amount6']
  - Float columns: 0: []
Number of categorical columns: 4:
['Gender', 'Education_Level', 'Marital_Status', 'default']
  - Multiclass columns: 2: ['Education_Level', 'Marital_Status']
  - Binary columns: 2: ['Gender', 'default']
  - Boolean columns: 0: []
Total categorical cardinality: 15
Total types count:
total numerical: 20 (int: 20, float: 0),
Total categorical: 4 (multi-class: 2, bin_cat: 2, bool_cat: 0):
Columns with missing values: 0

{'dtypes': {'Credit_Amount': 'Int64',
  'Gender': 'String',
  'Education_Level': 'String',
  'Marital_Status': 'String',
  'Age': 'Int64',
  'Pay_0': 'Int64',
  'Pay_2': 'Int64',
  'Pay_3': 'Int64',
  'Pay_4': 'Int64',
  'Pay_5': 'Int64',
  'Pay_6': 'Int64',
  'Bill_Amount1': 'Int64',
  'Bill_Amount2': 'Int64',
  'Bill_Amount3': 'Int64',
  'Bill_Amount4': 'Int64',
  'Bill_Amount5': 'Int64',
  'Bill_Amount6': 'Int64',
  'Pay_Amount1': 'Int64',
  'Pay_Amount2': 'Int64',
  'Pay_Amount3': 'Int64',
  'Pay_Amount4': 'Int64',
  'Pay_Amount5': 'Int64',
  'Pay_Amount6': 'Int64',
  'default': 'String'},
 'shape': (30000, 24),
 'numCols': ['Credit_Amount',
  'Age',
  'Pay_0',
  'Pay_2',
  'Pay_3',
  'Pay_4',
  'Pay_5',
  'Pay_6',
  'Bill_Amount1',
  'Bill_Amount2',
  'Bill_Amount3',
  'Bill_Amount4',
  'Bill_Amount5',
  'Bill_Amount6',
  'Pay_Amount1',
  'Pay_Amount2',
  'Pay_Amount3',
  'Pay_Amount4',
  'Pay_Amount5',
  'Pay_Amount6'],
 'numColsTotal': 20,
 'intCols': ['Credit_Amount',
  'Age',
  'Pay_0',
  'Pay_2',
  'Pay_3',
  'Pay_4',
  'Pay_5',
  'Pay_6',
  'Bill_Amount1',
  'Bill_Amount2',
  'Bill_Amount3',
  'Bill_Amount4',
  'Bill_Amount5',
  'Bill_Amount6',
  'Pay_Amount1',
  'Pay_Amount2',
  'Pay_Amount3',
  'Pay_Amount4',
  'Pay_Amount5',
  'Pay_Amount6'],
 'intColsTotal': 20,
 'floatCols': [],
 'floatColsTotal': 0,
 'catCols': ['Gender', 'Education_Level', 'Marital_Status', 'default'],
 'catColsTotal': 4,
 'binCols': ['Gender', 'default'],
 'binColsTotal': 2,
 'boolCols': [],
 'boolColsTotal': 0,
 'cardinality': {'Gender': 2,
  'Education_Level': 7,
  'Marital_Status': 4,
  'default': 2},
 'total_cardinality': 15,
 'nulls': {'Credit_Amount': 0,
  'Gender': 0,
  'Education_Level': 0,
  'Marital_Status': 0,
  'Age': 0,
  'Pay_0': 0,
  'Pay_2': 0,
  'Pay_3': 0,
  'Pay_4': 0,
  'Pay_5': 0,
  'Pay_6': 0,
  'Bill_Amount1': 0,
  'Bill_Amount2': 0,
  'Bill_Amount3': 0,
  'Bill_Amount4': 0,
  'Bill_Amount5': 0,
  'Bill_Amount6': 0,
  'Pay_Amount1': 0,
  'Pay_Amount2': 0,
  'Pay_Amount3': 0,
  'Pay_Amount4': 0,
  'Pay_Amount5': 0,
  'Pay_Amount6': 0,
  'default': 0},
 'missing_pct': {'Credit_Amount': 0.0,
  'Gender': 0.0,
  'Education_Level': 0.0,
  'Marital_Status': 0.0,
  'Age': 0.0,
  'Pay_0': 0.0,
  'Pay_2': 0.0,
  'Pay_3': 0.0,
  'Pay_4': 0.0,
  'Pay_5': 0.0,
  'Pay_6': 0.0,
  'Bill_Amount1': 0.0,
  'Bill_Amount2': 0.0,
  'Bill_Amount3': 0.0,
  'Bill_Amount4': 0.0,
  'Bill_Amount5': 0.0,
  'Bill_Amount6': 0.0,
  'Pay_Amount1': 0.0,
  'Pay_Amount2': 0.0,
  'Pay_Amount3': 0.0,
  'Pay_Amount4': 0.0,
  'Pay_Amount5': 0.0,
  'Pay_Amount6': 0.0,
  'default': 0.0},
 'numeric_stats': {'Credit_Amount': {'mean': 167484.32266666667,
   'std': 129747.6615672024,
   'min': 10000.0,
   'median': 140000.0,
   'max': 1000000.0,
   'missing': 0},
  'Age': {'mean': 35.4855,
   'std': 9.21790406809019,
   'min': 21.0,
   'median': 34.0,
   'max': 79.0,
   'missing': 0},
  'Pay_0': {'mean': -0.0167,
   'std': 1.1238015279973348,
   'min': -2.0,
   'median': 0.0,
   'max': 8.0,
   'missing': 0},
  'Pay_2': {'mean': -0.13376666666666667,
   'std': 1.1971859730345533,
   'min': -2.0,
   'median': 0.0,
   'max': 8.0,
   'missing': 0},
  'Pay_3': {'mean': -0.1662,
   'std': 1.1968675684465733,
   'min': -2.0,
   'median': 0.0,
   'max': 8.0,
   'missing': 0},
  'Pay_4': {'mean': -0.22066666666666668,
   'std': 1.1691386224023368,
   'min': -2.0,
   'median': 0.0,
   'max': 8.0,
   'missing': 0},
  'Pay_5': {'mean': -0.2662,
   'std': 1.1331874060027483,
   'min': -2.0,
   'median': 0.0,
   'max': 8.0,
   'missing': 0},
  'Pay_6': {'mean': -0.2911,
   'std': 1.1499876256079027,
   'min': -2.0,
   'median': 0.0,
   'max': 8.0,
   'missing': 0},
  'Bill_Amount1': {'mean': 51223.3309,
   'std': 73635.86057552954,
   'min': -165580.0,
   'median': 22381.5,
   'max': 964511.0,
   'missing': 0},
  'Bill_Amount2': {'mean': 49179.07516666667,
   'std': 71173.76878252835,
   'min': -69777.0,
   'median': 21200.0,
   'max': 983931.0,
   'missing': 0},
  'Bill_Amount3': {'mean': 47013.1548,
   'std': 69349.3874270368,
   'min': -157264.0,
   'median': 20088.5,
   'max': 1664089.0,
   'missing': 0},
  'Bill_Amount4': {'mean': 43262.94896666666,
   'std': 64332.85613391631,
   'min': -170000.0,
   'median': 19052.0,
   'max': 891586.0,
   'missing': 0},
  'Bill_Amount5': {'mean': 40311.40096666667,
   'std': 60797.155770264864,
   'min': -81334.0,
   'median': 18104.5,
   'max': 927171.0,
   'missing': 0},
  'Bill_Amount6': {'mean': 38871.7604,
   'std': 59554.10753674573,
   'min': -339603.0,
   'median': 17071.0,
   'max': 961664.0,
   'missing': 0},
  'Pay_Amount1': {'mean': 5663.5805,
   'std': 16563.28035402577,
   'min': 0.0,
   'median': 2100.0,
   'max': 873552.0,
   'missing': 0},
  'Pay_Amount2': {'mean': 5921.1635,
   'std': 23040.87040205724,
   'min': 0.0,
   'median': 2009.0,
   'max': 1684259.0,
   'missing': 0},
  'Pay_Amount3': {'mean': 5225.6815,
   'std': 17606.961469803104,
   'min': 0.0,
   'median': 1800.0,
   'max': 896040.0,
   'missing': 0},
  'Pay_Amount4': {'mean': 4826.076866666666,
   'std': 15666.159744032013,
   'min': 0.0,
   'median': 1500.0,
   'max': 621000.0,
   'missing': 0},
  'Pay_Amount5': {'mean': 4799.387633333334,
   'std': 15278.305679144789,
   'min': 0.0,
   'median': 1500.0,
   'max': 426529.0,
   'missing': 0},
  'Pay_Amount6': {'mean': 5215.502566666667,
   'std': 17777.465775435303,
   'min': 0.0,
   'median': 1500.0,
   'max': 528666.0,
   'missing': 0}},
 'top_unique': {'Gender': ['2', '1'],
  'Education_Level': ['0', '2', '6', '4', '1', '3', '5'],
  'Marital_Status': ['1', '2', '3', '0'],
  'default': ['0', '1']}}

### cdc_diabetes

In [4]:
cdc_diabetes_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(name="cdc_diabetes", source="uci", df_type="polars")
cdc_diabetes_df

shape: (253_680, 22)
┌────────┬──────────┬───────────┬─────┬───┬─────┬───────────┬────────┬─────────────────┐
│ HighBP ┆ HighChol ┆ CholCheck ┆ BMI ┆ … ┆ Age ┆ Education ┆ Income ┆ Diabetes_binary │
│ ---    ┆ ---      ┆ ---       ┆ --- ┆   ┆ --- ┆ ---       ┆ ---    ┆ ---             │
│ i64    ┆ i64      ┆ i64       ┆ i64 ┆   ┆ i64 ┆ i64       ┆ i64    ┆ i64             │
╞════════╪══════════╪═══════════╪═════╪═══╪═════╪═══════════╪════════╪═════════════════╡
│ 1      ┆ 1        ┆ 1         ┆ 40  ┆ … ┆ 9   ┆ 4         ┆ 3      ┆ 0               │
│ 0      ┆ 0        ┆ 0         ┆ 25  ┆ … ┆ 7   ┆ 6         ┆ 1      ┆ 0               │
│ 1      ┆ 1        ┆ 1         ┆ 28  ┆ … ┆ 9   ┆ 4         ┆ 8      ┆ 0               │
│ 1      ┆ 0        ┆ 1         ┆ 27  ┆ … ┆ 11  ┆ 3         ┆ 6      ┆ 0               │
│ 1      ┆ 1        ┆ 1         ┆ 24  ┆ … ┆ 11  ┆ 5         ┆ 4      ┆ 0               │
│ …      ┆ …        ┆ …         ┆ …   ┆ … ┆ …   ┆ …         ┆ …      ┆ …               │
│ 1      ┆ 1        ┆ 1         ┆ 45  ┆ … ┆ 5   ┆ 6         ┆ 7      ┆ 0               │
│ 1      ┆ 1        ┆ 1         ┆ 18  ┆ … ┆ 11  ┆ 2         ┆ 4      ┆ 1               │
│ 0      ┆ 0        ┆ 1         ┆ 28  ┆ … ┆ 2   ┆ 5         ┆ 2      ┆ 0               │
│ 1      ┆ 0        ┆ 1         ┆ 23  ┆ … ┆ 7   ┆ 5         ┆ 1      ┆ 0               │
│ 1      ┆ 1        ┆ 1         ┆ 25  ┆ … ┆ 9   ┆ 6         ┆ 2      ┆ 1               │
└────────┴──────────┴───────────┴─────┴───┴─────┴───────────┴────────┴─────────────────┘

In [7]:
# get_df_info_pl(cdc_diabetes_df)

In [13]:
binCols = [k for k,v in  var_types.items() if v=="Binary"]
cdc_diabetes_df = cdc_diabetes_df.with_columns(pl.col(binCols).cast(pl.Utf8))

In [14]:
get_df_info_pl(cdc_diabetes_df)

DataFrame shape: (253680, 22)
Data types (according to dtypes):
Number of numerical columns: 7:
['BMI', 'GenHlth', 'MentHlth', 'PhysHlth', 'Age', 'Education', 'Income']
  - Integer columns: 7: ['BMI', 'GenHlth', 'MentHlth', 'PhysHlth', 'Age', 'Education', 'Income']
  - Float columns: 0: []
Number of categorical columns: 15:
['HighBP', 'HighChol', 'CholCheck', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'DiffWalk', 'Sex', 'Diabetes_binary']
  - Multiclass columns: 0: []
  - Binary columns: 15: ['HighBP', 'HighChol', 'CholCheck', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'DiffWalk', 'Sex', 'Diabetes_binary']
  - Boolean columns: 0: []
Total categorical cardinality: 30
Total types count:
total numerical: 7 (int: 7, float: 0),
Total categorical: 15 (multi-class: 0, bin_cat: 15, bool_cat: 0):
Columns with missing values: 0

{'dtypes': {'HighBP': 'String',
  'HighChol': 'String',
  'CholCheck': 'String',
  'BMI': 'Int64',
  'Smoker': 'String',
  'Stroke': 'String',
  'HeartDiseaseorAttack': 'String',
  'PhysActivity': 'String',
  'Fruits': 'String',
  'Veggies': 'String',
  'HvyAlcoholConsump': 'String',
  'AnyHealthcare': 'String',
  'NoDocbcCost': 'String',
  'GenHlth': 'Int64',
  'MentHlth': 'Int64',
  'PhysHlth': 'Int64',
  'DiffWalk': 'String',
  'Sex': 'String',
  'Age': 'Int64',
  'Education': 'Int64',
  'Income': 'Int64',
  'Diabetes_binary': 'String'},
 'shape': (253680, 22),
 'numCols': ['BMI',
  'GenHlth',
  'MentHlth',
  'PhysHlth',
  'Age',
  'Education',
  'Income'],
 'numColsTotal': 7,
 'intCols': ['BMI',
  'GenHlth',
  'MentHlth',
  'PhysHlth',
  'Age',
  'Education',
  'Income'],
 'intColsTotal': 7,
 'floatCols': [],
 'floatColsTotal': 0,
 'catCols': ['HighBP',
  'HighChol',
  'CholCheck',
  'Smoker',
  'Stroke',
  'HeartDiseaseorAttack',
  'PhysActivity',
  'Fruits',
  'Veggies',
  'HvyAlcoholConsump',
  'AnyHealthcare',
  'NoDocbcCost',
  'DiffWalk',
  'Sex',
  'Diabetes_binary'],
 'catColsTotal': 15,
 'binCols': ['HighBP',
  'HighChol',
  'CholCheck',
  'Smoker',
  'Stroke',
  'HeartDiseaseorAttack',
  'PhysActivity',
  'Fruits',
  'Veggies',
  'HvyAlcoholConsump',
  'AnyHealthcare',
  'NoDocbcCost',
  'DiffWalk',
  'Sex',
  'Diabetes_binary'],
 'binColsTotal': 15,
 'boolCols': [],
 'boolColsTotal': 0,
 'cardinality': {'HighBP': 2,
  'HighChol': 2,
  'CholCheck': 2,
  'Smoker': 2,
  'Stroke': 2,
  'HeartDiseaseorAttack': 2,
  'PhysActivity': 2,
  'Fruits': 2,
  'Veggies': 2,
  'HvyAlcoholConsump': 2,
  'AnyHealthcare': 2,
  'NoDocbcCost': 2,
  'DiffWalk': 2,
  'Sex': 2,
  'Diabetes_binary': 2},
 'total_cardinality': 30,
 'nulls': {'HighBP': 0,
  'HighChol': 0,
  'CholCheck': 0,
  'BMI': 0,
  'Smoker': 0,
  'Stroke': 0,
  'HeartDiseaseorAttack': 0,
  'PhysActivity': 0,
  'Fruits': 0,
  'Veggies': 0,
  'HvyAlcoholConsump': 0,
  'AnyHealthcare': 0,
  'NoDocbcCost': 0,
  'GenHlth': 0,
  'MentHlth': 0,
  'PhysHlth': 0,
  'DiffWalk': 0,
  'Sex': 0,
  'Age': 0,
  'Education': 0,
  'Income': 0,
  'Diabetes_binary': 0},
 'missing_pct': {'HighBP': 0.0,
  'HighChol': 0.0,
  'CholCheck': 0.0,
  'BMI': 0.0,
  'Smoker': 0.0,
  'Stroke': 0.0,
  'HeartDiseaseorAttack': 0.0,
  'PhysActivity': 0.0,
  'Fruits': 0.0,
  'Veggies': 0.0,
  'HvyAlcoholConsump': 0.0,
  'AnyHealthcare': 0.0,
  'NoDocbcCost': 0.0,
  'GenHlth': 0.0,
  'MentHlth': 0.0,
  'PhysHlth': 0.0,
  'DiffWalk': 0.0,
  'Sex': 0.0,
  'Age': 0.0,
  'Education': 0.0,
  'Income': 0.0,
  'Diabetes_binary': 0.0},
 'numeric_stats': {'BMI': {'mean': 28.382363607694735,
   'std': 6.608694201406006,
   'min': 12.0,
   'median': 27.0,
   'max': 98.0,
   'missing': 0},
  'GenHlth': {'mean': 2.5113923052664773,
   'std': 1.0684773622803945,
   'min': 1.0,
   'median': 2.0,
   'max': 5.0,
   'missing': 0},
  'MentHlth': {'mean': 3.1847721538946705,
   'std': 7.412846696196167,
   'min': 0.0,
   'median': 0.0,
   'max': 30.0,
   'missing': 0},
  'PhysHlth': {'mean': 4.2420805739514345,
   'std': 8.71795130717512,
   'min': 0.0,
   'median': 0.0,
   'max': 30.0,
   'missing': 0},
  'Age': {'mean': 8.032119205298013,
   'std': 3.054220434168484,
   'min': 1.0,
   'median': 8.0,
   'max': 13.0,
   'missing': 0},
  'Education': {'mean': 5.050433617155472,
   'std': 0.9857741757276517,
   'min': 1.0,
   'median': 5.0,
   'max': 6.0,
   'missing': 0},
  'Income': {'mean': 6.053874960580258,
   'std': 2.071147566271521,
   'min': 1.0,
   'median': 7.0,
   'max': 8.0,
   'missing': 0}},
 'top_unique': {'HighBP': ['1', '0'],
  'HighChol': ['1', '0'],
  'CholCheck': ['1', '0'],
  'Smoker': ['0', '1'],
  'Stroke': ['0', '1'],
  'HeartDiseaseorAttack': ['0', '1'],
  'PhysActivity': ['1', '0'],
  'Fruits': ['0', '1'],
  'Veggies': ['1', '0'],
  'HvyAlcoholConsump': ['0', '1'],
  'AnyHealthcare': ['1', '0'],
  'NoDocbcCost': ['0', '1'],
  'DiffWalk': ['0', '1'],
  'Sex': ['1', '0'],
  'Diabetes_binary': ['0', '1']}}

In [ ]:
ordinalCols = ["GenHlth", "Education", "Income"]
intCols = ["MentHlth", "PhysHlth", "BMI", "Age"]
binaryCols = [
    "HighBP",
    "HighChol",
    "CholCheck",
    "Smoker",
    "Stroke",
    "HeartDiseaseorAttack",
    "PhysActivity",
    "Fruits",
    "Veggies",
    "HvyAlcoholConsump",
    "AnyHealthcare",
    "NoDocbcCost",
    "DiffWalk",
    "Sex",
    "Diabetes_binary",
]

In [ ]:
len(cdc_diabetes.columns) == len(ordinalCols) + len(intCols) + len(binaryCols)

### Census Income

probably shouldn't not include...

In [15]:
census_income_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(name="census-income_full", source="uci", df_type="polars")
census_income_df

shape: (199_523, 42)
┌──────┬─────────────────────────────────┬────────┬────────┬───┬─────────┬─────────┬──────┬────────┐
│ AAGE ┆ ACLSWKR                         ┆ ADTINK ┆ ADTOCC ┆ … ┆ WKSWORK ┆ AHRSPAY ┆ year ┆ income │
│ ---  ┆ ---                             ┆ ---    ┆ ---    ┆   ┆ ---     ┆ ---     ┆ ---  ┆ ---    │
│ i64  ┆ str                             ┆ i64    ┆ i64    ┆   ┆ i64     ┆ i64     ┆ i64  ┆ str    │
╞══════╪═════════════════════════════════╪════════╪════════╪═══╪═════════╪═════════╪══════╪════════╡
│ 73   ┆  Not in universe                ┆ 0      ┆ 0      ┆ … ┆ 0       ┆ 0       ┆ 95   ┆ -50000 │
│ 58   ┆  Self-employed-not incorporate… ┆ 4      ┆ 34     ┆ … ┆ 52      ┆ 0       ┆ 94   ┆ -50000 │
│ 18   ┆  Not in universe                ┆ 0      ┆ 0      ┆ … ┆ 0       ┆ 0       ┆ 95   ┆ -50000 │
│ 9    ┆  Not in universe                ┆ 0      ┆ 0      ┆ … ┆ 0       ┆ 0       ┆ 94   ┆ -50000 │
│ 10   ┆  Not in universe                ┆ 0      ┆ 0      ┆ … ┆ 0       ┆ 0       ┆ 94   ┆ -50000 │
│ …    ┆ …                               ┆ …      ┆ …      ┆ … ┆ …       ┆ …       ┆ …    ┆ …      │
│ 87   ┆  Not in universe                ┆ 0      ┆ 0      ┆ … ┆ 0       ┆ 0       ┆ 95   ┆ -50000 │
│ 65   ┆  Self-employed-incorporated     ┆ 37     ┆ 2      ┆ … ┆ 52      ┆ 0       ┆ 94   ┆ -50000 │
│ 47   ┆  Not in universe                ┆ 0      ┆ 0      ┆ … ┆ 52      ┆ 0       ┆ 95   ┆ -50000 │
│ 16   ┆  Not in universe                ┆ 0      ┆ 0      ┆ … ┆ 0       ┆ 0       ┆ 95   ┆ -50000 │
│ 32   ┆  Private                        ┆ 42     ┆ 30     ┆ … ┆ 52      ┆ 0       ┆ 94   ┆ -50000 │
└──────┴─────────────────────────────────┴────────┴────────┴───┴─────────┴─────────┴──────┴────────┘

In [17]:
prediction_task

'binary_classification'

In [16]:
get_df_info_pl(census_income_df)

DataFrame shape: (199523, 42)
Data types (according to dtypes):
Number of numerical columns: 13:
['AAGE', 'ADTINK', 'ADTOCC', 'CAPGAIN', 'GAPLOSS', 'DIVVAL', 'MARSUPWRT', 'NOEMP', 'SEOTR', 'VETYN', 'WKSWORK', 'AHRSPAY', 'year']
  - Integer columns: 12: ['AAGE', 'ADTINK', 'ADTOCC', 'CAPGAIN', 'GAPLOSS', 'DIVVAL', 'NOEMP', 'SEOTR', 'VETYN', 'WKSWORK', 'AHRSPAY', 'year']
  - Float columns: 1: ['MARSUPWRT']
Number of categorical columns: 29:
['ACLSWKR', 'AHGA', 'AHSCOL', 'AMARITL', 'AMJIND', 'AMJOCC', 'ARACE', 'AREORGN', 'ASEX', 'AUNMEM', 'AUNTYPE', 'AWKSTAT', 'FILESTAT', 'GRINREG', 'GRINST', 'HHDFMX', 'HHDREL', 'MIGMTR1', 'MIGMTR3', 'MIGMTR4', 'MIGSAME', 'MIGSUN', 'PARENT', 'PEFNTVTY', 'PEMNTVTY', 'PENATVTY', 'PRCITSHP', 'VETQVA', 'income']
  - Multiclass columns: 27: ['ACLSWKR', 'AHGA', 'AHSCOL', 'AMARITL', 'AMJIND', 'AMJOCC', 'ARACE', 'AREORGN', 'AUNMEM', 'AUNTYPE', 'AWKSTAT', 'FILESTAT', 'GRINREG', 'GRINST', 'HHDFMX', 'HHDREL', 'MIGMTR1', 'MIGMTR3', 'MIGMTR4', 'MIGSAME', 'MIGSUN', 'PARENT', 'PEFNTVTY', 'PEMNTVTY', 'PENATVTY', 'PRCITSHP', 'VETQVA']
  - Binary columns: 2: ['ASEX', 'income']
  - Boolean columns: 0: []
Total categorical cardinality: 398
Total types count:
total numerical: 13 (int: 12, float: 1),
Total categorical: 29 (multi-class: 27, bin_cat: 2, bool_cat: 0):
Columns with missing values: 8

{'dtypes': {'AAGE': 'Int64',
  'ACLSWKR': 'String',
  'ADTINK': 'Int64',
  'ADTOCC': 'Int64',
  'AHGA': 'String',
  'AHSCOL': 'String',
  'AMARITL': 'String',
  'AMJIND': 'String',
  'AMJOCC': 'String',
  'ARACE': 'String',
  'AREORGN': 'String',
  'ASEX': 'String',
  'AUNMEM': 'String',
  'AUNTYPE': 'String',
  'AWKSTAT': 'String',
  'CAPGAIN': 'Int64',
  'GAPLOSS': 'Int64',
  'DIVVAL': 'Int64',
  'FILESTAT': 'String',
  'GRINREG': 'String',
  'GRINST': 'String',
  'HHDFMX': 'String',
  'HHDREL': 'String',
  'MARSUPWRT': 'Float64',
  'MIGMTR1': 'String',
  'MIGMTR3': 'String',
  'MIGMTR4': 'String',
  'MIGSAME': 'String',
  'MIGSUN': 'String',
  'NOEMP': 'Int64',
  'PARENT': 'String',
  'PEFNTVTY': 'String',
  'PEMNTVTY': 'String',
  'PENATVTY': 'String',
  'PRCITSHP': 'String',
  'SEOTR': 'Int64',
  'VETQVA': 'String',
  'VETYN': 'Int64',
  'WKSWORK': 'Int64',
  'AHRSPAY': 'Int64',
  'year': 'Int64',
  'income': 'String'},
 'shape': (199523, 42),
 'numCols': ['AAGE',
  'ADTINK',
  'ADTOCC',
  'CAPGAIN',
  'GAPLOSS',
  'DIVVAL',
  'MARSUPWRT',
  'NOEMP',
  'SEOTR',
  'VETYN',
  'WKSWORK',
  'AHRSPAY',
  'year'],
 'numColsTotal': 13,
 'intCols': ['AAGE',
  'ADTINK',
  'ADTOCC',
  'CAPGAIN',
  'GAPLOSS',
  'DIVVAL',
  'NOEMP',
  'SEOTR',
  'VETYN',
  'WKSWORK',
  'AHRSPAY',
  'year'],
 'intColsTotal': 12,
 'floatCols': ['MARSUPWRT'],
 'floatColsTotal': 1,
 'catCols': ['ACLSWKR',
  'AHGA',
  'AHSCOL',
  'AMARITL',
  'AMJIND',
  'AMJOCC',
  'ARACE',
  'AREORGN',
  'ASEX',
  'AUNMEM',
  'AUNTYPE',
  'AWKSTAT',
  'FILESTAT',
  'GRINREG',
  'GRINST',
  'HHDFMX',
  'HHDREL',
  'MIGMTR1',
  'MIGMTR3',
  'MIGMTR4',
  'MIGSAME',
  'MIGSUN',
  'PARENT',
  'PEFNTVTY',
  'PEMNTVTY',
  'PENATVTY',
  'PRCITSHP',
  'VETQVA',
  'income'],
 'catColsTotal': 29,
 'binCols': ['ASEX', 'income'],
 'binColsTotal': 2,
 'boolCols': [],
 'boolColsTotal': 0,
 'cardinality': {'ACLSWKR': 9,
  'AHGA': 17,
  'AHSCOL': 3,
  'AMARITL': 7,
  'AMJIND': 24,
  'AMJOCC': 15,
  'ARACE': 5,
  'AREORGN': 10,
  'ASEX': 2,
  'AUNMEM': 3,
  'AUNTYPE': 6,
  'AWKSTAT': 8,
  'FILESTAT': 6,
  'GRINREG': 6,
  'GRINST': 51,
  'HHDFMX': 38,
  'HHDREL': 8,
  'MIGMTR1': 10,
  'MIGMTR3': 9,
  'MIGMTR4': 10,
  'MIGSAME': 3,
  'MIGSUN': 4,
  'PARENT': 5,
  'PEFNTVTY': 43,
  'PEMNTVTY': 43,
  'PENATVTY': 43,
  'PRCITSHP': 5,
  'VETQVA': 3,
  'income': 2},
 'total_cardinality': 398,
 'nulls': {'AAGE': 0,
  'ACLSWKR': 0,
  'ADTINK': 0,
  'ADTOCC': 0,
  'AHGA': 0,
  'AHSCOL': 0,
  'AMARITL': 0,
  'AMJIND': 0,
  'AMJOCC': 0,
  'ARACE': 0,
  'AREORGN': 0,
  'ASEX': 0,
  'AUNMEM': 0,
  'AUNTYPE': 0,
  'AWKSTAT': 0,
  'CAPGAIN': 0,
  'GAPLOSS': 0,
  'DIVVAL': 0,
  'FILESTAT': 0,
  'GRINREG': 0,
  'GRINST': 708,
  'HHDFMX': 0,
  'HHDREL': 0,
  'MARSUPWRT': 0,
  'MIGMTR1': 99696,
  'MIGMTR3': 99696,
  'MIGMTR4': 99696,
  'MIGSAME': 0,
  'MIGSUN': 99696,
  'NOEMP': 0,
  'PARENT': 0,
  'PEFNTVTY': 6713,
  'PEMNTVTY': 6119,
  'PENATVTY': 3393,
  'PRCITSHP': 0,
  'SEOTR': 0,
  'VETQVA': 0,
  'VETYN': 0,
  'WKSWORK': 0,
  'AHRSPAY': 0,
  'year': 0,
  'income': 0},
 'missing_pct': {'AAGE': 0.0,
  'ACLSWKR': 0.0,
  'ADTINK': 0.0,
  'ADTOCC': 0.0,
  'AHGA': 0.0,
  'AHSCOL': 0.0,
  'AMARITL': 0.0,
  'AMJIND': 0.0,
  'AMJOCC': 0.0,
  'ARACE': 0.0,
  'AREORGN': 0.0,
  'ASEX': 0.0,
  'AUNMEM': 0.0,
  'AUNTYPE': 0.0,
  'AWKSTAT': 0.0,
  'CAPGAIN': 0.0,
  'GAPLOSS': 0.0,
  'DIVVAL': 0.0,
  'FILESTAT': 0.0,
  'GRINREG': 0.0,
  'GRINST': 0.3548,
  'HHDFMX': 0.0,
  'HHDREL': 0.0,
  'MARSUPWRT': 0.0,
  'MIGMTR1': 49.9672,
  'MIGMTR3': 49.9672,
  'MIGMTR4': 49.9672,
  'MIGSAME': 0.0,
  'MIGSUN': 49.9672,
  'NOEMP': 0.0,
  'PARENT': 0.0,
  'PEFNTVTY': 3.3645,
  'PEMNTVTY': 3.0668,
  'PENATVTY': 1.7006,
  'PRCITSHP': 0.0,
  'SEOTR': 0.0,
  'VETQVA': 0.0,
  'VETYN': 0.0,
  'WKSWORK': 0.0,
  'AHRSPAY': 0.0,
  'year': 0.0,
  'income': 0.0},
 'numeric_stats': {'AAGE': {'mean': 34.494198663813194,
   'std': 22.31089520665029,
   'min': 0.0,
   'median': 33.0,
   'max': 90.0,
   'missing': 0},
  'ADTINK': {'mean': 15.352320283877047,
   'std': 18.06712879785797,
   'min': 0.0,
   'median': 0.0,
   'max': 51.0,
   'missing': 0},
  'ADTOCC': {'mean': 11.306556136385279,
   'std': 14.454203916353698,
   'min': 0.0,
   'median': 0.0,
   'max': 46.0,
   'missing': 0},
  'CAPGAIN': {'mean': 434.7189897906507,
   'std': 4697.531279712534,
   'min': 0.0,
   'median': 0.0,
   'max': 99999.0,
   'missing': 0},
  'GAPLOSS': {'mean': 37.313788385298935,
   'std': 271.89642836496506,
   'min': 0.0,
   'median': 0.0,
   'max': 4608.0,
   'missing': 0},
  'DIVVAL': {'mean': 197.52953293605248,
   'std': 1984.1636583823408,
   'min': 0.0,
   'median': 0.0,
   'max': 99999.0,
   'missing': 0},
  'MARSUPWRT': {'mean': 1740.3802692922623,
   'std': 993.7681557874058,
   'min': 37.87,
   'median': 1618.31,
   'max': 18656.3,
   'missing': 0},
  'NOEMP': {'mean': 1.9561804904697704,
   'std': 2.3651255054923563,
   'min': 0.0,
   'median': 1.0,
   'max': 6.0,
   'missing': 0},
  'SEOTR': {'mean': 0.17543842063321022,
   'std': 0.553694399300424,
   'min': 0.0,
   'median': 0.0,
   'max': 2.0,
   'missing': 0},
  'VETYN': {'mean': 1.5148328764102383,
   'std': 0.8514734448628334,
   'min': 0.0,
   'median': 2.0,
   'max': 2.0,
   'missing': 0},
  'WKSWORK': {'mean': 23.174897129654227,
   'std': 24.41148816750421,
   'min': 0.0,
   'median': 8.0,
   'max': 52.0,
   'missing': 0},
  'AHRSPAY': {'mean': 55.426908175999756,
   'std': 274.89645390284187,
   'min': 0.0,
   'median': 0.0,
   'max': 9999.0,
   'missing': 0},
  'year': {'mean': 94.49967171704515,
   'std': 0.5000011452231069,
   'min': 94.0,
   'median': 94.0,
   'max': 95.0,
   'missing': 0}},
 'top_unique': {'ACLSWKR': [' Self-employed-not incorporated',
   ' State government',
   ' Private',
   ' Never worked',
   ' Federal government',
   ' Self-employed-incorporated',
   ' Not in universe',
   ' Without pay',
   ' Local government'],
  'AHGA': [' Bachelors degree(BA AB BS)',
   ' 9th grade',
   ' Associates degree-occup /vocational',
   ' Masters degree(MA MS MEng MEd MSW MBA)',
   ' 11th grade',
   ' 5th or 6th grade',
   ' 1st 2nd 3rd or 4th grade',
   ' 10th grade',
   ' Associates degree-academic program',
   ' 12th grade no diploma'],
  'AHSCOL': [' High school', ' Not in universe', ' College or university'],
  'AMARITL': [' Married-spouse absent',
   ' Separated',
   ' Married-A F spouse present',
   ' Married-civilian spouse present',
   ' Divorced',
   ' Widowed',
   ' Never married'],
  'AMJIND': [' Private household services',
   ' Not in universe or children',
   ' Forestry and fisheries',
   ' Armed Forces',
   ' Retail trade',
   ' Hospital services',
   ' Social services',
   ' Agriculture',
   ' Entertainment',
   ' Public administration'],
  'AMJOCC': [' Sales',
   ' Adm support including clerical',
   ' Protective services',
   ' Technicians and related support',
   ' Professional specialty',
   ' Private household services',
   ' Executive admin and managerial',
   ' Transportation and material moving',
   ' Farming forestry and fishing',
   ' Other service'],
  'ARACE': [' Other',
   ' Black',
   ' Amer Indian Aleut or Eskimo',
   ' Asian or Pacific Islander',
   ' White'],
  'AREORGN': [' NA',
   ' All other',
   ' Central or South American',
   ' Cuban',
   ' Do not know',
   ' Puerto Rican',
   ' Chicano',
   ' Mexican-American',
   ' Other Spanish',
   ' Mexican (Mexicano)'],
  'ASEX': [' Female', ' Male'],
  'AUNMEM': [' No', ' Not in universe', ' Yes'],
  'AUNTYPE': [' Job leaver',
   ' Not in universe',
   ' New entrant',
   ' Job loser - on layoff',
   ' Re-entrant',
   ' Other job loser'],
  'AWKSTAT': [' PT for econ reasons usually PT',
   ' Unemployed part- time',
   ' Children or Armed Forces',
   ' PT for econ reasons usually FT',
   ' PT for non-econ reasons usually FT',
   ' Not in labor force',
   ' Unemployed full-time',
   ' Full-time schedules'],
  'FILESTAT': [' Joint both under 65',
   ' Joint one under 65 & one 65+',
   ' Head of household',
   ' Single',
   ' Nonfiler',
   ' Joint both 65+'],
  'GRINREG': [' West',
   ' Not in universe',
   ' Abroad',
   ' Northeast',
   ' South',
   ' Midwest'],
  'GRINST': [' Pennsylvania',
   ' Massachusetts',
   ' Texas',
   ' Maine',
   ' Louisiana',
   ' Utah',
   ' New Hampshire',
   ' Virginia',
   ' Maryland',
   ' Wyoming'],
  'HHDFMX': [' Child under 18 of RP of unrel subfamily',
   ' In group quarters',
   ' Householder',
   ' Grandchild <18 never marr child of subfamily RP',
   ' Child <18 ever marr RP of subfamily',
   ' Child 18+ never marr RP of subfamily',
   ' Grandchild 18+ never marr RP of subfamily',
   ' RP of unrelated subfamily',
   ' Nonfamily householder',
   ' Grandchild 18+ ever marr RP of subfamily'],
  'HHDREL': [' Spouse of householder',
   ' Child under 18 never married',
   ' Child under 18 ever married',
   ' Other relative of householder',
   ' Nonrelative of householder',
   ' Child 18 or older',
   ' Householder',
   ' Group Quarters- Secondary individual'],
  'MIGMTR1': [' Abroad to MSA',
   ' Abroad to nonMSA',
   ' NonMSA to MSA',
   ' MSA to nonMSA',
   ' Not in universe',
   ' Nonmover',
   ' NonMSA to nonMSA',
   ' Not identifiable',
   ' MSA to MSA',
   None],
  'MIGMTR3': [' Different county same state',
   ' Same county',
   ' Abroad',
   ' Different region',
   None,
   ' Nonmover',
   ' Not in universe',
   ' Different state same division',
   ' Different division same region'],
  'MIGMTR4': [' Abroad',
   ' Different state in Northeast',
   ' Same county',
   ' Different state in Midwest',
   ' Different county same state',
   ' Different state in West',
   ' Not in universe',
   ' Different state in South',
   None,
   ' Nonmover'],
  'MIGSAME': [' Yes', ' No', ' Not in universe under 1 year old'],
  'MIGSUN': [' No', None, ' Yes', ' Not in universe'],
  'PARENT': [' Neither parent present',
   ' Mother only present',
   ' Not in universe',
   ' Both parents present',
   ' Father only present'],
  'PEFNTVTY': [' Jamaica',
   ' Ireland',
   ' Philippines',
   ' Cambodia',
   ' United-States',
   ' Columbia',
   ' Scotland',
   ' Yugoslavia',
   ' South Korea',
   ' Iran'],
  'PEMNTVTY': [' Japan',
   ' El-Salvador',
   ' Poland',
   ' Taiwan',
   ' Puerto-Rico',
   ' Panama',
   ' Philippines',
   ' Haiti',
   ' Italy',
   ' France'],
  'PENATVTY': [' Haiti',
   ' Hungary',
   ' Peru',
   ' Scotland',
   ' Japan',
   ' Portugal',
   ' Dominican-Republic',
   ' Mexico',
   ' China',
   ' Cuba'],
  'PRCITSHP': [' Native- Born abroad of American Parent(s)',
   ' Native- Born in Puerto Rico or U S Outlying',
   ' Foreign born- Not a citizen of U S ',
   ' Foreign born- U S citizen by naturalization',
   ' Native- Born in the United States'],
  'VETQVA': [' Not in universe', ' Yes', ' No'],
  'income': ['-50000', ' 50000+.']}}

### Support2

In [19]:
support2_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(name="support2", source="uci", df_type="polars")
support2_df

shape: (9_105, 45)
┌──────────┬────────┬──────────────┬──────────────┬───┬───────────┬───────┬──────────┬─────────────┐
│ age      ┆ sex    ┆ dzgroup      ┆ dzclass      ┆ … ┆ adlsc     ┆ death ┆ hospdead ┆ sfdm2       │
│ ---      ┆ ---    ┆ ---          ┆ ---          ┆   ┆ ---       ┆ ---   ┆ ---      ┆ ---         │
│ f64      ┆ str    ┆ str          ┆ str          ┆   ┆ f64       ┆ i64   ┆ i64      ┆ str         │
╞══════════╪════════╪══════════════╪══════════════╪═══╪═══════════╪═══════╪══════════╪═════════════╡
│ 62.84998 ┆ male   ┆ Lung Cancer  ┆ Cancer       ┆ … ┆ 7.0       ┆ 0     ┆ 0        ┆ null        │
│ 60.33899 ┆ female ┆ Cirrhosis    ┆ COPD/CHF/Cir ┆ … ┆ 1.0       ┆ 1     ┆ 1        ┆ <2 mo.      │
│          ┆        ┆              ┆ rhosis       ┆   ┆           ┆       ┆          ┆ follow-up   │
│ 52.74698 ┆ female ┆ Cirrhosis    ┆ COPD/CHF/Cir ┆ … ┆ 0.0       ┆ 1     ┆ 0        ┆ <2 mo.      │
│          ┆        ┆              ┆ rhosis       ┆   ┆           ┆       ┆          ┆ follow-up   │
│ 42.38498 ┆ female ┆ Lung Cancer  ┆ Cancer       ┆ … ┆ 0.0       ┆ 1     ┆ 0        ┆ no(M2 and   │
│          ┆        ┆              ┆              ┆   ┆           ┆       ┆          ┆ SIP pres)   │
│ 79.88495 ┆ female ┆ ARF/MOSF     ┆ ARF/MOSF     ┆ … ┆ 2.0       ┆ 0     ┆ 0        ┆ no(M2 and   │
│          ┆        ┆ w/Sepsis     ┆              ┆   ┆           ┆       ┆          ┆ SIP pres)   │
│ …        ┆ …      ┆ …            ┆ …            ┆ … ┆ …         ┆ …     ┆ …        ┆ …           │
│ 66.073   ┆ male   ┆ ARF/MOSF     ┆ ARF/MOSF     ┆ … ┆ 0.0       ┆ 0     ┆ 0        ┆ null        │
│          ┆        ┆ w/Sepsis     ┆              ┆   ┆           ┆       ┆          ┆             │
│ 55.15399 ┆ female ┆ Coma         ┆ Coma         ┆ … ┆ 0.0       ┆ 0     ┆ 0        ┆ null        │
│ 70.38196 ┆ male   ┆ ARF/MOSF     ┆ ARF/MOSF     ┆ … ┆ 2.5253906 ┆ 0     ┆ 0        ┆ null        │
│          ┆        ┆ w/Sepsis     ┆              ┆   ┆           ┆       ┆          ┆             │
│ 47.01999 ┆ male   ┆ MOSF w/Malig ┆ ARF/MOSF     ┆ … ┆ 0.0       ┆ 1     ┆ 1        ┆ <2 mo.      │
│          ┆        ┆              ┆              ┆   ┆           ┆       ┆          ┆ follow-up   │
│ 81.53894 ┆ female ┆ ARF/MOSF     ┆ ARF/MOSF     ┆ … ┆ 0.494751  ┆ 1     ┆ 0        ┆ no(M2 and   │
│          ┆        ┆ w/Sepsis     ┆              ┆   ┆           ┆       ┆          ┆ SIP pres)   │
└──────────┴────────┴──────────────┴──────────────┴───┴───────────┴───────┴──────────┴─────────────┘

In [21]:
# get_df_info_pl(support2_df)

### diabetes_130us

In [22]:
diabetes_130us_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(name="diabetes_130us", source="uci", df_type="polars")
diabetes_130us_df

/opt/miniconda3/envs/mixtabank/lib/python3.13/site-packages/ucimlrepo/fetch.py:97: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_url)

shape: (101_766, 48)
┌───────────────┬────────┬─────────┬────────┬───┬──────────────┬────────┬─────────────┬────────────┐
│ race          ┆ gender ┆ age     ┆ weight ┆ … ┆ metformin-pi ┆ change ┆ diabetesMed ┆ readmitted │
│ ---           ┆ ---    ┆ ---     ┆ ---    ┆   ┆ oglitazone   ┆ ---    ┆ ---         ┆ ---        │
│ str           ┆ str    ┆ str     ┆ str    ┆   ┆ ---          ┆ str    ┆ str         ┆ str        │
│               ┆        ┆         ┆        ┆   ┆ str          ┆        ┆             ┆            │
╞═══════════════╪════════╪═════════╪════════╪═══╪══════════════╪════════╪═════════════╪════════════╡
│ Caucasian     ┆ Female ┆ [0-10)  ┆ null   ┆ … ┆ No           ┆ No     ┆ No          ┆ NO         │
│ Caucasian     ┆ Female ┆ [10-20) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ >30        │
│ AfricanAmeric ┆ Female ┆ [20-30) ┆ null   ┆ … ┆ No           ┆ No     ┆ Yes         ┆ NO         │
│ an            ┆        ┆         ┆        ┆   ┆              ┆        ┆             ┆            │
│ Caucasian     ┆ Male   ┆ [30-40) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ NO         │
│ Caucasian     ┆ Male   ┆ [40-50) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ NO         │
│ …             ┆ …      ┆ …       ┆ …      ┆ … ┆ …            ┆ …      ┆ …           ┆ …          │
│ AfricanAmeric ┆ Male   ┆ [70-80) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ >30        │
│ an            ┆        ┆         ┆        ┆   ┆              ┆        ┆             ┆            │
│ AfricanAmeric ┆ Female ┆ [80-90) ┆ null   ┆ … ┆ No           ┆ No     ┆ Yes         ┆ NO         │
│ an            ┆        ┆         ┆        ┆   ┆              ┆        ┆             ┆            │
│ Caucasian     ┆ Male   ┆ [70-80) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ NO         │
│ Caucasian     ┆ Female ┆ [80-90) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ NO         │
│ Caucasian     ┆ Male   ┆ [70-80) ┆ null   ┆ … ┆ No           ┆ No     ┆ No          ┆ NO         │
└───────────────┴────────┴─────────┴────────┴───┴──────────────┴────────┴─────────────┴────────────┘

In [24]:
diabetes_130us_df.null_count().sum()

shape: (1, 48)
┌──────┬────────┬─────┬────────┬───┬────────────────────────┬────────┬─────────────┬────────────┐
│ race ┆ gender ┆ age ┆ weight ┆ … ┆ metformin-pioglitazone ┆ change ┆ diabetesMed ┆ readmitted │
│ ---  ┆ ---    ┆ --- ┆ ---    ┆   ┆ ---                    ┆ ---    ┆ ---         ┆ ---        │
│ u32  ┆ u32    ┆ u32 ┆ u32    ┆   ┆ u32                    ┆ u32    ┆ u32         ┆ u32        │
╞══════╪════════╪═════╪════════╪═══╪════════════════════════╪════════╪═════════════╪════════════╡
│ 2273 ┆ 0      ┆ 0   ┆ 98569  ┆ … ┆ 0                      ┆ 0      ┆ 0           ┆ 0          │
└──────┴────────┴─────┴────────┴───┴────────────────────────┴────────┴─────────────┴────────────┘

In [26]:
get_df_info_pl(diabetes_130us_df)

DataFrame shape: (101766, 48)
Data types (according to dtypes):
Number of numerical columns: 11:
['admission_type_id', 'discharge_disposition_id', 'admission_source_id', 'time_in_hospital', 'num_lab_procedures', 'num_procedures', 'num_medications', 'number_outpatient', 'number_emergency', 'number_inpatient', 'number_diagnoses']
  - Integer columns: 11: ['admission_type_id', 'discharge_disposition_id', 'admission_source_id', 'time_in_hospital', 'num_lab_procedures', 'num_procedures', 'num_medications', 'number_outpatient', 'number_emergency', 'number_inpatient', 'number_diagnoses']
  - Float columns: 0: []
Number of categorical columns: 37:
['race', 'gender', 'age', 'weight', 'payer_code', 'medical_specialty', 'diag_1', 'diag_2', 'diag_3', 'max_glu_serum', 'A1Cresult', 'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide', 'examide', 'citoglipton', 'insulin', 'glyburide-metformin', 'glipizide-metformin', 'glimepiride-pioglitazone', 'metformin-rosiglitazone', 'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted']
  - Multiclass columns: 26: ['race', 'gender', 'age', 'weight', 'payer_code', 'medical_specialty', 'diag_1', 'diag_2', 'diag_3', 'max_glu_serum', 'A1Cresult', 'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'glipizide', 'glyburide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'tolazamide', 'insulin', 'glyburide-metformin', 'readmitted']
  - Binary columns: 9: ['acetohexamide', 'tolbutamide', 'troglitazone', 'glipizide-metformin', 'glimepiride-pioglitazone', 'metformin-rosiglitazone', 'metformin-pioglitazone', 'change', 'diabetesMed']
  - Boolean columns: 0: []
Total categorical cardinality: 2462
Total types count:
total numerical: 11 (int: 11, float: 0),
Total categorical: 37 (multi-class: 26, bin_cat: 9, bool_cat: 0):
Columns with missing values: 9

{'dtypes': {'race': 'String',
  'gender': 'String',
  'age': 'String',
  'weight': 'String',
  'admission_type_id': 'Int64',
  'discharge_disposition_id': 'Int64',
  'admission_source_id': 'Int64',
  'time_in_hospital': 'Int64',
  'payer_code': 'String',
  'medical_specialty': 'String',
  'num_lab_procedures': 'Int64',
  'num_procedures': 'Int64',
  'num_medications': 'Int64',
  'number_outpatient': 'Int64',
  'number_emergency': 'Int64',
  'number_inpatient': 'Int64',
  'diag_1': 'String',
  'diag_2': 'String',
  'diag_3': 'String',
  'number_diagnoses': 'Int64',
  'max_glu_serum': 'String',
  'A1Cresult': 'String',
  'metformin': 'String',
  'repaglinide': 'String',
  'nateglinide': 'String',
  'chlorpropamide': 'String',
  'glimepiride': 'String',
  'acetohexamide': 'String',
  'glipizide': 'String',
  'glyburide': 'String',
  'tolbutamide': 'String',
  'pioglitazone': 'String',
  'rosiglitazone': 'String',
  'acarbose': 'String',
  'miglitol': 'String',
  'troglitazone': 'String',
  'tolazamide': 'String',
  'examide': 'String',
  'citoglipton': 'String',
  'insulin': 'String',
  'glyburide-metformin': 'String',
  'glipizide-metformin': 'String',
  'glimepiride-pioglitazone': 'String',
  'metformin-rosiglitazone': 'String',
  'metformin-pioglitazone': 'String',
  'change': 'String',
  'diabetesMed': 'String',
  'readmitted': 'String'},
 'shape': (101766, 48),
 'numCols': ['admission_type_id',
  'discharge_disposition_id',
  'admission_source_id',
  'time_in_hospital',
  'num_lab_procedures',
  'num_procedures',
  'num_medications',
  'number_outpatient',
  'number_emergency',
  'number_inpatient',
  'number_diagnoses'],
 'numColsTotal': 11,
 'intCols': ['admission_type_id',
  'discharge_disposition_id',
  'admission_source_id',
  'time_in_hospital',
  'num_lab_procedures',
  'num_procedures',
  'num_medications',
  'number_outpatient',
  'number_emergency',
  'number_inpatient',
  'number_diagnoses'],
 'intColsTotal': 11,
 'floatCols': [],
 'floatColsTotal': 0,
 'catCols': ['race',
  'gender',
  'age',
  'weight',
  'payer_code',
  'medical_specialty',
  'diag_1',
  'diag_2',
  'diag_3',
  'max_glu_serum',
  'A1Cresult',
  'metformin',
  'repaglinide',
  'nateglinide',
  'chlorpropamide',
  'glimepiride',
  'acetohexamide',
  'glipizide',
  'glyburide',
  'tolbutamide',
  'pioglitazone',
  'rosiglitazone',
  'acarbose',
  'miglitol',
  'troglitazone',
  'tolazamide',
  'examide',
  'citoglipton',
  'insulin',
  'glyburide-metformin',
  'glipizide-metformin',
  'glimepiride-pioglitazone',
  'metformin-rosiglitazone',
  'metformin-pioglitazone',
  'change',
  'diabetesMed',
  'readmitted'],
 'catColsTotal': 37,
 'binCols': ['acetohexamide',
  'tolbutamide',
  'troglitazone',
  'glipizide-metformin',
  'glimepiride-pioglitazone',
  'metformin-rosiglitazone',
  'metformin-pioglitazone',
  'change',
  'diabetesMed'],
 'binColsTotal': 9,
 'boolCols': [],
 'boolColsTotal': 0,
 'cardinality': {'race': 6,
  'gender': 3,
  'age': 10,
  'weight': 10,
  'payer_code': 18,
  'medical_specialty': 73,
  'diag_1': 717,
  'diag_2': 749,
  'diag_3': 790,
  'max_glu_serum': 4,
  'A1Cresult': 4,
  'metformin': 4,
  'repaglinide': 4,
  'nateglinide': 4,
  'chlorpropamide': 4,
  'glimepiride': 4,
  'acetohexamide': 2,
  'glipizide': 4,
  'glyburide': 4,
  'tolbutamide': 2,
  'pioglitazone': 4,
  'rosiglitazone': 4,
  'acarbose': 4,
  'miglitol': 4,
  'troglitazone': 2,
  'tolazamide': 3,
  'examide': 1,
  'citoglipton': 1,
  'insulin': 4,
  'glyburide-metformin': 4,
  'glipizide-metformin': 2,
  'glimepiride-pioglitazone': 2,
  'metformin-rosiglitazone': 2,
  'metformin-pioglitazone': 2,
  'change': 2,
  'diabetesMed': 2,
  'readmitted': 3},
 'total_cardinality': 2462,
 'nulls': {'race': 2273,
  'gender': 0,
  'age': 0,
  'weight': 98569,
  'admission_type_id': 0,
  'discharge_disposition_id': 0,
  'admission_source_id': 0,
  'time_in_hospital': 0,
  'payer_code': 40256,
  'medical_specialty': 49949,
  'num_lab_procedures': 0,
  'num_procedures': 0,
  'num_medications': 0,
  'number_outpatient': 0,
  'number_emergency': 0,
  'number_inpatient': 0,
  'diag_1': 21,
  'diag_2': 358,
  'diag_3': 1423,
  'number_diagnoses': 0,
  'max_glu_serum': 96420,
  'A1Cresult': 84748,
  'metformin': 0,
  'repaglinide': 0,
  'nateglinide': 0,
  'chlorpropamide': 0,
  'glimepiride': 0,
  'acetohexamide': 0,
  'glipizide': 0,
  'glyburide': 0,
  'tolbutamide': 0,
  'pioglitazone': 0,
  'rosiglitazone': 0,
  'acarbose': 0,
  'miglitol': 0,
  'troglitazone': 0,
  'tolazamide': 0,
  'examide': 0,
  'citoglipton': 0,
  'insulin': 0,
  'glyburide-metformin': 0,
  'glipizide-metformin': 0,
  'glimepiride-pioglitazone': 0,
  'metformin-rosiglitazone': 0,
  'metformin-pioglitazone': 0,
  'change': 0,
  'diabetesMed': 0,
  'readmitted': 0},
 'missing_pct': {'race': 2.2336,
  'gender': 0.0,
  'age': 0.0,
  'weight': 96.8585,
  'admission_type_id': 0.0,
  'discharge_disposition_id': 0.0,
  'admission_source_id': 0.0,
  'time_in_hospital': 0.0,
  'payer_code': 39.5574,
  'medical_specialty': 49.0822,
  'num_lab_procedures': 0.0,
  'num_procedures': 0.0,
  'num_medications': 0.0,
  'number_outpatient': 0.0,
  'number_emergency': 0.0,
  'number_inpatient': 0.0,
  'diag_1': 0.0206,
  'diag_2': 0.3518,
  'diag_3': 1.3983,
  'number_diagnoses': 0.0,
  'max_glu_serum': 94.7468,
  'A1Cresult': 83.2773,
  'metformin': 0.0,
  'repaglinide': 0.0,
  'nateglinide': 0.0,
  'chlorpropamide': 0.0,
  'glimepiride': 0.0,
  'acetohexamide': 0.0,
  'glipizide': 0.0,
  'glyburide': 0.0,
  'tolbutamide': 0.0,
  'pioglitazone': 0.0,
  'rosiglitazone': 0.0,
  'acarbose': 0.0,
  'miglitol': 0.0,
  'troglitazone': 0.0,
  'tolazamide': 0.0,
  'examide': 0.0,
  'citoglipton': 0.0,
  'insulin': 0.0,
  'glyburide-metformin': 0.0,
  'glipizide-metformin': 0.0,
  'glimepiride-pioglitazone': 0.0,
  'metformin-rosiglitazone': 0.0,
  'metformin-pioglitazone': 0.0,
  'change': 0.0,
  'diabetesMed': 0.0,
  'readmitted': 0.0},
 'numeric_stats': {'admission_type_id': {'mean': 2.024006053102215,
   'std': 1.4454028297561208,
   'min': 1.0,
   'median': 1.0,
   'max': 8.0,
   'missing': 0},
  'discharge_disposition_id': {'mean': 3.7156417664052825,
   'std': 5.28016550929927,
   'min': 1.0,
   'median': 1.0,
   'max': 28.0,
   'missing': 0},
  'admission_source_id': {'mean': 5.754436648782501,
   'std': 4.064080834283903,
   'min': 1.0,
   'median': 7.0,
   'max': 25.0,
   'missing': 0},
  'time_in_hospital': {'mean': 4.395986871843248,
   'std': 2.985107767471267,
   'min': 1.0,
   'median': 4.0,
   'max': 14.0,
   'missing': 0},
  'num_lab_procedures': {'mean': 43.09564098028811,
   'std': 19.674362249142124,
   'min': 1.0,
   'median': 44.0,
   'max': 132.0,
   'missing': 0},
  'num_procedures': {'mean': 1.339730361810428,
   'std': 1.7058069791211594,
   'min': 0.0,
   'median': 1.0,
   'max': 6.0,
   'missing': 0},
  'num_medications': {'mean': 16.021844230882614,
   'std': 8.127566209167286,
   'min': 1.0,
   'median': 15.0,
   'max': 81.0,
   'missing': 0},
  'number_outpatient': {'mean': 0.36935715268360747,
   'std': 1.2672650965326768,
   'min': 0.0,
   'median': 0.0,
   'max': 42.0,
   'missing': 0},
  'number_emergency': {'mean': 0.19783621248747127,
   'std': 0.9304722684224637,
   'min': 0.0,
   'median': 0.0,
   'max': 76.0,
   'missing': 0},
  'number_inpatient': {'mean': 0.635565906098304,
   'std': 1.2628632900973231,
   'min': 0.0,
   'median': 0.0,
   'max': 21.0,
   'missing': 0},
  'number_diagnoses': {'mean': 7.422606764538254,
   'std': 1.9336001449974274,
   'min': 1.0,
   'median': 8.0,
   'max': 16.0,
   'missing': 0}},
 'top_unique': {'race': ['AfricanAmerican',
   'Caucasian',
   None,
   'Hispanic',
   'Other',
   'Asian'],
  'gender': ['Female', 'Unknown/Invalid', 'Male'],
  'age': ['[90-100)',
   '[20-30)',
   '[30-40)',
   '[80-90)',
   '[0-10)',
   '[50-60)',
   '[60-70)',
   '[10-20)',
   '[70-80)',
   '[40-50)'],
  'weight': ['>200',
   '[0-25)',
   '[150-175)',
   '[125-150)',
   '[75-100)',
   '[175-200)',
   '[25-50)',
   None,
   '[50-75)',
   '[100-125)'],
  'payer_code': ['SP', 'OT', 'UN', 'HM', 'FR', 'CP', None, 'MD', 'WC', 'CH'],
  'medical_specialty': ['PhysicalMedicineandRehabilitation',
   'Psychiatry-Addictive',
   'Pediatrics-CriticalCare',
   'Pediatrics-Neurology',
   'Orthopedics-Reconstructive',
   'Pediatrics-Endocrinology',
   'Obstetrics',
   'Surgery-General',
   'Pediatrics-InfectiousDiseases',
   'Gastroenterology'],
  'diag_1': ['990',
   '784',
   '357',
   '735',
   '721',
   '558',
   '293',
   '431',
   '462',
   '892'],
  'diag_2': ['704',
   'V23',
   '536',
   '860',
   '484',
   '140',
   '172',
   '52',
   '241',
   '543'],
  'diag_3': ['656',
   '831',
   '810',
   '348',
   '280',
   'E932',
   '524',
   '250.6',
   '250.92',
   '180'],
  'max_glu_serum': ['>200', 'Norm', '>300', None],
  'A1Cresult': ['>7', 'Norm', None, '>8'],
  'metformin': ['Steady', 'No', 'Up', 'Down'],
  'repaglinide': ['Up', 'Steady', 'Down', 'No'],
  'nateglinide': ['Down', 'No', 'Steady', 'Up'],
  'chlorpropamide': ['Up', 'No', 'Down', 'Steady'],
  'glimepiride': ['Steady', 'No', 'Down', 'Up'],
  'acetohexamide': ['No', 'Steady'],
  'glipizide': ['Up', 'Down', 'Steady', 'No'],
  'glyburide': ['Up', 'No', 'Down', 'Steady'],
  'tolbutamide': ['Steady', 'No'],
  'pioglitazone': ['Up', 'Down', 'No', 'Steady'],
  'rosiglitazone': ['No', 'Steady', 'Up', 'Down'],
  'acarbose': ['Steady', 'Down', 'No', 'Up'],
  'miglitol': ['Up', 'Down', 'Steady', 'No'],
  'troglitazone': ['No', 'Steady'],
  'tolazamide': ['Up', 'Steady', 'No'],
  'examide': ['No'],
  'citoglipton': ['No'],
  'insulin': ['No', 'Down', 'Up', 'Steady'],
  'glyburide-metformin': ['Steady', 'No', 'Up', 'Down'],
  'glipizide-metformin': ['Steady', 'No'],
  'glimepiride-pioglitazone': ['Steady', 'No'],
  'metformin-rosiglitazone': ['Steady', 'No'],
  'metformin-pioglitazone': ['No', 'Steady'],
  'change': ['Ch', 'No'],
  'diabetesMed': ['Yes', 'No'],
  'readmitted': ['>30', '<30', 'NO']}}

### Nursery

In [27]:
nursery_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(name="nursery", source="uci", df_type="polars")
nursery_df

shape: (12_960, 9)
┌────────────┬───────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ parents    ┆ has_nurs  ┆ form     ┆ children ┆ … ┆ finance   ┆ social    ┆ health    ┆ class     │
│ ---        ┆ ---       ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str       ┆ str      ┆ str      ┆   ┆ str       ┆ str       ┆ str       ┆ str       │
╞════════════╪═══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ usual      ┆ proper    ┆ complete ┆ 1        ┆ … ┆ convenien ┆ nonprob   ┆ recommend ┆ recommend │
│            ┆           ┆          ┆          ┆   ┆ t         ┆           ┆ ed        ┆           │
│ usual      ┆ proper    ┆ complete ┆ 1        ┆ … ┆ convenien ┆ nonprob   ┆ priority  ┆ priority  │
│            ┆           ┆          ┆          ┆   ┆ t         ┆           ┆           ┆           │
│ usual      ┆ proper    ┆ complete ┆ 1        ┆ … ┆ convenien ┆ nonprob   ┆ not_recom ┆ not_recom │
│            ┆           ┆          ┆          ┆   ┆ t         ┆           ┆           ┆           │
│ usual      ┆ proper    ┆ complete ┆ 1        ┆ … ┆ convenien ┆ slightly_ ┆ recommend ┆ recommend │
│            ┆           ┆          ┆          ┆   ┆ t         ┆ prob      ┆ ed        ┆           │
│ usual      ┆ proper    ┆ complete ┆ 1        ┆ … ┆ convenien ┆ slightly_ ┆ priority  ┆ priority  │
│            ┆           ┆          ┆          ┆   ┆ t         ┆ prob      ┆           ┆           │
│ …          ┆ …         ┆ …        ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ great_pret ┆ very_crit ┆ foster   ┆ more     ┆ … ┆ inconv    ┆ slightly_ ┆ priority  ┆ spec_prio │
│            ┆           ┆          ┆          ┆   ┆           ┆ prob      ┆           ┆ r         │
│ great_pret ┆ very_crit ┆ foster   ┆ more     ┆ … ┆ inconv    ┆ slightly_ ┆ not_recom ┆ not_recom │
│            ┆           ┆          ┆          ┆   ┆           ┆ prob      ┆           ┆           │
│ great_pret ┆ very_crit ┆ foster   ┆ more     ┆ … ┆ inconv    ┆ problemat ┆ recommend ┆ spec_prio │
│            ┆           ┆          ┆          ┆   ┆           ┆ ic        ┆ ed        ┆ r         │
│ great_pret ┆ very_crit ┆ foster   ┆ more     ┆ … ┆ inconv    ┆ problemat ┆ priority  ┆ spec_prio │
│            ┆           ┆          ┆          ┆   ┆           ┆ ic        ┆           ┆ r         │
│ great_pret ┆ very_crit ┆ foster   ┆ more     ┆ … ┆ inconv    ┆ problemat ┆ not_recom ┆ not_recom │
│            ┆           ┆          ┆          ┆   ┆           ┆ ic        ┆           ┆           │
└────────────┴───────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [28]:
get_df_info_pl(nursery_df)

DataFrame shape: (12960, 9)
Data types (according to dtypes):
Number of numerical columns: 0:
[]
  - Integer columns: 0: []
  - Float columns: 0: []
Number of categorical columns: 9:
['parents', 'has_nurs', 'form', 'children', 'housing', 'finance', 'social', 'health', 'class']
  - Multiclass columns: 8: ['parents', 'has_nurs', 'form', 'children', 'housing', 'social', 'health', 'class']
  - Binary columns: 1: ['finance']
  - Boolean columns: 0: []
Total categorical cardinality: 32
Total types count:
total numerical: 0 (int: 0, float: 0),
Total categorical: 9 (multi-class: 8, bin_cat: 1, bool_cat: 0):
Columns with missing values: 0

{'dtypes': {'parents': 'String',
  'has_nurs': 'String',
  'form': 'String',
  'children': 'String',
  'housing': 'String',
  'finance': 'String',
  'social': 'String',
  'health': 'String',
  'class': 'String'},
 'shape': (12960, 9),
 'numCols': [],
 'numColsTotal': 0,
 'intCols': [],
 'intColsTotal': 0,
 'floatCols': [],
 'floatColsTotal': 0,
 'catCols': ['parents',
  'has_nurs',
  'form',
  'children',
  'housing',
  'finance',
  'social',
  'health',
  'class'],
 'catColsTotal': 9,
 'binCols': ['finance'],
 'binColsTotal': 1,
 'boolCols': [],
 'boolColsTotal': 0,
 'cardinality': {'parents': 3,
  'has_nurs': 5,
  'form': 4,
  'children': 4,
  'housing': 3,
  'finance': 2,
  'social': 3,
  'health': 3,
  'class': 5},
 'total_cardinality': 32,
 'nulls': {'parents': 0,
  'has_nurs': 0,
  'form': 0,
  'children': 0,
  'housing': 0,
  'finance': 0,
  'social': 0,
  'health': 0,
  'class': 0},
 'missing_pct': {'parents': 0.0,
  'has_nurs': 0.0,
  'form': 0.0,
  'children': 0.0,
  'housing': 0.0,
  'finance': 0.0,
  'social': 0.0,
  'health': 0.0,
  'class': 0.0},
 'numeric_stats': {},
 'top_unique': {'parents': ['great_pret', 'usual', 'pretentious'],
  'has_nurs': ['critical', 'improper', 'very_crit', 'proper', 'less_proper'],
  'form': ['complete', 'completed', 'foster', 'incomplete'],
  'children': ['1', 'more', '3', '2'],
  'housing': ['convenient', 'less_conv', 'critical'],
  'finance': ['convenient', 'inconv'],
  'social': ['slightly_prob', 'nonprob', 'problematic'],
  'health': ['priority', 'not_recom', 'recommended'],
  'class': ['recommend', 'very_recom', 'spec_prior', 'priority', 'not_recom']}}

### taiwanese_bankruptcy

In [30]:
bankruptcy_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(name="taiwanese_bankruptcy", source="uci", df_type="polars")
bankruptcy_df

shape: (6_819, 96)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ ROA(C)    ┆ ROA(A)    ┆ ROA(B)    ┆ Operating ┆ … ┆ Interest  ┆ Net       ┆ Equity to ┆ Bankrupt │
│ before    ┆ before    ┆ before    ┆ Gross     ┆   ┆ Coverage  ┆ Income    ┆ Liability ┆ ?        │
│ interest  ┆ interest  ┆ interest  ┆ Margin    ┆   ┆ Ratio     ┆ Flag      ┆ ---       ┆ ---      │
│ and de…   ┆ and % …   ┆ and de…   ┆ ---       ┆   ┆ (Inte…    ┆ ---       ┆ f64       ┆ i64      │
│ ---       ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ i64       ┆           ┆          │
│ f64       ┆ f64       ┆ f64       ┆           ┆   ┆ f64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.370594  ┆ 0.424389  ┆ 0.40575   ┆ 0.601457  ┆ … ┆ 0.56405   ┆ 1         ┆ 0.016469  ┆ 1        │
│ 0.464291  ┆ 0.538214  ┆ 0.51673   ┆ 0.610235  ┆ … ┆ 0.570175  ┆ 1         ┆ 0.020794  ┆ 1        │
│ 0.426071  ┆ 0.499019  ┆ 0.472295  ┆ 0.60145   ┆ … ┆ 0.563706  ┆ 1         ┆ 0.016474  ┆ 1        │
│ 0.399844  ┆ 0.451265  ┆ 0.457733  ┆ 0.583541  ┆ … ┆ 0.564663  ┆ 1         ┆ 0.023982  ┆ 1        │
│ 0.465022  ┆ 0.538432  ┆ 0.522298  ┆ 0.598783  ┆ … ┆ 0.575617  ┆ 1         ┆ 0.03549   ┆ 1        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 0.493687  ┆ 0.539468  ┆ 0.54323   ┆ 0.604455  ┆ … ┆ 0.566193  ┆ 1         ┆ 0.02989   ┆ 0        │
│ 0.475162  ┆ 0.538269  ┆ 0.524172  ┆ 0.598308  ┆ … ┆ 0.566018  ┆ 1         ┆ 0.038284  ┆ 0        │
│ 0.472725  ┆ 0.533744  ┆ 0.520638  ┆ 0.610444  ┆ … ┆ 0.565158  ┆ 1         ┆ 0.097649  ┆ 0        │
│ 0.506264  ┆ 0.559911  ┆ 0.554045  ┆ 0.60785   ┆ … ┆ 0.565302  ┆ 1         ┆ 0.044009  ┆ 0        │
│ 0.493053  ┆ 0.570105  ┆ 0.549548  ┆ 0.627409  ┆ … ┆ 0.565167  ┆ 1         ┆ 0.233902  ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [55]:
# ' Net Income Flag' has only 1 unique value of 0. Drop this column.
bankruptcy_df = bankruptcy_df.drop([" Net Income Flag"])

In [58]:
tempCols = ['Bankrupt?',' Liability-Assets Flag', ]
# Select only the integer columns
bankruptcy_df = bankruptcy_df.with_columns(pl.col(tempCols).cast(pl.Utf8))

In [59]:
get_df_info_pl(bankruptcy_df)

DataFrame shape: (6819, 95)
Data types (according to dtypes):
Number of numerical columns: 93:
[' ROA(C) before interest and depreciation before interest', ' ROA(A) before interest and % after tax', ' ROA(B) before interest and depreciation after tax', ' Operating Gross Margin', ' Realized Sales Gross Margin', ' Operating Profit Rate', ' Pre-tax net Interest Rate', ' After-tax net Interest Rate', ' Non-industry income and expenditure/revenue', ' Continuous interest rate (after tax)', ' Operating Expense Rate', ' Research and development expense rate', ' Cash flow rate', ' Interest-bearing debt interest rate', ' Tax rate (A)', ' Net Value Per Share (B)', ' Net Value Per Share (A)', ' Net Value Per Share (C)', ' Persistent EPS in the Last Four Seasons', ' Cash Flow Per Share', ' Revenue Per Share (Yuan ¥)', ' Operating Profit Per Share (Yuan ¥)', ' Per Share Net profit before tax (Yuan ¥)', ' Realized Sales Gross Profit Growth Rate', ' Operating Profit Growth Rate', ' After-tax Net Profit Growth Rate', ' Regular Net Profit Growth Rate', ' Continuous Net Profit Growth Rate', ' Total Asset Growth Rate', ' Net Value Growth Rate', ' Total Asset Return Growth Rate Ratio', ' Cash Reinvestment %', ' Current Ratio', ' Quick Ratio', ' Interest Expense Ratio', ' Total debt/Total net worth', ' Debt ratio %', ' Net worth/Assets', ' Long-term fund suitability ratio (A)', ' Borrowing dependency', ' Contingent liabilities/Net worth', ' Operating profit/Paid-in capital', ' Net profit before tax/Paid-in capital', ' Inventory and accounts receivable/Net value', ' Total Asset Turnover', ' Accounts Receivable Turnover', ' Average Collection Days', ' Inventory Turnover Rate (times)', ' Fixed Assets Turnover Frequency', ' Net Worth Turnover Rate (times)', ' Revenue per person', ' Operating profit per person', ' Allocation rate per person', ' Working Capital to Total Assets', ' Quick Assets/Total Assets', ' Current Assets/Total Assets', ' Cash/Total Assets', ' Quick Assets/Current Liability', ' Cash/Current Liability', ' Current Liability to Assets', ' Operating Funds to Liability', ' Inventory/Working Capital', ' Inventory/Current Liability', ' Current Liabilities/Liability', ' Working Capital/Equity', ' Current Liabilities/Equity', ' Long-term Liability to Current Assets', ' Retained Earnings to Total Assets', ' Total income/Total expense', ' Total expense/Assets', ' Current Asset Turnover Rate', ' Quick Asset Turnover Rate', ' Working capitcal Turnover Rate', ' Cash Turnover Rate', ' Cash Flow to Sales', ' Fixed Assets to Assets', ' Current Liability to Liability', ' Current Liability to Equity', ' Equity to Long-term Liability', ' Cash Flow to Total Assets', ' Cash Flow to Liability', ' CFO to Assets', ' Cash Flow to Equity', ' Current Liability to Current Assets', ' Net Income to Total Assets', ' Total assets to GNP price', ' No-credit Interval', ' Gross Profit to Sales', " Net Income to Stockholder's Equity", ' Liability to Equity', ' Degree of Financial Leverage (DFL)', ' Interest Coverage Ratio (Interest expense to EBIT)', ' Equity to Liability']
  - Integer columns: 0: []
  - Float columns: 93: [' ROA(C) before interest and depreciation before interest', ' ROA(A) before interest and % after tax', ' ROA(B) before interest and depreciation after tax', ' Operating Gross Margin', ' Realized Sales Gross Margin', ' Operating Profit Rate', ' Pre-tax net Interest Rate', ' After-tax net Interest Rate', ' Non-industry income and expenditure/revenue', ' Continuous interest rate (after tax)', ' Operating Expense Rate', ' Research and development expense rate', ' Cash flow rate', ' Interest-bearing debt interest rate', ' Tax rate (A)', ' Net Value Per Share (B)', ' Net Value Per Share (A)', ' Net Value Per Share (C)', ' Persistent EPS in the Last Four Seasons', ' Cash Flow Per Share', ' Revenue Per Share (Yuan ¥)', ' Operating Profit Per Share (Yuan ¥)', ' Per Share Net profit before tax (Yuan ¥)', ' Realized Sales Gross Profit Growth Rate', ' Operating Profit Growth Rate', ' After-tax Net Profit Growth Rate', ' Regular Net Profit Growth Rate', ' Continuous Net Profit Growth Rate', ' Total Asset Growth Rate', ' Net Value Growth Rate', ' Total Asset Return Growth Rate Ratio', ' Cash Reinvestment %', ' Current Ratio', ' Quick Ratio', ' Interest Expense Ratio', ' Total debt/Total net worth', ' Debt ratio %', ' Net worth/Assets', ' Long-term fund suitability ratio (A)', ' Borrowing dependency', ' Contingent liabilities/Net worth', ' Operating profit/Paid-in capital', ' Net profit before tax/Paid-in capital', ' Inventory and accounts receivable/Net value', ' Total Asset Turnover', ' Accounts Receivable Turnover', ' Average Collection Days', ' Inventory Turnover Rate (times)', ' Fixed Assets Turnover Frequency', ' Net Worth Turnover Rate (times)', ' Revenue per person', ' Operating profit per person', ' Allocation rate per person', ' Working Capital to Total Assets', ' Quick Assets/Total Assets', ' Current Assets/Total Assets', ' Cash/Total Assets', ' Quick Assets/Current Liability', ' Cash/Current Liability', ' Current Liability to Assets', ' Operating Funds to Liability', ' Inventory/Working Capital', ' Inventory/Current Liability', ' Current Liabilities/Liability', ' Working Capital/Equity', ' Current Liabilities/Equity', ' Long-term Liability to Current Assets', ' Retained Earnings to Total Assets', ' Total income/Total expense', ' Total expense/Assets', ' Current Asset Turnover Rate', ' Quick Asset Turnover Rate', ' Working capitcal Turnover Rate', ' Cash Turnover Rate', ' Cash Flow to Sales', ' Fixed Assets to Assets', ' Current Liability to Liability', ' Current Liability to Equity', ' Equity to Long-term Liability', ' Cash Flow to Total Assets', ' Cash Flow to Liability', ' CFO to Assets', ' Cash Flow to Equity', ' Current Liability to Current Assets', ' Net Income to Total Assets', ' Total assets to GNP price', ' No-credit Interval', ' Gross Profit to Sales', " Net Income to Stockholder's Equity", ' Liability to Equity', ' Degree of Financial Leverage (DFL)', ' Interest Coverage Ratio (Interest expense to EBIT)', ' Equity to Liability']
Number of categorical columns: 2:
[' Liability-Assets Flag', 'Bankrupt?']
  - Multiclass columns: 0: []
  - Binary columns: 2: [' Liability-Assets Flag', 'Bankrupt?']
  - Boolean columns: 0: []
Total categorical cardinality: 4
Total types count:
total numerical: 93 (int: 0, float: 93),
Total categorical: 2 (multi-class: 0, bin_cat: 2, bool_cat: 0):
Columns with missing values: 0

{'dtypes': {' ROA(C) before interest and depreciation before interest': 'Float64',
  ' ROA(A) before interest and % after tax': 'Float64',
  ' ROA(B) before interest and depreciation after tax': 'Float64',
  ' Operating Gross Margin': 'Float64',
  ' Realized Sales Gross Margin': 'Float64',
  ' Operating Profit Rate': 'Float64',
  ' Pre-tax net Interest Rate': 'Float64',
  ' After-tax net Interest Rate': 'Float64',
  ' Non-industry income and expenditure/revenue': 'Float64',
  ' Continuous interest rate (after tax)': 'Float64',
  ' Operating Expense Rate': 'Float64',
  ' Research and development expense rate': 'Float64',
  ' Cash flow rate': 'Float64',
  ' Interest-bearing debt interest rate': 'Float64',
  ' Tax rate (A)': 'Float64',
  ' Net Value Per Share (B)': 'Float64',
  ' Net Value Per Share (A)': 'Float64',
  ' Net Value Per Share (C)': 'Float64',
  ' Persistent EPS in the Last Four Seasons': 'Float64',
  ' Cash Flow Per Share': 'Float64',
  ' Revenue Per Share (Yuan ¥)': 'Float64',
  ' Operating Profit Per Share (Yuan ¥)': 'Float64',
  ' Per Share Net profit before tax (Yuan ¥)': 'Float64',
  ' Realized Sales Gross Profit Growth Rate': 'Float64',
  ' Operating Profit Growth Rate': 'Float64',
  ' After-tax Net Profit Growth Rate': 'Float64',
  ' Regular Net Profit Growth Rate': 'Float64',
  ' Continuous Net Profit Growth Rate': 'Float64',
  ' Total Asset Growth Rate': 'Float64',
  ' Net Value Growth Rate': 'Float64',
  ' Total Asset Return Growth Rate Ratio': 'Float64',
  ' Cash Reinvestment %': 'Float64',
  ' Current Ratio': 'Float64',
  ' Quick Ratio': 'Float64',
  ' Interest Expense Ratio': 'Float64',
  ' Total debt/Total net worth': 'Float64',
  ' Debt ratio %': 'Float64',
  ' Net worth/Assets': 'Float64',
  ' Long-term fund suitability ratio (A)': 'Float64',
  ' Borrowing dependency': 'Float64',
  ' Contingent liabilities/Net worth': 'Float64',
  ' Operating profit/Paid-in capital': 'Float64',
  ' Net profit before tax/Paid-in capital': 'Float64',
  ' Inventory and accounts receivable/Net value': 'Float64',
  ' Total Asset Turnover': 'Float64',
  ' Accounts Receivable Turnover': 'Float64',
  ' Average Collection Days': 'Float64',
  ' Inventory Turnover Rate (times)': 'Float64',
  ' Fixed Assets Turnover Frequency': 'Float64',
  ' Net Worth Turnover Rate (times)': 'Float64',
  ' Revenue per person': 'Float64',
  ' Operating profit per person': 'Float64',
  ' Allocation rate per person': 'Float64',
  ' Working Capital to Total Assets': 'Float64',
  ' Quick Assets/Total Assets': 'Float64',
  ' Current Assets/Total Assets': 'Float64',
  ' Cash/Total Assets': 'Float64',
  ' Quick Assets/Current Liability': 'Float64',
  ' Cash/Current Liability': 'Float64',
  ' Current Liability to Assets': 'Float64',
  ' Operating Funds to Liability': 'Float64',
  ' Inventory/Working Capital': 'Float64',
  ' Inventory/Current Liability': 'Float64',
  ' Current Liabilities/Liability': 'Float64',
  ' Working Capital/Equity': 'Float64',
  ' Current Liabilities/Equity': 'Float64',
  ' Long-term Liability to Current Assets': 'Float64',
  ' Retained Earnings to Total Assets': 'Float64',
  ' Total income/Total expense': 'Float64',
  ' Total expense/Assets': 'Float64',
  ' Current Asset Turnover Rate': 'Float64',
  ' Quick Asset Turnover Rate': 'Float64',
  ' Working capitcal Turnover Rate': 'Float64',
  ' Cash Turnover Rate': 'Float64',
  ' Cash Flow to Sales': 'Float64',
  ' Fixed Assets to Assets': 'Float64',
  ' Current Liability to Liability': 'Float64',
  ' Current Liability to Equity': 'Float64',
  ' Equity to Long-term Liability': 'Float64',
  ' Cash Flow to Total Assets': 'Float64',
  ' Cash Flow to Liability': 'Float64',
  ' CFO to Assets': 'Float64',
  ' Cash Flow to Equity': 'Float64',
  ' Current Liability to Current Assets': 'Float64',
  ' Liability-Assets Flag': 'String',
  ' Net Income to Total Assets': 'Float64',
  ' Total assets to GNP price': 'Float64',
  ' No-credit Interval': 'Float64',
  ' Gross Profit to Sales': 'Float64',
  " Net Income to Stockholder's Equity": 'Float64',
  ' Liability to Equity': 'Float64',
  ' Degree of Financial Leverage (DFL)': 'Float64',
  ' Interest Coverage Ratio (Interest expense to EBIT)': 'Float64',
  ' Equity to Liability': 'Float64',
  'Bankrupt?': 'String'},
 'shape': (6819, 95),
 'numCols': [' ROA(C) before interest and depreciation before interest',
  ' ROA(A) before interest and % after tax',
  ' ROA(B) before interest and depreciation after tax',
  ' Operating Gross Margin',
  ' Realized Sales Gross Margin',
  ' Operating Profit Rate',
  ' Pre-tax net Interest Rate',
  ' After-tax net Interest Rate',
  ' Non-industry income and expenditure/revenue',
  ' Continuous interest rate (after tax)',
  ' Operating Expense Rate',
  ' Research and development expense rate',
  ' Cash flow rate',
  ' Interest-bearing debt interest rate',
  ' Tax rate (A)',
  ' Net Value Per Share (B)',
  ' Net Value Per Share (A)',
  ' Net Value Per Share (C)',
  ' Persistent EPS in the Last Four Seasons',
  ' Cash Flow Per Share',
  ' Revenue Per Share (Yuan ¥)',
  ' Operating Profit Per Share (Yuan ¥)',
  ' Per Share Net profit before tax (Yuan ¥)',
  ' Realized Sales Gross Profit Growth Rate',
  ' Operating Profit Growth Rate',
  ' After-tax Net Profit Growth Rate',
  ' Regular Net Profit Growth Rate',
  ' Continuous Net Profit Growth Rate',
  ' Total Asset Growth Rate',
  ' Net Value Growth Rate',
  ' Total Asset Return Growth Rate Ratio',
  ' Cash Reinvestment %',
  ' Current Ratio',
  ' Quick Ratio',
  ' Interest Expense Ratio',
  ' Total debt/Total net worth',
  ' Debt ratio %',
  ' Net worth/Assets',
  ' Long-term fund suitability ratio (A)',
  ' Borrowing dependency',
  ' Contingent liabilities/Net worth',
  ' Operating profit/Paid-in capital',
  ' Net profit before tax/Paid-in capital',
  ' Inventory and accounts receivable/Net value',
  ' Total Asset Turnover',
  ' Accounts Receivable Turnover',
  ' Average Collection Days',
  ' Inventory Turnover Rate (times)',
  ' Fixed Assets Turnover Frequency',
  ' Net Worth Turnover Rate (times)',
  ' Revenue per person',
  ' Operating profit per person',
  ' Allocation rate per person',
  ' Working Capital to Total Assets',
  ' Quick Assets/Total Assets',
  ' Current Assets/Total Assets',
  ' Cash/Total Assets',
  ' Quick Assets/Current Liability',
  ' Cash/Current Liability',
  ' Current Liability to Assets',
  ' Operating Funds to Liability',
  ' Inventory/Working Capital',
  ' Inventory/Current Liability',
  ' Current Liabilities/Liability',
  ' Working Capital/Equity',
  ' Current Liabilities/Equity',
  ' Long-term Liability to Current Assets',
  ' Retained Earnings to Total Assets',
  ' Total income/Total expense',
  ' Total expense/Assets',
  ' Current Asset Turnover Rate',
  ' Quick Asset Turnover Rate',
  ' Working capitcal Turnover Rate',
  ' Cash Turnover Rate',
  ' Cash Flow to Sales',
  ' Fixed Assets to Assets',
  ' Current Liability to Liability',
  ' Current Liability to Equity',
  ' Equity to Long-term Liability',
  ' Cash Flow to Total Assets',
  ' Cash Flow to Liability',
  ' CFO to Assets',
  ' Cash Flow to Equity',
  ' Current Liability to Current Assets',
  ' Net Income to Total Assets',
  ' Total assets to GNP price',
  ' No-credit Interval',
  ' Gross Profit to Sales',
  " Net Income to Stockholder's Equity",
  ' Liability to Equity',
  ' Degree of Financial Leverage (DFL)',
  ' Interest Coverage Ratio (Interest expense to EBIT)',
  ' Equity to Liability'],
 'numColsTotal': 93,
 'intCols': [],
 'intColsTotal': 0,
 'floatCols': [' ROA(C) before interest and depreciation before interest',
  ' ROA(A) before interest and % after tax',
  ' ROA(B) before interest and depreciation after tax',
  ' Operating Gross Margin',
  ' Realized Sales Gross Margin',
  ' Operating Profit Rate',
  ' Pre-tax net Interest Rate',
  ' After-tax net Interest Rate',
  ' Non-industry income and expenditure/revenue',
  ' Continuous interest rate (after tax)',
  ' Operating Expense Rate',
  ' Research and development expense rate',
  ' Cash flow rate',
  ' Interest-bearing debt interest rate',
  ' Tax rate (A)',
  ' Net Value Per Share (B)',
  ' Net Value Per Share (A)',
  ' Net Value Per Share (C)',
  ' Persistent EPS in the Last Four Seasons',
  ' Cash Flow Per Share',
  ' Revenue Per Share (Yuan ¥)',
  ' Operating Profit Per Share (Yuan ¥)',
  ' Per Share Net profit before tax (Yuan ¥)',
  ' Realized Sales Gross Profit Growth Rate',
  ' Operating Profit Growth Rate',
  ' After-tax Net Profit Growth Rate',
  ' Regular Net Profit Growth Rate',
  ' Continuous Net Profit Growth Rate',
  ' Total Asset Growth Rate',
  ' Net Value Growth Rate',
  ' Total Asset Return Growth Rate Ratio',
  ' Cash Reinvestment %',
  ' Current Ratio',
  ' Quick Ratio',
  ' Interest Expense Ratio',
  ' Total debt/Total net worth',
  ' Debt ratio %',
  ' Net worth/Assets',
  ' Long-term fund suitability ratio (A)',
  ' Borrowing dependency',
  ' Contingent liabilities/Net worth',
  ' Operating profit/Paid-in capital',
  ' Net profit before tax/Paid-in capital',
  ' Inventory and accounts receivable/Net value',
  ' Total Asset Turnover',
  ' Accounts Receivable Turnover',
  ' Average Collection Days',
  ' Inventory Turnover Rate (times)',
  ' Fixed Assets Turnover Frequency',
  ' Net Worth Turnover Rate (times)',
  ' Revenue per person',
  ' Operating profit per person',
  ' Allocation rate per person',
  ' Working Capital to Total Assets',
  ' Quick Assets/Total Assets',
  ' Current Assets/Total Assets',
  ' Cash/Total Assets',
  ' Quick Assets/Current Liability',
  ' Cash/Current Liability',
  ' Current Liability to Assets',
  ' Operating Funds to Liability',
  ' Inventory/Working Capital',
  ' Inventory/Current Liability',
  ' Current Liabilities/Liability',
  ' Working Capital/Equity',
  ' Current Liabilities/Equity',
  ' Long-term Liability to Current Assets',
  ' Retained Earnings to Total Assets',
  ' Total income/Total expense',
  ' Total expense/Assets',
  ' Current Asset Turnover Rate',
  ' Quick Asset Turnover Rate',
  ' Working capitcal Turnover Rate',
  ' Cash Turnover Rate',
  ' Cash Flow to Sales',
  ' Fixed Assets to Assets',
  ' Current Liability to Liability',
  ' Current Liability to Equity',
  ' Equity to Long-term Liability',
  ' Cash Flow to Total Assets',
  ' Cash Flow to Liability',
  ' CFO to Assets',
  ' Cash Flow to Equity',
  ' Current Liability to Current Assets',
  ' Net Income to Total Assets',
  ' Total assets to GNP price',
  ' No-credit Interval',
  ' Gross Profit to Sales',
  " Net Income to Stockholder's Equity",
  ' Liability to Equity',
  ' Degree of Financial Leverage (DFL)',
  ' Interest Coverage Ratio (Interest expense to EBIT)',
  ' Equity to Liability'],
 'floatColsTotal': 93,
 'catCols': [' Liability-Assets Flag', 'Bankrupt?'],
 'catColsTotal': 2,
 'binCols': [' Liability-Assets Flag', 'Bankrupt?'],
 'binColsTotal': 2,
 'boolCols': [],
 'boolColsTotal': 0,
 'cardinality': {' Liability-Assets Flag': 2, 'Bankrupt?': 2},
 'total_cardinality': 4,
 'nulls': {' ROA(C) before interest and depreciation before interest': 0,
  ' ROA(A) before interest and % after tax': 0,
  ' ROA(B) before interest and depreciation after tax': 0,
  ' Operating Gross Margin': 0,
  ' Realized Sales Gross Margin': 0,
  ' Operating Profit Rate': 0,
  ' Pre-tax net Interest Rate': 0,
  ' After-tax net Interest Rate': 0,
  ' Non-industry income and expenditure/revenue': 0,
  ' Continuous interest rate (after tax)': 0,
  ' Operating Expense Rate': 0,
  ' Research and development expense rate': 0,
  ' Cash flow rate': 0,
  ' Interest-bearing debt interest rate': 0,
  ' Tax rate (A)': 0,
  ' Net Value Per Share (B)': 0,
  ' Net Value Per Share (A)': 0,
  ' Net Value Per Share (C)': 0,
  ' Persistent EPS in the Last Four Seasons': 0,
  ' Cash Flow Per Share': 0,
  ' Revenue Per Share (Yuan ¥)': 0,
  ' Operating Profit Per Share (Yuan ¥)': 0,
  ' Per Share Net profit before tax (Yuan ¥)': 0,
  ' Realized Sales Gross Profit Growth Rate': 0,
  ' Operating Profit Growth Rate': 0,
  ' After-tax Net Profit Growth Rate': 0,
  ' Regular Net Profit Growth Rate': 0,
  ' Continuous Net Profit Growth Rate': 0,
  ' Total Asset Growth Rate': 0,
  ' Net Value Growth Rate': 0,
  ' Total Asset Return Growth Rate Ratio': 0,
  ' Cash Reinvestment %': 0,
  ' Current Ratio': 0,
  ' Quick Ratio': 0,
  ' Interest Expense Ratio': 0,
  ' Total debt/Total net worth': 0,
  ' Debt ratio %': 0,
  ' Net worth/Assets': 0,
  ' Long-term fund suitability ratio (A)': 0,
  ' Borrowing dependency': 0,
  ' Contingent liabilities/Net worth': 0,
  ' Operating profit/Paid-in capital': 0,
  ' Net profit before tax/Paid-in capital': 0,
  ' Inventory and accounts receivable/Net value': 0,
  ' Total Asset Turnover': 0,
  ' Accounts Receivable Turnover': 0,
  ' Average Collection Days': 0,
  ' Inventory Turnover Rate (times)': 0,
  ' Fixed Assets Turnover Frequency': 0,
  ' Net Worth Turnover Rate (times)': 0,
  ' Revenue per person': 0,
  ' Operating profit per person': 0,
  ' Allocation rate per person': 0,
  ' Working Capital to Total Assets': 0,
  ' Quick Assets/Total Assets': 0,
  ' Current Assets/Total Assets': 0,
  ' Cash/Total Assets': 0,
  ' Quick Assets/Current Liability': 0,
  ' Cash/Current Liability': 0,
  ' Current Liability to Assets': 0,
  ' Operating Funds to Liability': 0,
  ' Inventory/Working Capital': 0,
  ' Inventory/Current Liability': 0,
  ' Current Liabilities/Liability': 0,
  ' Working Capital/Equity': 0,
  ' Current Liabilities/Equity': 0,
  ' Long-term Liability to Current Assets': 0,
  ' Retained Earnings to Total Assets': 0,
  ' Total income/Total expense': 0,
  ' Total expense/Assets': 0,
  ' Current Asset Turnover Rate': 0,
  ' Quick Asset Turnover Rate': 0,
  ' Working capitcal Turnover Rate': 0,
  ' Cash Turnover Rate': 0,
  ' Cash Flow to Sales': 0,
  ' Fixed Assets to Assets': 0,
  ' Current Liability to Liability': 0,
  ' Current Liability to Equity': 0,
  ' Equity to Long-term Liability': 0,
  ' Cash Flow to Total Assets': 0,
  ' Cash Flow to Liability': 0,
  ' CFO to Assets': 0,
  ' Cash Flow to Equity': 0,
  ' Current Liability to Current Assets': 0,
  ' Liability-Assets Flag': 0,
  ' Net Income to Total Assets': 0,
  ' Total assets to GNP price': 0,
  ' No-credit Interval': 0,
  ' Gross Profit to Sales': 0,
  " Net Income to Stockholder's Equity": 0,
  ' Liability to Equity': 0,
  ' Degree of Financial Leverage (DFL)': 0,
  ' Interest Coverage Ratio (Interest expense to EBIT)': 0,
  ' Equity to Liability': 0,
  'Bankrupt?': 0},
 'missing_pct': {' ROA(C) before interest and depreciation before interest': 0.0,
  ' ROA(A) before interest and % after tax': 0.0,
  ' ROA(B) before interest and depreciation after tax': 0.0,
  ' Operating Gross Margin': 0.0,
  ' Realized Sales Gross Margin': 0.0,
  ' Operating Profit Rate': 0.0,
  ' Pre-tax net Interest Rate': 0.0,
  ' After-tax net Interest Rate': 0.0,
  ' Non-industry income and expenditure/revenue': 0.0,
  ' Continuous interest rate (after tax)': 0.0,
  ' Operating Expense Rate': 0.0,
  ' Research and development expense rate': 0.0,
  ' Cash flow rate': 0.0,
  ' Interest-bearing debt interest rate': 0.0,
  ' Tax rate (A)': 0.0,
  ' Net Value Per Share (B)': 0.0,
  ' Net Value Per Share (A)': 0.0,
  ' Net Value Per Share (C)': 0.0,
  ' Persistent EPS in the Last Four Seasons': 0.0,
  ' Cash Flow Per Share': 0.0,
  ' Revenue Per Share (Yuan ¥)': 0.0,
  ' Operating Profit Per Share (Yuan ¥)': 0.0,
  ' Per Share Net profit before tax (Yuan ¥)': 0.0,
  ' Realized Sales Gross Profit Growth Rate': 0.0,
  ' Operating Profit Growth Rate': 0.0,
  ' After-tax Net Profit Growth Rate': 0.0,
  ' Regular Net Profit Growth Rate': 0.0,
  ' Continuous Net Profit Growth Rate': 0.0,
  ' Total Asset Growth Rate': 0.0,
  ' Net Value Growth Rate': 0.0,
  ' Total Asset Return Growth Rate Ratio': 0.0,
  ' Cash Reinvestment %': 0.0,
  ' Current Ratio': 0.0,
  ' Quick Ratio': 0.0,
  ' Interest Expense Ratio': 0.0,
  ' Total debt/Total net worth': 0.0,
  ' Debt ratio %': 0.0,
  ' Net worth/Assets': 0.0,
  ' Long-term fund suitability ratio (A)': 0.0,
  ' Borrowing dependency': 0.0,
  ' Contingent liabilities/Net worth': 0.0,
  ' Operating profit/Paid-in capital': 0.0,
  ' Net profit before tax/Paid-in capital': 0.0,
  ' Inventory and accounts receivable/Net value': 0.0,
  ' Total Asset Turnover': 0.0,
  ' Accounts Receivable Turnover': 0.0,
  ' Average Collection Days': 0.0,
  ' Inventory Turnover Rate (times)': 0.0,
  ' Fixed Assets Turnover Frequency': 0.0,
  ' Net Worth Turnover Rate (times)': 0.0,
  ' Revenue per person': 0.0,
  ' Operating profit per person': 0.0,
  ' Allocation rate per person': 0.0,
  ' Working Capital to Total Assets': 0.0,
  ' Quick Assets/Total Assets': 0.0,
  ' Current Assets/Total Assets': 0.0,
  ' Cash/Total Assets': 0.0,
  ' Quick Assets/Current Liability': 0.0,
  ' Cash/Current Liability': 0.0,
  ' Current Liability to Assets': 0.0,
  ' Operating Funds to Liability': 0.0,
  ' Inventory/Working Capital': 0.0,
  ' Inventory/Current Liability': 0.0,
  ' Current Liabilities/Liability': 0.0,
  ' Working Capital/Equity': 0.0,
  ' Current Liabilities/Equity': 0.0,
  ' Long-term Liability to Current Assets': 0.0,
  ' Retained Earnings to Total Assets': 0.0,
  ' Total income/Total expense': 0.0,
  ' Total expense/Assets': 0.0,
  ' Current Asset Turnover Rate': 0.0,
  ' Quick Asset Turnover Rate': 0.0,
  ' Working capitcal Turnover Rate': 0.0,
  ' Cash Turnover Rate': 0.0,
  ' Cash Flow to Sales': 0.0,
  ' Fixed Assets to Assets': 0.0,
  ' Current Liability to Liability': 0.0,
  ' Current Liability to Equity': 0.0,
  ' Equity to Long-term Liability': 0.0,
  ' Cash Flow to Total Assets': 0.0,
  ' Cash Flow to Liability': 0.0,
  ' CFO to Assets': 0.0,
  ' Cash Flow to Equity': 0.0,
  ' Current Liability to Current Assets': 0.0,
  ' Liability-Assets Flag': 0.0,
  ' Net Income to Total Assets': 0.0,
  ' Total assets to GNP price': 0.0,
  ' No-credit Interval': 0.0,
  ' Gross Profit to Sales': 0.0,
  " Net Income to Stockholder's Equity": 0.0,
  ' Liability to Equity': 0.0,
  ' Degree of Financial Leverage (DFL)': 0.0,
  ' Interest Coverage Ratio (Interest expense to EBIT)': 0.0,
  ' Equity to Liability': 0.0,
  'Bankrupt?': 0.0},
 'numeric_stats': {' ROA(C) before interest and depreciation before interest': {'mean': 0.5051796332417815,
   'std': 0.060685638754284434,
   'min': 0.0,
   'median': 0.502705601325988,
   'max': 1.0,
   'missing': 0},
  ' ROA(A) before interest and % after tax': {'mean': 0.5586249158750463,
   'std': 0.06562003103170726,
   'min': 0.0,
   'median': 0.559801569995639,
   'max': 1.0,
   'missing': 0},
  ' ROA(B) before interest and depreciation after tax': {'mean': 0.5535887093516656,
   'std': 0.061594809291875656,
   'min': 0.0,
   'median': 0.552277959205525,
   'max': 1.0,
   'missing': 0},
  ' Operating Gross Margin': {'mean': 0.6079480383703836,
   'std': 0.016933812548221454,
   'min': 0.0,
   'median': 0.605997492036495,
   'max': 1.0,
   'missing': 0},
  ' Realized Sales Gross Margin': {'mean': 0.607929469176979,
   'std': 0.016916070055675785,
   'min': 0.0,
   'median': 0.605975871661454,
   'max': 1.0,
   'missing': 0},
  ' Operating Profit Rate': {'mean': 0.998755127790044,
   'std': 0.013010025092984129,
   'min': 0.0,
   'median': 0.999022239374566,
   'max': 1.0,
   'missing': 0},
  ' Pre-tax net Interest Rate': {'mean': 0.7971897524712904,
   'std': 0.012868988419884597,
   'min': 0.0,
   'median': 0.797463610578231,
   'max': 1.0,
   'missing': 0},
  ' After-tax net Interest Rate': {'mean': 0.809083593513535,
   'std': 0.013600653945149045,
   'min': 0.0,
   'median': 0.809375198550956,
   'max': 1.0,
   'missing': 0},
  ' Non-industry income and expenditure/revenue': {'mean': 0.303622923649734,
   'std': 0.01116343983812855,
   'min': 0.0,
   'median': 0.303525492830123,
   'max': 1.0,
   'missing': 0},
  ' Continuous interest rate (after tax)': {'mean': 0.7813814325261416,

### apartment_rent_classified

In [2]:
# def convert_dtypes(df, var_types, inplace=False, verbose=False):
#     """
#     Convert pandas DataFrame columns to dtypes described in var_types dict.
#     var_types: mapping col_name -> type string (e.g. 'Categorical','Integer','Float','Boolean','Datetime',...)
#     Returns converted DataFrame (or modifies in place if inplace=True).
#     """
#     df_out = df if inplace else df.copy()
#     bool_map = {"yes": True, "no": False, "y": True, "n": False,
#                 "true": True, "false": False, "t": True, "f": False,
#                 "1": True, "0": False}

#     for col, t in var_types.items():
#         if col not in df_out.columns:
#             if verbose:
#                 print(f"skip missing column: {col}")
#             continue

#         t_low = str(t).strip().lower()
#         s = df_out[col]

#         try:
#             if "date" in t_low or "time" in t_low or "datetime" in t_low:
#                 df_out[col] = pd.to_datetime(s, errors="coerce")
#                 if verbose: print(f"{col} -> datetime64[ns]")

#             elif "bool" in t_low or "binary" in t_low:
#                 # try mapping common string tokens first, else coerce numeric
#                 mapped = s.astype("string").str.strip().str.lower().map(bool_map)
#                 if mapped.isna().all():
#                     # fallback to numeric then boolean
#                     num = pd.to_numeric(s, errors="coerce")
#                     df_out[col] = num.fillna(0).astype("boolean")
#                 else:
#                     df_out[col] = mapped.astype("boolean")
#                 if verbose: print(f"{col} -> boolean (nullable)")

#             elif "int" in t_low:
#                 num = pd.to_numeric(s, errors="coerce")
#                 df_out[col] = num.astype(pd.Int64Dtype())
#                 if verbose: print(f"{col} -> Int64 (nullable)")

#             elif "float" in t_low:
#                 num = pd.to_numeric(s, errors="coerce")
#                 df_out[col] = num.astype(pd.Float64Dtype())
#                 if verbose: print(f"{col} -> Float64 (nullable)")

#             elif "cat" in t_low or "string" in t_low or "text" in t_low:
#                 # prefer pandas nullable string dtype
#                 df_out[col] = s.astype(pd.StringDtype())
#                 if verbose: print(f"{col} -> StringDtype (nullable)")

#             else:
#                 # fallback: leave as object/string
#                 df_out[col] = s
#                 if verbose: print(f"{col} -> left as original dtype ({s.dtype})")
#         except Exception as e:
#             if verbose:
#                 print(f"conversion failed for {col}: {e} -- leaving original dtype")
#             df_out[col] = s

#     return df_out if not inplace else None

# apartment_rent_new_df = convert_dtypes(apartment_rent_df, var_types, inplace=False, verbose=True)

In [72]:
# apartment_rent_df

In [57]:
# # change the types in var_types to pandas dtypes:
# var_types_pd = {k: (pd.StringDtype() if v=="Categorical" else (pd.Int64Dtype() if v=="Integer" else (pd.Float64Dtype() if v=="Float" else pd.StringDtype))) for k,v in var_types.items()}

# # change dtypes according to var_types types:
# apartment_rent_df = apartment_rent_df.astype(var_types)

In [4]:
apartment_rent_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(name="apartment_rent_classified", source="uci", df_type="pandas")
apartment_rent_df

/opt/miniconda3/envs/mixtabank/lib/python3.13/site-packages/ucimlrepo/fetch.py:97: DtypeWarning: Columns (0,5,6,12,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_url)

,category,title,body,amenities,bathrooms,bedrooms,currency,fee,has_photo,pets_allowed,...,price_display,price_type,square_feet,address,cityname,state,latitude,longitude,source,time
0,housing/rent/apartment,One BR 507 & 509 Esplanade,"This unit is located at 507 & 509 Esplanade, R...",NaN,1,1,USD,No,Thumbnail,Cats,...,2195,Monthly,542,507 509 Esplanade,Redondo Beach,CA,33.8520,-118.3759,RentLingo,1.577360e+09
1,housing/rent/apartment,Three BR 146 Lochview Drive,"This unit is located at 146 Lochview Drive, Ne...",NaN,1.5,3,USD,No,Thumbnail,"Cats,Dogs",...,1250,Monthly,1500,146 Lochview Dr,Newport News,VA,37.0867,-76.4941,RentLingo,1.577360e+09
2,housing/rent/apartment,Three BR 3101 Morningside Drive,This unit is located at 3101 Morningside Drive...,NaN,2,3,USD,No,Thumbnail,NaN,...,1395,Monthly,1650,3101 Morningside Dr,Raleigh,NC,35.8230,-78.6438,RentLingo,1.577360e+09
3,housing/rent/apartment,Two BR 209 Aegean Way,"This unit is located at 209 Aegean Way, Vacavi...",NaN,1,2,USD,No,Thumbnail,"Cats,Dogs",...,1600,Monthly,820,209 Aegean Way,Vacaville,CA,38.3622,-121.9712,RentLingo,1.577360e+09
4,housing/rent/apartment,One BR 4805 Marquette NE,"This unit is located at 4805 Marquette NE, Alb...",NaN,1,1,USD,No,Thumbnail,"Cats,Dogs",...,975,Monthly,624,4805 Marquette NE,Albuquerque,NM,35.1038,-106.6110,RentLingo,1.577360e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99821,housing/rent/apartment,Houston - superb Apartment nearby fine dining,"Redefining urban living, in southeast Houston,...","Gym,Parking,Patio/Deck,Playground,Storage,Wood...",1.0,1.0,USD,No,Yes,NaN,...,780,Monthly,605,NaN,Houston,TX,29.6151,-95.1998,RentDigs.com,1.544186e+09
99822,housing/rent/apartment,The Best of the Best in the City of Jacksonvil...,Courtney Manor Apartments offer the best of ev...,"AC,Cable or Satellite,Clubhouse,Dishwasher,Gym...",2.0,2.0,USD,No,Yes,"Cats,Dogs",...,813,Monthly,921,NaN,Jacksonville,FL,30.2254,-81.7579,RentDigs.com,1.544186e+09
99823,housing/rent/apartment,A great & large One BR apartment. Pet OK!,"Fully remodeled, new floor, kitchen cabinet, s...","Garbage Disposal,Refrigerator",1.0,1.0,USD,No,Yes,"Cats,Dogs",...,1325,Monthly,650,NaN,San Diego,CA,32.7379,-117.0914,RentDigs.com,1.544186e+09
99824,housing/rent/apartment,"The Crest offers studio, 1, 2 & Three BR homes...","Amenities include a fitness facilities, swimmi...","Gym,Pool",1.0,1.0,USD,No,Yes,"Cats,Dogs",...,931,Monthly,701,NaN,Huntersville,NC,35.4158,-80.8451,RentDigs.com,1.544186e+09
99825,housing/rent/apartment,Large Remodeled Two BR 1. Five BA Apartment Home,This is a brand new 2 Beds 1. five Bathrooms A...,"Gated,Parking,Wood Floors",1.5,2.0,USD,No,Yes,NaN,...,1595,Monthly,900,NaN,San Diego,CA,32.7379,-117.0914,RentDigs.com,1.544186e+09

Cleanup and preprocessing:

In [5]:
apartment_rent_df['bathrooms'] = apartment_rent_df['bathrooms'].replace(["No",], 0, inplace=False)
apartment_rent_df['bathrooms'] = apartment_rent_df['bathrooms'].replace(["Thumbnail",], np.nan, inplace=False)
apartment_rent_df['bathrooms'] = apartment_rent_df['bathrooms'].astype("Float64")

apartment_rent_df['bedrooms'] = apartment_rent_df['bedrooms'].replace(["No",], 0, inplace=False)
apartment_rent_df['bedrooms'] = apartment_rent_df['bedrooms'].replace(["Thumbnail","Cats,Dogs"], np.nan, inplace=False)
apartment_rent_df['bedrooms'] = apartment_rent_df['bedrooms'].astype("Float64").astype("Int64")

apartment_rent_df["square_feet"] = apartment_rent_df["square_feet"].replace(["NJ","CA"], np.nan)
apartment_rent_df = apartment_rent_df.astype({"square_feet": "Float64", }).astype({"square_feet": "Int64", })

apartment_rent_df["state"] = apartment_rent_df["state"].replace(["RentDigs.com"], np.nan)
apartment_rent_df = apartment_rent_df.astype({"state": "object", })

cols_to_keep = ['category', 'bathrooms', 'bedrooms',   'amenities',
       'currency', 'fee', 'has_photo', 'pets_allowed', 'price',
       'price_type', 'square_feet',   'cityname',
       'state',  'source',  ]
# removed: {'address', 'body', 'latitude', 'longitude', 'price_display', 'time', 'title'}
apartment_rent_new_df = apartment_rent_df[cols_to_keep]
apartment_rent_new_df

,category,bathrooms,bedrooms,amenities,currency,fee,has_photo,pets_allowed,price,price_type,square_feet,cityname,state,source
0,housing/rent/apartment,1.0,1,NaN,USD,No,Thumbnail,Cats,2195.0,Monthly,542,Redondo Beach,CA,RentLingo
1,housing/rent/apartment,1.5,3,NaN,USD,No,Thumbnail,"Cats,Dogs",1250.0,Monthly,1500,Newport News,VA,RentLingo
2,housing/rent/apartment,2.0,3,NaN,USD,No,Thumbnail,NaN,1395.0,Monthly,1650,Raleigh,NC,RentLingo
3,housing/rent/apartment,1.0,2,NaN,USD,No,Thumbnail,"Cats,Dogs",1600.0,Monthly,820,Vacaville,CA,RentLingo
4,housing/rent/apartment,1.0,1,NaN,USD,No,Thumbnail,"Cats,Dogs",975.0,Monthly,624,Albuquerque,NM,RentLingo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99821,housing/rent/apartment,1.0,1,"Gym,Parking,Patio/Deck,Playground,Storage,Wood...",USD,No,Yes,NaN,780.0,Monthly,605,Houston,TX,RentDigs.com
99822,housing/rent/apartment,2.0,2,"AC,Cable or Satellite,Clubhouse,Dishwasher,Gym...",USD,No,Yes,"Cats,Dogs",813.0,Monthly,921,Jacksonville,FL,RentDigs.com
99823,housing/rent/apartment,1.0,1,"Garbage Disposal,Refrigerator",USD,No,Yes,"Cats,Dogs",1325.0,Monthly,650,San Diego,CA,RentDigs.com
99824,housing/rent/apartment,1.0,1,"Gym,Pool",USD,No,Yes,"Cats,Dogs",931.0,Monthly,701,Huntersville,NC,RentDigs.com
99825,housing/rent/apartment,1.5,2,"Gated,Parking,Wood Floors",USD,No,Yes,NaN,1595.0,Monthly,900,San Diego,CA,RentDigs.com

In [9]:
# get_df_info_pd(apartment_rent_new_df.drop("amenities",axis=1))

### Covertype

In [10]:
covertype_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(name="covertype", source="uci", df_type="polars")
covertype_df

shape: (581_012, 55)
┌───────────┬────────┬───────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ Elevation ┆ Aspect ┆ Slope ┆ Horizontal_ ┆ … ┆ Wilderness ┆ Wilderness ┆ Wilderness ┆ Cover_Type │
│ ---       ┆ ---    ┆ ---   ┆ Distance_To ┆   ┆ _Area2     ┆ _Area3     ┆ _Area4     ┆ ---        │
│ i64       ┆ i64    ┆ i64   ┆ _Hydrolo…   ┆   ┆ ---        ┆ ---        ┆ ---        ┆ i64        │
│           ┆        ┆       ┆ ---         ┆   ┆ i64        ┆ i64        ┆ i64        ┆            │
│           ┆        ┆       ┆ i64         ┆   ┆            ┆            ┆            ┆            │
╞═══════════╪════════╪═══════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 2596      ┆ 51     ┆ 3     ┆ 258         ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 5          │
│ 2590      ┆ 56     ┆ 2     ┆ 212         ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 5          │
│ 2804      ┆ 139    ┆ 9     ┆ 268         ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 2          │
│ 2785      ┆ 155    ┆ 18    ┆ 242         ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 2          │
│ 2595      ┆ 45     ┆ 2     ┆ 153         ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 5          │
│ …         ┆ …      ┆ …     ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 2396      ┆ 153    ┆ 20    ┆ 85          ┆ … ┆ 0          ┆ 1          ┆ 0          ┆ 3          │
│ 2391      ┆ 152    ┆ 19    ┆ 67          ┆ … ┆ 0          ┆ 1          ┆ 0          ┆ 3          │
│ 2386      ┆ 159    ┆ 17    ┆ 60          ┆ … ┆ 0          ┆ 1          ┆ 0          ┆ 3          │
│ 2384      ┆ 170    ┆ 15    ┆ 60          ┆ … ┆ 0          ┆ 1          ┆ 0          ┆ 3          │
│ 2383      ┆ 165    ┆ 13    ┆ 60          ┆ … ┆ 0          ┆ 1          ┆ 0          ┆ 3          │
└───────────┴────────┴───────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [13]:
# get the number of unique values in each column:
covertype_df.select(pl.all().n_unique())

shape: (1, 55)
┌───────────┬────────┬───────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ Elevation ┆ Aspect ┆ Slope ┆ Horizontal_ ┆ … ┆ Wilderness ┆ Wilderness ┆ Wilderness ┆ Cover_Type │
│ ---       ┆ ---    ┆ ---   ┆ Distance_To ┆   ┆ _Area2     ┆ _Area3     ┆ _Area4     ┆ ---        │
│ u32       ┆ u32    ┆ u32   ┆ _Hydrolo…   ┆   ┆ ---        ┆ ---        ┆ ---        ┆ u32        │
│           ┆        ┆       ┆ ---         ┆   ┆ u32        ┆ u32        ┆ u32        ┆            │
│           ┆        ┆       ┆ u32         ┆   ┆            ┆            ┆            ┆            │
╞═══════════╪════════╪═══════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 1978      ┆ 361    ┆ 67    ┆ 551         ┆ … ┆ 2          ┆ 2          ┆ 2          ┆ 7          │
└───────────┴────────┴───────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [16]:
catCols = ['Soil_Type1',
 'Soil_Type2',
 'Soil_Type3',
 'Soil_Type4',
 'Soil_Type5',
 'Soil_Type6',
 'Soil_Type7',
 'Soil_Type8',
 'Soil_Type9',
 'Soil_Type10',
 'Soil_Type11',
 'Soil_Type12',
 'Soil_Type13',
 'Soil_Type14',
 'Soil_Type15',
 'Soil_Type16',
 'Soil_Type17',
 'Soil_Type18',
 'Soil_Type19',
 'Soil_Type20',
 'Soil_Type21',
 'Soil_Type22',
 'Soil_Type23',
 'Soil_Type24',
 'Soil_Type25',
 'Soil_Type26',
 'Soil_Type27',
 'Soil_Type28',
 'Soil_Type29',
 'Soil_Type30',
 'Soil_Type31',
 'Soil_Type32',
 'Soil_Type33',
 'Soil_Type34',
 'Soil_Type35',
 'Soil_Type36',
 'Soil_Type37',
 'Soil_Type38',
 'Soil_Type39',
 'Soil_Type40',
 'Wilderness_Area2',
 'Wilderness_Area3',
 'Wilderness_Area4',
 'Cover_Type']

In [17]:
covertype_df = covertype_df.with_columns(pl.col(catCols).cast(pl.Utf8))

In [19]:
# get_df_info_pl(covertype_df)

In [179]:
# covertype["data"]["features"].nunique()
# covertype["data"]["features"].dtypes

## C'est fini