In [1]:
import os
import json
import numpy as np
import polars as pl
import pandas as pd
from ucimlrepo import fetch_ucirepo
import pickle

import kagglehub
from kagglehub import KaggleDatasetAdapter
# from kaggle.api.kaggle_api_extended import KaggleApi

import mixtabank
from mixtabank.src.utils import (
    dataset_loader,
    get_df_info_pl,
    get_df_info_pd,
    pl_train_valid_test_split,
    get_pl_metadata,
)

/opt/miniconda3/envs/mixtabank/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## MixTaBank Datasets Loading Walkthrough

Mixtabank datasets dictionary per repository:

In [2]:
mixtabank.uci_dict
# mixtabank.kaggle_dict

{'bank-marketing': {'uci_id': 222,
  'name': 'Bank Marketing',
  'repository_url': 'https://archive.ics.uci.edu/dataset/222/bank+marketing',
  'data_url': 'https://archive.ics.uci.edu/static/public/222/data.csv',
  'target_col': 'y',
  'prediction_task': 'binary_classification',
  'shape': [45211, 17],
  'types': {'intCols': 7,
   'floatCols': 0,
   'bool/binCols': 5,
   'multi-classCols': 6},
  'total_cardinality': 46},
 'adult-census': {'uci_id': 2,
  'name': 'Adult',
  'repository_url': 'https://archive.ics.uci.edu/dataset/2/adult',
  'data_url': 'https://archive.ics.uci.edu/static/public/2/adult.data',
  'target_col': 'income',
  'prediction_task': 'binary_classification',
  'shape': [48842, 15],
  'types': {'intCols': 6,
   'floatCols': 0,
   'bool/binCols': 2,
   'multi-classCols': 7},
  'total_cardinality': 107},
 'credit-defualt-taiwan': {'uci_id': 350,
  'name': 'Default of Credit Card Clients',
  'repository_url': 'https://archive.ics.uci.edu/dataset/350/default+of+credit+card+clients',
  'data_url': 'https://archive.ics.uci.edu/static/public/350/default+of+credit+card+clients.data',
  'target_col': 'Y',
  'prediction_task': 'binary_classification',
  'shape': [30000, 24],
  'types': {'intCols': 20,
   'floatCols': 0,
   'bool/binCols': 2,
   'multi-classCols': 2},
  'total_cardinality': 15},
 'cdc_diabetes': {'uci_id': 891,
  'name': 'CDC Diabetes Health Indicators',
  'repository_url': 'https://archive.ics.uci.edu/dataset/891/diabetes',
  'data_url': 'https://archive.ics.uci.edu/static/public/891/diabetes.data',
  'target_col': 'Diabetes_binary',
  'prediction_task': 'binary_classification',
  'shape': [253680, 22],
  'types': {'intCols': 7,
   'floatCols': 0,
   'bool/binCols': 15,
   'multi-classCols': 0},
  'total_cardinality': 30},
 'census-income_full': {'uci_id': 117,
  'name': 'Census Income (KDD)',
  'repository_url': 'https://archive.ics.uci.edu/dataset/117/census+income+kdd',
  'data_url': 'https://archive.ics.uci.edu/static/public/117/census+income+kdd.data',
  'target_col': 'income',
  'prediction_task': 'binary_classification',
  'shape': [199523, 42],
  'types': {'intCols': 12,
   'floatCols': 12,
   'bool/binCols': 2,
   'multi-classCols': 27},
  'total_cardinality': 398},
 'support2': {'uci_id': 880,
  'name': 'SUPPORT2',
  'repository_url': 'https://archive.ics.uci.edu/dataset/880/support2',
  'data_url': 'https://archive.ics.uci.edu/static/public/880/support2.data',
  'target_col': 'death',
  'prediction_task': 'binary_classification',
  'shape': [9105, 45],
  'types': {'intCols': 6,
   'floatCols': 31,
   'bool/binCols': 1,
   'multi-classCols': 7},
  'total_cardinality': 38},
 'diabetes_130us': {'uci_id': 296,
  'name': 'Diabetes 130-US hospitals for years 1999-2008',
  'repository_url': 'https://archive.ics.uci.edu/dataset/296/diabetes+130-us+hospitals+for+years+1999-2008',
  'data_url': 'https://archive.ics.uci.edu/static/public/296/diabetes+130-us+hospitals+for+years+1999-2008.data',
  'target_col': 'readmitted',
  'prediction_task': 'binary_classification',
  'shape': [101766, 48],
  'types': {'intCols': 11,
   'floatCols': 0,
   'bool/binCols': 9,
   'multi-classCols': 26},
  'total_cardinality': 2462},
 'nursery': {'uci_id': 76,
  'name': 'Nursery',
  'repository_url': 'https://archive.ics.uci.edu/dataset/76/nursery',
  'data_url': 'https://archive.ics.uci.edu/dataset/76/nursery.data',
  'target_col': 'class',
  'prediction_task': 'multi_class_classification',
  'shape': [12960, 9],
  'types': {'intCols': 0,
   'floatCols': 0,
   'bool/binCols': 1,
   'multi-classCols': 8},
  'total_cardinality': 32},
 'taiwanese_bankruptcy': {'uci_id': 572,
  'name': 'Taiwanese Bankruptcy',
  'repository_url': 'https://archive.ics.uci.edu/dataset/572/taiwanese+bankruptcy+prediction',
  'data_url': 'https://archive.ics.uci.edu/dataset/572/taiwanese+bankruptcy+prediction.data',
  'target_col': 'Bankrupt?',
  'prediction_task': 'binary_classification',
  'shape': [6819, 95],
  'types': {'intCols': 0,
   'floatCols': 93,
   'bool/binCols': 2,
   'multi-classCols': 0},
  'total_cardinality': 4},
 'apartment_rent_classified': {'uci_id': 555,
  'name': 'Apartment Rent Classified',
  'repository_url': 'https://archive.ics.uci.edu/dataset/555/apartment+for+rent+classified',
  'data_url': 'https://archive.ics.uci.edu/dataset/555/apartment+for+rent+classified.data',
  'target_col': ['square_feet', 'price'],
  'prediction_task': 'regression',
  'shape': [99826, 14],
  'types': {'intCols': 2,
   'floatCols': 2,
   'bool/binCols': 0,
   'multi-classCols': 10},
  'total_cardinality': 4},
 'covertype': {'uci_id': 31,
  'name': 'Covertype',
  'repository_url': 'https://archive.ics.uci.edu/dataset/31/covertype',
  'data_url': 'https://archive.ics.uci.edu/dataset/31/covertype.data',
  'target_col': 'Cover_Type',
  'prediction_task': 'multi_class_classification',
  'shape': [581012, 55],
  'types': {'intCols': 11,
   'floatCols': 0,
   'bool/binCols': 43,
   'multi-classCols': 1},
  'total_cardinality': 93},
 'beijing_pm25': {'uci_id': 381,
  'name': 'Beijing PM2.5 Data',
  'repository_url': 'https://archive.ics.uci.edu/dataset/381/beijing+pm2+5+data',
  'data_url': 'https://archive.ics.uci.edu/dataset/381/beijing+pm2+5+data',
  'target_col': 'pm2.5',
  'prediction_task': 'regression',
  'shape': [43824, 11],
  'types': {'intCols': 10,
   'floatCols': 1,
   'bool/binCols': 0,
   'multi-classCols': 1},
  'total_cardinality': 0},
 'magic': {'uci_id': 381,
  'name': 'Magic Gamma Telescope Data',
  'repository_url': 'https://archive.ics.uci.edu/dataset/159/magic+gamma+telescope',
  'data_url': 'https://archive.ics.uci.edu/dataset/159/magic+gamma+telescope+data',
  'target_col': 'class',
  'prediction_task': 'binary_classification',
  'shape': [19020, 11],
  'types': {'intCols': 0,
   'floatCols': 10,
   'bool/binCols': 1,
   'multi-classCols': 0},
  'total_cardinality': 0}}

## Kaggle

### Home Credit Default Risk

In [131]:
home_credit_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(
    name="home-credit", source="kaggle", df_type="polars"
)

home_credit_df = home_credit_df.cast({"TARGET": pl.Utf8, "AMT_INCOME_TOTAL": pl.Int64, "AMT_GOODS_PRICE": pl.Int64})

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).

In [132]:
home_credit_df

shape: (307_511, 122)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ SK_ID_CURR ┆ TARGET ┆ NAME_CONTR ┆ CODE_GEND ┆ … ┆ AMT_REQ_C ┆ AMT_REQ_C ┆ AMT_REQ_C ┆ AMT_REQ_C │
│ ---        ┆ ---    ┆ ACT_TYPE   ┆ ER        ┆   ┆ REDIT_BUR ┆ REDIT_BUR ┆ REDIT_BUR ┆ REDIT_BUR │
│ i64        ┆ str    ┆ ---        ┆ ---       ┆   ┆ EAU_WEEK  ┆ EAU_MON   ┆ EAU_QRT   ┆ EAU_YEAR  │
│            ┆        ┆ str        ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆        ┆            ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 100002     ┆ 1      ┆ Cash loans ┆ M         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0       │
│ 100003     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 100004     ┆ 0      ┆ Revolving  ┆ M         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│            ┆        ┆ loans      ┆           ┆   ┆           ┆           ┆           ┆           │
│ 100006     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 100007     ┆ 0      ┆ Cash loans ┆ M         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ …          ┆ …      ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 456251     ┆ 0      ┆ Cash loans ┆ M         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 456252     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 456253     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ 0.0       ┆ 1.0       ┆ 0.0       ┆ 1.0       │
│ 456254     ┆ 1      ┆ Cash loans ┆ F         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 456255     ┆ 0      ┆ Cash loans ┆ F         ┆ … ┆ 0.0       ┆ 2.0       ┆ 0.0       ┆ 1.0       │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [133]:
home_credit_df.select(pl.all().n_unique())

shape: (1, 122)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ SK_ID_CURR ┆ TARGET ┆ NAME_CONTR ┆ CODE_GEND ┆ … ┆ AMT_REQ_C ┆ AMT_REQ_C ┆ AMT_REQ_C ┆ AMT_REQ_C │
│ ---        ┆ ---    ┆ ACT_TYPE   ┆ ER        ┆   ┆ REDIT_BUR ┆ REDIT_BUR ┆ REDIT_BUR ┆ REDIT_BUR │
│ u32        ┆ u32    ┆ ---        ┆ ---       ┆   ┆ EAU_WEEK  ┆ EAU_MON   ┆ EAU_QRT   ┆ EAU_YEAR  │
│            ┆        ┆ u32        ┆ u32       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆        ┆            ┆           ┆   ┆ u32       ┆ u32       ┆ u32       ┆ u32       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 307511     ┆ 2      ┆ 2          ┆ 3         ┆ … ┆ 10        ┆ 25        ┆ 12        ┆ 26        │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [134]:
credit_col_list = [
    "NAME_CONTRACT_TYPE",
    "CODE_GENDER",
    "FLAG_OWN_CAR",
    "FLAG_OWN_REALTY",
    "NAME_TYPE_SUITE",
    "NAME_INCOME_TYPE",
    "NAME_EDUCATION_TYPE",
    "NAME_FAMILY_STATUS",
    "NAME_HOUSING_TYPE",
    "OCCUPATION_TYPE",
    "WEEKDAY_APPR_PROCESS_START",
    "ORGANIZATION_TYPE",
    # 'FONDKAPREMONT_MODE', 'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE',  'EMERGENCYSTATE_MODE', # introduce a lot of nans
    "AMT_INCOME_TOTAL",
    "AMT_CREDIT",
    "AMT_ANNUITY",
    "AMT_GOODS_PRICE",
    "TARGET",
]
home_credit_df = home_credit_df[credit_col_list].drop_nulls()
home_credit_df
# home_credit_df = home_credit_df.with_columns(pl.col("TARGET").cast(str))

shape: (210_201, 17)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬────────┐
│ NAME_CONTR ┆ CODE_GENDE ┆ FLAG_OWN_ ┆ FLAG_OWN_ ┆ … ┆ AMT_CREDI ┆ AMT_ANNUI ┆ AMT_GOODS ┆ TARGET │
│ ACT_TYPE   ┆ R          ┆ CAR       ┆ REALTY    ┆   ┆ T         ┆ TY        ┆ _PRICE    ┆ ---    │
│ ---        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str    │
│ str        ┆ str        ┆ str       ┆ str       ┆   ┆ f64       ┆ f64       ┆ i64       ┆        │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪════════╡
│ Cash loans ┆ M          ┆ N         ┆ Y         ┆ … ┆ 406597.5  ┆ 24700.5   ┆ 351000    ┆ 1      │
│ Cash loans ┆ F          ┆ N         ┆ N         ┆ … ┆ 1293502.5 ┆ 35698.5   ┆ 1129500   ┆ 0      │
│ Revolving  ┆ M          ┆ Y         ┆ Y         ┆ … ┆ 135000.0  ┆ 6750.0    ┆ 135000    ┆ 0      │
│ loans      ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆        │
│ Cash loans ┆ F          ┆ N         ┆ Y         ┆ … ┆ 312682.5  ┆ 29686.5   ┆ 297000    ┆ 0      │
│ Cash loans ┆ M          ┆ N         ┆ Y         ┆ … ┆ 513000.0  ┆ 21865.5   ┆ 513000    ┆ 0      │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …      │
│ Cash loans ┆ F          ┆ N         ┆ Y         ┆ … ┆ 331920.0  ┆ 16096.5   ┆ 225000    ┆ 0      │
│ Cash loans ┆ M          ┆ N         ┆ N         ┆ … ┆ 254700.0  ┆ 27558.0   ┆ 225000    ┆ 0      │
│ Cash loans ┆ F          ┆ N         ┆ Y         ┆ … ┆ 677664.0  ┆ 29979.0   ┆ 585000    ┆ 0      │
│ Cash loans ┆ F          ┆ N         ┆ Y         ┆ … ┆ 370107.0  ┆ 20205.0   ┆ 319500    ┆ 1      │
│ Cash loans ┆ F          ┆ N         ┆ N         ┆ … ┆ 675000.0  ┆ 49117.5   ┆ 675000    ┆ 0      │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴────────┘

In [135]:
# Get metadata for Polars DataFrame
pl_metadata = get_pl_metadata(home_credit_df)
# pp(pl_metadata)

# Retrieves column types from metadata
catCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "categorical"]
intCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "numerical" and v["subtype"] == "int"]
floatCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "numerical" and v["subtype"] == "float"]
binCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "categorical" and v["subtype"] == "binary"]
numCols = intCols + floatCols
print("catCols: ", catCols)
print("intCols: ", intCols)
print("floatCols: ", floatCols)
print("binCols: ", binCols)
print("numCols: ", numCols)
print("target_col: ", target_col_name)

catCols:  ['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE', 'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE', 'TARGET']
intCols:  ['AMT_INCOME_TOTAL', 'AMT_GOODS_PRICE']
floatCols:  ['AMT_CREDIT', 'AMT_ANNUITY']
binCols:  ['NAME_CONTRACT_TYPE', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'TARGET']
numCols:  ['AMT_INCOME_TOTAL', 'AMT_GOODS_PRICE', 'AMT_CREDIT', 'AMT_ANNUITY']
target_col:  TARGET

In [136]:
home_credit_df.shape == home_credit_df.drop_nulls().shape

True

In [137]:
catCols_noTarget = [j for j in catCols if j != target_col_name]
print("catCols_noTarget: ", catCols_noTarget)  # catCols_noTarget

catCols_noTarget:  ['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE', 'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE']

In [138]:
num_col_idx = [i for i, col in enumerate(home_credit_df.columns) if col in numCols]
cat_col_idx = [i for i, col in enumerate(home_credit_df.columns) if col in catCols_noTarget]
target_col_idx = home_credit_df.columns.index(target_col_name)
cat_col_idx, num_col_idx, target_col_idx

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], [12, 13, 14, 15], 16)

In [139]:
home_credit_df = home_credit_df.select(catCols_noTarget + numCols + [target_col_name])
home_credit_df

shape: (210_201, 17)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬────────┐
│ NAME_CONTR ┆ CODE_GENDE ┆ FLAG_OWN_ ┆ FLAG_OWN_ ┆ … ┆ AMT_GOODS ┆ AMT_CREDI ┆ AMT_ANNUI ┆ TARGET │
│ ACT_TYPE   ┆ R          ┆ CAR       ┆ REALTY    ┆   ┆ _PRICE    ┆ T         ┆ TY        ┆ ---    │
│ ---        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str    │
│ str        ┆ str        ┆ str       ┆ str       ┆   ┆ i64       ┆ f64       ┆ f64       ┆        │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪════════╡
│ Cash loans ┆ M          ┆ N         ┆ Y         ┆ … ┆ 351000    ┆ 406597.5  ┆ 24700.5   ┆ 1      │
│ Cash loans ┆ F          ┆ N         ┆ N         ┆ … ┆ 1129500   ┆ 1293502.5 ┆ 35698.5   ┆ 0      │
│ Revolving  ┆ M          ┆ Y         ┆ Y         ┆ … ┆ 135000    ┆ 135000.0  ┆ 6750.0    ┆ 0      │
│ loans      ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆        │
│ Cash loans ┆ F          ┆ N         ┆ Y         ┆ … ┆ 297000    ┆ 312682.5  ┆ 29686.5   ┆ 0      │
│ Cash loans ┆ M          ┆ N         ┆ Y         ┆ … ┆ 513000    ┆ 513000.0  ┆ 21865.5   ┆ 0      │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …      │
│ Cash loans ┆ F          ┆ N         ┆ Y         ┆ … ┆ 225000    ┆ 331920.0  ┆ 16096.5   ┆ 0      │
│ Cash loans ┆ M          ┆ N         ┆ N         ┆ … ┆ 225000    ┆ 254700.0  ┆ 27558.0   ┆ 0      │
│ Cash loans ┆ F          ┆ N         ┆ Y         ┆ … ┆ 585000    ┆ 677664.0  ┆ 29979.0   ┆ 0      │
│ Cash loans ┆ F          ┆ N         ┆ Y         ┆ … ┆ 319500    ┆ 370107.0  ┆ 20205.0   ┆ 1      │
│ Cash loans ┆ F          ┆ N         ┆ N         ┆ … ┆ 675000    ┆ 675000.0  ┆ 49117.5   ┆ 0      │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴────────┘

In [140]:
train, valid, test = pl_train_valid_test_split(home_credit_df, splits=[0.7, 0.15, 0.15], seed=420)

print("Train shape:", train.shape, "Valid shape:", valid.shape, "Test shape:", test.shape)

Train shape: (147140, 17) Valid shape: (31530, 17) Test shape: (31531, 17)

In [141]:
#### save the datasets as parquet:
info = get_df_info_pl(home_credit_df)

home_credit_path = "/Users/leec/Documents/datasets/parquet/home_credit/"
# make sure the output directory exists, and create it if it doesn't:
os.makedirs(home_credit_path, exist_ok=True)

home_credit_train_output_path = os.path.join(home_credit_path, "home_credit_train.parquet")
home_credit_valid_output_path = os.path.join(home_credit_path, "home_credit_valid.parquet")
home_credit_test_output_path = os.path.join(home_credit_path, "home_credit_test.parquet")

train.write_parquet(home_credit_train_output_path)
valid.write_parquet(home_credit_valid_output_path)
test.write_parquet(home_credit_test_output_path)


# create an `info.json` file with the metadata information:
metadata = {
    "name": "home_credit",
    "task_type": "binclass", # binclass, multiclass, regression 
    "target_col_name": target_col_name,
    "train_size": train.shape[0],
    "val_size": valid.shape[0],
    "test_size": test.shape[0],
    "catCols": info["catCols"],
    "intCols": info["intCols"],
    "floatCols": info["floatCols"]   
}

metadata_output_path = os.path.join(home_credit_path, "info.json")
with open(metadata_output_path, "w") as f:
    json.dump(metadata, f, indent=4)
    
metadata

DataFrame shape: (210201, 17)
Data types (according to dtypes):
Number of numerical columns: 4:
['AMT_INCOME_TOTAL', 'AMT_GOODS_PRICE', 'AMT_CREDIT', 'AMT_ANNUITY']
  - Integer columns: 2: ['AMT_INCOME_TOTAL', 'AMT_GOODS_PRICE']
  - Float columns: 2: ['AMT_CREDIT', 'AMT_ANNUITY']
Number of categorical columns: 13:
['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE', 'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE', 'TARGET']
  - Multiclass columns: 9: ['CODE_GENDER', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE', 'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE']
  - Binary columns: 4: ['NAME_CONTRACT_TYPE', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'TARGET']
  - Boolean columns: 0: []
Total categorical cardinality: 123
Total types count:
total numerical: 4 (int: 2, float: 2),
Total categorical: 13 (multi-class: 9, bin_cat: 4, bool_cat: 0):
Columns with missing values: 0

{'name': 'home_credit',
 'task_type': 'binclass',
 'target_col_name': 'TARGET',
 'train_size': 147140,
 'val_size': 31530,
 'test_size': 31531,
 'catCols': ['NAME_CONTRACT_TYPE',
  'CODE_GENDER',
  'FLAG_OWN_CAR',
  'FLAG_OWN_REALTY',
  'NAME_TYPE_SUITE',
  'NAME_INCOME_TYPE',
  'NAME_EDUCATION_TYPE',
  'NAME_FAMILY_STATUS',
  'NAME_HOUSING_TYPE',
  'OCCUPATION_TYPE',
  'WEEKDAY_APPR_PROCESS_START',
  'ORGANIZATION_TYPE',
  'TARGET'],
 'intCols': ['AMT_INCOME_TOTAL', 'AMT_GOODS_PRICE'],
 'floatCols': ['AMT_CREDIT', 'AMT_ANNUITY']}

In [75]:
# save the datasets as pickle:
home_credit_output_path = "/Users/leec/Documents/datasets/home_credit/"
# make sure the output directory exists, and create it if it doesn't:
os.makedirs(home_credit_output_path, exist_ok=True)

home_credit_train_output_path = os.path.join(home_credit_output_path, "home_credit_train.pkl")
home_credit_valid_output_path = os.path.join(home_credit_output_path, "home_credit_valid.pkl")
home_credit_test_output_path = os.path.join(home_credit_output_path, "home_credit_test.pkl")

# pickle the datasets:
with open(home_credit_train_output_path, "wb") as f:
    pickle.dump(train, f)
with open(home_credit_valid_output_path, "wb") as f:
    pickle.dump(valid, f)
with open(home_credit_test_output_path, "wb") as f:
    pickle.dump(test, f)


## also save as csv:

home_credit_train_output_path = os.path.join(home_credit_output_path, "home_credit_train.csv")
home_credit_valid_output_path = os.path.join(home_credit_output_path, "home_credit_valid.csv")
home_credit_test_output_path = os.path.join(home_credit_output_path, "home_credit_test.csv")

train.write_csv(home_credit_train_output_path)
valid.write_csv(home_credit_valid_output_path)
test.write_csv(home_credit_test_output_path)

In [77]:
tmp = get_df_info_pl(home_credit_df)

DataFrame shape: (210201, 17)
Data types (according to dtypes):
Number of numerical columns: 4:
['AMT_INCOME_TOTAL', 'AMT_GOODS_PRICE', 'AMT_CREDIT', 'AMT_ANNUITY']
  - Integer columns: 2: ['AMT_INCOME_TOTAL', 'AMT_GOODS_PRICE']
  - Float columns: 2: ['AMT_CREDIT', 'AMT_ANNUITY']
Number of categorical columns: 13:
['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE', 'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE', 'TARGET']
  - Multiclass columns: 9: ['CODE_GENDER', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE', 'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE']
  - Binary columns: 4: ['NAME_CONTRACT_TYPE', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'TARGET']
  - Boolean columns: 0: []
Total categorical cardinality: 123
Total types count:
total numerical: 4 (int: 2, float: 2),
Total categorical: 13 (multi-class: 9, bin_cat: 4, bool_cat: 0):
Columns with missing values: 0

In [78]:
home_credit_df.columns

['NAME_CONTRACT_TYPE',
 'CODE_GENDER',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'NAME_TYPE_SUITE',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'OCCUPATION_TYPE',
 'WEEKDAY_APPR_PROCESS_START',
 'ORGANIZATION_TYPE',
 'AMT_INCOME_TOTAL',
 'AMT_GOODS_PRICE',
 'AMT_CREDIT',
 'AMT_ANNUITY',
 'TARGET']

### MIMIC iii

In [155]:
mimic_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(
    name="mimic-iii", source="kaggle", df_type="polars"
)
mimic_df = mimic_df.cast({"ICD9_CODE": pl.Utf8,})

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).

In [156]:
target_col_name,prediction_task

('DISCHARGE_LOCATION', 'multi-class_classification')

In [157]:
mimic_df

shape: (556_617, 11)
┌────────┬─────────────┬─────┬─────────────┬───┬───────────┬─────────────┬─────────────┬───────────┐
│ GENDER ┆ icu_length_ ┆ age ┆ ADMISSION_T ┆ … ┆ ETHNICITY ┆ DIAGNOSIS   ┆ DRUG        ┆ ICD9_CODE │
│ ---    ┆ of_stay     ┆ --- ┆ YPE         ┆   ┆ ---       ┆ ---         ┆ ---         ┆ ---       │
│ str    ┆ ---         ┆ i64 ┆ ---         ┆   ┆ str       ┆ str         ┆ str         ┆ str       │
│        ┆ i64         ┆     ┆ str         ┆   ┆           ┆             ┆             ┆           │
╞════════╪═════════════╪═════╪═════════════╪═══╪═══════════╪═════════════╪═════════════╪═══════════╡
│ F      ┆ 52          ┆ 74  ┆ EMERGENCY   ┆ … ┆ WHITE     ┆ HUMERAL     ┆ Cefazolin   ┆ 8181      │
│        ┆             ┆     ┆             ┆   ┆           ┆ FRACTURE    ┆             ┆           │
│ F      ┆ 52          ┆ 74  ┆ EMERGENCY   ┆ … ┆ WHITE     ┆ HUMERAL     ┆ Cefazolin   ┆ 9904      │
│        ┆             ┆     ┆             ┆   ┆           ┆ FRACTURE    ┆             ┆           │
│ F      ┆ 52          ┆ 74  ┆ EMERGENCY   ┆ … ┆ WHITE     ┆ HUMERAL     ┆ Magnesium   ┆ 8181      │
│        ┆             ┆     ┆             ┆   ┆           ┆ FRACTURE    ┆ Sulfate     ┆           │
│ F      ┆ 52          ┆ 74  ┆ EMERGENCY   ┆ … ┆ WHITE     ┆ HUMERAL     ┆ Magnesium   ┆ 9904      │
│        ┆             ┆     ┆             ┆   ┆           ┆ FRACTURE    ┆ Sulfate     ┆           │
│ F      ┆ 52          ┆ 74  ┆ EMERGENCY   ┆ … ┆ WHITE     ┆ HUMERAL     ┆ 1/2 NS      ┆ 8181      │
│        ┆             ┆     ┆             ┆   ┆           ┆ FRACTURE    ┆             ┆           │
│ …      ┆ …           ┆ …   ┆ …           ┆ … ┆ …         ┆ …           ┆ …           ┆ …         │
│ F      ┆ 18          ┆ 20  ┆ EMERGENCY   ┆ … ┆ OTHER     ┆ STATUS POST ┆ Morphine    ┆ 8659      │
│        ┆             ┆     ┆             ┆   ┆           ┆ MOTOR       ┆ Sulfate     ┆           │
│        ┆             ┆     ┆             ┆   ┆           ┆ VEHICLE     ┆             ┆           │
│        ┆             ┆     ┆             ┆   ┆           ┆ ACCI…       ┆             ┆           │
│ F      ┆ 18          ┆ 20  ┆ EMERGENCY   ┆ … ┆ OTHER     ┆ STATUS POST ┆ Potassium   ┆ 118       │
│        ┆             ┆     ┆             ┆   ┆           ┆ MOTOR       ┆ Chloride    ┆           │
│        ┆             ┆     ┆             ┆   ┆           ┆ VEHICLE     ┆             ┆           │
│        ┆             ┆     ┆             ┆   ┆           ┆ ACCI…       ┆             ┆           │
│ F      ┆ 18          ┆ 20  ┆ EMERGENCY   ┆ … ┆ OTHER     ┆ STATUS POST ┆ Potassium   ┆ 3891      │
│        ┆             ┆     ┆             ┆   ┆           ┆ MOTOR       ┆ Chloride    ┆           │
│        ┆             ┆     ┆             ┆   ┆           ┆ VEHICLE     ┆             ┆           │
│        ┆             ┆     ┆             ┆   ┆           ┆ ACCI…       ┆             ┆           │
│ F      ┆ 18          ┆ 20  ┆ EMERGENCY   ┆ … ┆ OTHER     ┆ STATUS POST ┆ Potassium   ┆ 3893      │
│        ┆             ┆     ┆             ┆   ┆           ┆ MOTOR       ┆ Chloride    ┆           │
│        ┆             ┆     ┆             ┆   ┆           ┆ VEHICLE     ┆             ┆           │
│        ┆             ┆     ┆             ┆   ┆           ┆ ACCI…       ┆             ┆           │
│ F      ┆ 18          ┆ 20  ┆ EMERGENCY   ┆ … ┆ OTHER     ┆ STATUS POST ┆ Potassium   ┆ 8659      │
│        ┆             ┆     ┆             ┆   ┆           ┆ MOTOR       ┆ Chloride    ┆           │
│        ┆             ┆     ┆             ┆   ┆           ┆ VEHICLE     ┆             ┆           │
│        ┆             ┆     ┆             ┆   ┆           ┆ ACCI…       ┆             ┆           │
└────────┴─────────────┴─────┴─────────────┴───┴───────────┴─────────────┴─────────────┴───────────┘

In [158]:
mimic_df['DISCHARGE_LOCATION'].unique().count()

10

In [159]:
tmp = get_df_info_pl(mimic_df)

DataFrame shape: (556617, 11)
Data types (according to dtypes):
Number of numerical columns: 2:
['icu_length_of_stay', 'age']
  - Integer columns: 2: ['icu_length_of_stay', 'age']
  - Float columns: 0: []
Number of categorical columns: 9:
['GENDER', 'ADMISSION_TYPE', 'ADMISSION_LOCATION', 'DISCHARGE_LOCATION', 'INSURANCE', 'ETHNICITY', 'DIAGNOSIS', 'DRUG', 'ICD9_CODE']
  - Multiclass columns: 8: ['ADMISSION_TYPE', 'ADMISSION_LOCATION', 'DISCHARGE_LOCATION', 'INSURANCE', 'ETHNICITY', 'DIAGNOSIS', 'DRUG', 'ICD9_CODE']
  - Binary columns: 1: ['GENDER']
  - Boolean columns: 0: []
Total categorical cardinality: 850
Total types count:
total numerical: 2 (int: 2, float: 0),
Total categorical: 9 (multi-class: 8, bin_cat: 1, bool_cat: 0):
Columns with missing values: 0

In [160]:
assert mimic_df.drop_nans().shape == mimic_df.shape
assert mimic_df.drop_nulls().shape == mimic_df.shape

In [161]:
# Get metadata for Polars DataFrame
pl_metadata = get_pl_metadata(mimic_df)
# pp(pl_metadata)

# Retrieves column types from metadata
catCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "categorical"]
intCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "numerical" and v["subtype"] == "int"]
floatCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "numerical" and v["subtype"] == "float"]
binCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "categorical" and v["subtype"] == "binary"]
numCols = intCols + floatCols
print("catCols: ", catCols)
print("intCols: ", intCols)
print("floatCols: ", floatCols)
print("binCols: ", binCols)
print("numCols: ", numCols)
print("target_col: ", target_col_name)

catCols:  ['GENDER', 'ADMISSION_TYPE', 'ADMISSION_LOCATION', 'DISCHARGE_LOCATION', 'INSURANCE', 'ETHNICITY', 'DIAGNOSIS', 'DRUG', 'ICD9_CODE']
intCols:  ['icu_length_of_stay', 'age']
floatCols:  []
binCols:  ['GENDER']
numCols:  ['icu_length_of_stay', 'age']
target_col:  DISCHARGE_LOCATION

In [162]:
catCols_noTarget = [j for j in catCols if j != target_col_name]
print("catCols_noTarget: ", catCols_noTarget)  # catCols_noTarget

catCols_noTarget:  ['GENDER', 'ADMISSION_TYPE', 'ADMISSION_LOCATION', 'INSURANCE', 'ETHNICITY', 'DIAGNOSIS', 'DRUG', 'ICD9_CODE']

In [163]:
mimic_df = mimic_df.select(catCols_noTarget + numCols + [target_col_name])
mimic_df

shape: (556_617, 11)
┌────────┬─────────────┬─────────────┬───────────┬───┬───────────┬─────────────┬─────┬─────────────┐
│ GENDER ┆ ADMISSION_T ┆ ADMISSION_L ┆ INSURANCE ┆ … ┆ ICD9_CODE ┆ icu_length_ ┆ age ┆ DISCHARGE_L │
│ ---    ┆ YPE         ┆ OCATION     ┆ ---       ┆   ┆ ---       ┆ of_stay     ┆ --- ┆ OCATION     │
│ str    ┆ ---         ┆ ---         ┆ str       ┆   ┆ str       ┆ ---         ┆ i64 ┆ ---         │
│        ┆ str         ┆ str         ┆           ┆   ┆           ┆ i64         ┆     ┆ str         │
╞════════╪═════════════╪═════════════╪═══════════╪═══╪═══════════╪═════════════╪═════╪═════════════╡
│ F      ┆ EMERGENCY   ┆ EMERGENCY   ┆ Medicare  ┆ … ┆ 8181      ┆ 52          ┆ 74  ┆ SNF         │
│        ┆             ┆ ROOM ADMIT  ┆           ┆   ┆           ┆             ┆     ┆             │
│ F      ┆ EMERGENCY   ┆ EMERGENCY   ┆ Medicare  ┆ … ┆ 9904      ┆ 52          ┆ 74  ┆ SNF         │
│        ┆             ┆ ROOM ADMIT  ┆           ┆   ┆           ┆             ┆     ┆             │
│ F      ┆ EMERGENCY   ┆ EMERGENCY   ┆ Medicare  ┆ … ┆ 8181      ┆ 52          ┆ 74  ┆ SNF         │
│        ┆             ┆ ROOM ADMIT  ┆           ┆   ┆           ┆             ┆     ┆             │
│ F      ┆ EMERGENCY   ┆ EMERGENCY   ┆ Medicare  ┆ … ┆ 9904      ┆ 52          ┆ 74  ┆ SNF         │
│        ┆             ┆ ROOM ADMIT  ┆           ┆   ┆           ┆             ┆     ┆             │
│ F      ┆ EMERGENCY   ┆ EMERGENCY   ┆ Medicare  ┆ … ┆ 8181      ┆ 52          ┆ 74  ┆ SNF         │
│        ┆             ┆ ROOM ADMIT  ┆           ┆   ┆           ┆             ┆     ┆             │
│ …      ┆ …           ┆ …           ┆ …         ┆ … ┆ …         ┆ …           ┆ …   ┆ …           │
│ F      ┆ EMERGENCY   ┆ EMERGENCY   ┆ Private   ┆ … ┆ 8659      ┆ 18          ┆ 20  ┆ DEAD/EXPIRE │
│        ┆             ┆ ROOM ADMIT  ┆           ┆   ┆           ┆             ┆     ┆ D           │
│ F      ┆ EMERGENCY   ┆ EMERGENCY   ┆ Private   ┆ … ┆ 118       ┆ 18          ┆ 20  ┆ DEAD/EXPIRE │
│        ┆             ┆ ROOM ADMIT  ┆           ┆   ┆           ┆             ┆     ┆ D           │
│ F      ┆ EMERGENCY   ┆ EMERGENCY   ┆ Private   ┆ … ┆ 3891      ┆ 18          ┆ 20  ┆ DEAD/EXPIRE │
│        ┆             ┆ ROOM ADMIT  ┆           ┆   ┆           ┆             ┆     ┆ D           │
│ F      ┆ EMERGENCY   ┆ EMERGENCY   ┆ Private   ┆ … ┆ 3893      ┆ 18          ┆ 20  ┆ DEAD/EXPIRE │
│        ┆             ┆ ROOM ADMIT  ┆           ┆   ┆           ┆             ┆     ┆ D           │
│ F      ┆ EMERGENCY   ┆ EMERGENCY   ┆ Private   ┆ … ┆ 8659      ┆ 18          ┆ 20  ┆ DEAD/EXPIRE │
│        ┆             ┆ ROOM ADMIT  ┆           ┆   ┆           ┆             ┆     ┆ D           │
└────────┴─────────────┴─────────────┴───────────┴───┴───────────┴─────────────┴─────┴─────────────┘

In [164]:
num_col_idx = [i for i, col in enumerate(mimic_df.columns) if col in numCols]
cat_col_idx = [i for i, col in enumerate(mimic_df.columns) if col in catCols_noTarget]
target_col_idx = mimic_df.columns.index(target_col_name)
cat_col_idx, num_col_idx, target_col_idx

([0, 1, 2, 3, 4, 5, 6, 7], [8, 9], 10)

In [165]:
train.columns

['Education',
 'Income',
 'HighBP',
 'HighChol',
 'CholCheck',
 'Smoker',
 'Stroke',
 'HeartDiseaseorAttack',
 'PhysActivity',
 'Fruits',
 'Veggies',
 'HvyAlcoholConsump',
 'AnyHealthcare',
 'NoDocbcCost',
 'DiffWalk',
 'Sex',
 'BMI',
 'GenHlth',
 'MentHlth',
 'PhysHlth',
 'Age',
 'Diabetes_binary']

In [166]:
train, valid, test = pl_train_valid_test_split(mimic_df, splits=[0.7, 0.15, 0.15], seed=420)

print("Train shape:", train.shape, "Valid shape:", valid.shape, "Test shape:", test.shape)

Train shape: (389631, 11) Valid shape: (83493, 11) Test shape: (83493, 11)

In [167]:
#### save the datasets as parquet:
info = get_df_info_pl(mimic_df)

mimic_path = "/Users/leec/Documents/datasets/parquet/mimic/"
# make sure the output directory exists, and create it if it doesn't:
os.makedirs(mimic_path, exist_ok=True)

mimic_train_output_path = os.path.join(mimic_path, "mimic_train.parquet")
mimic_valid_output_path = os.path.join(mimic_path, "mimic_valid.parquet")
mimic_test_output_path = os.path.join(mimic_path, "mimic_test.parquet")

train.write_parquet(mimic_train_output_path)
valid.write_parquet(mimic_valid_output_path)
test.write_parquet(mimic_test_output_path)


# create an `info.json` file with the metadata information:
metadata = {
    "name": "mimic",
    "task_type": "multiclass", # binclass, multiclass, regression 
    "target_col_name": target_col_name,
    "train_size": train.shape[0],
    "val_size": valid.shape[0],
    "test_size": test.shape[0],
    "catCols": info["catCols"],
    "intCols": info["intCols"],
    "floatCols": info["floatCols"]   
}

metadata_output_path = os.path.join(mimic_path, "info.json")
with open(metadata_output_path, "w") as f:
    json.dump(metadata, f, indent=4)
    
metadata

DataFrame shape: (556617, 11)
Data types (according to dtypes):
Number of numerical columns: 2:
['icu_length_of_stay', 'age']
  - Integer columns: 2: ['icu_length_of_stay', 'age']
  - Float columns: 0: []
Number of categorical columns: 9:
['GENDER', 'ADMISSION_TYPE', 'ADMISSION_LOCATION', 'INSURANCE', 'ETHNICITY', 'DIAGNOSIS', 'DRUG', 'ICD9_CODE', 'DISCHARGE_LOCATION']
  - Multiclass columns: 8: ['ADMISSION_TYPE', 'ADMISSION_LOCATION', 'INSURANCE', 'ETHNICITY', 'DIAGNOSIS', 'DRUG', 'ICD9_CODE', 'DISCHARGE_LOCATION']
  - Binary columns: 1: ['GENDER']
  - Boolean columns: 0: []
Total categorical cardinality: 850
Total types count:
total numerical: 2 (int: 2, float: 0),
Total categorical: 9 (multi-class: 8, bin_cat: 1, bool_cat: 0):
Columns with missing values: 0

{'name': 'mimic',
 'task_type': 'multiclass',
 'target_col_name': 'DISCHARGE_LOCATION',
 'train_size': 389631,
 'val_size': 83493,
 'test_size': 83493,
 'catCols': ['GENDER',
  'ADMISSION_TYPE',
  'ADMISSION_LOCATION',
  'INSURANCE',
  'ETHNICITY',
  'DIAGNOSIS',
  'DRUG',
  'ICD9_CODE',
  'DISCHARGE_LOCATION'],
 'intCols': ['icu_length_of_stay', 'age'],
 'floatCols': []}

In [22]:
# save the datasets as pickle:
mimic_df_output_path = "/Users/leec/Documents/datasets/mimic/"
# make sure the output directory exists, and create it if it doesn't:
os.makedirs(mimic_df_output_path, exist_ok=True)

mimic_df_train_output_path = os.path.join(mimic_df_output_path, "mimic_train.pkl")
mimic_df_valid_output_path = os.path.join(mimic_df_output_path, "mimic_valid.pkl")
mimic_df_test_output_path = os.path.join(mimic_df_output_path, "mimic_test.pkl")

# pickle the datasets:
with open(mimic_df_train_output_path, "wb") as f:
    pickle.dump(train, f)
with open(mimic_df_valid_output_path, "wb") as f:
    pickle.dump(valid, f)
with open(mimic_df_test_output_path, "wb") as f:
    pickle.dump(test, f)


## also save as csv:

mimic_df_train_output_path = os.path.join(mimic_df_output_path, "mimic_train.csv")
mimic_df_valid_output_path = os.path.join(mimic_df_output_path, "mimic_valid.csv")
mimic_df_test_output_path = os.path.join(mimic_df_output_path, "mimic_test.csv")

train.write_csv(mimic_df_train_output_path)
valid.write_csv(mimic_df_valid_output_path)
test.write_csv(mimic_df_test_output_path)

In [84]:
tmp = get_df_info_pl(mimic_df)

DataFrame shape: (556617, 11)
Data types (according to dtypes):
Number of numerical columns: 2:
['icu_length_of_stay', 'age']
  - Integer columns: 2: ['icu_length_of_stay', 'age']
  - Float columns: 0: []
Number of categorical columns: 9:
['GENDER', 'ADMISSION_TYPE', 'ADMISSION_LOCATION', 'DISCHARGE_LOCATION', 'INSURANCE', 'ETHNICITY', 'DIAGNOSIS', 'DRUG', 'ICD9_CODE']
  - Multiclass columns: 8: ['ADMISSION_TYPE', 'ADMISSION_LOCATION', 'DISCHARGE_LOCATION', 'INSURANCE', 'ETHNICITY', 'DIAGNOSIS', 'DRUG', 'ICD9_CODE']
  - Binary columns: 1: ['GENDER']
  - Boolean columns: 0: []
Total categorical cardinality: 850
Total types count:
total numerical: 2 (int: 2, float: 0),
Total categorical: 9 (multi-class: 8, bin_cat: 1, bool_cat: 0):
Columns with missing values: 0

### Petfinder_Tab

In [15]:
dataset_path = "datuman/petfinder-adoption-tabular-only-tables"
file_name = "petfinder_tab_processed.csv"

# Load the file directly into a Polars DataFrame
df = kagglehub.dataset_load(KaggleDatasetAdapter.POLARS, dataset_path, file_name).collect()

# get_df_info_pl(df)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).

Petfinder preprocessing

In [16]:
target_col_name = "is_adopted"

In [17]:
df = df.with_columns(pl.col(target_col_name).cast(pl.String))

In [18]:
info = get_df_info_pl(df)

DataFrame shape: (14993, 18)
Data types (according to dtypes):
Number of numerical columns: 11:
['Age', 'MaturitySize', 'FurLength', 'Vaccinated', 'Dewormed', 'Sterilized', 'Health', 'Quantity', 'Fee', 'VideoAmt', 'PhotoAmt']
  - Integer columns: 11: ['Age', 'MaturitySize', 'FurLength', 'Vaccinated', 'Dewormed', 'Sterilized', 'Health', 'Quantity', 'Fee', 'VideoAmt', 'PhotoAmt']
  - Float columns: 0: []
Number of categorical columns: 7:
['Type', 'Gender', 'Breed1', 'Color1', 'Color2', 'State', 'is_adopted']
  - Multiclass columns: 5: ['Gender', 'Breed1', 'Color1', 'Color2', 'State']
  - Binary columns: 2: ['Type', 'is_adopted']
  - Boolean columns: 0: []
Total categorical cardinality: 210
Total types count:
total numerical: 11 (int: 11, float: 0),
Total categorical: 7 (multi-class: 5, bin_cat: 2, bool_cat: 0):
Columns with missing values: 1

In [19]:
df = df.drop_nulls()
df.null_count()

shape: (1, 18)
┌──────┬────────┬────────┬────────┬───┬─────┬──────────┬──────────┬────────────┐
│ Type ┆ Gender ┆ Breed1 ┆ Color1 ┆ … ┆ Fee ┆ VideoAmt ┆ PhotoAmt ┆ is_adopted │
│ ---  ┆ ---    ┆ ---    ┆ ---    ┆   ┆ --- ┆ ---      ┆ ---      ┆ ---        │
│ u32  ┆ u32    ┆ u32    ┆ u32    ┆   ┆ u32 ┆ u32      ┆ u32      ┆ u32        │
╞══════╪════════╪════════╪════════╪═══╪═════╪══════════╪══════════╪════════════╡
│ 0    ┆ 0      ┆ 0      ┆ 0      ┆ … ┆ 0   ┆ 0        ┆ 0        ┆ 0          │
└──────┴────────┴────────┴────────┴───┴─────┴──────────┴──────────┴────────────┘

In [20]:
catCols_noTarget = info["catCols"].copy()
catCols_noTarget.remove(target_col_name)
catCols_noTarget

['Type', 'Gender', 'Breed1', 'Color1', 'Color2', 'State']

In [21]:
df.columns

['Type',
 'Gender',
 'Breed1',
 'Color1',
 'Color2',
 'State',
 'Age',
 'MaturitySize',
 'FurLength',
 'Vaccinated',
 'Dewormed',
 'Sterilized',
 'Health',
 'Quantity',
 'Fee',
 'VideoAmt',
 'PhotoAmt',
 'is_adopted']

In [22]:
# get a list of indexes of numerical columns:
num_col_idx = [i for i, col in enumerate(df.columns) if col in info["numCols"]]
cat_col_idx = [i for i, col in enumerate(df.columns) if col in catCols_noTarget]
target_col_idx = df.columns.index(target_col_name)
cat_col_idx, num_col_idx, target_col_idx

([0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], 17)

In [23]:
df["State"].unique()

shape: (14,)
Series: 'State' [str]
[
	"Kedah"
	"Pulau Pinang"
	"Terengganu"
	"Sabah"
	"Selangor"
	…
	"Kelantan"
	"Negeri Sembilan"
	"Kuala Lumpur"
	"Melaka"
	"Labuan"
]

In [ ]:
train, valid, test = pl_train_valid_test_split(df, splits=[0.7, 0.15, 0.15], seed=420)

print("Train shape:", train.shape, "Valid shape:", valid.shape, "Test shape:", test.shape)

Train shape: (10483, 18) Valid shape: (2246, 18) Test shape: (2247, 18)

In [ ]:
#### save the datasets as parquet:


petfinder_output_path = "/Users/leec/Documents/datasets/parquet/petfinder_tab/"
# make sure the output directory exists, and create it if it doesn't:
os.makedirs(petfinder_output_path, exist_ok=True)

petfinder_train_output_path = os.path.join(petfinder_output_path, "petfinder_tab_train.parquet")
petfinder_valid_output_path = os.path.join(petfinder_output_path, "petfinder_tab_valid.parquet")
petfinder_test_output_path = os.path.join(petfinder_output_path, "petfinder_tab_test.parquet")

train.write_parquet(petfinder_train_output_path)
valid.write_parquet(petfinder_valid_output_path)
test.write_parquet(petfinder_test_output_path)


# create an `info.json` file with the metadata information:
metadata = {
    "name": "petfinder",
    "task_type": "binclass", # binclass, multiclass, regression 
    "target_col_name": target_col_name,
    "train_size": train.shape[0],
    "val_size": valid.shape[0],
    "test_size": test.shape[0],
    "catCols": info["catCols"],
    "intCols": info["intCols"],
    "floatCols": info["floatCols"]   
}

metadata_output_path = os.path.join(petfinder_output_path, "info.json")
with open(metadata_output_path, "w") as f:
    json.dump(metadata, f, indent=4)
    
metadata

In [ ]:
train, valid, test = pl_train_valid_test_split(df, splits=[0.7, 0.15, 0.15], seed=420)

petfinder_output_path = "/Users/leec/Documents/datasets/petfinder_tab/"
petfinder_train_output_path = os.path.join(petfinder_output_path, "petfinder_tab_train.csv")
petfinder_valid_output_path = os.path.join(petfinder_output_path, "petfinder_tab_valid.csv")
petfinder_test_output_path = os.path.join(petfinder_output_path, "petfinder_tab_test.csv")

train.write_csv(petfinder_train_output_path)
valid.write_csv(petfinder_valid_output_path)
test.write_csv(petfinder_test_output_path)

In [13]:
# petfinder_output_path = "/Users/leec/Documents/datasets/petfinder_tab/"
petfinder_train_output_path = os.path.join(petfinder_output_path, "petfinder_tab_train.pkl")
petfinder_valid_output_path = os.path.join(petfinder_output_path, "petfinder_tab_valid.pkl")
petfinder_test_output_path = os.path.join(petfinder_output_path, "petfinder_tab_test.pkl")

# pickle the datasets:
with open(petfinder_train_output_path, "wb") as f:
    pickle.dump(train, f)
with open(petfinder_valid_output_path, "wb") as f:
    pickle.dump(valid, f)
with open(petfinder_test_output_path, "wb") as f:
    pickle.dump(test, f)

In [ ]:
# df.write_csv(petfinder_output)

In [63]:
train.null_count()

shape: (1, 18)
┌──────┬────────┬────────┬────────┬───┬─────┬──────────┬──────────┬────────────┐
│ Type ┆ Gender ┆ Breed1 ┆ Color1 ┆ … ┆ Fee ┆ VideoAmt ┆ PhotoAmt ┆ is_adopted │
│ ---  ┆ ---    ┆ ---    ┆ ---    ┆   ┆ --- ┆ ---      ┆ ---      ┆ ---        │
│ u32  ┆ u32    ┆ u32    ┆ u32    ┆   ┆ u32 ┆ u32      ┆ u32      ┆ u32        │
╞══════╪════════╪════════╪════════╪═══╪═════╪══════════╪══════════╪════════════╡
│ 0    ┆ 0      ┆ 0      ┆ 0      ┆ … ┆ 0   ┆ 0        ┆ 0        ┆ 0          │
└──────┴────────┴────────┴────────┴───┴─────┴──────────┴──────────┴────────────┘

shape: (2_249, 18)
┌──────┬────────┬──────────────────────┬────────┬───┬─────┬──────────┬──────────┬────────────┐
│ Type ┆ Gender ┆ Breed1               ┆ Color1 ┆ … ┆ Fee ┆ VideoAmt ┆ PhotoAmt ┆ is_adopted │
│ ---  ┆ ---    ┆ ---                  ┆ ---    ┆   ┆ --- ┆ ---      ┆ ---      ┆ ---        │
│ str  ┆ str    ┆ str                  ┆ str    ┆   ┆ i64 ┆ i64      ┆ i64      ┆ i64        │
╞══════╪════════╪══════════════════════╪════════╪═══╪═════╪══════════╪══════════╪════════════╡
│ Cat  ┆ Male   ┆ Domestic Short Hair  ┆ Black  ┆ … ┆ 0   ┆ 0        ┆ 4        ┆ 1          │
│ Dog  ┆ Female ┆ Mixed Breed          ┆ Black  ┆ … ┆ 0   ┆ 0        ┆ 4        ┆ 1          │
│ Cat  ┆ Male   ┆ Domestic Short Hair  ┆ Black  ┆ … ┆ 0   ┆ 0        ┆ 10       ┆ 1          │
│ Dog  ┆ Female ┆ German Shepherd Dog  ┆ Black  ┆ … ┆ 0   ┆ 0        ┆ 3        ┆ 1          │
│ Cat  ┆ Female ┆ Domestic Medium Hair ┆ Cream  ┆ … ┆ 0   ┆ 0        ┆ 2        ┆ 0          │
│ …    ┆ …      ┆ …                    ┆ …      ┆ … ┆ …   ┆ …        ┆ …        ┆ …          │
│ Cat  ┆ Mixed  ┆ Domestic Short Hair  ┆ Black  ┆ … ┆ 0   ┆ 0        ┆ 3        ┆ 1          │
│ Cat  ┆ Mixed  ┆ Domestic Medium Hair ┆ Black  ┆ … ┆ 0   ┆ 0        ┆ 3        ┆ 0          │
│ Cat  ┆ Mixed  ┆ Domestic Medium Hair ┆ Cream  ┆ … ┆ 30  ┆ 0        ┆ 5        ┆ 1          │
│ Cat  ┆ Female ┆ Domestic Short Hair  ┆ Yellow ┆ … ┆ 0   ┆ 0        ┆ 3        ┆ 0          │
│ Dog  ┆ Male   ┆ Mixed Breed          ┆ Brown  ┆ … ┆ 0   ┆ 0        ┆ 1        ┆ 1          │
└──────┴────────┴──────────────────────┴────────┴───┴─────┴──────────┴──────────┴────────────┘

In [ ]:
train["State"].unique()

shape: (14,)
Series: 'State' [str]
[
	"Kelantan"
	"Pulau Pinang"
	"Perak"
	"Johor"
	"Sarawak"
	…
	"Selangor"
	"Labuan"
	"Sabah"
	"Negeri Sembilan"
	"Kedah"
]

### Clickstream

In [137]:
 "clickstream":{"uci_id":553,
        "name": "Clickstream Data for Online Retail",
        "repository_url": "https://archive.ics.uci.edu/dataset/553/clickstream+data+for+online+retail",
        "data_url": "https://archive.ics.uci.edu/static/public/553/clickstream+data+for+online+retail.data",
        'target_col': 'buy',
        'prediction_task': 'binary_classification',
        "shape": (287, 13),
    },

SyntaxError: illegal target for annotation (3019678334.py, line 1)

In [ ]:
clickstream_data = fetch_ucirepo(id=NAME_URL_DICT_UCI["clickstream"]["uci_id"])
# target_col_name = "buy"
# prediction_task = "binary_classification"
X = pl.from_pandas(clickstream_data.data.features)
Y = pl.from_pandas(clickstream_data.data.targets)
clickstream = pl.concat([X, Y], how="horizontal")
clickstream

### Criteo

In [168]:
# home_credit_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(
#     name="home-credit", source="kaggle", df_type="polars"
# )

# home_credit_df = home_credit_df.cast({"TARGET": pl.Utf8, "AMT_INCOME_TOTAL": pl.Int64, "AMT_GOODS_PRICE": pl.Int64})

In [169]:
criteo_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(
    name="criteo-1m", source="kaggle", df_type="polars")

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).

In [170]:
criteo_df.null_count()

shape: (1, 40)
┌────────┬──────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ target ┆ intCol_0 ┆ intCol_1 ┆ intCol_2 ┆ … ┆ catCol_22 ┆ catCol_23 ┆ catCol_24 ┆ catCol_25 │
│ ---    ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ u32    ┆ u32      ┆ u32      ┆ u32      ┆   ┆ u32       ┆ u32       ┆ u32       ┆ u32       │
╞════════╪══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0      ┆ 423003   ┆ 0        ┆ 235054   ┆ … ┆ 0         ┆ 36345     ┆ 483901    ┆ 483901    │
└────────┴──────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [171]:
criteo_df['catCol_10'].unique().shape[0]

4731

In [172]:
df_filtered = criteo_df.select(
    [col for col in criteo_df.columns if (criteo_df[col].null_count() <= 100000)  & (criteo_df[col].unique().shape[0]<5000)]
)
df_filtered = df_filtered.drop_nulls()

In [173]:
# calculate the number of unqiues in each columns

for col in df_filtered.columns:
    print(col, df_filtered[col].unique().shape[0])

target 2
intCol_1 4047
intCol_6 1321
intCol_7 323
intCol_8 3088
intCol_10 122
catCol_0 1243
catCol_1 530
catCol_4 266
catCol_7 556
catCol_8 3
catCol_10 4712
catCol_12 3065
catCol_13 26
catCol_16 10
catCol_17 3818
catCol_22 15

In [175]:
tmp_output = get_df_info_pl(df_filtered)
# tmp_output = tmp_output.wi

DataFrame shape: (959140, 17)
Data types (according to dtypes):
Number of numerical columns: 6:
['target', 'intCol_1', 'intCol_6', 'intCol_7', 'intCol_8', 'intCol_10']
  - Integer columns: 6: ['target', 'intCol_1', 'intCol_6', 'intCol_7', 'intCol_8', 'intCol_10']
  - Float columns: 0: []
Number of categorical columns: 11:
['catCol_0', 'catCol_1', 'catCol_4', 'catCol_7', 'catCol_8', 'catCol_10', 'catCol_12', 'catCol_13', 'catCol_16', 'catCol_17', 'catCol_22']
  - Multiclass columns: 11: ['catCol_0', 'catCol_1', 'catCol_4', 'catCol_7', 'catCol_8', 'catCol_10', 'catCol_12', 'catCol_13', 'catCol_16', 'catCol_17', 'catCol_22']
  - Binary columns: 0: []
  - Boolean columns: 0: []
Total categorical cardinality: 14244
Total types count:
total numerical: 6 (int: 6, float: 0),
Total categorical: 11 (multi-class: 11, bin_cat: 0, bool_cat: 0):
Columns with missing values: 0

In [176]:
df_filtered = df_filtered.with_columns(pl.col(target_col_name).cast(pl.String))

In [177]:
# Get metadata for Polars DataFrame
pl_metadata = get_pl_metadata(df_filtered)
# pp(pl_metadata)

# Retrieves column types from metadata
catCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "categorical"]
intCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "numerical" and v["subtype"] == "int"]
floatCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "numerical" and v["subtype"] == "float"]
binCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "categorical" and v["subtype"] == "binary"]
numCols = intCols + floatCols
print("catCols: ", catCols)
print("intCols: ", intCols)
print("floatCols: ", floatCols)
print("binCols: ", binCols)
print("numCols: ", numCols)
print("target_col: ", target_col_name)

catCols:  ['target', 'catCol_0', 'catCol_1', 'catCol_4', 'catCol_7', 'catCol_8', 'catCol_10', 'catCol_12', 'catCol_13', 'catCol_16', 'catCol_17', 'catCol_22']
intCols:  ['intCol_1', 'intCol_6', 'intCol_7', 'intCol_8', 'intCol_10']
floatCols:  []
binCols:  ['target']
numCols:  ['intCol_1', 'intCol_6', 'intCol_7', 'intCol_8', 'intCol_10']
target_col:  target

In [178]:
catCols_noTarget = [j for j in catCols if j != target_col_name]
catCols_noTarget
# get a list of indexes of numerical columns:
num_col_idx = [i for i, col in enumerate(df_filtered.columns) if col in numCols]
cat_col_idx = [i for i, col in enumerate(df_filtered.columns) if col in catCols_noTarget]
target_col_idx = df_filtered.columns.index(target_col_name)
cat_col_idx, num_col_idx, target_col_idx

([6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], [1, 2, 3, 4, 5], 0)

In [179]:
train, valid, test = pl_train_valid_test_split(df_filtered, splits=[0.7, 0.15, 0.15], seed=420)
print("Train shape:", train.shape, "Valid shape:", valid.shape, "Test shape:", test.shape)

Train shape: (671398, 17) Valid shape: (143871, 17) Test shape: (143871, 17)

In [180]:
#### save the datasets as parquet:
info = get_df_info_pl(df_filtered)

criteo1M_path = "/Users/leec/Documents/datasets/parquet/criteo1M/"
# make sure the output directory exists, and create it if it doesn't:
os.makedirs(criteo1M_path, exist_ok=True)

criteo1M_train_output_path = os.path.join(criteo1M_path, "criteo1M_train.parquet")
criteo1M_valid_output_path = os.path.join(criteo1M_path, "criteo1M_valid.parquet")
criteo1M_test_output_path = os.path.join(criteo1M_path, "criteo1M_test.parquet")

train.write_parquet(criteo1M_train_output_path)
valid.write_parquet(criteo1M_valid_output_path)
test.write_parquet(criteo1M_test_output_path)


# create an `info.json` file with the metadata information:
metadata = {
    "name": "criteo1M",
    "task_type": "binclass", # binclass, multiclass, regression 
    "target_col_name": target_col_name,
    "train_size": train.shape[0],
    "val_size": valid.shape[0],
    "test_size": test.shape[0],
    "catCols": info["catCols"],
    "intCols": info["intCols"],
    "floatCols": info["floatCols"]   
}

metadata_output_path = os.path.join(criteo1M_path, "info.json")
with open(metadata_output_path, "w") as f:
    json.dump(metadata, f, indent=4)
    
metadata

DataFrame shape: (959140, 17)
Data types (according to dtypes):
Number of numerical columns: 5:
['intCol_1', 'intCol_6', 'intCol_7', 'intCol_8', 'intCol_10']
  - Integer columns: 5: ['intCol_1', 'intCol_6', 'intCol_7', 'intCol_8', 'intCol_10']
  - Float columns: 0: []
Number of categorical columns: 12:
['target', 'catCol_0', 'catCol_1', 'catCol_4', 'catCol_7', 'catCol_8', 'catCol_10', 'catCol_12', 'catCol_13', 'catCol_16', 'catCol_17', 'catCol_22']
  - Multiclass columns: 11: ['catCol_0', 'catCol_1', 'catCol_4', 'catCol_7', 'catCol_8', 'catCol_10', 'catCol_12', 'catCol_13', 'catCol_16', 'catCol_17', 'catCol_22']
  - Binary columns: 1: ['target']
  - Boolean columns: 0: []
Total categorical cardinality: 14246
Total types count:
total numerical: 5 (int: 5, float: 0),
Total categorical: 12 (multi-class: 11, bin_cat: 1, bool_cat: 0):
Columns with missing values: 0

{'name': 'criteo1M',
 'task_type': 'binclass',
 'target_col_name': 'target',
 'train_size': 671398,
 'val_size': 143871,
 'test_size': 143871,
 'catCols': ['target',
  'catCol_0',
  'catCol_1',
  'catCol_4',
  'catCol_7',
  'catCol_8',
  'catCol_10',
  'catCol_12',
  'catCol_13',
  'catCol_16',
  'catCol_17',
  'catCol_22'],
 'intCols': ['intCol_1', 'intCol_6', 'intCol_7', 'intCol_8', 'intCol_10'],
 'floatCols': []}

In [ ]:





criteo_output_path = "/Users/leec/Documents/datasets/criteo_1m/"
criteo_train_output_path = os.path.join(criteo_output_path, "criteo_train.csv")
criteo_valid_output_path = os.path.join(criteo_output_path, "criteo_valid.csv")
criteo_test_output_path = os.path.join(criteo_output_path, "criteo_test.csv")

train.write_csv(criteo_train_output_path)
valid.write_csv(criteo_valid_output_path)
test.write_csv(criteo_test_output_path)


criteo_train_output_path = os.path.join(criteo_output_path, "criteo_train.pkl")
criteo_valid_output_path = os.path.join(criteo_output_path, "criteo_valid.pkl")
criteo_test_output_path = os.path.join(criteo_output_path, "criteo_test.pkl")

# pickle the datasets:
with open(criteo_train_output_path, "wb") as f:
    pickle.dump(train, f)
with open(criteo_valid_output_path, "wb") as f:
    pickle.dump(valid, f)
with open(criteo_test_output_path, "wb") as f:
    pickle.dump(test, f)

In [ ]:
# data_path = "/Users/leec/Documents/datasets/Criteo/"

# ## Criteo Dataset:
# criteo_names = (
#     ["target"]
#     + ["intCol_{}".format(i) for i in range(13)]
#     + ["catCol_{}".format(i) for i in range(26)]
# )
# criteo_dtypes = ["object"] + ["Int64"] * 13 + ["object"] * 26
# criteo_path = os.path.join(data_path, "Criteo_1M.csv")
# dataframe = pd.read_csv(
#     criteo_path,
#     delimiter="\t",
#     names=criteo_names,
#     dtype={i: j for i, j in zip(criteo_names, criteo_dtypes)},
# )
# # dataframe[["catCol_{}".format(i) for i in range(26)]] = dataframe[
# #     ["catCol_{}".format(i) for i in range(26)]
# # ].fillna("99")

# dataframe = dataframe.astype({"target": int})

In [ ]:
# dataframe = dataframe[['target']+['catCol_{}'.format(i) for i in range(5)]+
#                      ['intCol_{}'.format(i) for i in range(5)]] #.iloc[:500000,]
# dataframe = dataframe[
#     ["target"]
#     + ["catCol_0"]
#     + ["catCol_1"]
#     + ["catCol_4"]
#     + ["catCol_5"]
#     + ["catCol_8"]
#     + ["intCol_{}".format(i) for i in range(5)]
# ]  # .iloc[:200000,]
# dataframe = dataframe.dropna()
# dataframe = dataframe.astype(
#     {i: "int64" for i in ["intCol_{}".format(i) for i in range(5)]}
# )
# dataframe = dataframe.astype({"target": int})
# print("Dataframe shape: ", dataframe.shape)

Dataframe shape:  (406654, 11)

## UCI

In [ ]:
# NAME_URL_DICT_UCI = {
#     "bank-marketing": {
#         "uci_id": 222,
#         "name": "Bank Marketing",
#         "repository_url": "https://archive.ics.uci.edu/dataset/222/bank+marketing",
#         "data_url": "https://archive.ics.uci.edu/static/public/222/data.csv",
#         "target_col": "y",
#         "prediction_task": "binary_classification",
#         "shape": (45211, 17),
#         "types": {"intCols": 7, "floatCols": 10, "boolCols": 1, "catCols": 10},
#     },
#     "adult-census": {
#         "uci_id": 2,
#         "name": "Adult",
#         "repository_url": "https://archive.ics.uci.edu/dataset/2/adult",
#         "data_url": "https://archive.ics.uci.edu/static/public/2/adult.data",
#         "target_col": "income",
#         "prediction_task": "binary_classification",
#         "shape": (48842, 15),
#     },
#     "credit-defualt-taiwan": {
#         "uci_id": 350,
#         "name": "Default of Credit Card Clients",
#         "repository_url": "https://archive.ics.uci.edu/dataset/350/default+of+credit+card+clients",
#         "data_url": "https://archive.ics.uci.edu/static/public/350/default+of+credit+card+clients.data",
#         "target_col": "default payment next month",
#         "prediction_task": "binary_classification",
#         "shape": (30000, 24),
#     },
#     "cdc_diabetes": {
#         "uci_id": 891,
#         "name": "CDC Diabetes Health Indicators",
#         "repository_url": "https://archive.ics.uci.edu/dataset/891/diabetes",
#         "data_url": "https://archive.ics.uci.edu/static/public/891/diabetes.data",
#         "target_col": "Diabetes_binary",
#         "prediction_task": "binary_classification",
#         "shape": (253, 680, 21),
#     },
#     "census-income_full": {
#         "uci_id": 117,
#         "name": "Census Income (KDD)",
#         "repository_url": "https://archive.ics.uci.edu/dataset/117/census+income+kdd",
#         "data_url": "https://archive.ics.uci.edu/static/public/117/census+income+kdd.data",
#         "target_col": "income",
#         "prediction_task": "binary_classification",
#         "shape": (299285, 41),
#     },
#     "support2": {
#         "uci_id": 880,
#         "name": "SUPPORT2",
#         "repository_url": "https://archive.ics.uci.edu/dataset/880/support2",
#         "data_url": "https://archive.ics.uci.edu/static/public/880/support2.data",
#         "target_col": "death",
#         "prediction_task": "binary_classification",
#         "shape": (9105, 21),
#     },
#     "diabetes_130us": {
#         "uci_id": 296,
#         "name": "Diabetes 130-US hospitals for years 1999-2008",
#         "repository_url": "https://archive.ics.uci.edu/dataset/296/diabetes+130-us+hospitals+for+years+1999-2008",
#         "data_url": "https://archive.ics.uci.edu/static/public/296/diabetes+130-us+hospitals+for+years+1999-2008.data",
#         "target_col": "readmitted",
#         "prediction_task": "binary_classification",
#         "shape": (130, 50),
#         "types": {"numCols": 27, "catCols": 23},
#     },
#     "nursery": {
#         "uci_id": 76,
#         "name": "Nursery",
#         "repository_url": "https://archive.ics.uci.edu/dataset/76/nursery",
#         "data_url": "https://archive.ics.uci.edu/dataset/76/nursery.data",
#         "target_col": "class",
#         "prediction_task": "multi_class_classification",
#         "shape": (12960, 8),
#     },
#     "taiwanese_bankruptcy": {
#         "uci_id": 572,
#         "name": "Taiwanese Bankruptcy",
#         "repository_url": "https://archive.ics.uci.edu/dataset/572/taiwanese+bankruptcy+prediction",
#         "data_url": "https://archive.ics.uci.edu/dataset/572/taiwanese+bankruptcy+prediction.data",
#         "target_col": "Bankrupt?",
#         "prediction_task": "binary_classification",
#         "shape": (6819, 96),
#     },
#     "apartment_rent_classified": {
#         "uci_id": 555,
#         "name": "Apartment Rent Classified",
#         "repository_url": "https://archive.ics.uci.edu/dataset/555/apartment+for+rent+classified",
#         "data_url": "https://archive.ics.uci.edu/dataset/555/apartment+for+rent+classified.data",
#         "target_col": ["square_feet", "price"],
#         "prediction_task": "regression",
#         "shape": (99826, 21),
#     },
#     "covertype": {
#         "uci_id": 31,
#         "name": "Covertype",
#         "repository_url": "https://archive.ics.uci.edu/dataset/31/covertype",
#         "data_url": "https://archive.ics.uci.edu/dataset/31/covertype.data",
#         "target_col": "Cover_Type",
#         "prediction_task": "multi_class_classification",
#         "shape": (581012, 55),
#     },
#     # "adult": "https://archive.ics.uci.edu/static/public/2/adult.zip",
#     # "default": "https://archive.ics.uci.edu/static/public/350/default+of+credit+card+clients.zip",
#     # "magic": "https://archive.ics.uci.edu/static/public/159/magic+gamma+telescope.zip",
#     # "shoppers": "https://archive.ics.uci.edu/static/public/468/online+shoppers+purchasing+intention+dataset.zip",
#     # "beijing": "https://archive.ics.uci.edu/static/public/381/beijing+pm2+5+data.zip",
#     # "news": "https://archive.ics.uci.edu/static/public/332/online+news+popularity.zip",
# }

### Bank-Marketing

In [34]:
bank_marketing_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(
    name="bank-marketing", source="uci", df_type="polars"
)
print("shape: ", bank_marketing_df.shape)
print("target_col_name: ", target_col_name)
print("prediction_task: ", prediction_task)
print("metadata: ", metadata)

shape:  (45211, 17)
target_col_name:  y
prediction_task:  binary_classification
metadata:  {'uci_id': 222, 'name': 'Bank Marketing', 'repository_url': 'https://archive.ics.uci.edu/dataset/222/bank+marketing', 'data_url': 'https://archive.ics.uci.edu/static/public/222/data.csv', 'abstract': 'The data is related with direct marketing campaigns (phone calls) of a Portuguese banking institution. The classification goal is to predict if the client will subscribe a term deposit (variable y).', 'area': 'Business', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 45211, 'num_features': 16, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Age', 'Occupation', 'Marital Status', 'Education Level'], 'target_col': ['y'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 2014, 'last_updated': 'Fri Aug 18 2023', 'dataset_doi': '10.24432/C5K306', 'creators': ['S. Moro', 'P. Rita', 'P. Cortez'], 'intro_paper': {'ID': 277, 'type': 'NATIVE', 'title': 'A data-driven approach to predict the success of bank telemarketing', 'authors': 'Sérgio Moro, P. Cortez, P. Rita', 'venue': 'Decision Support Systems', 'year': 2014, 'journal': None, 'DOI': '10.1016/j.dss.2014.03.001', 'URL': 'https://www.semanticscholar.org/paper/cab86052882d126d43f72108c6cb41b295cc8a9e', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': "The data is related with direct marketing campaigns of a Portuguese banking institution. The marketing campaigns were based on phone calls. Often, more than one contact to the same client was required, in order to access if the product (bank term deposit) would be ('yes') or not ('no') subscribed. \n\nThere are four datasets: \n1) bank-additional-full.csv with all examples (41188) and 20 inputs, ordered by date (from May 2008 to November 2010), very close to the data analyzed in [Moro et al., 2014]\n2) bank-additional.csv with 10% of the examples (4119), randomly selected from 1), and 20 inputs.\n3) bank-full.csv with all examples and 17 inputs, ordered by date (older version of this dataset with less inputs). \n4) bank.csv with 10% of the examples and 17 inputs, randomly selected from 3 (older version of this dataset with less inputs). \nThe smallest datasets are provided to test more computationally demanding machine learning algorithms (e.g., SVM). \n\nThe classification goal is to predict if the client will subscribe (yes/no) a term deposit (variable y).", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Input variables:\n   # bank client data:\n   1 - age (numeric)\n   2 - job : type of job (categorical: "admin.","unknown","unemployed","management","housemaid","entrepreneur","student",\n                                       "blue-collar","self-employed","retired","technician","services") \n   3 - marital : marital status (categorical: "married","divorced","single"; note: "divorced" means divorced or widowed)\n   4 - education (categorical: "unknown","secondary","primary","tertiary")\n   5 - default: has credit in default? (binary: "yes","no")\n   6 - balance: average yearly balance, in euros (numeric) \n   7 - housing: has housing loan? (binary: "yes","no")\n   8 - loan: has personal loan? (binary: "yes","no")\n   # related with the last contact of the current campaign:\n   9 - contact: contact communication type (categorical: "unknown","telephone","cellular") \n  10 - day: last contact day of the month (numeric)\n  11 - month: last contact month of year (categorical: "jan", "feb", "mar", ..., "nov", "dec")\n  12 - duration: last contact duration, in seconds (numeric)\n   # other attributes:\n  13 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)\n  14 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric, -1 means client was not previously contacted)\n  15 - previous: number of contacts performed before this campaign and for this client (numeric)\n  16 - poutcome: outcome of the previous marketing campaign (categorical: "unknown","other","failure","success")\n\n  Output variable (desired target):\n  17 - y - has the client subscribed a term deposit? (binary: "yes","no")\n', 'citation': None}}

In [35]:
# removing high nulls count columns:
bank_marketing_df = bank_marketing_df.drop(["poutcome", "contact"])
bank_marketing_df = bank_marketing_df.drop_nulls()
# df = df.drop_nulls()

In [36]:
bank_info = get_df_info_pl(bank_marketing_df)

DataFrame shape: (43193, 15)
Data types (according to dtypes):
Number of numerical columns: 7:
['age', 'balance', 'day_of_week', 'duration', 'campaign', 'pdays', 'previous']
  - Integer columns: 7: ['age', 'balance', 'day_of_week', 'duration', 'campaign', 'pdays', 'previous']
  - Float columns: 0: []
Number of categorical columns: 8:
['job', 'marital', 'education', 'default', 'housing', 'loan', 'month', 'y']
  - Multiclass columns: 4: ['job', 'marital', 'education', 'month']
  - Binary columns: 4: ['default', 'housing', 'loan', 'y']
  - Boolean columns: 0: []
Total categorical cardinality: 37
Total types count:
total numerical: 7 (int: 7, float: 0),
Total categorical: 8 (multi-class: 4, bin_cat: 4, bool_cat: 0):
Columns with missing values: 0

In [37]:
# Get metadata for Polars DataFrame
pl_metadata = get_pl_metadata(bank_marketing_df)
# pp(pl_metadata)

# Retrieves column types from metadata
catCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "categorical"]
intCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "numerical" and v["subtype"] == "int"]
floatCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "numerical" and v["subtype"] == "float"]
binCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "categorical" and v["subtype"] == "binary"]
numCols = intCols + floatCols
print("catCols: ", catCols)
print("intCols: ", intCols)
print("floatCols: ", floatCols)
print("binCols: ", binCols)
print("numCols: ", numCols)
print("target_col: ", target_col_name)

catCols:  ['job', 'marital', 'education', 'default', 'housing', 'loan', 'month', 'y']
intCols:  ['age', 'balance', 'day_of_week', 'duration', 'campaign', 'pdays', 'previous']
floatCols:  []
binCols:  ['default', 'housing', 'loan', 'y']
numCols:  ['age', 'balance', 'day_of_week', 'duration', 'campaign', 'pdays', 'previous']
target_col:  y

In [38]:
# getting
catCols_noTarget = [j for j in catCols if j != target_col_name]
print("catCols_noTarget: ", catCols_noTarget)  # catCols_noTarget
# # get a list of indexes of numerical columns:
# num_col_idx = [i for i, col in enumerate(bank_marketing_df.columns) if col in numCols]
# cat_col_idx = [i for i, col in enumerate(bank_marketing_df.columns) if col in catCols_noTarget]
# target_col_idx = bank_marketing_df.columns.index(target_col_name)
# cat_col_idx, num_col_idx, target_col_idx

catCols_noTarget:  ['job', 'marital', 'education', 'default', 'housing', 'loan', 'month']

In [39]:
bank_marketing_df = bank_marketing_df.select(catCols_noTarget + numCols + [target_col_name])
bank_marketing_df

shape: (43_193, 15)
┌──────────────┬──────────┬───────────┬─────────┬───┬──────────┬───────┬──────────┬─────┐
│ job          ┆ marital  ┆ education ┆ default ┆ … ┆ campaign ┆ pdays ┆ previous ┆ y   │
│ ---          ┆ ---      ┆ ---       ┆ ---     ┆   ┆ ---      ┆ ---   ┆ ---      ┆ --- │
│ str          ┆ str      ┆ str       ┆ str     ┆   ┆ i64      ┆ i64   ┆ i64      ┆ str │
╞══════════════╪══════════╪═══════════╪═════════╪═══╪══════════╪═══════╪══════════╪═════╡
│ management   ┆ married  ┆ tertiary  ┆ no      ┆ … ┆ 1        ┆ -1    ┆ 0        ┆ no  │
│ technician   ┆ single   ┆ secondary ┆ no      ┆ … ┆ 1        ┆ -1    ┆ 0        ┆ no  │
│ entrepreneur ┆ married  ┆ secondary ┆ no      ┆ … ┆ 1        ┆ -1    ┆ 0        ┆ no  │
│ management   ┆ married  ┆ tertiary  ┆ no      ┆ … ┆ 1        ┆ -1    ┆ 0        ┆ no  │
│ management   ┆ single   ┆ tertiary  ┆ no      ┆ … ┆ 1        ┆ -1    ┆ 0        ┆ no  │
│ …            ┆ …        ┆ …         ┆ …       ┆ … ┆ …        ┆ …     ┆ …        ┆ …   │
│ technician   ┆ married  ┆ tertiary  ┆ no      ┆ … ┆ 3        ┆ -1    ┆ 0        ┆ yes │
│ retired      ┆ divorced ┆ primary   ┆ no      ┆ … ┆ 2        ┆ -1    ┆ 0        ┆ yes │
│ retired      ┆ married  ┆ secondary ┆ no      ┆ … ┆ 5        ┆ 184   ┆ 3        ┆ yes │
│ blue-collar  ┆ married  ┆ secondary ┆ no      ┆ … ┆ 4        ┆ -1    ┆ 0        ┆ no  │
│ entrepreneur ┆ married  ┆ secondary ┆ no      ┆ … ┆ 2        ┆ 188   ┆ 11       ┆ no  │
└──────────────┴──────────┴───────────┴─────────┴───┴──────────┴───────┴──────────┴─────┘

In [40]:
num_col_idx = [i for i, col in enumerate(bank_marketing_df.columns) if col in numCols]
cat_col_idx = [i for i, col in enumerate(bank_marketing_df.columns) if col in catCols_noTarget]
target_col_idx = bank_marketing_df.columns.index(target_col_name)
cat_col_idx, num_col_idx, target_col_idx

([0, 1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12, 13], 14)

In [41]:
bank_marketing_df.columns

['job',
 'marital',
 'education',
 'default',
 'housing',
 'loan',
 'month',
 'age',
 'balance',
 'day_of_week',
 'duration',
 'campaign',
 'pdays',
 'previous',
 'y']

In [42]:
bank_marketing_df

shape: (43_193, 15)
┌──────────────┬──────────┬───────────┬─────────┬───┬──────────┬───────┬──────────┬─────┐
│ job          ┆ marital  ┆ education ┆ default ┆ … ┆ campaign ┆ pdays ┆ previous ┆ y   │
│ ---          ┆ ---      ┆ ---       ┆ ---     ┆   ┆ ---      ┆ ---   ┆ ---      ┆ --- │
│ str          ┆ str      ┆ str       ┆ str     ┆   ┆ i64      ┆ i64   ┆ i64      ┆ str │
╞══════════════╪══════════╪═══════════╪═════════╪═══╪══════════╪═══════╪══════════╪═════╡
│ management   ┆ married  ┆ tertiary  ┆ no      ┆ … ┆ 1        ┆ -1    ┆ 0        ┆ no  │
│ technician   ┆ single   ┆ secondary ┆ no      ┆ … ┆ 1        ┆ -1    ┆ 0        ┆ no  │
│ entrepreneur ┆ married  ┆ secondary ┆ no      ┆ … ┆ 1        ┆ -1    ┆ 0        ┆ no  │
│ management   ┆ married  ┆ tertiary  ┆ no      ┆ … ┆ 1        ┆ -1    ┆ 0        ┆ no  │
│ management   ┆ single   ┆ tertiary  ┆ no      ┆ … ┆ 1        ┆ -1    ┆ 0        ┆ no  │
│ …            ┆ …        ┆ …         ┆ …       ┆ … ┆ …        ┆ …     ┆ …        ┆ …   │
│ technician   ┆ married  ┆ tertiary  ┆ no      ┆ … ┆ 3        ┆ -1    ┆ 0        ┆ yes │
│ retired      ┆ divorced ┆ primary   ┆ no      ┆ … ┆ 2        ┆ -1    ┆ 0        ┆ yes │
│ retired      ┆ married  ┆ secondary ┆ no      ┆ … ┆ 5        ┆ 184   ┆ 3        ┆ yes │
│ blue-collar  ┆ married  ┆ secondary ┆ no      ┆ … ┆ 4        ┆ -1    ┆ 0        ┆ no  │
│ entrepreneur ┆ married  ┆ secondary ┆ no      ┆ … ┆ 2        ┆ 188   ┆ 11       ┆ no  │
└──────────────┴──────────┴───────────┴─────────┴───┴──────────┴───────┴──────────┴─────┘

In [45]:
info= get_df_info_pl(bank_marketing_df)

DataFrame shape: (43193, 15)
Data types (according to dtypes):
Number of numerical columns: 7:
['age', 'balance', 'day_of_week', 'duration', 'campaign', 'pdays', 'previous']
  - Integer columns: 7: ['age', 'balance', 'day_of_week', 'duration', 'campaign', 'pdays', 'previous']
  - Float columns: 0: []
Number of categorical columns: 8:
['job', 'marital', 'education', 'default', 'housing', 'loan', 'month', 'y']
  - Multiclass columns: 4: ['job', 'marital', 'education', 'month']
  - Binary columns: 4: ['default', 'housing', 'loan', 'y']
  - Boolean columns: 0: []
Total categorical cardinality: 37
Total types count:
total numerical: 7 (int: 7, float: 0),
Total categorical: 8 (multi-class: 4, bin_cat: 4, bool_cat: 0):
Columns with missing values: 0

In [43]:
train, valid, test = pl_train_valid_test_split(bank_marketing_df, splits=[0.7, 0.15, 0.15], seed=420)

print("Train shape:", train.shape, "Valid shape:", valid.shape, "Test shape:", test.shape)

Train shape: (30235, 15) Valid shape: (6479, 15) Test shape: (6479, 15)

In [46]:
#### save the datasets as parquet:


bank_marketing_output_path = "/Users/leec/Documents/datasets/parquet/bank_marketing/"
# make sure the output directory exists, and create it if it doesn't:
os.makedirs(bank_marketing_output_path, exist_ok=True)

bank_marketing_train_output_path = os.path.join(bank_marketing_output_path, "bank_marketing_train.parquet")
bank_marketing_valid_output_path = os.path.join(bank_marketing_output_path, "bank_marketing_valid.parquet")
bank_marketing_test_output_path = os.path.join(bank_marketing_output_path, "bank_marketing_test.parquet")

train.write_parquet(bank_marketing_train_output_path)
valid.write_parquet(bank_marketing_valid_output_path)
test.write_parquet(bank_marketing_test_output_path)


# create an `info.json` file with the metadata information:
metadata = {
    "name": "bank_marketing",
    "task_type": "binclass", # binclass, multiclass, regression 
    "target_col_name": target_col_name,
    "train_size": train.shape[0],
    "val_size": valid.shape[0],
    "test_size": test.shape[0],
    "catCols": info["catCols"],
    "intCols": info["intCols"],
    "floatCols": info["floatCols"]   
}

metadata_output_path = os.path.join(bank_marketing_output_path, "info.json")
with open(metadata_output_path, "w") as f:
    json.dump(metadata, f, indent=4)
    
metadata

{'name': 'bank_marketing',
 'task_type': 'binclass',
 'target_col_name': 'y',
 'train_size': 30235,
 'val_size': 6479,
 'test_size': 6479,
 'catCols': ['job',
  'marital',
  'education',
  'default',
  'housing',
  'loan',
  'month',
  'y'],
 'intCols': ['age',
  'balance',
  'day_of_week',
  'duration',
  'campaign',
  'pdays',
  'previous'],
 'floatCols': []}

In [ ]:
# save the datasets as pickle:
bank_marketing_output_path = "/Users/leec/Documents/datasets/bank_marketing/"
bank_marketing_train_output_path = os.path.join(bank_marketing_output_path, "bank_marketing_train.pkl")
bank_marketing_valid_output_path = os.path.join(bank_marketing_output_path, "bank_marketing_valid.pkl")
bank_marketing_test_output_path = os.path.join(bank_marketing_output_path, "bank_marketing_test.pkl")

# pickle the datasets:
with open(bank_marketing_train_output_path, "wb") as f:
    pickle.dump(train, f)
with open(bank_marketing_valid_output_path, "wb") as f:
    pickle.dump(valid, f)
with open(bank_marketing_test_output_path, "wb") as f:
    pickle.dump(test, f)


## also save as csv:

bank_marketing_train_output_path = os.path.join(bank_marketing_output_path, "bank_marketing_train.csv")
bank_marketing_valid_output_path = os.path.join(bank_marketing_output_path, "bank_marketing_valid.csv")
bank_marketing_test_output_path = os.path.join(bank_marketing_output_path, "bank_marketing_test.csv")

train.write_csv(bank_marketing_train_output_path)
valid.write_csv(bank_marketing_valid_output_path)
test.write_csv(bank_marketing_test_output_path)

In [ ]:
bank_marketing_df.select(bank_info["intCols"]).with_columns(pl.all().unique().count())

shape: (45_211, 7)
┌─────┬─────────┬─────────────┬──────────┬──────────┬───────┬──────────┐
│ age ┆ balance ┆ day_of_week ┆ duration ┆ campaign ┆ pdays ┆ previous │
│ --- ┆ ---     ┆ ---         ┆ ---      ┆ ---      ┆ ---   ┆ ---      │
│ u32 ┆ u32     ┆ u32         ┆ u32      ┆ u32      ┆ u32   ┆ u32      │
╞═════╪═════════╪═════════════╪══════════╪══════════╪═══════╪══════════╡
│ 77  ┆ 7168    ┆ 31          ┆ 1573     ┆ 48       ┆ 559   ┆ 41       │
│ 77  ┆ 7168    ┆ 31          ┆ 1573     ┆ 48       ┆ 559   ┆ 41       │
│ 77  ┆ 7168    ┆ 31          ┆ 1573     ┆ 48       ┆ 559   ┆ 41       │
│ 77  ┆ 7168    ┆ 31          ┆ 1573     ┆ 48       ┆ 559   ┆ 41       │
│ 77  ┆ 7168    ┆ 31          ┆ 1573     ┆ 48       ┆ 559   ┆ 41       │
│ …   ┆ …       ┆ …           ┆ …        ┆ …        ┆ …     ┆ …        │
│ 77  ┆ 7168    ┆ 31          ┆ 1573     ┆ 48       ┆ 559   ┆ 41       │
│ 77  ┆ 7168    ┆ 31          ┆ 1573     ┆ 48       ┆ 559   ┆ 41       │
│ 77  ┆ 7168    ┆ 31          ┆ 1573     ┆ 48       ┆ 559   ┆ 41       │
│ 77  ┆ 7168    ┆ 31          ┆ 1573     ┆ 48       ┆ 559   ┆ 41       │
│ 77  ┆ 7168    ┆ 31          ┆ 1573     ┆ 48       ┆ 559   ┆ 41       │
└─────┴─────────┴─────────────┴──────────┴──────────┴───────┴──────────┘

### Adult Census

In [104]:
# adult_data = fetch_ucirepo(id=mixtabank.uci_dict["adult-census"]["uci_id"])
# target_col_name = "is_high_income"
# prediction_task = "binary_classification"
# X = pl.from_pandas(adult_data.data.features)
# Y = pl.from_pandas(adult_data.data.targets)
# adult = pl.concat([X, Y], how="horizontal")
adult_census_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(
    name="adult-census", source="uci", df_type="polars"
)
var_types, target_col_name, prediction_task

({'age': 'Integer',
  'workclass': 'Categorical',
  'fnlwgt': 'Integer',
  'education': 'Categorical',
  'education-num': 'Integer',
  'marital-status': 'Categorical',
  'occupation': 'Categorical',
  'relationship': 'Categorical',
  'race': 'Categorical',
  'sex': 'Binary',
  'capital-gain': 'Integer',
  'capital-loss': 'Integer',
  'hours-per-week': 'Integer',
  'native-country': 'Categorical',
  'income': 'Binary'},
 'income',
 'binary_classification')

In [105]:
adult_census_df

shape: (48_842, 15)
┌─────┬──────────────┬────────┬───────────┬───┬──────────────┬──────────────┬─────────────┬────────┐
│ age ┆ workclass    ┆ fnlwgt ┆ education ┆ … ┆ capital-loss ┆ hours-per-we ┆ native-coun ┆ income │
│ --- ┆ ---          ┆ ---    ┆ ---       ┆   ┆ ---          ┆ ek           ┆ try         ┆ ---    │
│ i64 ┆ str          ┆ i64    ┆ str       ┆   ┆ i64          ┆ ---          ┆ ---         ┆ str    │
│     ┆              ┆        ┆           ┆   ┆              ┆ i64          ┆ str         ┆        │
╞═════╪══════════════╪════════╪═══════════╪═══╪══════════════╪══════════════╪═════════════╪════════╡
│ 39  ┆ State-gov    ┆ 77516  ┆ Bachelors ┆ … ┆ 0            ┆ 40           ┆ United-Stat ┆ <=50K  │
│     ┆              ┆        ┆           ┆   ┆              ┆              ┆ es          ┆        │
│ 50  ┆ Self-emp-not ┆ 83311  ┆ Bachelors ┆ … ┆ 0            ┆ 13           ┆ United-Stat ┆ <=50K  │
│     ┆ -inc         ┆        ┆           ┆   ┆              ┆              ┆ es          ┆        │
│ 38  ┆ Private      ┆ 215646 ┆ HS-grad   ┆ … ┆ 0            ┆ 40           ┆ United-Stat ┆ <=50K  │
│     ┆              ┆        ┆           ┆   ┆              ┆              ┆ es          ┆        │
│ 53  ┆ Private      ┆ 234721 ┆ 11th      ┆ … ┆ 0            ┆ 40           ┆ United-Stat ┆ <=50K  │
│     ┆              ┆        ┆           ┆   ┆              ┆              ┆ es          ┆        │
│ 28  ┆ Private      ┆ 338409 ┆ Bachelors ┆ … ┆ 0            ┆ 40           ┆ Cuba        ┆ <=50K  │
│ …   ┆ …            ┆ …      ┆ …         ┆ … ┆ …            ┆ …            ┆ …           ┆ …      │
│ 39  ┆ Private      ┆ 215419 ┆ Bachelors ┆ … ┆ 0            ┆ 36           ┆ United-Stat ┆ <=50K. │
│     ┆              ┆        ┆           ┆   ┆              ┆              ┆ es          ┆        │
│ 64  ┆ null         ┆ 321403 ┆ HS-grad   ┆ … ┆ 0            ┆ 40           ┆ United-Stat ┆ <=50K. │
│     ┆              ┆        ┆           ┆   ┆              ┆              ┆ es          ┆        │
│ 38  ┆ Private      ┆ 374983 ┆ Bachelors ┆ … ┆ 0            ┆ 50           ┆ United-Stat ┆ <=50K. │
│     ┆              ┆        ┆           ┆   ┆              ┆              ┆ es          ┆        │
│ 44  ┆ Private      ┆ 83891  ┆ Bachelors ┆ … ┆ 0            ┆ 40           ┆ United-Stat ┆ <=50K. │
│     ┆              ┆        ┆           ┆   ┆              ┆              ┆ es          ┆        │
│ 35  ┆ Self-emp-inc ┆ 182148 ┆ Bachelors ┆ … ┆ 0            ┆ 60           ┆ United-Stat ┆ >50K.  │
│     ┆              ┆        ┆           ┆   ┆              ┆              ┆ es          ┆        │
└─────┴──────────────┴────────┴───────────┴───┴──────────────┴──────────────┴─────────────┴────────┘

In [106]:
adult_census_df = adult_census_df.with_columns(
    pl.when(pl.col("income") == ">50K.").then(1).otherwise(0).alias("is_high_income").cast(str)
)
adult_census_df = adult_census_df.drop(["income"])  # Drop un-used columns
target_col_name = "is_high_income"
adult_census_df

shape: (48_842, 15)
┌─────┬─────────────┬────────┬───────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ age ┆ workclass   ┆ fnlwgt ┆ education ┆ … ┆ capital-los ┆ hours-per-w ┆ native-cou ┆ is_high_in │
│ --- ┆ ---         ┆ ---    ┆ ---       ┆   ┆ s           ┆ eek         ┆ ntry       ┆ come       │
│ i64 ┆ str         ┆ i64    ┆ str       ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│     ┆             ┆        ┆           ┆   ┆ i64         ┆ i64         ┆ str        ┆ str        │
╞═════╪═════════════╪════════╪═══════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ 39  ┆ State-gov   ┆ 77516  ┆ Bachelors ┆ … ┆ 0           ┆ 40          ┆ United-Sta ┆ 0          │
│     ┆             ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 50  ┆ Self-emp-no ┆ 83311  ┆ Bachelors ┆ … ┆ 0           ┆ 13          ┆ United-Sta ┆ 0          │
│     ┆ t-inc       ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 38  ┆ Private     ┆ 215646 ┆ HS-grad   ┆ … ┆ 0           ┆ 40          ┆ United-Sta ┆ 0          │
│     ┆             ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 53  ┆ Private     ┆ 234721 ┆ 11th      ┆ … ┆ 0           ┆ 40          ┆ United-Sta ┆ 0          │
│     ┆             ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 28  ┆ Private     ┆ 338409 ┆ Bachelors ┆ … ┆ 0           ┆ 40          ┆ Cuba       ┆ 0          │
│ …   ┆ …           ┆ …      ┆ …         ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ 39  ┆ Private     ┆ 215419 ┆ Bachelors ┆ … ┆ 0           ┆ 36          ┆ United-Sta ┆ 0          │
│     ┆             ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 64  ┆ null        ┆ 321403 ┆ HS-grad   ┆ … ┆ 0           ┆ 40          ┆ United-Sta ┆ 0          │
│     ┆             ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 38  ┆ Private     ┆ 374983 ┆ Bachelors ┆ … ┆ 0           ┆ 50          ┆ United-Sta ┆ 0          │
│     ┆             ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 44  ┆ Private     ┆ 83891  ┆ Bachelors ┆ … ┆ 0           ┆ 40          ┆ United-Sta ┆ 0          │
│     ┆             ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
│ 35  ┆ Self-emp-in ┆ 182148 ┆ Bachelors ┆ … ┆ 0           ┆ 60          ┆ United-Sta ┆ 1          │
│     ┆ c           ┆        ┆           ┆   ┆             ┆             ┆ tes        ┆            │
└─────┴─────────────┴────────┴───────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [107]:
df_info = get_df_info_pl(adult_census_df)
# df_info

DataFrame shape: (48842, 15)
Data types (according to dtypes):
Number of numerical columns: 6:
['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week']
  - Integer columns: 6: ['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week']
  - Float columns: 0: []
Number of categorical columns: 9:
['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country', 'is_high_income']
  - Multiclass columns: 7: ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'native-country']
  - Binary columns: 2: ['sex', 'is_high_income']
  - Boolean columns: 0: []
Total categorical cardinality: 107
Total types count:
total numerical: 6 (int: 6, float: 0),
Total categorical: 9 (multi-class: 7, bin_cat: 2, bool_cat: 0):
Columns with missing values: 3

In [108]:
# Get metadata for Polars DataFrame
pl_metadata = get_pl_metadata(adult_census_df)
# pp(pl_metadata)

# Retrieves column types from metadata
catCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "categorical"]
intCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "numerical" and v["subtype"] == "int"]
floatCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "numerical" and v["subtype"] == "float"]
binCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "categorical" and v["subtype"] == "binary"]
numCols = intCols + floatCols
print("catCols: ", catCols)
print("intCols: ", intCols)
print("floatCols: ", floatCols)
print("binCols: ", binCols)
print("numCols: ", numCols)
print("target_col: ", target_col_name)

catCols:  ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country', 'is_high_income']
intCols:  ['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week']
floatCols:  []
binCols:  ['sex', 'is_high_income']
numCols:  ['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week']
target_col:  is_high_income

In [109]:
catCols_noTarget = [j for j in catCols if j != target_col_name]
print("catCols_noTarget: ", catCols_noTarget)  # catCols_noTarget

catCols_noTarget:  ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']

In [110]:
num_col_idx = [i for i, col in enumerate(adult_census_df.columns) if col in numCols]
cat_col_idx = [i for i, col in enumerate(adult_census_df.columns) if col in catCols_noTarget]
target_col_idx = adult_census_df.columns.index(target_col_name)
cat_col_idx, num_col_idx, target_col_idx

([1, 3, 5, 6, 7, 8, 9, 13], [0, 2, 4, 10, 11, 12], 14)

In [111]:
adult_census_df = adult_census_df.select(catCols_noTarget + numCols + [target_col_name])
adult_census_df

shape: (48_842, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ workclass ┆ education ┆ marital-s ┆ occupatio ┆ … ┆ capital-g ┆ capital-l ┆ hours-per ┆ is_high_ │
│ ---       ┆ ---       ┆ tatus     ┆ n         ┆   ┆ ain       ┆ oss       ┆ -week     ┆ income   │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ i64       ┆ i64       ┆ i64       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ State-gov ┆ Bachelors ┆ Never-mar ┆ Adm-cleri ┆ … ┆ 2174      ┆ 0         ┆ 40        ┆ 0        │
│           ┆           ┆ ried      ┆ cal       ┆   ┆           ┆           ┆           ┆          │
│ Self-emp- ┆ Bachelors ┆ Married-c ┆ Exec-mana ┆ … ┆ 0         ┆ 0         ┆ 13        ┆ 0        │
│ not-inc   ┆           ┆ iv-spouse ┆ gerial    ┆   ┆           ┆           ┆           ┆          │
│ Private   ┆ HS-grad   ┆ Divorced  ┆ Handlers- ┆ … ┆ 0         ┆ 0         ┆ 40        ┆ 0        │
│           ┆           ┆           ┆ cleaners  ┆   ┆           ┆           ┆           ┆          │
│ Private   ┆ 11th      ┆ Married-c ┆ Handlers- ┆ … ┆ 0         ┆ 0         ┆ 40        ┆ 0        │
│           ┆           ┆ iv-spouse ┆ cleaners  ┆   ┆           ┆           ┆           ┆          │
│ Private   ┆ Bachelors ┆ Married-c ┆ Prof-spec ┆ … ┆ 0         ┆ 0         ┆ 40        ┆ 0        │
│           ┆           ┆ iv-spouse ┆ ialty     ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Private   ┆ Bachelors ┆ Divorced  ┆ Prof-spec ┆ … ┆ 0         ┆ 0         ┆ 36        ┆ 0        │
│           ┆           ┆           ┆ ialty     ┆   ┆           ┆           ┆           ┆          │
│ null      ┆ HS-grad   ┆ Widowed   ┆ null      ┆ … ┆ 0         ┆ 0         ┆ 40        ┆ 0        │
│ Private   ┆ Bachelors ┆ Married-c ┆ Prof-spec ┆ … ┆ 0         ┆ 0         ┆ 50        ┆ 0        │
│           ┆           ┆ iv-spouse ┆ ialty     ┆   ┆           ┆           ┆           ┆          │
│ Private   ┆ Bachelors ┆ Divorced  ┆ Adm-cleri ┆ … ┆ 5455      ┆ 0         ┆ 40        ┆ 0        │
│           ┆           ┆           ┆ cal       ┆   ┆           ┆           ┆           ┆          │
│ Self-emp- ┆ Bachelors ┆ Married-c ┆ Exec-mana ┆ … ┆ 0         ┆ 0         ┆ 60        ┆ 1        │
│ inc       ┆           ┆ iv-spouse ┆ gerial    ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [112]:
adult_census_df = adult_census_df.drop_nulls()

In [113]:
adult_census_df.shape

(47621, 15)

In [114]:
adult_census_df.drop_nans()

shape: (47_621, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ workclass ┆ education ┆ marital-s ┆ occupatio ┆ … ┆ capital-g ┆ capital-l ┆ hours-per ┆ is_high_ │
│ ---       ┆ ---       ┆ tatus     ┆ n         ┆   ┆ ain       ┆ oss       ┆ -week     ┆ income   │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ i64       ┆ i64       ┆ i64       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ State-gov ┆ Bachelors ┆ Never-mar ┆ Adm-cleri ┆ … ┆ 2174      ┆ 0         ┆ 40        ┆ 0        │
│           ┆           ┆ ried      ┆ cal       ┆   ┆           ┆           ┆           ┆          │
│ Self-emp- ┆ Bachelors ┆ Married-c ┆ Exec-mana ┆ … ┆ 0         ┆ 0         ┆ 13        ┆ 0        │
│ not-inc   ┆           ┆ iv-spouse ┆ gerial    ┆   ┆           ┆           ┆           ┆          │
│ Private   ┆ HS-grad   ┆ Divorced  ┆ Handlers- ┆ … ┆ 0         ┆ 0         ┆ 40        ┆ 0        │
│           ┆           ┆           ┆ cleaners  ┆   ┆           ┆           ┆           ┆          │
│ Private   ┆ 11th      ┆ Married-c ┆ Handlers- ┆ … ┆ 0         ┆ 0         ┆ 40        ┆ 0        │
│           ┆           ┆ iv-spouse ┆ cleaners  ┆   ┆           ┆           ┆           ┆          │
│ Private   ┆ Bachelors ┆ Married-c ┆ Prof-spec ┆ … ┆ 0         ┆ 0         ┆ 40        ┆ 0        │
│           ┆           ┆ iv-spouse ┆ ialty     ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Private   ┆ Bachelors ┆ Never-mar ┆ Prof-spec ┆ … ┆ 0         ┆ 0         ┆ 40        ┆ 0        │
│           ┆           ┆ ried      ┆ ialty     ┆   ┆           ┆           ┆           ┆          │
│ Private   ┆ Bachelors ┆ Divorced  ┆ Prof-spec ┆ … ┆ 0         ┆ 0         ┆ 36        ┆ 0        │
│           ┆           ┆           ┆ ialty     ┆   ┆           ┆           ┆           ┆          │
│ Private   ┆ Bachelors ┆ Married-c ┆ Prof-spec ┆ … ┆ 0         ┆ 0         ┆ 50        ┆ 0        │
│           ┆           ┆ iv-spouse ┆ ialty     ┆   ┆           ┆           ┆           ┆          │
│ Private   ┆ Bachelors ┆ Divorced  ┆ Adm-cleri ┆ … ┆ 5455      ┆ 0         ┆ 40        ┆ 0        │
│           ┆           ┆           ┆ cal       ┆   ┆           ┆           ┆           ┆          │
│ Self-emp- ┆ Bachelors ┆ Married-c ┆ Exec-mana ┆ … ┆ 0         ┆ 0         ┆ 60        ┆ 1        │
│ inc       ┆           ┆ iv-spouse ┆ gerial    ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [115]:
train, valid, test = pl_train_valid_test_split(adult_census_df, splits=[0.7, 0.15, 0.15], seed=420)

print("Train shape:", train.shape, "Valid shape:", valid.shape, "Test shape:", test.shape)

Train shape: (33334, 15) Valid shape: (7143, 15) Test shape: (7144, 15)

In [116]:
#### save the datasets as parquet:
info = get_df_info_pl(adult_census_df)

adult_census_path = "/Users/leec/Documents/datasets/parquet/adult_census/"
# make sure the output directory exists, and create it if it doesn't:
os.makedirs(adult_census_path, exist_ok=True)

adult_census_train_output_path = os.path.join(adult_census_path, "adult_census_train.parquet")
adult_census_valid_output_path = os.path.join(adult_census_path, "adult_census_valid.parquet")
adult_census_test_output_path = os.path.join(adult_census_path, "adult_census_test.parquet")

train.write_parquet(adult_census_train_output_path)
valid.write_parquet(adult_census_valid_output_path)
test.write_parquet(adult_census_test_output_path)


# create an `info.json` file with the metadata information:
metadata = {
    "name": "adult_census",
    "task_type": "binclass", # binclass, multiclass, regression 
    "target_col_name": target_col_name,
    "train_size": train.shape[0],
    "val_size": valid.shape[0],
    "test_size": test.shape[0],
    "catCols": info["catCols"],
    "intCols": info["intCols"],
    "floatCols": info["floatCols"]   
}

metadata_output_path = os.path.join(adult_census_path, "info.json")
with open(metadata_output_path, "w") as f:
    json.dump(metadata, f, indent=4)
    
metadata

DataFrame shape: (47621, 15)
Data types (according to dtypes):
Number of numerical columns: 6:
['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week']
  - Integer columns: 6: ['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week']
  - Float columns: 0: []
Number of categorical columns: 9:
['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country', 'is_high_income']
  - Multiclass columns: 7: ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'native-country']
  - Binary columns: 2: ['sex', 'is_high_income']
  - Boolean columns: 0: []
Total categorical cardinality: 104
Total types count:
total numerical: 6 (int: 6, float: 0),
Total categorical: 9 (multi-class: 7, bin_cat: 2, bool_cat: 0):
Columns with missing values: 0

{'name': 'adult_census',
 'task_type': 'binclass',
 'target_col_name': 'is_high_income',
 'train_size': 33334,
 'val_size': 7143,
 'test_size': 7144,
 'catCols': ['workclass',
  'education',
  'marital-status',
  'occupation',
  'relationship',
  'race',
  'sex',
  'native-country',
  'is_high_income'],
 'intCols': ['age',
  'fnlwgt',
  'education-num',
  'capital-gain',
  'capital-loss',
  'hours-per-week'],
 'floatCols': []}

In [ ]:
# save the datasets as pickle:
adult_census_output_path = "/Users/leec/Documents/datasets/adult_census/"
# make sure the output directory exists, and create it if it doesn't:
os.makedirs(adult_census_output_path, exist_ok=True)

adult_census_train_output_path = os.path.join(adult_census_output_path, "adult_census_train.pkl")
adult_census_valid_output_path = os.path.join(adult_census_output_path, "adult_census_valid.pkl")
adult_census_test_output_path = os.path.join(adult_census_output_path, "adult_census_test.pkl")

# pickle the datasets:
with open(adult_census_train_output_path, "wb") as f:
    pickle.dump(train, f)
with open(adult_census_valid_output_path, "wb") as f:
    pickle.dump(valid, f)
with open(adult_census_test_output_path, "wb") as f:
    pickle.dump(test, f)


## also save as csv:

adult_census_train_output_path = os.path.join(adult_census_output_path, "adult_census_train.csv")
adult_census_valid_output_path = os.path.join(adult_census_output_path, "adult_census_valid.csv")
adult_census_test_output_path = os.path.join(adult_census_output_path, "adult_census_test.csv")

train.write_csv(adult_census_train_output_path)
valid.write_csv(adult_census_valid_output_path)
test.write_csv(adult_census_test_output_path)

In [30]:
train.columns

['workclass',
 'education',
 'marital-status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'native-country',
 'age',
 'fnlwgt',
 'education-num',
 'capital-gain',
 'capital-loss',
 'hours-per-week',
 'is_high_income']

### Credit-default Taiwan

In [77]:
credit_taiwan_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(
    name="credit-defualt-taiwan", source="uci", df_type="polars"
)
var_types, target_col_name, prediction_task

({'ID': 'Integer',
  'X1': 'Integer',
  'X2': 'Integer',
  'X3': 'Integer',
  'X4': 'Integer',
  'X5': 'Integer',
  'X6': 'Integer',
  'X7': 'Integer',
  'X8': 'Integer',
  'X9': 'Integer',
  'X10': 'Integer',
  'X11': 'Integer',
  'X12': 'Integer',
  'X13': 'Integer',
  'X14': 'Integer',
  'X15': 'Integer',
  'X16': 'Integer',
  'X17': 'Integer',
  'X18': 'Integer',
  'X19': 'Integer',
  'X20': 'Integer',
  'X21': 'Integer',
  'X22': 'Integer',
  'X23': 'Integer',
  'Y': 'Binary'},
 'Y',
 'binary_classification')

In [78]:
credit_taiwan_df

shape: (30_000, 24)
┌────────┬─────┬─────┬─────┬───┬──────┬───────┬──────┬─────┐
│ X1     ┆ X2  ┆ X3  ┆ X4  ┆ … ┆ X21  ┆ X22   ┆ X23  ┆ Y   │
│ ---    ┆ --- ┆ --- ┆ --- ┆   ┆ ---  ┆ ---   ┆ ---  ┆ --- │
│ i64    ┆ i64 ┆ i64 ┆ i64 ┆   ┆ i64  ┆ i64   ┆ i64  ┆ i64 │
╞════════╪═════╪═════╪═════╪═══╪══════╪═══════╪══════╪═════╡
│ 20000  ┆ 2   ┆ 2   ┆ 1   ┆ … ┆ 0    ┆ 0     ┆ 0    ┆ 1   │
│ 120000 ┆ 2   ┆ 2   ┆ 2   ┆ … ┆ 1000 ┆ 0     ┆ 2000 ┆ 1   │
│ 90000  ┆ 2   ┆ 2   ┆ 2   ┆ … ┆ 1000 ┆ 1000  ┆ 5000 ┆ 0   │
│ 50000  ┆ 2   ┆ 2   ┆ 1   ┆ … ┆ 1100 ┆ 1069  ┆ 1000 ┆ 0   │
│ 50000  ┆ 1   ┆ 2   ┆ 1   ┆ … ┆ 9000 ┆ 689   ┆ 679  ┆ 0   │
│ …      ┆ …   ┆ …   ┆ …   ┆ … ┆ …    ┆ …     ┆ …    ┆ …   │
│ 220000 ┆ 1   ┆ 3   ┆ 1   ┆ … ┆ 3047 ┆ 5000  ┆ 1000 ┆ 0   │
│ 150000 ┆ 1   ┆ 3   ┆ 2   ┆ … ┆ 129  ┆ 0     ┆ 0    ┆ 0   │
│ 30000  ┆ 1   ┆ 2   ┆ 2   ┆ … ┆ 4200 ┆ 2000  ┆ 3100 ┆ 1   │
│ 80000  ┆ 1   ┆ 3   ┆ 1   ┆ … ┆ 1926 ┆ 52964 ┆ 1804 ┆ 1   │
│ 50000  ┆ 1   ┆ 2   ┆ 1   ┆ … ┆ 1000 ┆ 1000  ┆ 1000 ┆ 1   │
└────────┴─────┴─────┴─────┴───┴──────┴───────┴──────┴─────┘

In [79]:
# get_df_info_pl(credit_taiwan_df)

In [80]:
metadata["additional_info"]["variable_info"].split("\r\n")

['This research employed a binary variable, default payment (Yes = 1, No = 0), as the response variable. This study reviewed the literature and used the following 23 variables as explanatory variables:',
 'X1: Amount of the given credit (NT dollar): it includes both the individual consumer credit and his/her family (supplementary) credit.',
 'X2: Gender (1 = male; 2 = female).',
 'X3: Education (1 = graduate school; 2 = university; 3 = high school; 4 = others).',
 'X4: Marital status (1 = married; 2 = single; 3 = others).',
 'X5: Age (year).',
 'X6 - X11: History of past payment. We tracked the past monthly payment records (from April to September, 2005) as follows: X6 = the repayment status in September, 2005; X7 = the repayment status in August, 2005; . . .;X11 = the repayment status in April, 2005. The measurement scale for the repayment status is: -1 = pay duly; 1 = payment delay for one month; 2 = payment delay for two months; . . .; 8 = payment delay for eight months; 9 = payment delay for nine months and above.',
 'X12-X17: Amount of bill statement (NT dollar). X12 = amount of bill statement in September, 2005; X13 = amount of bill statement in August, 2005; . . .; X17 = amount of bill statement in April, 2005. ',
 'X18-X23: Amount of previous payment (NT dollar). X18 = amount paid in September, 2005; X19 = amount paid in August, 2005; . . .;X23 = amount paid in April, 2005.',
 '']

In [81]:
col_mapping = {
    "X1": "Credit_Amount",
    "X2": "Gender",
    "X3": "Education_Level",
    "X4": "Marital_Status",
    "X5": "Age",
    "X6": "Pay_0",
    "X7": "Pay_2",
    "X8": "Pay_3",
    "X9": "Pay_4",
    "X10": "Pay_5",
    "X11": "Pay_6",
    "X12": "Bill_Amount1",
    "X13": "Bill_Amount2",
    "X14": "Bill_Amount3",
    "X15": "Bill_Amount4",
    "X16": "Bill_Amount5",
    "X17": "Bill_Amount6",
    "X18": "Pay_Amount1",
    "X19": "Pay_Amount2",
    "X20": "Pay_Amount3",
    "X21": "Pay_Amount4",
    "X22": "Pay_Amount5",
    "X23": "Pay_Amount6",
    "Y": "default",
}

catCols = [
    "Gender",
    "Education_Level",
    "Marital_Status",
    "default",
]


credit_taiwan_df = credit_taiwan_df.rename(col_mapping)
credit_taiwan_df = credit_taiwan_df.with_columns(pl.col(catCols).cast(pl.Utf8))
credit_taiwan_df

shape: (30_000, 24)
┌────────────┬────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬─────────┐
│ Credit_Amo ┆ Gender ┆ Education_ ┆ Marital_St ┆ … ┆ Pay_Amount ┆ Pay_Amoun ┆ Pay_Amoun ┆ default │
│ unt        ┆ ---    ┆ Level      ┆ atus       ┆   ┆ 4          ┆ t5        ┆ t6        ┆ ---     │
│ ---        ┆ str    ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ str     │
│ i64        ┆        ┆ str        ┆ str        ┆   ┆ i64        ┆ i64       ┆ i64       ┆         │
╞════════════╪════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═════════╡
│ 20000      ┆ 2      ┆ 2          ┆ 1          ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 1       │
│ 120000     ┆ 2      ┆ 2          ┆ 2          ┆ … ┆ 1000       ┆ 0         ┆ 2000      ┆ 1       │
│ 90000      ┆ 2      ┆ 2          ┆ 2          ┆ … ┆ 1000       ┆ 1000      ┆ 5000      ┆ 0       │
│ 50000      ┆ 2      ┆ 2          ┆ 1          ┆ … ┆ 1100       ┆ 1069      ┆ 1000      ┆ 0       │
│ 50000      ┆ 1      ┆ 2          ┆ 1          ┆ … ┆ 9000       ┆ 689       ┆ 679       ┆ 0       │
│ …          ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …       │
│ 220000     ┆ 1      ┆ 3          ┆ 1          ┆ … ┆ 3047       ┆ 5000      ┆ 1000      ┆ 0       │
│ 150000     ┆ 1      ┆ 3          ┆ 2          ┆ … ┆ 129        ┆ 0         ┆ 0         ┆ 0       │
│ 30000      ┆ 1      ┆ 2          ┆ 2          ┆ … ┆ 4200       ┆ 2000      ┆ 3100      ┆ 1       │
│ 80000      ┆ 1      ┆ 3          ┆ 1          ┆ … ┆ 1926       ┆ 52964     ┆ 1804      ┆ 1       │
│ 50000      ┆ 1      ┆ 2          ┆ 1          ┆ … ┆ 1000       ┆ 1000      ┆ 1000      ┆ 1       │
└────────────┴────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴─────────┘

In [82]:
credit_taiwan_df.drop_nulls()

shape: (30_000, 24)
┌────────────┬────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬─────────┐
│ Credit_Amo ┆ Gender ┆ Education_ ┆ Marital_St ┆ … ┆ Pay_Amount ┆ Pay_Amoun ┆ Pay_Amoun ┆ default │
│ unt        ┆ ---    ┆ Level      ┆ atus       ┆   ┆ 4          ┆ t5        ┆ t6        ┆ ---     │
│ ---        ┆ str    ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ str     │
│ i64        ┆        ┆ str        ┆ str        ┆   ┆ i64        ┆ i64       ┆ i64       ┆         │
╞════════════╪════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═════════╡
│ 20000      ┆ 2      ┆ 2          ┆ 1          ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 1       │
│ 120000     ┆ 2      ┆ 2          ┆ 2          ┆ … ┆ 1000       ┆ 0         ┆ 2000      ┆ 1       │
│ 90000      ┆ 2      ┆ 2          ┆ 2          ┆ … ┆ 1000       ┆ 1000      ┆ 5000      ┆ 0       │
│ 50000      ┆ 2      ┆ 2          ┆ 1          ┆ … ┆ 1100       ┆ 1069      ┆ 1000      ┆ 0       │
│ 50000      ┆ 1      ┆ 2          ┆ 1          ┆ … ┆ 9000       ┆ 689       ┆ 679       ┆ 0       │
│ …          ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …       │
│ 220000     ┆ 1      ┆ 3          ┆ 1          ┆ … ┆ 3047       ┆ 5000      ┆ 1000      ┆ 0       │
│ 150000     ┆ 1      ┆ 3          ┆ 2          ┆ … ┆ 129        ┆ 0         ┆ 0         ┆ 0       │
│ 30000      ┆ 1      ┆ 2          ┆ 2          ┆ … ┆ 4200       ┆ 2000      ┆ 3100      ┆ 1       │
│ 80000      ┆ 1      ┆ 3          ┆ 1          ┆ … ┆ 1926       ┆ 52964     ┆ 1804      ┆ 1       │
│ 50000      ┆ 1      ┆ 2          ┆ 1          ┆ … ┆ 1000       ┆ 1000      ┆ 1000      ┆ 1       │
└────────────┴────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴─────────┘

In [83]:
get_df_info_pl(credit_taiwan_df)

DataFrame shape: (30000, 24)
Data types (according to dtypes):
Number of numerical columns: 20:
['Credit_Amount', 'Age', 'Pay_0', 'Pay_2', 'Pay_3', 'Pay_4', 'Pay_5', 'Pay_6', 'Bill_Amount1', 'Bill_Amount2', 'Bill_Amount3', 'Bill_Amount4', 'Bill_Amount5', 'Bill_Amount6', 'Pay_Amount1', 'Pay_Amount2', 'Pay_Amount3', 'Pay_Amount4', 'Pay_Amount5', 'Pay_Amount6']
  - Integer columns: 20: ['Credit_Amount', 'Age', 'Pay_0', 'Pay_2', 'Pay_3', 'Pay_4', 'Pay_5', 'Pay_6', 'Bill_Amount1', 'Bill_Amount2', 'Bill_Amount3', 'Bill_Amount4', 'Bill_Amount5', 'Bill_Amount6', 'Pay_Amount1', 'Pay_Amount2', 'Pay_Amount3', 'Pay_Amount4', 'Pay_Amount5', 'Pay_Amount6']
  - Float columns: 0: []
Number of categorical columns: 4:
['Gender', 'Education_Level', 'Marital_Status', 'default']
  - Multiclass columns: 2: ['Education_Level', 'Marital_Status']
  - Binary columns: 2: ['Gender', 'default']
  - Boolean columns: 0: []
Total categorical cardinality: 15
Total types count:
total numerical: 20 (int: 20, float: 0),
Total categorical: 4 (multi-class: 2, bin_cat: 2, bool_cat: 0):
Columns with missing values: 0

{'dtypes': {'Credit_Amount': 'Int64',
  'Gender': 'String',
  'Education_Level': 'String',
  'Marital_Status': 'String',
  'Age': 'Int64',
  'Pay_0': 'Int64',
  'Pay_2': 'Int64',
  'Pay_3': 'Int64',
  'Pay_4': 'Int64',
  'Pay_5': 'Int64',
  'Pay_6': 'Int64',
  'Bill_Amount1': 'Int64',
  'Bill_Amount2': 'Int64',
  'Bill_Amount3': 'Int64',
  'Bill_Amount4': 'Int64',
  'Bill_Amount5': 'Int64',
  'Bill_Amount6': 'Int64',
  'Pay_Amount1': 'Int64',
  'Pay_Amount2': 'Int64',
  'Pay_Amount3': 'Int64',
  'Pay_Amount4': 'Int64',
  'Pay_Amount5': 'Int64',
  'Pay_Amount6': 'Int64',
  'default': 'String'},
 'shape': (30000, 24),
 'numCols': ['Credit_Amount',
  'Age',
  'Pay_0',
  'Pay_2',
  'Pay_3',
  'Pay_4',
  'Pay_5',
  'Pay_6',
  'Bill_Amount1',
  'Bill_Amount2',
  'Bill_Amount3',
  'Bill_Amount4',
  'Bill_Amount5',
  'Bill_Amount6',
  'Pay_Amount1',
  'Pay_Amount2',
  'Pay_Amount3',
  'Pay_Amount4',
  'Pay_Amount5',
  'Pay_Amount6'],
 'numColsTotal': 20,
 'intCols': ['Credit_Amount',
  'Age',
  'Pay_0',
  'Pay_2',
  'Pay_3',
  'Pay_4',
  'Pay_5',
  'Pay_6',
  'Bill_Amount1',
  'Bill_Amount2',
  'Bill_Amount3',
  'Bill_Amount4',
  'Bill_Amount5',
  'Bill_Amount6',
  'Pay_Amount1',
  'Pay_Amount2',
  'Pay_Amount3',
  'Pay_Amount4',
  'Pay_Amount5',
  'Pay_Amount6'],
 'intColsTotal': 20,
 'floatCols': [],
 'floatColsTotal': 0,
 'catCols': ['Gender', 'Education_Level', 'Marital_Status', 'default'],
 'catColsTotal': 4,
 'binCols': ['Gender', 'default'],
 'binColsTotal': 2,
 'boolCols': [],
 'boolColsTotal': 0,
 'cardinality': {'Gender': 2,
  'Education_Level': 7,
  'Marital_Status': 4,
  'default': 2},
 'total_cardinality': 15,
 'nulls': {'Credit_Amount': 0,
  'Gender': 0,
  'Education_Level': 0,
  'Marital_Status': 0,
  'Age': 0,
  'Pay_0': 0,
  'Pay_2': 0,
  'Pay_3': 0,
  'Pay_4': 0,
  'Pay_5': 0,
  'Pay_6': 0,
  'Bill_Amount1': 0,
  'Bill_Amount2': 0,
  'Bill_Amount3': 0,
  'Bill_Amount4': 0,
  'Bill_Amount5': 0,
  'Bill_Amount6': 0,
  'Pay_Amount1': 0,
  'Pay_Amount2': 0,
  'Pay_Amount3': 0,
  'Pay_Amount4': 0,
  'Pay_Amount5': 0,
  'Pay_Amount6': 0,
  'default': 0},
 'missing_pct': {'Credit_Amount': 0.0,
  'Gender': 0.0,
  'Education_Level': 0.0,
  'Marital_Status': 0.0,
  'Age': 0.0,
  'Pay_0': 0.0,
  'Pay_2': 0.0,
  'Pay_3': 0.0,
  'Pay_4': 0.0,
  'Pay_5': 0.0,
  'Pay_6': 0.0,
  'Bill_Amount1': 0.0,
  'Bill_Amount2': 0.0,
  'Bill_Amount3': 0.0,
  'Bill_Amount4': 0.0,
  'Bill_Amount5': 0.0,
  'Bill_Amount6': 0.0,
  'Pay_Amount1': 0.0,
  'Pay_Amount2': 0.0,
  'Pay_Amount3': 0.0,
  'Pay_Amount4': 0.0,
  'Pay_Amount5': 0.0,
  'Pay_Amount6': 0.0,
  'default': 0.0},
 'numeric_stats': {'Credit_Amount': {'mean': 167484.32266666667,
   'std': 129747.6615672024,
   'min': 10000.0,
   'median': 140000.0,
   'max': 1000000.0,
   'missing': 0},
  'Age': {'mean': 35.4855,
   'std': 9.21790406809019,
   'min': 21.0,
   'median': 34.0,
   'max': 79.0,
   'missing': 0},
  'Pay_0': {'mean': -0.0167,
   'std': 1.1238015279973348,
   'min': -2.0,
   'median': 0.0,
   'max': 8.0,
   'missing': 0},
  'Pay_2': {'mean': -0.13376666666666667,
   'std': 1.1971859730345533,
   'min': -2.0,
   'median': 0.0,
   'max': 8.0,
   'missing': 0},
  'Pay_3': {'mean': -0.1662,
   'std': 1.1968675684465733,
   'min': -2.0,
   'median': 0.0,
   'max': 8.0,
   'missing': 0},
  'Pay_4': {'mean': -0.22066666666666668,
   'std': 1.1691386224023368,
   'min': -2.0,
   'median': 0.0,
   'max': 8.0,
   'missing': 0},
  'Pay_5': {'mean': -0.2662,
   'std': 1.1331874060027483,
   'min': -2.0,
   'median': 0.0,
   'max': 8.0,
   'missing': 0},
  'Pay_6': {'mean': -0.2911,
   'std': 1.1499876256079027,
   'min': -2.0,
   'median': 0.0,
   'max': 8.0,
   'missing': 0},
  'Bill_Amount1': {'mean': 51223.3309,
   'std': 73635.86057552954,
   'min': -165580.0,
   'median': 22381.5,
   'max': 964511.0,
   'missing': 0},
  'Bill_Amount2': {'mean': 49179.07516666667,
   'std': 71173.76878252835,
   'min': -69777.0,
   'median': 21200.0,
   'max': 983931.0,
   'missing': 0},
  'Bill_Amount3': {'mean': 47013.1548,
   'std': 69349.3874270368,
   'min': -157264.0,
   'median': 20088.5,
   'max': 1664089.0,
   'missing': 0},
  'Bill_Amount4': {'mean': 43262.94896666666,
   'std': 64332.85613391631,
   'min': -170000.0,
   'median': 19052.0,
   'max': 891586.0,
   'missing': 0},
  'Bill_Amount5': {'mean': 40311.40096666667,
   'std': 60797.155770264864,
   'min': -81334.0,
   'median': 18104.5,
   'max': 927171.0,
   'missing': 0},
  'Bill_Amount6': {'mean': 38871.7604,
   'std': 59554.10753674573,
   'min': -339603.0,
   'median': 17071.0,
   'max': 961664.0,
   'missing': 0},
  'Pay_Amount1': {'mean': 5663.5805,
   'std': 16563.28035402577,
   'min': 0.0,
   'median': 2100.0,
   'max': 873552.0,
   'missing': 0},
  'Pay_Amount2': {'mean': 5921.1635,
   'std': 23040.87040205724,
   'min': 0.0,
   'median': 2009.0,
   'max': 1684259.0,
   'missing': 0},
  'Pay_Amount3': {'mean': 5225.6815,
   'std': 17606.961469803104,
   'min': 0.0,
   'median': 1800.0,
   'max': 896040.0,
   'missing': 0},
  'Pay_Amount4': {'mean': 4826.076866666666,
   'std': 15666.159744032013,
   'min': 0.0,
   'median': 1500.0,
   'max': 621000.0,
   'missing': 0},
  'Pay_Amount5': {'mean': 4799.387633333334,
   'std': 15278.305679144789,
   'min': 0.0,
   'median': 1500.0,
   'max': 426529.0,
   'missing': 0},
  'Pay_Amount6': {'mean': 5215.502566666667,
   'std': 17777.465775435303,
   'min': 0.0,
   'median': 1500.0,
   'max': 528666.0,
   'missing': 0}},
 'top_unique': {'Gender': ['2', '1'],
  'Education_Level': ['6', '2', '1', '5', '3', '0', '4'],
  'Marital_Status': ['2', '1', '3', '0'],
  'default': ['0', '1']}}

In [84]:
target_col_name = "default"

In [85]:
# Get metadata for Polars DataFrame
pl_metadata = get_pl_metadata(credit_taiwan_df)
# pp(pl_metadata)

# Retrieves column types from metadata
catCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "categorical"]
intCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "numerical" and v["subtype"] == "int"]
floatCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "numerical" and v["subtype"] == "float"]
binCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "categorical" and v["subtype"] == "binary"]
numCols = intCols + floatCols
print("catCols: ", catCols)
print("intCols: ", intCols)
print("floatCols: ", floatCols)
print("binCols: ", binCols)
print("numCols: ", numCols)
print("target_col: ", target_col_name)

catCols:  ['Gender', 'Education_Level', 'Marital_Status', 'default']
intCols:  ['Credit_Amount', 'Age', 'Pay_0', 'Pay_2', 'Pay_3', 'Pay_4', 'Pay_5', 'Pay_6', 'Bill_Amount1', 'Bill_Amount2', 'Bill_Amount3', 'Bill_Amount4', 'Bill_Amount5', 'Bill_Amount6', 'Pay_Amount1', 'Pay_Amount2', 'Pay_Amount3', 'Pay_Amount4', 'Pay_Amount5', 'Pay_Amount6']
floatCols:  []
binCols:  ['Gender', 'default']
numCols:  ['Credit_Amount', 'Age', 'Pay_0', 'Pay_2', 'Pay_3', 'Pay_4', 'Pay_5', 'Pay_6', 'Bill_Amount1', 'Bill_Amount2', 'Bill_Amount3', 'Bill_Amount4', 'Bill_Amount5', 'Bill_Amount6', 'Pay_Amount1', 'Pay_Amount2', 'Pay_Amount3', 'Pay_Amount4', 'Pay_Amount5', 'Pay_Amount6']
target_col:  default

In [86]:
catCols_noTarget = [j for j in catCols if j != target_col_name]
catCols_noTarget
# get a list of indexes of numerical columns:
num_col_idx = [i for i, col in enumerate(credit_taiwan_df.columns) if col in numCols]
cat_col_idx = [i for i, col in enumerate(credit_taiwan_df.columns) if col in catCols_noTarget]
target_col_idx = credit_taiwan_df.columns.index(target_col_name)
cat_col_idx, num_col_idx, target_col_idx

([1, 2, 3],
 [0, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
 23)

In [87]:
catCols_noTarget + numCols + [target_col_name]

['Gender',
 'Education_Level',
 'Marital_Status',
 'Credit_Amount',
 'Age',
 'Pay_0',
 'Pay_2',
 'Pay_3',
 'Pay_4',
 'Pay_5',
 'Pay_6',
 'Bill_Amount1',
 'Bill_Amount2',
 'Bill_Amount3',
 'Bill_Amount4',
 'Bill_Amount5',
 'Bill_Amount6',
 'Pay_Amount1',
 'Pay_Amount2',
 'Pay_Amount3',
 'Pay_Amount4',
 'Pay_Amount5',
 'Pay_Amount6',
 'default']

In [88]:
credit_taiwan_df = credit_taiwan_df.select(catCols_noTarget + numCols + [target_col_name])
credit_taiwan_df

shape: (30_000, 24)
┌────────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬─────────┐
│ Gender ┆ Education_ ┆ Marital_St ┆ Credit_Amo ┆ … ┆ Pay_Amount ┆ Pay_Amoun ┆ Pay_Amoun ┆ default │
│ ---    ┆ Level      ┆ atus       ┆ unt        ┆   ┆ 4          ┆ t5        ┆ t6        ┆ ---     │
│ str    ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ str     │
│        ┆ str        ┆ str        ┆ i64        ┆   ┆ i64        ┆ i64       ┆ i64       ┆         │
╞════════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═════════╡
│ 2      ┆ 2          ┆ 1          ┆ 20000      ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 1       │
│ 2      ┆ 2          ┆ 2          ┆ 120000     ┆ … ┆ 1000       ┆ 0         ┆ 2000      ┆ 1       │
│ 2      ┆ 2          ┆ 2          ┆ 90000      ┆ … ┆ 1000       ┆ 1000      ┆ 5000      ┆ 0       │
│ 2      ┆ 2          ┆ 1          ┆ 50000      ┆ … ┆ 1100       ┆ 1069      ┆ 1000      ┆ 0       │
│ 1      ┆ 2          ┆ 1          ┆ 50000      ┆ … ┆ 9000       ┆ 689       ┆ 679       ┆ 0       │
│ …      ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …       │
│ 1      ┆ 3          ┆ 1          ┆ 220000     ┆ … ┆ 3047       ┆ 5000      ┆ 1000      ┆ 0       │
│ 1      ┆ 3          ┆ 2          ┆ 150000     ┆ … ┆ 129        ┆ 0         ┆ 0         ┆ 0       │
│ 1      ┆ 2          ┆ 2          ┆ 30000      ┆ … ┆ 4200       ┆ 2000      ┆ 3100      ┆ 1       │
│ 1      ┆ 3          ┆ 1          ┆ 80000      ┆ … ┆ 1926       ┆ 52964     ┆ 1804      ┆ 1       │
│ 1      ┆ 2          ┆ 1          ┆ 50000      ┆ … ┆ 1000       ┆ 1000      ┆ 1000      ┆ 1       │
└────────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴─────────┘

In [89]:
credit_taiwan_df.schema

Schema([('Gender', String),
        ('Education_Level', String),
        ('Marital_Status', String),
        ('Credit_Amount', Int64),
        ('Age', Int64),
        ('Pay_0', Int64),
        ('Pay_2', Int64),
        ('Pay_3', Int64),
        ('Pay_4', Int64),
        ('Pay_5', Int64),
        ('Pay_6', Int64),
        ('Bill_Amount1', Int64),
        ('Bill_Amount2', Int64),
        ('Bill_Amount3', Int64),
        ('Bill_Amount4', Int64),
        ('Bill_Amount5', Int64),
        ('Bill_Amount6', Int64),
        ('Pay_Amount1', Int64),
        ('Pay_Amount2', Int64),
        ('Pay_Amount3', Int64),
        ('Pay_Amount4', Int64),
        ('Pay_Amount5', Int64),
        ('Pay_Amount6', Int64),
        ('default', String)])

In [90]:
train, valid, test = pl_train_valid_test_split(credit_taiwan_df, splits=[0.7, 0.15, 0.15], seed=420)

print("Train shape:", train.shape, "Valid shape:", valid.shape, "Test shape:", test.shape)

Train shape: (21000, 24) Valid shape: (4500, 24) Test shape: (4500, 24)

In [91]:
#### save the datasets as parquet:
info = get_df_info_pl(credit_taiwan_df)

credit_taiwan_path = "/Users/leec/Documents/datasets/parquet/credit_taiwan/"
# make sure the output directory exists, and create it if it doesn't:
os.makedirs(credit_taiwan_path, exist_ok=True)

credit_taiwan_train_output_path = os.path.join(credit_taiwan_path, "credit_taiwan_train.parquet")
credit_taiwan_valid_output_path = os.path.join(credit_taiwan_path, "credit_taiwan_valid.parquet")
credit_taiwan_test_output_path = os.path.join(credit_taiwan_path, "credit_taiwan_test.parquet")

train.write_parquet(credit_taiwan_train_output_path)
valid.write_parquet(credit_taiwan_valid_output_path)
test.write_parquet(credit_taiwan_test_output_path)


# create an `info.json` file with the metadata information:
metadata = {
    "name": "credit_taiwan",
    "task_type": "binclass", # binclass, multiclass, regression 
    "target_col_name": target_col_name,
    "train_size": train.shape[0],
    "val_size": valid.shape[0],
    "test_size": test.shape[0],
    "catCols": info["catCols"],
    "intCols": info["intCols"],
    "floatCols": info["floatCols"]   
}

metadata_output_path = os.path.join(credit_taiwan_path, "info.json")
with open(metadata_output_path, "w") as f:
    json.dump(metadata, f, indent=4)
    
metadata

DataFrame shape: (30000, 24)
Data types (according to dtypes):
Number of numerical columns: 20:
['Credit_Amount', 'Age', 'Pay_0', 'Pay_2', 'Pay_3', 'Pay_4', 'Pay_5', 'Pay_6', 'Bill_Amount1', 'Bill_Amount2', 'Bill_Amount3', 'Bill_Amount4', 'Bill_Amount5', 'Bill_Amount6', 'Pay_Amount1', 'Pay_Amount2', 'Pay_Amount3', 'Pay_Amount4', 'Pay_Amount5', 'Pay_Amount6']
  - Integer columns: 20: ['Credit_Amount', 'Age', 'Pay_0', 'Pay_2', 'Pay_3', 'Pay_4', 'Pay_5', 'Pay_6', 'Bill_Amount1', 'Bill_Amount2', 'Bill_Amount3', 'Bill_Amount4', 'Bill_Amount5', 'Bill_Amount6', 'Pay_Amount1', 'Pay_Amount2', 'Pay_Amount3', 'Pay_Amount4', 'Pay_Amount5', 'Pay_Amount6']
  - Float columns: 0: []
Number of categorical columns: 4:
['Gender', 'Education_Level', 'Marital_Status', 'default']
  - Multiclass columns: 2: ['Education_Level', 'Marital_Status']
  - Binary columns: 2: ['Gender', 'default']
  - Boolean columns: 0: []
Total categorical cardinality: 15
Total types count:
total numerical: 20 (int: 20, float: 0),
Total categorical: 4 (multi-class: 2, bin_cat: 2, bool_cat: 0):
Columns with missing values: 0

{'name': 'credit_taiwan',
 'task_type': 'binclass',
 'target_col_name': 'default',
 'train_size': 21000,
 'val_size': 4500,
 'test_size': 4500,
 'catCols': ['Gender', 'Education_Level', 'Marital_Status', 'default'],
 'intCols': ['Credit_Amount',
  'Age',
  'Pay_0',
  'Pay_2',
  'Pay_3',
  'Pay_4',
  'Pay_5',
  'Pay_6',
  'Bill_Amount1',
  'Bill_Amount2',
  'Bill_Amount3',
  'Bill_Amount4',
  'Bill_Amount5',
  'Bill_Amount6',
  'Pay_Amount1',
  'Pay_Amount2',
  'Pay_Amount3',
  'Pay_Amount4',
  'Pay_Amount5',
  'Pay_Amount6'],
 'floatCols': []}

In [ ]:
credit_taiwan_output_path = "/Users/leec/Documents/datasets/credit_taiwan/"
credit_taiwan_train_output_path = os.path.join(credit_taiwan_output_path, "credit_taiwan_train.pkl")
credit_taiwan_valid_output_path = os.path.join(credit_taiwan_output_path, "credit_taiwan_valid.pkl")
credit_taiwan_test_output_path = os.path.join(credit_taiwan_output_path, "credit_taiwan_test.pkl")

# pickle the datasets:
with open(credit_taiwan_train_output_path, "wb") as f:
    pickle.dump(train, f)
with open(credit_taiwan_valid_output_path, "wb") as f:
    pickle.dump(valid, f)
with open(credit_taiwan_test_output_path, "wb") as f:
    pickle.dump(test, f)

In [62]:
credit_taiwan_output_path = "/Users/leec/Documents/datasets/credit_taiwan/"
credit_taiwan_train_output_path = os.path.join(credit_taiwan_output_path, "credit_taiwan_train.csv")
credit_taiwan_valid_output_path = os.path.join(credit_taiwan_output_path, "credit_taiwan_valid.csv")
credit_taiwan_test_output_path = os.path.join(credit_taiwan_output_path, "credit_taiwan_test.csv")

train.write_csv(credit_taiwan_train_output_path)
valid.write_csv(credit_taiwan_valid_output_path)
test.write_csv(credit_taiwan_test_output_path)

### cdc_diabetes

In [142]:
cdc_diabetes_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(
    name="cdc_diabetes", source="uci", df_type="polars"
)
cdc_diabetes_df

shape: (253_680, 22)
┌────────┬──────────┬───────────┬─────┬───┬─────┬───────────┬────────┬─────────────────┐
│ HighBP ┆ HighChol ┆ CholCheck ┆ BMI ┆ … ┆ Age ┆ Education ┆ Income ┆ Diabetes_binary │
│ ---    ┆ ---      ┆ ---       ┆ --- ┆   ┆ --- ┆ ---       ┆ ---    ┆ ---             │
│ i64    ┆ i64      ┆ i64       ┆ i64 ┆   ┆ i64 ┆ i64       ┆ i64    ┆ i64             │
╞════════╪══════════╪═══════════╪═════╪═══╪═════╪═══════════╪════════╪═════════════════╡
│ 1      ┆ 1        ┆ 1         ┆ 40  ┆ … ┆ 9   ┆ 4         ┆ 3      ┆ 0               │
│ 0      ┆ 0        ┆ 0         ┆ 25  ┆ … ┆ 7   ┆ 6         ┆ 1      ┆ 0               │
│ 1      ┆ 1        ┆ 1         ┆ 28  ┆ … ┆ 9   ┆ 4         ┆ 8      ┆ 0               │
│ 1      ┆ 0        ┆ 1         ┆ 27  ┆ … ┆ 11  ┆ 3         ┆ 6      ┆ 0               │
│ 1      ┆ 1        ┆ 1         ┆ 24  ┆ … ┆ 11  ┆ 5         ┆ 4      ┆ 0               │
│ …      ┆ …        ┆ …         ┆ …   ┆ … ┆ …   ┆ …         ┆ …      ┆ …               │
│ 1      ┆ 1        ┆ 1         ┆ 45  ┆ … ┆ 5   ┆ 6         ┆ 7      ┆ 0               │
│ 1      ┆ 1        ┆ 1         ┆ 18  ┆ … ┆ 11  ┆ 2         ┆ 4      ┆ 1               │
│ 0      ┆ 0        ┆ 1         ┆ 28  ┆ … ┆ 2   ┆ 5         ┆ 2      ┆ 0               │
│ 1      ┆ 0        ┆ 1         ┆ 23  ┆ … ┆ 7   ┆ 5         ┆ 1      ┆ 0               │
│ 1      ┆ 1        ┆ 1         ┆ 25  ┆ … ┆ 9   ┆ 6         ┆ 2      ┆ 1               │
└────────┴──────────┴───────────┴─────┴───┴─────┴───────────┴────────┴─────────────────┘

In [143]:
var_types

{'ID': 'Integer',
 'Diabetes_binary': 'Binary',
 'HighBP': 'Binary',
 'HighChol': 'Binary',
 'CholCheck': 'Binary',
 'BMI': 'Integer',
 'Smoker': 'Binary',
 'Stroke': 'Binary',
 'HeartDiseaseorAttack': 'Binary',
 'PhysActivity': 'Binary',
 'Fruits': 'Binary',
 'Veggies': 'Binary',
 'HvyAlcoholConsump': 'Binary',
 'AnyHealthcare': 'Binary',
 'NoDocbcCost': 'Binary',
 'GenHlth': 'Integer',
 'MentHlth': 'Integer',
 'PhysHlth': 'Integer',
 'DiffWalk': 'Binary',
 'Sex': 'Binary',
 'Age': 'Integer',
 'Education': 'Integer',
 'Income': 'Integer'}

In [144]:
# var_types.pop("ID")
intCols = [ k for k,v in var_types.items() if v == 'Integer']
binCols = [ k for k,v in var_types.items() if v == 'Binary']
floatCols = [ k for k,v in var_types.items() if v == 'Float']
# incCols = [ k for k,v in var_types.items() if v == 'Integer']
print(f"integer columns: {intCols}")
print(f"binary columns: {binCols}")
print(f"float columns: {floatCols}")
print(f"total number of columns: {len(intCols)+len(binCols)}")

integer columns: ['ID', 'BMI', 'GenHlth', 'MentHlth', 'PhysHlth', 'Age', 'Education', 'Income']
binary columns: ['Diabetes_binary', 'HighBP', 'HighChol', 'CholCheck', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'DiffWalk', 'Sex']
float columns: []
total number of columns: 23

In [145]:
intCols = ['BMI', 'GenHlth', 'MentHlth', 'PhysHlth', 'Age', ]
binCols =  ['Diabetes_binary', 'HighBP', 'HighChol', 'CholCheck', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'DiffWalk', 'Sex']
multiCatCols = ['Education','Income']
catCols = multiCatCols+binCols 
assert len(intCols + binCols + multiCatCols) == len(cdc_diabetes_df.columns)

In [146]:
# binCols = [k for k, v in var_types.items() if v == "Binary"]
# cdc_diabetes_df = cdc_diabetes_df.with_columns(pl.col(binCols).cast(pl.Utf8))
# tmp = get_df_info_pl(cdc_diabetes_df)

In [147]:
assert cdc_diabetes_df.drop_nans().shape == cdc_diabetes_df.shape
assert cdc_diabetes_df.drop_nulls().shape == cdc_diabetes_df.shape

In [148]:
# Get metadata for Polars DataFrame
# pl_metadata = get_pl_metadata(cdc_diabetes_df)
# pp(pl_metadata)

# Retrieves column types from metadata
# catCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "categorical"]
# intCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "numerical" and v["subtype"] == "int"]
# floatCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "numerical" and v["subtype"] == "float"]
# binCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "categorical" and v["subtype"] == "binary"]
numCols = intCols + floatCols
print("catCols: ", catCols)
print("intCols: ", intCols)
print("floatCols: ", floatCols)
print("binCols: ", binCols)
print("numCols: ", numCols)
print("target_col: ", target_col_name)

catCols:  ['Education', 'Income', 'Diabetes_binary', 'HighBP', 'HighChol', 'CholCheck', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'DiffWalk', 'Sex']
intCols:  ['BMI', 'GenHlth', 'MentHlth', 'PhysHlth', 'Age']
floatCols:  []
binCols:  ['Diabetes_binary', 'HighBP', 'HighChol', 'CholCheck', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'DiffWalk', 'Sex']
numCols:  ['BMI', 'GenHlth', 'MentHlth', 'PhysHlth', 'Age']
target_col:  Diabetes_binary

In [149]:
catCols_noTarget = [j for j in catCols if j != target_col_name]
print("catCols_noTarget: ", catCols_noTarget)  # catCols_noTarget

catCols_noTarget:  ['Education', 'Income', 'HighBP', 'HighChol', 'CholCheck', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'DiffWalk', 'Sex']

In [150]:
cdc_diabetes_df = cdc_diabetes_df.with_columns(pl.col(catCols).cast(pl.Utf8))

In [151]:
cdc_diabetes_df = cdc_diabetes_df.select(catCols_noTarget + numCols + [target_col_name])
cdc_diabetes_df

shape: (253_680, 22)
┌───────────┬────────┬────────┬──────────┬───┬──────────┬──────────┬─────┬─────────────────┐
│ Education ┆ Income ┆ HighBP ┆ HighChol ┆ … ┆ MentHlth ┆ PhysHlth ┆ Age ┆ Diabetes_binary │
│ ---       ┆ ---    ┆ ---    ┆ ---      ┆   ┆ ---      ┆ ---      ┆ --- ┆ ---             │
│ str       ┆ str    ┆ str    ┆ str      ┆   ┆ i64      ┆ i64      ┆ i64 ┆ str             │
╞═══════════╪════════╪════════╪══════════╪═══╪══════════╪══════════╪═════╪═════════════════╡
│ 4         ┆ 3      ┆ 1      ┆ 1        ┆ … ┆ 18       ┆ 15       ┆ 9   ┆ 0               │
│ 6         ┆ 1      ┆ 0      ┆ 0        ┆ … ┆ 0        ┆ 0        ┆ 7   ┆ 0               │
│ 4         ┆ 8      ┆ 1      ┆ 1        ┆ … ┆ 30       ┆ 30       ┆ 9   ┆ 0               │
│ 3         ┆ 6      ┆ 1      ┆ 0        ┆ … ┆ 0        ┆ 0        ┆ 11  ┆ 0               │
│ 5         ┆ 4      ┆ 1      ┆ 1        ┆ … ┆ 3        ┆ 0        ┆ 11  ┆ 0               │
│ …         ┆ …      ┆ …      ┆ …        ┆ … ┆ …        ┆ …        ┆ …   ┆ …               │
│ 6         ┆ 7      ┆ 1      ┆ 1        ┆ … ┆ 0        ┆ 5        ┆ 5   ┆ 0               │
│ 2         ┆ 4      ┆ 1      ┆ 1        ┆ … ┆ 0        ┆ 0        ┆ 11  ┆ 1               │
│ 5         ┆ 2      ┆ 0      ┆ 0        ┆ … ┆ 0        ┆ 0        ┆ 2   ┆ 0               │
│ 5         ┆ 1      ┆ 1      ┆ 0        ┆ … ┆ 0        ┆ 0        ┆ 7   ┆ 0               │
│ 6         ┆ 2      ┆ 1      ┆ 1        ┆ … ┆ 0        ┆ 0        ┆ 9   ┆ 1               │
└───────────┴────────┴────────┴──────────┴───┴──────────┴──────────┴─────┴─────────────────┘

In [152]:
tmp = get_df_info_pl(cdc_diabetes_df)

DataFrame shape: (253680, 22)
Data types (according to dtypes):
Number of numerical columns: 5:
['BMI', 'GenHlth', 'MentHlth', 'PhysHlth', 'Age']
  - Integer columns: 5: ['BMI', 'GenHlth', 'MentHlth', 'PhysHlth', 'Age']
  - Float columns: 0: []
Number of categorical columns: 17:
['Education', 'Income', 'HighBP', 'HighChol', 'CholCheck', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'DiffWalk', 'Sex', 'Diabetes_binary']
  - Multiclass columns: 2: ['Education', 'Income']
  - Binary columns: 15: ['HighBP', 'HighChol', 'CholCheck', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'DiffWalk', 'Sex', 'Diabetes_binary']
  - Boolean columns: 0: []
Total categorical cardinality: 44
Total types count:
total numerical: 5 (int: 5, float: 0),
Total categorical: 17 (multi-class: 2, bin_cat: 15, bool_cat: 0):
Columns with missing values: 0

In [153]:
train, valid, test = pl_train_valid_test_split(cdc_diabetes_df, splits=[0.7, 0.15, 0.15], seed=420)

print("Train shape:", train.shape, "Valid shape:", valid.shape, "Test shape:", test.shape)

Train shape: (177576, 22) Valid shape: (38052, 22) Test shape: (38052, 22)

In [154]:
#### save the datasets as parquet:
info = get_df_info_pl(cdc_diabetes_df)

cdc_diabetes_path = "/Users/leec/Documents/datasets/parquet/cdc_diabetes/"
# make sure the output directory exists, and create it if it doesn't:
os.makedirs(cdc_diabetes_path, exist_ok=True)

cdc_diabetes_train_output_path = os.path.join(cdc_diabetes_path, "cdc_diabetes_train.parquet")
cdc_diabetes_valid_output_path = os.path.join(cdc_diabetes_path, "cdc_diabetes_valid.parquet")
cdc_diabetes_test_output_path = os.path.join(cdc_diabetes_path, "cdc_diabetes_test.parquet")

train.write_parquet(cdc_diabetes_train_output_path)
valid.write_parquet(cdc_diabetes_valid_output_path)
test.write_parquet(cdc_diabetes_test_output_path)


# create an `info.json` file with the metadata information:
metadata = {
    "name": "cdc_diabetes",
    "task_type": "binclass", # binclass, multiclass, regression 
    "target_col_name": target_col_name,
    "train_size": train.shape[0],
    "val_size": valid.shape[0],
    "test_size": test.shape[0],
    "catCols": info["catCols"],
    "intCols": info["intCols"],
    "floatCols": info["floatCols"]   
}

metadata_output_path = os.path.join(cdc_diabetes_path, "info.json")
with open(metadata_output_path, "w") as f:
    json.dump(metadata, f, indent=4)
    
metadata

DataFrame shape: (253680, 22)
Data types (according to dtypes):
Number of numerical columns: 5:
['BMI', 'GenHlth', 'MentHlth', 'PhysHlth', 'Age']
  - Integer columns: 5: ['BMI', 'GenHlth', 'MentHlth', 'PhysHlth', 'Age']
  - Float columns: 0: []
Number of categorical columns: 17:
['Education', 'Income', 'HighBP', 'HighChol', 'CholCheck', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'DiffWalk', 'Sex', 'Diabetes_binary']
  - Multiclass columns: 2: ['Education', 'Income']
  - Binary columns: 15: ['HighBP', 'HighChol', 'CholCheck', 'Smoker', 'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'DiffWalk', 'Sex', 'Diabetes_binary']
  - Boolean columns: 0: []
Total categorical cardinality: 44
Total types count:
total numerical: 5 (int: 5, float: 0),
Total categorical: 17 (multi-class: 2, bin_cat: 15, bool_cat: 0):
Columns with missing values: 0

{'name': 'cdc_diabetes',
 'task_type': 'binclass',
 'target_col_name': 'Diabetes_binary',
 'train_size': 177576,
 'val_size': 38052,
 'test_size': 38052,
 'catCols': ['Education',
  'Income',
  'HighBP',
  'HighChol',
  'CholCheck',
  'Smoker',
  'Stroke',
  'HeartDiseaseorAttack',
  'PhysActivity',
  'Fruits',
  'Veggies',
  'HvyAlcoholConsump',
  'AnyHealthcare',
  'NoDocbcCost',
  'DiffWalk',
  'Sex',
  'Diabetes_binary'],
 'intCols': ['BMI', 'GenHlth', 'MentHlth', 'PhysHlth', 'Age'],
 'floatCols': []}

In [ ]:
# # save the datasets as pickle:
# cdc_diabetes_df_output_path = "/Users/leec/Documents/datasets/cdc_diabetes/"
# # make sure the output directory exists, and create it if it doesn't:
# os.makedirs(cdc_diabetes_df_output_path, exist_ok=True)

# cdc_diabetes_df_train_output_path = os.path.join(cdc_diabetes_df_output_path, "cdc_diabetes_train.pkl")
# cdc_diabetes_df_valid_output_path = os.path.join(cdc_diabetes_df_output_path, "cdc_diabetes_valid.pkl")
# cdc_diabetes_df_test_output_path = os.path.join(cdc_diabetes_df_output_path, "cdc_diabetes_test.pkl")

# # pickle the datasets:
# with open(cdc_diabetes_df_train_output_path, "wb") as f:
#     pickle.dump(train, f)
# with open(cdc_diabetes_df_valid_output_path, "wb") as f:
#     pickle.dump(valid, f)
# with open(cdc_diabetes_df_test_output_path, "wb") as f:
#     pickle.dump(test, f)


# ## also save as csv:

# cdc_diabetes_df_train_output_path = os.path.join(cdc_diabetes_df_output_path, "cdc_diabetes_train.csv")
# cdc_diabetes_df_valid_output_path = os.path.join(cdc_diabetes_df_output_path, "cdc_diabetes_valid.csv")
# cdc_diabetes_df_test_output_path = os.path.join(cdc_diabetes_df_output_path, "cdc_diabetes_test.csv")

# train.write_csv(cdc_diabetes_df_train_output_path)
# valid.write_csv(cdc_diabetes_df_valid_output_path)
# test.write_csv(cdc_diabetes_df_test_output_path)

In [52]:
num_col_idx = [i for i, col in enumerate(cdc_diabetes_df.columns) if col in numCols]
cat_col_idx = [i for i, col in enumerate(cdc_diabetes_df.columns) if col in catCols_noTarget]
target_col_idx = cdc_diabetes_df.columns.index(target_col_name)
cat_col_idx, num_col_idx, target_col_idx

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 21)

In [51]:
cdc_diabetes_df.columns

['Education',
 'Income',
 'HighBP',
 'HighChol',
 'CholCheck',
 'Smoker',
 'Stroke',
 'HeartDiseaseorAttack',
 'PhysActivity',
 'Fruits',
 'Veggies',
 'HvyAlcoholConsump',
 'AnyHealthcare',
 'NoDocbcCost',
 'DiffWalk',
 'Sex',
 'BMI',
 'GenHlth',
 'MentHlth',
 'PhysHlth',
 'Age',
 'Diabetes_binary']

### Census Income

probably shouldn't not include...

In [ ]:
census_income_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(
    name="census-income_full", source="uci", df_type="polars"
)
census_income_df

shape: (199_523, 42)
┌──────┬─────────────────────────────────┬────────┬────────┬───┬─────────┬─────────┬──────┬────────┐
│ AAGE ┆ ACLSWKR                         ┆ ADTINK ┆ ADTOCC ┆ … ┆ WKSWORK ┆ AHRSPAY ┆ year ┆ income │
│ ---  ┆ ---                             ┆ ---    ┆ ---    ┆   ┆ ---     ┆ ---     ┆ ---  ┆ ---    │
│ i64  ┆ str                             ┆ i64    ┆ i64    ┆   ┆ i64     ┆ i64     ┆ i64  ┆ str    │
╞══════╪═════════════════════════════════╪════════╪════════╪═══╪═════════╪═════════╪══════╪════════╡
│ 73   ┆  Not in universe                ┆ 0      ┆ 0      ┆ … ┆ 0       ┆ 0       ┆ 95   ┆ -50000 │
│ 58   ┆  Self-employed-not incorporate… ┆ 4      ┆ 34     ┆ … ┆ 52      ┆ 0       ┆ 94   ┆ -50000 │
│ 18   ┆  Not in universe                ┆ 0      ┆ 0      ┆ … ┆ 0       ┆ 0       ┆ 95   ┆ -50000 │
│ 9    ┆  Not in universe                ┆ 0      ┆ 0      ┆ … ┆ 0       ┆ 0       ┆ 94   ┆ -50000 │
│ 10   ┆  Not in universe                ┆ 0      ┆ 0      ┆ … ┆ 0       ┆ 0       ┆ 94   ┆ -50000 │
│ …    ┆ …                               ┆ …      ┆ …      ┆ … ┆ …       ┆ …       ┆ …    ┆ …      │
│ 87   ┆  Not in universe                ┆ 0      ┆ 0      ┆ … ┆ 0       ┆ 0       ┆ 95   ┆ -50000 │
│ 65   ┆  Self-employed-incorporated     ┆ 37     ┆ 2      ┆ … ┆ 52      ┆ 0       ┆ 94   ┆ -50000 │
│ 47   ┆  Not in universe                ┆ 0      ┆ 0      ┆ … ┆ 52      ┆ 0       ┆ 95   ┆ -50000 │
│ 16   ┆  Not in universe                ┆ 0      ┆ 0      ┆ … ┆ 0       ┆ 0       ┆ 95   ┆ -50000 │
│ 32   ┆  Private                        ┆ 42     ┆ 30     ┆ … ┆ 52      ┆ 0       ┆ 94   ┆ -50000 │
└──────┴─────────────────────────────────┴────────┴────────┴───┴─────────┴─────────┴──────┴────────┘

In [17]:
prediction_task

'binary_classification'

In [40]:
# get_df_info_pl(census_income_df)

### Support2

In [49]:
support2_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(
    name="support2", source="uci", df_type="polars"
)
support2_df

shape: (9_105, 45)
┌──────────┬────────┬──────────────┬──────────────┬───┬───────────┬───────┬──────────┬─────────────┐
│ age      ┆ sex    ┆ dzgroup      ┆ dzclass      ┆ … ┆ adlsc     ┆ death ┆ hospdead ┆ sfdm2       │
│ ---      ┆ ---    ┆ ---          ┆ ---          ┆   ┆ ---       ┆ ---   ┆ ---      ┆ ---         │
│ f64      ┆ str    ┆ str          ┆ str          ┆   ┆ f64       ┆ i64   ┆ i64      ┆ str         │
╞══════════╪════════╪══════════════╪══════════════╪═══╪═══════════╪═══════╪══════════╪═════════════╡
│ 62.84998 ┆ male   ┆ Lung Cancer  ┆ Cancer       ┆ … ┆ 7.0       ┆ 0     ┆ 0        ┆ null        │
│ 60.33899 ┆ female ┆ Cirrhosis    ┆ COPD/CHF/Cir ┆ … ┆ 1.0       ┆ 1     ┆ 1        ┆ <2 mo.      │
│          ┆        ┆              ┆ rhosis       ┆   ┆           ┆       ┆          ┆ follow-up   │
│ 52.74698 ┆ female ┆ Cirrhosis    ┆ COPD/CHF/Cir ┆ … ┆ 0.0       ┆ 1     ┆ 0        ┆ <2 mo.      │
│          ┆        ┆              ┆ rhosis       ┆   ┆           ┆       ┆          ┆ follow-up   │
│ 42.38498 ┆ female ┆ Lung Cancer  ┆ Cancer       ┆ … ┆ 0.0       ┆ 1     ┆ 0        ┆ no(M2 and   │
│          ┆        ┆              ┆              ┆   ┆           ┆       ┆          ┆ SIP pres)   │
│ 79.88495 ┆ female ┆ ARF/MOSF     ┆ ARF/MOSF     ┆ … ┆ 2.0       ┆ 0     ┆ 0        ┆ no(M2 and   │
│          ┆        ┆ w/Sepsis     ┆              ┆   ┆           ┆       ┆          ┆ SIP pres)   │
│ …        ┆ …      ┆ …            ┆ …            ┆ … ┆ …         ┆ …     ┆ …        ┆ …           │
│ 66.073   ┆ male   ┆ ARF/MOSF     ┆ ARF/MOSF     ┆ … ┆ 0.0       ┆ 0     ┆ 0        ┆ null        │
│          ┆        ┆ w/Sepsis     ┆              ┆   ┆           ┆       ┆          ┆             │
│ 55.15399 ┆ female ┆ Coma         ┆ Coma         ┆ … ┆ 0.0       ┆ 0     ┆ 0        ┆ null        │
│ 70.38196 ┆ male   ┆ ARF/MOSF     ┆ ARF/MOSF     ┆ … ┆ 2.5253906 ┆ 0     ┆ 0        ┆ null        │
│          ┆        ┆ w/Sepsis     ┆              ┆   ┆           ┆       ┆          ┆             │
│ 47.01999 ┆ male   ┆ MOSF w/Malig ┆ ARF/MOSF     ┆ … ┆ 0.0       ┆ 1     ┆ 1        ┆ <2 mo.      │
│          ┆        ┆              ┆              ┆   ┆           ┆       ┆          ┆ follow-up   │
│ 81.53894 ┆ female ┆ ARF/MOSF     ┆ ARF/MOSF     ┆ … ┆ 0.494751  ┆ 1     ┆ 0        ┆ no(M2 and   │
│          ┆        ┆ w/Sepsis     ┆              ┆   ┆           ┆       ┆          ┆ SIP pres)   │
└──────────┴────────┴──────────────┴──────────────┴───┴───────────┴───────┴──────────┴─────────────┘

In [50]:
target_col_name

'death'

In [51]:
# remove nulls from df
support2_df.null_count()

shape: (1, 45)
┌─────┬─────┬─────────┬─────────┬───┬───────┬───────┬──────────┬───────┐
│ age ┆ sex ┆ dzgroup ┆ dzclass ┆ … ┆ adlsc ┆ death ┆ hospdead ┆ sfdm2 │
│ --- ┆ --- ┆ ---     ┆ ---     ┆   ┆ ---   ┆ ---   ┆ ---      ┆ ---   │
│ u32 ┆ u32 ┆ u32     ┆ u32     ┆   ┆ u32   ┆ u32   ┆ u32      ┆ u32   │
╞═════╪═════╪═════════╪═════════╪═══╪═══════╪═══════╪══════════╪═══════╡
│ 0   ┆ 0   ┆ 0       ┆ 0       ┆ … ┆ 0     ┆ 0     ┆ 0        ┆ 1400  │
└─────┴─────┴─────────┴─────────┴───┴───────┴───────┴──────────┴───────┘

In [52]:
null_count_th = 1000
support2_limited_df = support2_df.select(
    [col for col in support2_df.columns if support2_df[col].null_count() <= null_count_th]
)

In [53]:
# set target column to binary:
support2_limited_df = support2_limited_df.with_columns(
    pl.col(target_col_name).cast(pl.Utf8)
)

In [54]:
# var_types

In [55]:
# set all binary columns to string:

support2_limited_df = support2_limited_df.with_columns(pl.col(["diabetes","dementia","hospdead"]).cast(pl.Utf8))

In [56]:
support2_limited_df = support2_limited_df.drop_nulls()

In [57]:
support2_limited_df

shape: (7_816, 30)
┌──────────┬────────┬─────────────┬─────────────────────┬───┬───────┬───────────┬───────┬──────────┐
│ age      ┆ sex    ┆ dzgroup     ┆ dzclass             ┆ … ┆ sod   ┆ adlsc     ┆ death ┆ hospdead │
│ ---      ┆ ---    ┆ ---         ┆ ---                 ┆   ┆ ---   ┆ ---       ┆ ---   ┆ ---      │
│ f64      ┆ str    ┆ str         ┆ str                 ┆   ┆ f64   ┆ f64       ┆ str   ┆ str      │
╞══════════╪════════╪═════════════╪═════════════════════╪═══╪═══════╪═══════════╪═══════╪══════════╡
│ 43.53998 ┆ female ┆ ARF/MOSF    ┆ ARF/MOSF            ┆ … ┆ 134.0 ┆ 2.7641602 ┆ 0     ┆ 0        │
│          ┆        ┆ w/Sepsis    ┆                     ┆   ┆       ┆           ┆       ┆          │
│ 63.66299 ┆ female ┆ ARF/MOSF    ┆ ARF/MOSF            ┆ … ┆ 130.0 ┆ 0.0       ┆ 1     ┆ 1        │
│          ┆        ┆ w/Sepsis    ┆                     ┆   ┆       ┆           ┆       ┆          │
│ 31.84399 ┆ male   ┆ Cirrhosis   ┆ COPD/CHF/Cirrhosis  ┆ … ┆ 122.0 ┆ 7.0       ┆ 1     ┆ 1        │
│ 48.70398 ┆ male   ┆ Lung Cancer ┆ Cancer              ┆ … ┆ 133.0 ┆ 3.2636719 ┆ 1     ┆ 0        │
│ 49.61298 ┆ female ┆ ARF/MOSF    ┆ ARF/MOSF            ┆ … ┆ 130.0 ┆ 5.0       ┆ 0     ┆ 0        │
│          ┆        ┆ w/Sepsis    ┆                     ┆   ┆       ┆           ┆       ┆          │
│ …        ┆ …      ┆ …           ┆ …                   ┆ … ┆ …     ┆ …         ┆ …     ┆ …        │
│ 70.42297 ┆ male   ┆ ARF/MOSF    ┆ ARF/MOSF            ┆ … ┆ 136.0 ┆ 2.7148438 ┆ 1     ┆ 0        │
│          ┆        ┆ w/Sepsis    ┆                     ┆   ┆       ┆           ┆       ┆          │
│ 68.61597 ┆ female ┆ COPD        ┆ COPD/CHF/Cirrhosis  ┆ … ┆ 128.0 ┆ 0.494751  ┆ 0     ┆ 0        │
│ 66.073   ┆ male   ┆ ARF/MOSF    ┆ ARF/MOSF            ┆ … ┆ 131.0 ┆ 0.0       ┆ 0     ┆ 0        │
│          ┆        ┆ w/Sepsis    ┆                     ┆   ┆       ┆           ┆       ┆          │
│ 70.38196 ┆ male   ┆ ARF/MOSF    ┆ ARF/MOSF            ┆ … ┆ 139.0 ┆ 2.5253906 ┆ 0     ┆ 0        │
│          ┆        ┆ w/Sepsis    ┆                     ┆   ┆       ┆           ┆       ┆          │
│ 81.53894 ┆ female ┆ ARF/MOSF    ┆ ARF/MOSF            ┆ … ┆ 137.0 ┆ 0.494751  ┆ 1     ┆ 0        │
│          ┆        ┆ w/Sepsis    ┆                     ┆   ┆       ┆           ┆       ┆          │
└──────────┴────────┴─────────────┴─────────────────────┴───┴───────┴───────────┴───────┴──────────┘

In [58]:
tmp = get_df_info_pl(support2_limited_df)

DataFrame shape: (7816, 30)
Data types (according to dtypes):
Number of numerical columns: 20:
['age', 'num.co', 'scoma', 'charges', 'totcst', 'avtisst', 'sps', 'aps', 'surv2m', 'surv6m', 'hday', 'dnrday', 'meanbp', 'wblc', 'hrt', 'resp', 'temp', 'crea', 'sod', 'adlsc']
  - Integer columns: 2: ['num.co', 'hday']
  - Float columns: 18: ['age', 'scoma', 'charges', 'totcst', 'avtisst', 'sps', 'aps', 'surv2m', 'surv6m', 'dnrday', 'meanbp', 'wblc', 'hrt', 'resp', 'temp', 'crea', 'sod', 'adlsc']
Number of categorical columns: 10:
['sex', 'dzgroup', 'dzclass', 'race', 'diabetes', 'dementia', 'ca', 'dnr', 'death', 'hospdead']
  - Multiclass columns: 5: ['dzgroup', 'dzclass', 'race', 'ca', 'dnr']
  - Binary columns: 5: ['sex', 'diabetes', 'dementia', 'death', 'hospdead']
  - Boolean columns: 0: []
Total categorical cardinality: 33
Total types count:
total numerical: 20 (int: 2, float: 18),
Total categorical: 10 (multi-class: 5, bin_cat: 5, bool_cat: 0):
Columns with missing values: 0

In [59]:
# support2_limited_df.write_parquet("/Users/leec/Documents/datasets/support2/support2_limited.parquet")

In [67]:
# Get metadata for Polars DataFrame
pl_metadata = get_pl_metadata(support2_limited_df)
# pp(pl_metadata)

# Retrieves column types from metadata
catCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "categorical"]
intCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "numerical" and v["subtype"] == "int"]
floatCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "numerical" and v["subtype"] == "float"]
binCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "categorical" and v["subtype"] == "binary"]
numCols = intCols + floatCols
print("catCols: ", catCols)
print("intCols: ", intCols)
print("floatCols: ", floatCols)
print("binCols: ", binCols)
print("numCols: ", numCols)
print("target_col: ", target_col_name)

catCols:  ['sex', 'dzgroup', 'dzclass', 'race', 'diabetes', 'dementia', 'ca', 'dnr', 'hospdead', 'death']
intCols:  ['num.co', 'hday']
floatCols:  ['age', 'scoma', 'charges', 'totcst', 'avtisst', 'sps', 'aps', 'surv2m', 'surv6m', 'dnrday', 'meanbp', 'wblc', 'hrt', 'resp', 'temp', 'crea', 'sod', 'adlsc']
binCols:  ['sex', 'diabetes', 'dementia', 'hospdead', 'death']
numCols:  ['num.co', 'hday', 'age', 'scoma', 'charges', 'totcst', 'avtisst', 'sps', 'aps', 'surv2m', 'surv6m', 'dnrday', 'meanbp', 'wblc', 'hrt', 'resp', 'temp', 'crea', 'sod', 'adlsc']
target_col:  death

In [61]:
catCols_noTarget = [j for j in catCols if j != target_col_name]
print("catCols_noTarget: ", catCols_noTarget)  # catCols_noTarget

catCols_noTarget:  ['sex', 'dzgroup', 'dzclass', 'race', 'diabetes', 'dementia', 'ca', 'dnr', 'hospdead']

In [62]:
support2_limited_df = support2_limited_df.select(catCols_noTarget + numCols + [target_col_name])
support2_limited_df

shape: (7_816, 30)
┌────────┬─────────────┬────────────────────┬───────┬───┬──────────┬───────┬───────────┬───────┐
│ sex    ┆ dzgroup     ┆ dzclass            ┆ race  ┆ … ┆ crea     ┆ sod   ┆ adlsc     ┆ death │
│ ---    ┆ ---         ┆ ---                ┆ ---   ┆   ┆ ---      ┆ ---   ┆ ---       ┆ ---   │
│ str    ┆ str         ┆ str                ┆ str   ┆   ┆ f64      ┆ f64   ┆ f64       ┆ str   │
╞════════╪═════════════╪════════════════════╪═══════╪═══╪══════════╪═══════╪═══════════╪═══════╡
│ female ┆ ARF/MOSF    ┆ ARF/MOSF           ┆ white ┆ … ┆ 0.599976 ┆ 134.0 ┆ 2.7641602 ┆ 0     │
│        ┆ w/Sepsis    ┆                    ┆       ┆   ┆          ┆       ┆           ┆       │
│ female ┆ ARF/MOSF    ┆ ARF/MOSF           ┆ white ┆ … ┆ 2.899902 ┆ 130.0 ┆ 0.0       ┆ 1     │
│        ┆ w/Sepsis    ┆                    ┆       ┆   ┆          ┆       ┆           ┆       │
│ male   ┆ Cirrhosis   ┆ COPD/CHF/Cirrhosis ┆ white ┆ … ┆ 0.299988 ┆ 122.0 ┆ 7.0       ┆ 1     │
│ male   ┆ Lung Cancer ┆ Cancer             ┆ other ┆ … ┆ 1.0      ┆ 133.0 ┆ 3.2636719 ┆ 1     │
│ female ┆ ARF/MOSF    ┆ ARF/MOSF           ┆ white ┆ … ┆ 0.599976 ┆ 130.0 ┆ 5.0       ┆ 0     │
│        ┆ w/Sepsis    ┆                    ┆       ┆   ┆          ┆       ┆           ┆       │
│ …      ┆ …           ┆ …                  ┆ …     ┆ … ┆ …        ┆ …     ┆ …         ┆ …     │
│ male   ┆ ARF/MOSF    ┆ ARF/MOSF           ┆ white ┆ … ┆ 1.199951 ┆ 136.0 ┆ 2.7148438 ┆ 1     │
│        ┆ w/Sepsis    ┆                    ┆       ┆   ┆          ┆       ┆           ┆       │
│ female ┆ COPD        ┆ COPD/CHF/Cirrhosis ┆ white ┆ … ┆ 0.799927 ┆ 128.0 ┆ 0.494751  ┆ 0     │
│ male   ┆ ARF/MOSF    ┆ ARF/MOSF           ┆ white ┆ … ┆ 1.099854 ┆ 131.0 ┆ 0.0       ┆ 0     │
│        ┆ w/Sepsis    ┆                    ┆       ┆   ┆          ┆       ┆           ┆       │
│ male   ┆ ARF/MOSF    ┆ ARF/MOSF           ┆ white ┆ … ┆ 2.699707 ┆ 139.0 ┆ 2.5253906 ┆ 0     │
│        ┆ w/Sepsis    ┆                    ┆       ┆   ┆          ┆       ┆           ┆       │
│ female ┆ ARF/MOSF    ┆ ARF/MOSF           ┆ white ┆ … ┆ 1.199951 ┆ 137.0 ┆ 0.494751  ┆ 1     │
│        ┆ w/Sepsis    ┆                    ┆       ┆   ┆          ┆       ┆           ┆       │
└────────┴─────────────┴────────────────────┴───────┴───┴──────────┴───────┴───────────┴───────┘

In [63]:
num_col_idx = [i for i, col in enumerate(support2_limited_df.columns) if col in numCols]
cat_col_idx = [i for i, col in enumerate(support2_limited_df.columns) if col in catCols_noTarget]
target_col_idx = support2_limited_df.columns.index(target_col_name)
cat_col_idx, num_col_idx, target_col_idx

([0, 1, 2, 3, 4, 5, 6, 7, 8],
 [9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28],
 29)

In [64]:
support2_limited_df["death"].value_counts()

shape: (2, 2)
┌───────┬───────┐
│ death ┆ count │
│ ---   ┆ ---   │
│ str   ┆ u32   │
╞═══════╪═══════╡
│ 0     ┆ 2442  │
│ 1     ┆ 5374  │
└───────┴───────┘

In [65]:
train, valid, test = pl_train_valid_test_split(support2_limited_df, splits=[0.7, 0.15, 0.15], seed=420)

print("Train shape:", train.shape, "Valid shape:", valid.shape, "Test shape:", test.shape)

Train shape: (5471, 30) Valid shape: (1172, 30) Test shape: (1173, 30)

In [69]:
#### save the datasets as parquet:
info = get_df_info_pl(support2_limited_df)

support2_output_path = "/Users/leec/Documents/datasets/parquet/support2/"
# make sure the output directory exists, and create it if it doesn't:
os.makedirs(support2_output_path, exist_ok=True)

support2_train_output_path = os.path.join(support2_output_path, "support2_train.parquet")
support2_valid_output_path = os.path.join(support2_output_path, "support2_valid.parquet")
support2_test_output_path = os.path.join(support2_output_path, "support2_test.parquet")

train.write_parquet(support2_train_output_path)
valid.write_parquet(support2_valid_output_path)
test.write_parquet(support2_test_output_path)


# create an `info.json` file with the metadata information:
metadata = {
    "name": "support2",
    "task_type": "binclass", # binclass, multiclass, regression 
    "target_col_name": target_col_name,
    "train_size": train.shape[0],
    "val_size": valid.shape[0],
    "test_size": test.shape[0],
    "catCols": info["catCols"],
    "intCols": info["intCols"],
    "floatCols": info["floatCols"]   
}

metadata_output_path = os.path.join(support2_output_path, "info.json")
with open(metadata_output_path, "w") as f:
    json.dump(metadata, f, indent=4)
    
metadata

DataFrame shape: (7816, 30)
Data types (according to dtypes):
Number of numerical columns: 20:
['num.co', 'hday', 'age', 'scoma', 'charges', 'totcst', 'avtisst', 'sps', 'aps', 'surv2m', 'surv6m', 'dnrday', 'meanbp', 'wblc', 'hrt', 'resp', 'temp', 'crea', 'sod', 'adlsc']
  - Integer columns: 2: ['num.co', 'hday']
  - Float columns: 18: ['age', 'scoma', 'charges', 'totcst', 'avtisst', 'sps', 'aps', 'surv2m', 'surv6m', 'dnrday', 'meanbp', 'wblc', 'hrt', 'resp', 'temp', 'crea', 'sod', 'adlsc']
Number of categorical columns: 10:
['sex', 'dzgroup', 'dzclass', 'race', 'diabetes', 'dementia', 'ca', 'dnr', 'hospdead', 'death']
  - Multiclass columns: 5: ['dzgroup', 'dzclass', 'race', 'ca', 'dnr']
  - Binary columns: 5: ['sex', 'diabetes', 'dementia', 'hospdead', 'death']
  - Boolean columns: 0: []
Total categorical cardinality: 33
Total types count:
total numerical: 20 (int: 2, float: 18),
Total categorical: 10 (multi-class: 5, bin_cat: 5, bool_cat: 0):
Columns with missing values: 0

{'name': 'support2',
 'task_type': 'binclass',
 'target_col_name': 'death',
 'train_size': 5471,
 'val_size': 1172,
 'test_size': 1173,
 'catCols': ['sex',
  'dzgroup',
  'dzclass',
  'race',
  'diabetes',
  'dementia',
  'ca',
  'dnr',
  'hospdead',
  'death'],
 'intCols': ['num.co', 'hday'],
 'floatCols': ['age',
  'scoma',
  'charges',
  'totcst',
  'avtisst',
  'sps',
  'aps',
  'surv2m',
  'surv6m',
  'dnrday',
  'meanbp',
  'wblc',
  'hrt',
  'resp',
  'temp',
  'crea',
  'sod',
  'adlsc']}

In [36]:
# save the datasets as pickle:
support2_output_path = "/Users/leec/Documents/datasets/support2/"
# make sure the output directory exists, and create it if it doesn't:
os.makedirs(support2_output_path, exist_ok=True)

support2_train_output_path = os.path.join(support2_output_path, "support2_train.pkl")
support2_valid_output_path = os.path.join(support2_output_path, "support2_valid.pkl")
support2_test_output_path = os.path.join(support2_output_path, "support2_test.pkl")

# pickle the datasets:
with open(support2_train_output_path, "wb") as f:
    pickle.dump(train, f)
with open(support2_valid_output_path, "wb") as f:
    pickle.dump(valid, f)
with open(support2_test_output_path, "wb") as f:
    pickle.dump(test, f)


## also save as csv:

support2_train_output_path = os.path.join(support2_output_path, "support2_train.csv")
support2_valid_output_path = os.path.join(support2_output_path, "support2_valid.csv")
support2_test_output_path = os.path.join(support2_output_path, "support2_test.csv")

train.write_csv(support2_train_output_path)
valid.write_csv(support2_valid_output_path)
test.write_csv(support2_test_output_path)

### diabetes_130us

In [117]:
diabetes_130us_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(
    name="diabetes_130us", source="uci", df_type="polars"
)
prediction_task = "multiclass_classification"
diabetes_130us_df

/opt/miniconda3/envs/mixtabank/lib/python3.13/site-packages/ucimlrepo/fetch.py:97: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_url)

shape: (101_766, 48)
┌───────────────┬────────┬─────────┬────────┬───┬──────────────┬────────┬─────────────┬────────────┐
│ race          ┆ gender ┆ age     ┆ weight ┆ … ┆ metformin-pi ┆ change ┆ diabetesMed ┆ readmitted │
│ ---           ┆ ---    ┆ ---     ┆ ---    ┆   ┆ oglitazone   ┆ ---    ┆ ---         ┆ ---        │
│ str           ┆ str    ┆ str     ┆ str    ┆   ┆ ---          ┆ str    ┆ str         ┆ str        │
│               ┆        ┆         ┆        ┆   ┆ str          ┆        ┆             ┆            │
╞═══════════════╪════════╪═════════╪════════╪═══╪══════════════╪════════╪═════════════╪════════════╡
│ Caucasian     ┆ Female ┆ [0-10)  ┆ null   ┆ … ┆ No           ┆ No     ┆ No          ┆ NO         │
│ Caucasian     ┆ Female ┆ [10-20) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ >30        │
│ AfricanAmeric ┆ Female ┆ [20-30) ┆ null   ┆ … ┆ No           ┆ No     ┆ Yes         ┆ NO         │
│ an            ┆        ┆         ┆        ┆   ┆              ┆        ┆             ┆            │
│ Caucasian     ┆ Male   ┆ [30-40) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ NO         │
│ Caucasian     ┆ Male   ┆ [40-50) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ NO         │
│ …             ┆ …      ┆ …       ┆ …      ┆ … ┆ …            ┆ …      ┆ …           ┆ …          │
│ AfricanAmeric ┆ Male   ┆ [70-80) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ >30        │
│ an            ┆        ┆         ┆        ┆   ┆              ┆        ┆             ┆            │
│ AfricanAmeric ┆ Female ┆ [80-90) ┆ null   ┆ … ┆ No           ┆ No     ┆ Yes         ┆ NO         │
│ an            ┆        ┆         ┆        ┆   ┆              ┆        ┆             ┆            │
│ Caucasian     ┆ Male   ┆ [70-80) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ NO         │
│ Caucasian     ┆ Female ┆ [80-90) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ NO         │
│ Caucasian     ┆ Male   ┆ [70-80) ┆ null   ┆ … ┆ No           ┆ No     ┆ No          ┆ NO         │
└───────────────┴────────┴─────────┴────────┴───┴──────────────┴────────┴─────────────┴────────────┘

Reducing multi-class to binary classification:

In [118]:
# diabetes_130us_df = diabetes_130us_df.with_columns(
#     pl.when(pl.col("readmitted") == "<30").then(pl.lit("yes")).otherwise(pl.lit("no")).alias("readmitted")
# ) 
prediction_task = "binary_classification"
diabetes_130us_df['readmitted'].value_counts()

shape: (3, 2)
┌────────────┬───────┐
│ readmitted ┆ count │
│ ---        ┆ ---   │
│ str        ┆ u32   │
╞════════════╪═══════╡
│ <30        ┆ 11357 │
│ NO         ┆ 54864 │
│ >30        ┆ 35545 │
└────────────┴───────┘

In [119]:
# metadata

In [120]:
# return rows with just digits
diabetes_130us_df = diabetes_130us_df.filter(pl.col("diag_1").str.contains(r"^\d+(\.\d+)?$"))
diabetes_130us_df = diabetes_130us_df.filter(pl.col("diag_2").str.contains(r"^\d+(\.\d+)?$"))
diabetes_130us_df = diabetes_130us_df.filter(pl.col("diag_3").str.contains(r"^\d+(\.\d+)?$"))

diabetes_130us_df = diabetes_130us_df.cast({"diag_1": pl.Float32}).cast({"diag_1": pl.Int32}).cast({"diag_1": pl.Utf8})
diabetes_130us_df = diabetes_130us_df.cast({"diag_2": pl.Float32}).cast({"diag_2": pl.Int32}).cast({"diag_2": pl.Utf8})
diabetes_130us_df = diabetes_130us_df.cast({"diag_3": pl.Float32}).cast({"diag_3": pl.Int32}).cast({"diag_3": pl.Utf8})

# diabetes_130us_df = diabetes_130us_df.cast({"diag_1": pl.Int32, "diag_2": pl.Int32, "diag_3": pl.Float64})
diabetes_130us_df

shape: (91_844, 48)
┌───────────────┬────────┬─────────┬────────┬───┬──────────────┬────────┬─────────────┬────────────┐
│ race          ┆ gender ┆ age     ┆ weight ┆ … ┆ metformin-pi ┆ change ┆ diabetesMed ┆ readmitted │
│ ---           ┆ ---    ┆ ---     ┆ ---    ┆   ┆ oglitazone   ┆ ---    ┆ ---         ┆ ---        │
│ str           ┆ str    ┆ str     ┆ str    ┆   ┆ ---          ┆ str    ┆ str         ┆ str        │
│               ┆        ┆         ┆        ┆   ┆ str          ┆        ┆             ┆            │
╞═══════════════╪════════╪═════════╪════════╪═══╪══════════════╪════════╪═════════════╪════════════╡
│ Caucasian     ┆ Female ┆ [10-20) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ >30        │
│ Caucasian     ┆ Male   ┆ [30-40) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ NO         │
│ Caucasian     ┆ Male   ┆ [40-50) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ NO         │
│ Caucasian     ┆ Male   ┆ [50-60) ┆ null   ┆ … ┆ No           ┆ No     ┆ Yes         ┆ >30        │
│ Caucasian     ┆ Male   ┆ [70-80) ┆ null   ┆ … ┆ No           ┆ No     ┆ Yes         ┆ >30        │
│ …             ┆ …      ┆ …       ┆ …      ┆ … ┆ …            ┆ …      ┆ …           ┆ …          │
│ AfricanAmeric ┆ Male   ┆ [70-80) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ >30        │
│ an            ┆        ┆         ┆        ┆   ┆              ┆        ┆             ┆            │
│ AfricanAmeric ┆ Female ┆ [80-90) ┆ null   ┆ … ┆ No           ┆ No     ┆ Yes         ┆ NO         │
│ an            ┆        ┆         ┆        ┆   ┆              ┆        ┆             ┆            │
│ Caucasian     ┆ Male   ┆ [70-80) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ NO         │
│ Caucasian     ┆ Female ┆ [80-90) ┆ null   ┆ … ┆ No           ┆ Ch     ┆ Yes         ┆ NO         │
│ Caucasian     ┆ Male   ┆ [70-80) ┆ null   ┆ … ┆ No           ┆ No     ┆ No          ┆ NO         │
└───────────────┴────────┴─────────┴────────┴───┴──────────────┴────────┴─────────────┴────────────┘

In [121]:
tmp = get_df_info_pl(diabetes_130us_df)

DataFrame shape: (91844, 48)
Data types (according to dtypes):
Number of numerical columns: 11:
['admission_type_id', 'discharge_disposition_id', 'admission_source_id', 'time_in_hospital', 'num_lab_procedures', 'num_procedures', 'num_medications', 'number_outpatient', 'number_emergency', 'number_inpatient', 'number_diagnoses']
  - Integer columns: 11: ['admission_type_id', 'discharge_disposition_id', 'admission_source_id', 'time_in_hospital', 'num_lab_procedures', 'num_procedures', 'num_medications', 'number_outpatient', 'number_emergency', 'number_inpatient', 'number_diagnoses']
  - Float columns: 0: []
Number of categorical columns: 37:
['race', 'gender', 'age', 'weight', 'payer_code', 'medical_specialty', 'diag_1', 'diag_2', 'diag_3', 'max_glu_serum', 'A1Cresult', 'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide', 'examide', 'citoglipton', 'insulin', 'glyburide-metformin', 'glipizide-metformin', 'glimepiride-pioglitazone', 'metformin-rosiglitazone', 'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted']
  - Multiclass columns: 26: ['race', 'gender', 'age', 'weight', 'payer_code', 'medical_specialty', 'diag_1', 'diag_2', 'diag_3', 'max_glu_serum', 'A1Cresult', 'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'glipizide', 'glyburide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'tolazamide', 'insulin', 'glyburide-metformin', 'readmitted']
  - Binary columns: 9: ['acetohexamide', 'tolbutamide', 'troglitazone', 'glipizide-metformin', 'glimepiride-pioglitazone', 'metformin-rosiglitazone', 'metformin-pioglitazone', 'change', 'diabetesMed']
  - Boolean columns: 0: []
Total categorical cardinality: 2086
Total types count:
total numerical: 11 (int: 11, float: 0),
Total categorical: 37 (multi-class: 26, bin_cat: 9, bool_cat: 0):
Columns with missing values: 6

In [122]:
diabetes_drop_cols = [
    "weight",
    "payer_code",
    "medical_specialty",
    "max_glu_serum",
    "A1Cresult",
]
diabetes_130us_df = diabetes_130us_df.drop(diabetes_drop_cols)
diabetes_130us_df.null_count().sum()

shape: (1, 43)
┌──────┬────────┬─────┬──────────────────┬───┬─────────────────┬────────┬─────────────┬────────────┐
│ race ┆ gender ┆ age ┆ admission_type_i ┆ … ┆ metformin-piogl ┆ change ┆ diabetesMed ┆ readmitted │
│ ---  ┆ ---    ┆ --- ┆ d                ┆   ┆ itazone         ┆ ---    ┆ ---         ┆ ---        │
│ u32  ┆ u32    ┆ u32 ┆ ---              ┆   ┆ ---             ┆ u32    ┆ u32         ┆ u32        │
│      ┆        ┆     ┆ u32              ┆   ┆ u32             ┆        ┆             ┆            │
╞══════╪════════╪═════╪══════════════════╪═══╪═════════════════╪════════╪═════════════╪════════════╡
│ 2062 ┆ 0      ┆ 0   ┆ 0                ┆ … ┆ 0               ┆ 0      ┆ 0           ┆ 0          │
└──────┴────────┴─────┴──────────────────┴───┴─────────────────┴────────┴─────────────┴────────────┘

In [123]:
diabetes_130us_df = diabetes_130us_df.drop_nulls()
print("Shape after dropping nulls: ", diabetes_130us_df.shape)
diabetes_130us_df = diabetes_130us_df.drop_nans()
print("Shape after dropping nans: ", diabetes_130us_df.shape)

Shape after dropping nulls:  (89782, 43)
Shape after dropping nans:  (89782, 43)

In [124]:
# Get metadata for Polars DataFrame
pl_metadata = get_pl_metadata(diabetes_130us_df)
# pp(pl_metadata)

# Retrieves column types from metadata
catCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "categorical"]
intCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "numerical" and v["subtype"] == "int"]
floatCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "numerical" and v["subtype"] == "float"]
binCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "categorical" and v["subtype"] == "binary"]
numCols = intCols + floatCols
print("catCols: ", catCols)
print("intCols: ", intCols)
print("floatCols: ", floatCols)
print("binCols: ", binCols)
print("numCols: ", numCols)
print("target_col: ", target_col_name)

catCols:  ['race', 'gender', 'age', 'diag_1', 'diag_2', 'diag_3', 'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide', 'examide', 'citoglipton', 'insulin', 'glyburide-metformin', 'glipizide-metformin', 'glimepiride-pioglitazone', 'metformin-rosiglitazone', 'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted']
intCols:  ['admission_type_id', 'discharge_disposition_id', 'admission_source_id', 'time_in_hospital', 'num_lab_procedures', 'num_procedures', 'num_medications', 'number_outpatient', 'number_emergency', 'number_inpatient', 'number_diagnoses']
floatCols:  []
binCols:  ['acetohexamide', 'tolbutamide', 'troglitazone', 'glipizide-metformin', 'glimepiride-pioglitazone', 'metformin-pioglitazone', 'change', 'diabetesMed']
numCols:  ['admission_type_id', 'discharge_disposition_id', 'admission_source_id', 'time_in_hospital', 'num_lab_procedures', 'num_procedures', 'num_medications', 'number_outpatient', 'number_emergency', 'number_inpatient', 'number_diagnoses']
target_col:  readmitted

In [125]:
catCols_noTarget = [j for j in catCols if j != target_col_name]
print("catCols_noTarget: ", catCols_noTarget)  # catCols_noTarget

catCols_noTarget:  ['race', 'gender', 'age', 'diag_1', 'diag_2', 'diag_3', 'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide', 'examide', 'citoglipton', 'insulin', 'glyburide-metformin', 'glipizide-metformin', 'glimepiride-pioglitazone', 'metformin-rosiglitazone', 'metformin-pioglitazone', 'change', 'diabetesMed']

In [126]:
diabetes_130us_df = diabetes_130us_df.select(catCols_noTarget + numCols + [target_col_name])
diabetes_130us_df

shape: (89_782, 43)
┌─────────────┬────────┬─────────┬────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ race        ┆ gender ┆ age     ┆ diag_1 ┆ … ┆ number_emer ┆ number_inp ┆ number_dia ┆ readmitted │
│ ---         ┆ ---    ┆ ---     ┆ ---    ┆   ┆ gency       ┆ atient     ┆ gnoses     ┆ ---        │
│ str         ┆ str    ┆ str     ┆ str    ┆   ┆ ---         ┆ ---        ┆ ---        ┆ str        │
│             ┆        ┆         ┆        ┆   ┆ i64         ┆ i64        ┆ i64        ┆            │
╞═════════════╪════════╪═════════╪════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ Caucasian   ┆ Female ┆ [10-20) ┆ 276    ┆ … ┆ 0           ┆ 0          ┆ 9          ┆ >30        │
│ Caucasian   ┆ Male   ┆ [30-40) ┆ 8      ┆ … ┆ 0           ┆ 0          ┆ 7          ┆ NO         │
│ Caucasian   ┆ Male   ┆ [40-50) ┆ 197    ┆ … ┆ 0           ┆ 0          ┆ 5          ┆ NO         │
│ Caucasian   ┆ Male   ┆ [50-60) ┆ 414    ┆ … ┆ 0           ┆ 0          ┆ 9          ┆ >30        │
│ Caucasian   ┆ Male   ┆ [70-80) ┆ 428    ┆ … ┆ 0           ┆ 0          ┆ 8          ┆ >30        │
│ …           ┆ …      ┆ …       ┆ …      ┆ … ┆ …           ┆ …          ┆ …          ┆ …          │
│ AfricanAmer ┆ Male   ┆ [70-80) ┆ 250    ┆ … ┆ 0           ┆ 0          ┆ 9          ┆ >30        │
│ ican        ┆        ┆         ┆        ┆   ┆             ┆            ┆            ┆            │
│ AfricanAmer ┆ Female ┆ [80-90) ┆ 560    ┆ … ┆ 0           ┆ 1          ┆ 9          ┆ NO         │
│ ican        ┆        ┆         ┆        ┆   ┆             ┆            ┆            ┆            │
│ Caucasian   ┆ Male   ┆ [70-80) ┆ 38     ┆ … ┆ 0           ┆ 0          ┆ 13         ┆ NO         │
│ Caucasian   ┆ Female ┆ [80-90) ┆ 996    ┆ … ┆ 0           ┆ 1          ┆ 9          ┆ NO         │
│ Caucasian   ┆ Male   ┆ [70-80) ┆ 530    ┆ … ┆ 0           ┆ 0          ┆ 9          ┆ NO         │
└─────────────┴────────┴─────────┴────────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [127]:
num_col_idx = [i for i, col in enumerate(diabetes_130us_df.columns) if col in numCols]
cat_col_idx = [i for i, col in enumerate(diabetes_130us_df.columns) if col in catCols_noTarget]
target_col_idx = diabetes_130us_df.columns.index(target_col_name)
cat_col_idx, num_col_idx, target_col_idx

([0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30],
 [31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41],
 42)

In [128]:
diabetes_130us_df["readmitted"].value_counts()

shape: (3, 2)
┌────────────┬───────┐
│ readmitted ┆ count │
│ ---        ┆ ---   │
│ str        ┆ u32   │
╞════════════╪═══════╡
│ >30        ┆ 31793 │
│ NO         ┆ 47904 │
│ <30        ┆ 10085 │
└────────────┴───────┘

In [129]:
train, valid, test = pl_train_valid_test_split(diabetes_130us_df, splits=[0.7, 0.15, 0.15], seed=420)

print("Train shape:", train.shape, "Valid shape:", valid.shape, "Test shape:", test.shape)

Train shape: (62847, 43) Valid shape: (13467, 43) Test shape: (13468, 43)

In [130]:
#### save the datasets as parquet:
info = get_df_info_pl(diabetes_130us_df)

diabetes_130us_path = "/Users/leec/Documents/datasets/parquet/diabetes_130us/"
# make sure the output directory exists, and create it if it doesn't:
os.makedirs(diabetes_130us_path, exist_ok=True)

diabetes_130us_train_output_path = os.path.join(diabetes_130us_path, "diabetes_130us_train.parquet")
diabetes_130us_valid_output_path = os.path.join(diabetes_130us_path, "diabetes_130us_valid.parquet")
diabetes_130us_test_output_path = os.path.join(diabetes_130us_path, "diabetes_130us_test.parquet")

train.write_parquet(diabetes_130us_train_output_path)
valid.write_parquet(diabetes_130us_valid_output_path)
test.write_parquet(diabetes_130us_test_output_path)


# create an `info.json` file with the metadata information:
metadata = {
    "name": "diabetes_130us",
    "task_type": "multiclass", # binclass, multiclass, regression 
    "target_col_name": target_col_name,
    "train_size": train.shape[0],
    "val_size": valid.shape[0],
    "test_size": test.shape[0],
    "catCols": info["catCols"],
    "intCols": info["intCols"],
    "floatCols": info["floatCols"]   
}

metadata_output_path = os.path.join(diabetes_130us_path, "info.json")
with open(metadata_output_path, "w") as f:
    json.dump(metadata, f, indent=4)
    
metadata

DataFrame shape: (89782, 43)
Data types (according to dtypes):
Number of numerical columns: 11:
['admission_type_id', 'discharge_disposition_id', 'admission_source_id', 'time_in_hospital', 'num_lab_procedures', 'num_procedures', 'num_medications', 'number_outpatient', 'number_emergency', 'number_inpatient', 'number_diagnoses']
  - Integer columns: 11: ['admission_type_id', 'discharge_disposition_id', 'admission_source_id', 'time_in_hospital', 'num_lab_procedures', 'num_procedures', 'num_medications', 'number_outpatient', 'number_emergency', 'number_inpatient', 'number_diagnoses']
  - Float columns: 0: []
Number of categorical columns: 32:
['race', 'gender', 'age', 'diag_1', 'diag_2', 'diag_3', 'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide', 'examide', 'citoglipton', 'insulin', 'glyburide-metformin', 'glipizide-metformin', 'glimepiride-pioglitazone', 'metformin-rosiglitazone', 'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted']
  - Multiclass columns: 21: ['race', 'gender', 'age', 'diag_1', 'diag_2', 'diag_3', 'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'glipizide', 'glyburide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'tolazamide', 'insulin', 'glyburide-metformin', 'readmitted']
  - Binary columns: 8: ['acetohexamide', 'tolbutamide', 'troglitazone', 'glipizide-metformin', 'glimepiride-pioglitazone', 'metformin-pioglitazone', 'change', 'diabetesMed']
  - Boolean columns: 0: []
Total categorical cardinality: 1972
Total types count:
total numerical: 11 (int: 11, float: 0),
Total categorical: 32 (multi-class: 21, bin_cat: 8, bool_cat: 0):
Columns with missing values: 0

{'name': 'diabetes_130us',
 'task_type': 'multiclass',
 'target_col_name': 'readmitted',
 'train_size': 62847,
 'val_size': 13467,
 'test_size': 13468,
 'catCols': ['race',
  'gender',
  'age',
  'diag_1',
  'diag_2',
  'diag_3',
  'metformin',
  'repaglinide',
  'nateglinide',
  'chlorpropamide',
  'glimepiride',
  'acetohexamide',
  'glipizide',
  'glyburide',
  'tolbutamide',
  'pioglitazone',
  'rosiglitazone',
  'acarbose',
  'miglitol',
  'troglitazone',
  'tolazamide',
  'examide',
  'citoglipton',
  'insulin',
  'glyburide-metformin',
  'glipizide-metformin',
  'glimepiride-pioglitazone',
  'metformin-rosiglitazone',
  'metformin-pioglitazone',
  'change',
  'diabetesMed',
  'readmitted'],
 'intCols': ['admission_type_id',
  'discharge_disposition_id',
  'admission_source_id',
  'time_in_hospital',
  'num_lab_procedures',
  'num_procedures',
  'num_medications',
  'number_outpatient',
  'number_emergency',
  'number_inpatient',
  'number_diagnoses'],
 'floatCols': []}

In [39]:
# save the datasets as pickle:
diabetes_130us_output_path = "/Users/leec/Documents/datasets/diabetes_130us/"
# make sure the output directory exists, and create it if it doesn't:
os.makedirs(diabetes_130us_output_path, exist_ok=True)

diabetes_130us_train_output_path = os.path.join(diabetes_130us_output_path, "diabetes_130us_train.pkl")
diabetes_130us_valid_output_path = os.path.join(diabetes_130us_output_path, "diabetes_130us_valid.pkl")
diabetes_130us_test_output_path = os.path.join(diabetes_130us_output_path, "diabetes_130us_test.pkl")

# pickle the datasets:
with open(diabetes_130us_train_output_path, "wb") as f:
    pickle.dump(train, f)
with open(diabetes_130us_valid_output_path, "wb") as f:
    pickle.dump(valid, f)
with open(diabetes_130us_test_output_path, "wb") as f:
    pickle.dump(test, f)


## also save as csv:

diabetes_130us_train_output_path = os.path.join(diabetes_130us_output_path, "diabetes_130us_train.csv")
diabetes_130us_valid_output_path = os.path.join(diabetes_130us_output_path, "diabetes_130us_valid.csv")
diabetes_130us_test_output_path = os.path.join(diabetes_130us_output_path, "diabetes_130us_test.csv")

train.write_csv(diabetes_130us_train_output_path)
valid.write_csv(diabetes_130us_valid_output_path)
test.write_csv(diabetes_130us_test_output_path)

In [38]:
train

shape: (62_847, 43)
┌───────────┬────────┬─────────┬────────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ race      ┆ gender ┆ age     ┆ diag_1 ┆ … ┆ number_emer ┆ number_inpa ┆ number_diag ┆ readmitted │
│ ---       ┆ ---    ┆ ---     ┆ ---    ┆   ┆ gency       ┆ tient       ┆ noses       ┆ ---        │
│ str       ┆ str    ┆ str     ┆ str    ┆   ┆ ---         ┆ ---         ┆ ---         ┆ str        │
│           ┆        ┆         ┆        ┆   ┆ i64         ┆ i64         ┆ i64         ┆            │
╞═══════════╪════════╪═════════╪════════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ Caucasian ┆ Female ┆ [10-20) ┆ 276    ┆ … ┆ 0           ┆ 0           ┆ 9           ┆ no         │
│ Caucasian ┆ Male   ┆ [30-40) ┆ 8      ┆ … ┆ 0           ┆ 0           ┆ 7           ┆ no         │
│ Caucasian ┆ Male   ┆ [40-50) ┆ 197    ┆ … ┆ 0           ┆ 0           ┆ 5           ┆ no         │
│ Caucasian ┆ Male   ┆ [50-60) ┆ 414    ┆ … ┆ 0           ┆ 0           ┆ 9           ┆ no         │
│ Caucasian ┆ Male   ┆ [70-80) ┆ 428    ┆ … ┆ 0           ┆ 0           ┆ 8           ┆ no         │
│ …         ┆ …      ┆ …       ┆ …      ┆ … ┆ …           ┆ …           ┆ …           ┆ …          │
│ Caucasian ┆ Female ┆ [70-80) ┆ 733    ┆ … ┆ 2           ┆ 2           ┆ 9           ┆ no         │
│ Caucasian ┆ Female ┆ [60-70) ┆ 486    ┆ … ┆ 0           ┆ 1           ┆ 9           ┆ no         │
│ Caucasian ┆ Female ┆ [80-90) ┆ 518    ┆ … ┆ 0           ┆ 1           ┆ 9           ┆ no         │
│ Caucasian ┆ Male   ┆ [80-90) ┆ 578    ┆ … ┆ 0           ┆ 0           ┆ 7           ┆ no         │
│ Caucasian ┆ Male   ┆ [70-80) ┆ 787    ┆ … ┆ 0           ┆ 0           ┆ 3           ┆ no         │
└───────────┴────────┴─────────┴────────┴───┴─────────────┴─────────────┴─────────────┴────────────┘

In [56]:
train_df.loc[train_df[col] == '?', col].shape[0]

0

In [ ]:
# train_df = train.to_pandas()
# for col in numCols:
#     if train_df.loc[train_df[col] == '?', col].shape[0]>0:
#         print(train_df.loc[train_df[col] == '?', col])
# for col in catCols:
#     if train_df.loc[train_df[col] == '?', col].shape[0]>0:
#         print(train_df.loc[train_df[col] == '?', col])
    
    
# test_df = test.to_pandas()
# for col in numCols:
#     if test_df.loc[test_df[col] == '?', col].shape[0]>0:
#         print(test_df.loc[test_df[col] == '?', col])
# for col in catCols:
#     if test_df.loc[test_df[col] == '?', col].shape[0]>0:
#         print(test_df.loc[test_df[col] == '?', col])

### Nursery

In [ ]:
nursery_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(
    name="nursery", source="uci", df_type="polars"
)
nursery_df

shape: (12_960, 9)
┌────────────┬───────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ parents    ┆ has_nurs  ┆ form     ┆ children ┆ … ┆ finance   ┆ social    ┆ health    ┆ class     │
│ ---        ┆ ---       ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str       ┆ str      ┆ str      ┆   ┆ str       ┆ str       ┆ str       ┆ str       │
╞════════════╪═══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ usual      ┆ proper    ┆ complete ┆ 1        ┆ … ┆ convenien ┆ nonprob   ┆ recommend ┆ recommend │
│            ┆           ┆          ┆          ┆   ┆ t         ┆           ┆ ed        ┆           │
│ usual      ┆ proper    ┆ complete ┆ 1        ┆ … ┆ convenien ┆ nonprob   ┆ priority  ┆ priority  │
│            ┆           ┆          ┆          ┆   ┆ t         ┆           ┆           ┆           │
│ usual      ┆ proper    ┆ complete ┆ 1        ┆ … ┆ convenien ┆ nonprob   ┆ not_recom ┆ not_recom │
│            ┆           ┆          ┆          ┆   ┆ t         ┆           ┆           ┆           │
│ usual      ┆ proper    ┆ complete ┆ 1        ┆ … ┆ convenien ┆ slightly_ ┆ recommend ┆ recommend │
│            ┆           ┆          ┆          ┆   ┆ t         ┆ prob      ┆ ed        ┆           │
│ usual      ┆ proper    ┆ complete ┆ 1        ┆ … ┆ convenien ┆ slightly_ ┆ priority  ┆ priority  │
│            ┆           ┆          ┆          ┆   ┆ t         ┆ prob      ┆           ┆           │
│ …          ┆ …         ┆ …        ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ great_pret ┆ very_crit ┆ foster   ┆ more     ┆ … ┆ inconv    ┆ slightly_ ┆ priority  ┆ spec_prio │
│            ┆           ┆          ┆          ┆   ┆           ┆ prob      ┆           ┆ r         │
│ great_pret ┆ very_crit ┆ foster   ┆ more     ┆ … ┆ inconv    ┆ slightly_ ┆ not_recom ┆ not_recom │
│            ┆           ┆          ┆          ┆   ┆           ┆ prob      ┆           ┆           │
│ great_pret ┆ very_crit ┆ foster   ┆ more     ┆ … ┆ inconv    ┆ problemat ┆ recommend ┆ spec_prio │
│            ┆           ┆          ┆          ┆   ┆           ┆ ic        ┆ ed        ┆ r         │
│ great_pret ┆ very_crit ┆ foster   ┆ more     ┆ … ┆ inconv    ┆ problemat ┆ priority  ┆ spec_prio │
│            ┆           ┆          ┆          ┆   ┆           ┆ ic        ┆           ┆ r         │
│ great_pret ┆ very_crit ┆ foster   ┆ more     ┆ … ┆ inconv    ┆ problemat ┆ not_recom ┆ not_recom │
│            ┆           ┆          ┆          ┆   ┆           ┆ ic        ┆           ┆           │
└────────────┴───────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [28]:
get_df_info_pl(nursery_df)

DataFrame shape: (12960, 9)
Data types (according to dtypes):
Number of numerical columns: 0:
[]
  - Integer columns: 0: []
  - Float columns: 0: []
Number of categorical columns: 9:
['parents', 'has_nurs', 'form', 'children', 'housing', 'finance', 'social', 'health', 'class']
  - Multiclass columns: 8: ['parents', 'has_nurs', 'form', 'children', 'housing', 'social', 'health', 'class']
  - Binary columns: 1: ['finance']
  - Boolean columns: 0: []
Total categorical cardinality: 32
Total types count:
total numerical: 0 (int: 0, float: 0),
Total categorical: 9 (multi-class: 8, bin_cat: 1, bool_cat: 0):
Columns with missing values: 0

{'dtypes': {'parents': 'String',
  'has_nurs': 'String',
  'form': 'String',
  'children': 'String',
  'housing': 'String',
  'finance': 'String',
  'social': 'String',
  'health': 'String',
  'class': 'String'},
 'shape': (12960, 9),
 'numCols': [],
 'numColsTotal': 0,
 'intCols': [],
 'intColsTotal': 0,
 'floatCols': [],
 'floatColsTotal': 0,
 'catCols': ['parents',
  'has_nurs',
  'form',
  'children',
  'housing',
  'finance',
  'social',
  'health',
  'class'],
 'catColsTotal': 9,
 'binCols': ['finance'],
 'binColsTotal': 1,
 'boolCols': [],
 'boolColsTotal': 0,
 'cardinality': {'parents': 3,
  'has_nurs': 5,
  'form': 4,
  'children': 4,
  'housing': 3,
  'finance': 2,
  'social': 3,
  'health': 3,
  'class': 5},
 'total_cardinality': 32,
 'nulls': {'parents': 0,
  'has_nurs': 0,
  'form': 0,
  'children': 0,
  'housing': 0,
  'finance': 0,
  'social': 0,
  'health': 0,
  'class': 0},
 'missing_pct': {'parents': 0.0,
  'has_nurs': 0.0,
  'form': 0.0,
  'children': 0.0,
  'housing': 0.0,
  'finance': 0.0,
  'social': 0.0,
  'health': 0.0,
  'class': 0.0},
 'numeric_stats': {},
 'top_unique': {'parents': ['great_pret', 'usual', 'pretentious'],
  'has_nurs': ['critical', 'improper', 'very_crit', 'proper', 'less_proper'],
  'form': ['complete', 'completed', 'foster', 'incomplete'],
  'children': ['1', 'more', '3', '2'],
  'housing': ['convenient', 'less_conv', 'critical'],
  'finance': ['convenient', 'inconv'],
  'social': ['slightly_prob', 'nonprob', 'problematic'],
  'health': ['priority', 'not_recom', 'recommended'],
  'class': ['recommend', 'very_recom', 'spec_prior', 'priority', 'not_recom']}}

### taiwanese_bankruptcy

In [ ]:
bankruptcy_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(
    name="taiwanese_bankruptcy", source="uci", df_type="polars"
)
bankruptcy_df

shape: (6_819, 96)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ ROA(C)    ┆ ROA(A)    ┆ ROA(B)    ┆ Operating ┆ … ┆ Interest  ┆ Net       ┆ Equity to ┆ Bankrupt │
│ before    ┆ before    ┆ before    ┆ Gross     ┆   ┆ Coverage  ┆ Income    ┆ Liability ┆ ?        │
│ interest  ┆ interest  ┆ interest  ┆ Margin    ┆   ┆ Ratio     ┆ Flag      ┆ ---       ┆ ---      │
│ and de…   ┆ and % …   ┆ and de…   ┆ ---       ┆   ┆ (Inte…    ┆ ---       ┆ f64       ┆ i64      │
│ ---       ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ i64       ┆           ┆          │
│ f64       ┆ f64       ┆ f64       ┆           ┆   ┆ f64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.370594  ┆ 0.424389  ┆ 0.40575   ┆ 0.601457  ┆ … ┆ 0.56405   ┆ 1         ┆ 0.016469  ┆ 1        │
│ 0.464291  ┆ 0.538214  ┆ 0.51673   ┆ 0.610235  ┆ … ┆ 0.570175  ┆ 1         ┆ 0.020794  ┆ 1        │
│ 0.426071  ┆ 0.499019  ┆ 0.472295  ┆ 0.60145   ┆ … ┆ 0.563706  ┆ 1         ┆ 0.016474  ┆ 1        │
│ 0.399844  ┆ 0.451265  ┆ 0.457733  ┆ 0.583541  ┆ … ┆ 0.564663  ┆ 1         ┆ 0.023982  ┆ 1        │
│ 0.465022  ┆ 0.538432  ┆ 0.522298  ┆ 0.598783  ┆ … ┆ 0.575617  ┆ 1         ┆ 0.03549   ┆ 1        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 0.493687  ┆ 0.539468  ┆ 0.54323   ┆ 0.604455  ┆ … ┆ 0.566193  ┆ 1         ┆ 0.02989   ┆ 0        │
│ 0.475162  ┆ 0.538269  ┆ 0.524172  ┆ 0.598308  ┆ … ┆ 0.566018  ┆ 1         ┆ 0.038284  ┆ 0        │
│ 0.472725  ┆ 0.533744  ┆ 0.520638  ┆ 0.610444  ┆ … ┆ 0.565158  ┆ 1         ┆ 0.097649  ┆ 0        │
│ 0.506264  ┆ 0.559911  ┆ 0.554045  ┆ 0.60785   ┆ … ┆ 0.565302  ┆ 1         ┆ 0.044009  ┆ 0        │
│ 0.493053  ┆ 0.570105  ┆ 0.549548  ┆ 0.627409  ┆ … ┆ 0.565167  ┆ 1         ┆ 0.233902  ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [55]:
# ' Net Income Flag' has only 1 unique value of 0. Drop this column.
bankruptcy_df = bankruptcy_df.drop([" Net Income Flag"])

In [ ]:
tempCols = [
    "Bankrupt?",
    " Liability-Assets Flag",
]
# Select only the integer columns
bankruptcy_df = bankruptcy_df.with_columns(pl.col(tempCols).cast(pl.Utf8))

In [59]:
get_df_info_pl(bankruptcy_df)

DataFrame shape: (6819, 95)
Data types (according to dtypes):
Number of numerical columns: 93:
[' ROA(C) before interest and depreciation before interest', ' ROA(A) before interest and % after tax', ' ROA(B) before interest and depreciation after tax', ' Operating Gross Margin', ' Realized Sales Gross Margin', ' Operating Profit Rate', ' Pre-tax net Interest Rate', ' After-tax net Interest Rate', ' Non-industry income and expenditure/revenue', ' Continuous interest rate (after tax)', ' Operating Expense Rate', ' Research and development expense rate', ' Cash flow rate', ' Interest-bearing debt interest rate', ' Tax rate (A)', ' Net Value Per Share (B)', ' Net Value Per Share (A)', ' Net Value Per Share (C)', ' Persistent EPS in the Last Four Seasons', ' Cash Flow Per Share', ' Revenue Per Share (Yuan ¥)', ' Operating Profit Per Share (Yuan ¥)', ' Per Share Net profit before tax (Yuan ¥)', ' Realized Sales Gross Profit Growth Rate', ' Operating Profit Growth Rate', ' After-tax Net Profit Growth Rate', ' Regular Net Profit Growth Rate', ' Continuous Net Profit Growth Rate', ' Total Asset Growth Rate', ' Net Value Growth Rate', ' Total Asset Return Growth Rate Ratio', ' Cash Reinvestment %', ' Current Ratio', ' Quick Ratio', ' Interest Expense Ratio', ' Total debt/Total net worth', ' Debt ratio %', ' Net worth/Assets', ' Long-term fund suitability ratio (A)', ' Borrowing dependency', ' Contingent liabilities/Net worth', ' Operating profit/Paid-in capital', ' Net profit before tax/Paid-in capital', ' Inventory and accounts receivable/Net value', ' Total Asset Turnover', ' Accounts Receivable Turnover', ' Average Collection Days', ' Inventory Turnover Rate (times)', ' Fixed Assets Turnover Frequency', ' Net Worth Turnover Rate (times)', ' Revenue per person', ' Operating profit per person', ' Allocation rate per person', ' Working Capital to Total Assets', ' Quick Assets/Total Assets', ' Current Assets/Total Assets', ' Cash/Total Assets', ' Quick Assets/Current Liability', ' Cash/Current Liability', ' Current Liability to Assets', ' Operating Funds to Liability', ' Inventory/Working Capital', ' Inventory/Current Liability', ' Current Liabilities/Liability', ' Working Capital/Equity', ' Current Liabilities/Equity', ' Long-term Liability to Current Assets', ' Retained Earnings to Total Assets', ' Total income/Total expense', ' Total expense/Assets', ' Current Asset Turnover Rate', ' Quick Asset Turnover Rate', ' Working capitcal Turnover Rate', ' Cash Turnover Rate', ' Cash Flow to Sales', ' Fixed Assets to Assets', ' Current Liability to Liability', ' Current Liability to Equity', ' Equity to Long-term Liability', ' Cash Flow to Total Assets', ' Cash Flow to Liability', ' CFO to Assets', ' Cash Flow to Equity', ' Current Liability to Current Assets', ' Net Income to Total Assets', ' Total assets to GNP price', ' No-credit Interval', ' Gross Profit to Sales', " Net Income to Stockholder's Equity", ' Liability to Equity', ' Degree of Financial Leverage (DFL)', ' Interest Coverage Ratio (Interest expense to EBIT)', ' Equity to Liability']
  - Integer columns: 0: []
  - Float columns: 93: [' ROA(C) before interest and depreciation before interest', ' ROA(A) before interest and % after tax', ' ROA(B) before interest and depreciation after tax', ' Operating Gross Margin', ' Realized Sales Gross Margin', ' Operating Profit Rate', ' Pre-tax net Interest Rate', ' After-tax net Interest Rate', ' Non-industry income and expenditure/revenue', ' Continuous interest rate (after tax)', ' Operating Expense Rate', ' Research and development expense rate', ' Cash flow rate', ' Interest-bearing debt interest rate', ' Tax rate (A)', ' Net Value Per Share (B)', ' Net Value Per Share (A)', ' Net Value Per Share (C)', ' Persistent EPS in the Last Four Seasons', ' Cash Flow Per Share', ' Revenue Per Share (Yuan ¥)', ' Operating Profit Per Share (Yuan ¥)', ' Per Share Net profit before tax (Yuan ¥)', ' Realized Sales Gross Profit Growth Rate', ' Operating Profit Growth Rate', ' After-tax Net Profit Growth Rate', ' Regular Net Profit Growth Rate', ' Continuous Net Profit Growth Rate', ' Total Asset Growth Rate', ' Net Value Growth Rate', ' Total Asset Return Growth Rate Ratio', ' Cash Reinvestment %', ' Current Ratio', ' Quick Ratio', ' Interest Expense Ratio', ' Total debt/Total net worth', ' Debt ratio %', ' Net worth/Assets', ' Long-term fund suitability ratio (A)', ' Borrowing dependency', ' Contingent liabilities/Net worth', ' Operating profit/Paid-in capital', ' Net profit before tax/Paid-in capital', ' Inventory and accounts receivable/Net value', ' Total Asset Turnover', ' Accounts Receivable Turnover', ' Average Collection Days', ' Inventory Turnover Rate (times)', ' Fixed Assets Turnover Frequency', ' Net Worth Turnover Rate (times)', ' Revenue per person', ' Operating profit per person', ' Allocation rate per person', ' Working Capital to Total Assets', ' Quick Assets/Total Assets', ' Current Assets/Total Assets', ' Cash/Total Assets', ' Quick Assets/Current Liability', ' Cash/Current Liability', ' Current Liability to Assets', ' Operating Funds to Liability', ' Inventory/Working Capital', ' Inventory/Current Liability', ' Current Liabilities/Liability', ' Working Capital/Equity', ' Current Liabilities/Equity', ' Long-term Liability to Current Assets', ' Retained Earnings to Total Assets', ' Total income/Total expense', ' Total expense/Assets', ' Current Asset Turnover Rate', ' Quick Asset Turnover Rate', ' Working capitcal Turnover Rate', ' Cash Turnover Rate', ' Cash Flow to Sales', ' Fixed Assets to Assets', ' Current Liability to Liability', ' Current Liability to Equity', ' Equity to Long-term Liability', ' Cash Flow to Total Assets', ' Cash Flow to Liability', ' CFO to Assets', ' Cash Flow to Equity', ' Current Liability to Current Assets', ' Net Income to Total Assets', ' Total assets to GNP price', ' No-credit Interval', ' Gross Profit to Sales', " Net Income to Stockholder's Equity", ' Liability to Equity', ' Degree of Financial Leverage (DFL)', ' Interest Coverage Ratio (Interest expense to EBIT)', ' Equity to Liability']
Number of categorical columns: 2:
[' Liability-Assets Flag', 'Bankrupt?']
  - Multiclass columns: 0: []
  - Binary columns: 2: [' Liability-Assets Flag', 'Bankrupt?']
  - Boolean columns: 0: []
Total categorical cardinality: 4
Total types count:
total numerical: 93 (int: 0, float: 93),
Total categorical: 2 (multi-class: 0, bin_cat: 2, bool_cat: 0):
Columns with missing values: 0

{'dtypes': {' ROA(C) before interest and depreciation before interest': 'Float64',
  ' ROA(A) before interest and % after tax': 'Float64',
  ' ROA(B) before interest and depreciation after tax': 'Float64',
  ' Operating Gross Margin': 'Float64',
  ' Realized Sales Gross Margin': 'Float64',
  ' Operating Profit Rate': 'Float64',
  ' Pre-tax net Interest Rate': 'Float64',
  ' After-tax net Interest Rate': 'Float64',
  ' Non-industry income and expenditure/revenue': 'Float64',
  ' Continuous interest rate (after tax)': 'Float64',
  ' Operating Expense Rate': 'Float64',
  ' Research and development expense rate': 'Float64',
  ' Cash flow rate': 'Float64',
  ' Interest-bearing debt interest rate': 'Float64',
  ' Tax rate (A)': 'Float64',
  ' Net Value Per Share (B)': 'Float64',
  ' Net Value Per Share (A)': 'Float64',
  ' Net Value Per Share (C)': 'Float64',
  ' Persistent EPS in the Last Four Seasons': 'Float64',
  ' Cash Flow Per Share': 'Float64',
  ' Revenue Per Share (Yuan ¥)': 'Float64',
  ' Operating Profit Per Share (Yuan ¥)': 'Float64',
  ' Per Share Net profit before tax (Yuan ¥)': 'Float64',
  ' Realized Sales Gross Profit Growth Rate': 'Float64',
  ' Operating Profit Growth Rate': 'Float64',
  ' After-tax Net Profit Growth Rate': 'Float64',
  ' Regular Net Profit Growth Rate': 'Float64',
  ' Continuous Net Profit Growth Rate': 'Float64',
  ' Total Asset Growth Rate': 'Float64',
  ' Net Value Growth Rate': 'Float64',
  ' Total Asset Return Growth Rate Ratio': 'Float64',
  ' Cash Reinvestment %': 'Float64',
  ' Current Ratio': 'Float64',
  ' Quick Ratio': 'Float64',
  ' Interest Expense Ratio': 'Float64',
  ' Total debt/Total net worth': 'Float64',
  ' Debt ratio %': 'Float64',
  ' Net worth/Assets': 'Float64',
  ' Long-term fund suitability ratio (A)': 'Float64',
  ' Borrowing dependency': 'Float64',
  ' Contingent liabilities/Net worth': 'Float64',
  ' Operating profit/Paid-in capital': 'Float64',
  ' Net profit before tax/Paid-in capital': 'Float64',
  ' Inventory and accounts receivable/Net value': 'Float64',
  ' Total Asset Turnover': 'Float64',
  ' Accounts Receivable Turnover': 'Float64',
  ' Average Collection Days': 'Float64',
  ' Inventory Turnover Rate (times)': 'Float64',
  ' Fixed Assets Turnover Frequency': 'Float64',
  ' Net Worth Turnover Rate (times)': 'Float64',
  ' Revenue per person': 'Float64',
  ' Operating profit per person': 'Float64',
  ' Allocation rate per person': 'Float64',
  ' Working Capital to Total Assets': 'Float64',
  ' Quick Assets/Total Assets': 'Float64',
  ' Current Assets/Total Assets': 'Float64',
  ' Cash/Total Assets': 'Float64',
  ' Quick Assets/Current Liability': 'Float64',
  ' Cash/Current Liability': 'Float64',
  ' Current Liability to Assets': 'Float64',
  ' Operating Funds to Liability': 'Float64',
  ' Inventory/Working Capital': 'Float64',
  ' Inventory/Current Liability': 'Float64',
  ' Current Liabilities/Liability': 'Float64',
  ' Working Capital/Equity': 'Float64',
  ' Current Liabilities/Equity': 'Float64',
  ' Long-term Liability to Current Assets': 'Float64',
  ' Retained Earnings to Total Assets': 'Float64',
  ' Total income/Total expense': 'Float64',
  ' Total expense/Assets': 'Float64',
  ' Current Asset Turnover Rate': 'Float64',
  ' Quick Asset Turnover Rate': 'Float64',
  ' Working capitcal Turnover Rate': 'Float64',
  ' Cash Turnover Rate': 'Float64',
  ' Cash Flow to Sales': 'Float64',
  ' Fixed Assets to Assets': 'Float64',
  ' Current Liability to Liability': 'Float64',
  ' Current Liability to Equity': 'Float64',
  ' Equity to Long-term Liability': 'Float64',
  ' Cash Flow to Total Assets': 'Float64',
  ' Cash Flow to Liability': 'Float64',
  ' CFO to Assets': 'Float64',
  ' Cash Flow to Equity': 'Float64',
  ' Current Liability to Current Assets': 'Float64',
  ' Liability-Assets Flag': 'String',
  ' Net Income to Total Assets': 'Float64',
  ' Total assets to GNP price': 'Float64',
  ' No-credit Interval': 'Float64',
  ' Gross Profit to Sales': 'Float64',
  " Net Income to Stockholder's Equity": 'Float64',
  ' Liability to Equity': 'Float64',
  ' Degree of Financial Leverage (DFL)': 'Float64',
  ' Interest Coverage Ratio (Interest expense to EBIT)': 'Float64',
  ' Equity to Liability': 'Float64',
  'Bankrupt?': 'String'},
 'shape': (6819, 95),
 'numCols': [' ROA(C) before interest and depreciation before interest',
  ' ROA(A) before interest and % after tax',
  ' ROA(B) before interest and depreciation after tax',
  ' Operating Gross Margin',
  ' Realized Sales Gross Margin',
  ' Operating Profit Rate',
  ' Pre-tax net Interest Rate',
  ' After-tax net Interest Rate',
  ' Non-industry income and expenditure/revenue',
  ' Continuous interest rate (after tax)',
  ' Operating Expense Rate',
  ' Research and development expense rate',
  ' Cash flow rate',
  ' Interest-bearing debt interest rate',
  ' Tax rate (A)',
  ' Net Value Per Share (B)',
  ' Net Value Per Share (A)',
  ' Net Value Per Share (C)',
  ' Persistent EPS in the Last Four Seasons',
  ' Cash Flow Per Share',
  ' Revenue Per Share (Yuan ¥)',
  ' Operating Profit Per Share (Yuan ¥)',
  ' Per Share Net profit before tax (Yuan ¥)',
  ' Realized Sales Gross Profit Growth Rate',
  ' Operating Profit Growth Rate',
  ' After-tax Net Profit Growth Rate',
  ' Regular Net Profit Growth Rate',
  ' Continuous Net Profit Growth Rate',
  ' Total Asset Growth Rate',
  ' Net Value Growth Rate',
  ' Total Asset Return Growth Rate Ratio',
  ' Cash Reinvestment %',
  ' Current Ratio',
  ' Quick Ratio',
  ' Interest Expense Ratio',
  ' Total debt/Total net worth',
  ' Debt ratio %',
  ' Net worth/Assets',
  ' Long-term fund suitability ratio (A)',
  ' Borrowing dependency',
  ' Contingent liabilities/Net worth',
  ' Operating profit/Paid-in capital',
  ' Net profit before tax/Paid-in capital',
  ' Inventory and accounts receivable/Net value',
  ' Total Asset Turnover',
  ' Accounts Receivable Turnover',
  ' Average Collection Days',
  ' Inventory Turnover Rate (times)',
  ' Fixed Assets Turnover Frequency',
  ' Net Worth Turnover Rate (times)',
  ' Revenue per person',
  ' Operating profit per person',
  ' Allocation rate per person',
  ' Working Capital to Total Assets',
  ' Quick Assets/Total Assets',
  ' Current Assets/Total Assets',
  ' Cash/Total Assets',
  ' Quick Assets/Current Liability',
  ' Cash/Current Liability',
  ' Current Liability to Assets',
  ' Operating Funds to Liability',
  ' Inventory/Working Capital',
  ' Inventory/Current Liability',
  ' Current Liabilities/Liability',
  ' Working Capital/Equity',
  ' Current Liabilities/Equity',
  ' Long-term Liability to Current Assets',
  ' Retained Earnings to Total Assets',
  ' Total income/Total expense',
  ' Total expense/Assets',
  ' Current Asset Turnover Rate',
  ' Quick Asset Turnover Rate',
  ' Working capitcal Turnover Rate',
  ' Cash Turnover Rate',
  ' Cash Flow to Sales',
  ' Fixed Assets to Assets',
  ' Current Liability to Liability',
  ' Current Liability to Equity',
  ' Equity to Long-term Liability',
  ' Cash Flow to Total Assets',
  ' Cash Flow to Liability',
  ' CFO to Assets',
  ' Cash Flow to Equity',
  ' Current Liability to Current Assets',
  ' Net Income to Total Assets',
  ' Total assets to GNP price',
  ' No-credit Interval',
  ' Gross Profit to Sales',
  " Net Income to Stockholder's Equity",
  ' Liability to Equity',
  ' Degree of Financial Leverage (DFL)',
  ' Interest Coverage Ratio (Interest expense to EBIT)',
  ' Equity to Liability'],
 'numColsTotal': 93,
 'intCols': [],
 'intColsTotal': 0,
 'floatCols': [' ROA(C) before interest and depreciation before interest',
  ' ROA(A) before interest and % after tax',
  ' ROA(B) before interest and depreciation after tax',
  ' Operating Gross Margin',
  ' Realized Sales Gross Margin',
  ' Operating Profit Rate',
  ' Pre-tax net Interest Rate',
  ' After-tax net Interest Rate',
  ' Non-industry income and expenditure/revenue',
  ' Continuous interest rate (after tax)',
  ' Operating Expense Rate',
  ' Research and development expense rate',
  ' Cash flow rate',
  ' Interest-bearing debt interest rate',
  ' Tax rate (A)',
  ' Net Value Per Share (B)',
  ' Net Value Per Share (A)',
  ' Net Value Per Share (C)',
  ' Persistent EPS in the Last Four Seasons',
  ' Cash Flow Per Share',
  ' Revenue Per Share (Yuan ¥)',
  ' Operating Profit Per Share (Yuan ¥)',
  ' Per Share Net profit before tax (Yuan ¥)',
  ' Realized Sales Gross Profit Growth Rate',
  ' Operating Profit Growth Rate',
  ' After-tax Net Profit Growth Rate',
  ' Regular Net Profit Growth Rate',
  ' Continuous Net Profit Growth Rate',
  ' Total Asset Growth Rate',
  ' Net Value Growth Rate',
  ' Total Asset Return Growth Rate Ratio',
  ' Cash Reinvestment %',
  ' Current Ratio',
  ' Quick Ratio',
  ' Interest Expense Ratio',
  ' Total debt/Total net worth',
  ' Debt ratio %',
  ' Net worth/Assets',
  ' Long-term fund suitability ratio (A)',
  ' Borrowing dependency',
  ' Contingent liabilities/Net worth',
  ' Operating profit/Paid-in capital',
  ' Net profit before tax/Paid-in capital',
  ' Inventory and accounts receivable/Net value',
  ' Total Asset Turnover',
  ' Accounts Receivable Turnover',
  ' Average Collection Days',
  ' Inventory Turnover Rate (times)',
  ' Fixed Assets Turnover Frequency',
  ' Net Worth Turnover Rate (times)',
  ' Revenue per person',
  ' Operating profit per person',
  ' Allocation rate per person',
  ' Working Capital to Total Assets',
  ' Quick Assets/Total Assets',
  ' Current Assets/Total Assets',
  ' Cash/Total Assets',
  ' Quick Assets/Current Liability',
  ' Cash/Current Liability',
  ' Current Liability to Assets',
  ' Operating Funds to Liability',
  ' Inventory/Working Capital',
  ' Inventory/Current Liability',
  ' Current Liabilities/Liability',
  ' Working Capital/Equity',
  ' Current Liabilities/Equity',
  ' Long-term Liability to Current Assets',
  ' Retained Earnings to Total Assets',
  ' Total income/Total expense',
  ' Total expense/Assets',
  ' Current Asset Turnover Rate',
  ' Quick Asset Turnover Rate',
  ' Working capitcal Turnover Rate',
  ' Cash Turnover Rate',
  ' Cash Flow to Sales',
  ' Fixed Assets to Assets',
  ' Current Liability to Liability',
  ' Current Liability to Equity',
  ' Equity to Long-term Liability',
  ' Cash Flow to Total Assets',
  ' Cash Flow to Liability',
  ' CFO to Assets',
  ' Cash Flow to Equity',
  ' Current Liability to Current Assets',
  ' Net Income to Total Assets',
  ' Total assets to GNP price',
  ' No-credit Interval',
  ' Gross Profit to Sales',
  " Net Income to Stockholder's Equity",
  ' Liability to Equity',
  ' Degree of Financial Leverage (DFL)',
  ' Interest Coverage Ratio (Interest expense to EBIT)',
  ' Equity to Liability'],
 'floatColsTotal': 93,
 'catCols': [' Liability-Assets Flag', 'Bankrupt?'],
 'catColsTotal': 2,
 'binCols': [' Liability-Assets Flag', 'Bankrupt?'],
 'binColsTotal': 2,
 'boolCols': [],
 'boolColsTotal': 0,
 'cardinality': {' Liability-Assets Flag': 2, 'Bankrupt?': 2},
 'total_cardinality': 4,
 'nulls': {' ROA(C) before interest and depreciation before interest': 0,
  ' ROA(A) before interest and % after tax': 0,
  ' ROA(B) before interest and depreciation after tax': 0,
  ' Operating Gross Margin': 0,
  ' Realized Sales Gross Margin': 0,
  ' Operating Profit Rate': 0,
  ' Pre-tax net Interest Rate': 0,
  ' After-tax net Interest Rate': 0,
  ' Non-industry income and expenditure/revenue': 0,
  ' Continuous interest rate (after tax)': 0,
  ' Operating Expense Rate': 0,
  ' Research and development expense rate': 0,
  ' Cash flow rate': 0,
  ' Interest-bearing debt interest rate': 0,
  ' Tax rate (A)': 0,
  ' Net Value Per Share (B)': 0,
  ' Net Value Per Share (A)': 0,
  ' Net Value Per Share (C)': 0,
  ' Persistent EPS in the Last Four Seasons': 0,
  ' Cash Flow Per Share': 0,
  ' Revenue Per Share (Yuan ¥)': 0,
  ' Operating Profit Per Share (Yuan ¥)': 0,
  ' Per Share Net profit before tax (Yuan ¥)': 0,
  ' Realized Sales Gross Profit Growth Rate': 0,
  ' Operating Profit Growth Rate': 0,
  ' After-tax Net Profit Growth Rate': 0,
  ' Regular Net Profit Growth Rate': 0,
  ' Continuous Net Profit Growth Rate': 0,
  ' Total Asset Growth Rate': 0,
  ' Net Value Growth Rate': 0,
  ' Total Asset Return Growth Rate Ratio': 0,
  ' Cash Reinvestment %': 0,
  ' Current Ratio': 0,
  ' Quick Ratio': 0,
  ' Interest Expense Ratio': 0,
  ' Total debt/Total net worth': 0,
  ' Debt ratio %': 0,
  ' Net worth/Assets': 0,
  ' Long-term fund suitability ratio (A)': 0,
  ' Borrowing dependency': 0,
  ' Contingent liabilities/Net worth': 0,
  ' Operating profit/Paid-in capital': 0,
  ' Net profit before tax/Paid-in capital': 0,
  ' Inventory and accounts receivable/Net value': 0,
  ' Total Asset Turnover': 0,
  ' Accounts Receivable Turnover': 0,
  ' Average Collection Days': 0,
  ' Inventory Turnover Rate (times)': 0,
  ' Fixed Assets Turnover Frequency': 0,
  ' Net Worth Turnover Rate (times)': 0,
  ' Revenue per person': 0,
  ' Operating profit per person': 0,
  ' Allocation rate per person': 0,
  ' Working Capital to Total Assets': 0,
  ' Quick Assets/Total Assets': 0,
  ' Current Assets/Total Assets': 0,
  ' Cash/Total Assets': 0,
  ' Quick Assets/Current Liability': 0,
  ' Cash/Current Liability': 0,
  ' Current Liability to Assets': 0,
  ' Operating Funds to Liability': 0,
  ' Inventory/Working Capital': 0,
  ' Inventory/Current Liability': 0,
  ' Current Liabilities/Liability': 0,
  ' Working Capital/Equity': 0,
  ' Current Liabilities/Equity': 0,
  ' Long-term Liability to Current Assets': 0,
  ' Retained Earnings to Total Assets': 0,
  ' Total income/Total expense': 0,
  ' Total expense/Assets': 0,
  ' Current Asset Turnover Rate': 0,
  ' Quick Asset Turnover Rate': 0,
  ' Working capitcal Turnover Rate': 0,
  ' Cash Turnover Rate': 0,
  ' Cash Flow to Sales': 0,
  ' Fixed Assets to Assets': 0,
  ' Current Liability to Liability': 0,
  ' Current Liability to Equity': 0,
  ' Equity to Long-term Liability': 0,
  ' Cash Flow to Total Assets': 0,
  ' Cash Flow to Liability': 0,
  ' CFO to Assets': 0,
  ' Cash Flow to Equity': 0,
  ' Current Liability to Current Assets': 0,
  ' Liability-Assets Flag': 0,
  ' Net Income to Total Assets': 0,
  ' Total assets to GNP price': 0,
  ' No-credit Interval': 0,
  ' Gross Profit to Sales': 0,
  " Net Income to Stockholder's Equity": 0,
  ' Liability to Equity': 0,
  ' Degree of Financial Leverage (DFL)': 0,
  ' Interest Coverage Ratio (Interest expense to EBIT)': 0,
  ' Equity to Liability': 0,
  'Bankrupt?': 0},
 'missing_pct': {' ROA(C) before interest and depreciation before interest': 0.0,
  ' ROA(A) before interest and % after tax': 0.0,
  ' ROA(B) before interest and depreciation after tax': 0.0,
  ' Operating Gross Margin': 0.0,
  ' Realized Sales Gross Margin': 0.0,
  ' Operating Profit Rate': 0.0,
  ' Pre-tax net Interest Rate': 0.0,
  ' After-tax net Interest Rate': 0.0,
  ' Non-industry income and expenditure/revenue': 0.0,
  ' Continuous interest rate (after tax)': 0.0,
  ' Operating Expense Rate': 0.0,
  ' Research and development expense rate': 0.0,
  ' Cash flow rate': 0.0,
  ' Interest-bearing debt interest rate': 0.0,
  ' Tax rate (A)': 0.0,
  ' Net Value Per Share (B)': 0.0,
  ' Net Value Per Share (A)': 0.0,
  ' Net Value Per Share (C)': 0.0,
  ' Persistent EPS in the Last Four Seasons': 0.0,
  ' Cash Flow Per Share': 0.0,
  ' Revenue Per Share (Yuan ¥)': 0.0,
  ' Operating Profit Per Share (Yuan ¥)': 0.0,
  ' Per Share Net profit before tax (Yuan ¥)': 0.0,
  ' Realized Sales Gross Profit Growth Rate': 0.0,
  ' Operating Profit Growth Rate': 0.0,
  ' After-tax Net Profit Growth Rate': 0.0,
  ' Regular Net Profit Growth Rate': 0.0,
  ' Continuous Net Profit Growth Rate': 0.0,
  ' Total Asset Growth Rate': 0.0,
  ' Net Value Growth Rate': 0.0,
  ' Total Asset Return Growth Rate Ratio': 0.0,
  ' Cash Reinvestment %': 0.0,
  ' Current Ratio': 0.0,
  ' Quick Ratio': 0.0,
  ' Interest Expense Ratio': 0.0,
  ' Total debt/Total net worth': 0.0,
  ' Debt ratio %': 0.0,
  ' Net worth/Assets': 0.0,
  ' Long-term fund suitability ratio (A)': 0.0,
  ' Borrowing dependency': 0.0,
  ' Contingent liabilities/Net worth': 0.0,
  ' Operating profit/Paid-in capital': 0.0,
  ' Net profit before tax/Paid-in capital': 0.0,
  ' Inventory and accounts receivable/Net value': 0.0,
  ' Total Asset Turnover': 0.0,
  ' Accounts Receivable Turnover': 0.0,
  ' Average Collection Days': 0.0,
  ' Inventory Turnover Rate (times)': 0.0,
  ' Fixed Assets Turnover Frequency': 0.0,
  ' Net Worth Turnover Rate (times)': 0.0,
  ' Revenue per person': 0.0,
  ' Operating profit per person': 0.0,
  ' Allocation rate per person': 0.0,
  ' Working Capital to Total Assets': 0.0,
  ' Quick Assets/Total Assets': 0.0,
  ' Current Assets/Total Assets': 0.0,
  ' Cash/Total Assets': 0.0,
  ' Quick Assets/Current Liability': 0.0,
  ' Cash/Current Liability': 0.0,
  ' Current Liability to Assets': 0.0,
  ' Operating Funds to Liability': 0.0,
  ' Inventory/Working Capital': 0.0,
  ' Inventory/Current Liability': 0.0,
  ' Current Liabilities/Liability': 0.0,
  ' Working Capital/Equity': 0.0,
  ' Current Liabilities/Equity': 0.0,
  ' Long-term Liability to Current Assets': 0.0,
  ' Retained Earnings to Total Assets': 0.0,
  ' Total income/Total expense': 0.0,
  ' Total expense/Assets': 0.0,
  ' Current Asset Turnover Rate': 0.0,
  ' Quick Asset Turnover Rate': 0.0,
  ' Working capitcal Turnover Rate': 0.0,
  ' Cash Turnover Rate': 0.0,
  ' Cash Flow to Sales': 0.0,
  ' Fixed Assets to Assets': 0.0,
  ' Current Liability to Liability': 0.0,
  ' Current Liability to Equity': 0.0,
  ' Equity to Long-term Liability': 0.0,
  ' Cash Flow to Total Assets': 0.0,
  ' Cash Flow to Liability': 0.0,
  ' CFO to Assets': 0.0,
  ' Cash Flow to Equity': 0.0,
  ' Current Liability to Current Assets': 0.0,
  ' Liability-Assets Flag': 0.0,
  ' Net Income to Total Assets': 0.0,
  ' Total assets to GNP price': 0.0,
  ' No-credit Interval': 0.0,
  ' Gross Profit to Sales': 0.0,
  " Net Income to Stockholder's Equity": 0.0,
  ' Liability to Equity': 0.0,
  ' Degree of Financial Leverage (DFL)': 0.0,
  ' Interest Coverage Ratio (Interest expense to EBIT)': 0.0,
  ' Equity to Liability': 0.0,
  'Bankrupt?': 0.0},
 'numeric_stats': {' ROA(C) before interest and depreciation before interest': {'mean': 0.5051796332417815,
   'std': 0.060685638754284434,
   'min': 0.0,
   'median': 0.502705601325988,
   'max': 1.0,
   'missing': 0},
  ' ROA(A) before interest and % after tax': {'mean': 0.5586249158750463,
   'std': 0.06562003103170726,
   'min': 0.0,
   'median': 0.559801569995639,
   'max': 1.0,
   'missing': 0},
  ' ROA(B) before interest and depreciation after tax': {'mean': 0.5535887093516656,
   'std': 0.061594809291875656,
   'min': 0.0,
   'median': 0.552277959205525,
   'max': 1.0,
   'missing': 0},
  ' Operating Gross Margin': {'mean': 0.6079480383703836,
   'std': 0.016933812548221454,
   'min': 0.0,
   'median': 0.605997492036495,
   'max': 1.0,
   'missing': 0},
  ' Realized Sales Gross Margin': {'mean': 0.607929469176979,
   'std': 0.016916070055675785,
   'min': 0.0,
   'median': 0.605975871661454,
   'max': 1.0,
   'missing': 0},
  ' Operating Profit Rate': {'mean': 0.998755127790044,
   'std': 0.013010025092984129,
   'min': 0.0,
   'median': 0.999022239374566,
   'max': 1.0,
   'missing': 0},
  ' Pre-tax net Interest Rate': {'mean': 0.7971897524712904,
   'std': 0.012868988419884597,
   'min': 0.0,
   'median': 0.797463610578231,
   'max': 1.0,
   'missing': 0},
  ' After-tax net Interest Rate': {'mean': 0.809083593513535,
   'std': 0.013600653945149045,
   'min': 0.0,
   'median': 0.809375198550956,
   'max': 1.0,
   'missing': 0},
  ' Non-industry income and expenditure/revenue': {'mean': 0.303622923649734,
   'std': 0.01116343983812855,
   'min': 0.0,
   'median': 0.303525492830123,
   'max': 1.0,
   'missing': 0},
  ' Continuous interest rate (after tax)': {'mean': 0.7813814325261416,

### apartment_rent_classified

In [2]:
# def convert_dtypes(df, var_types, inplace=False, verbose=False):
#     """
#     Convert pandas DataFrame columns to dtypes described in var_types dict.
#     var_types: mapping col_name -> type string (e.g. 'Categorical','Integer','Float','Boolean','Datetime',...)
#     Returns converted DataFrame (or modifies in place if inplace=True).
#     """
#     df_out = df if inplace else df.copy()
#     bool_map = {"yes": True, "no": False, "y": True, "n": False,
#                 "true": True, "false": False, "t": True, "f": False,
#                 "1": True, "0": False}

#     for col, t in var_types.items():
#         if col not in df_out.columns:
#             if verbose:
#                 print(f"skip missing column: {col}")
#             continue

#         t_low = str(t).strip().lower()
#         s = df_out[col]

#         try:
#             if "date" in t_low or "time" in t_low or "datetime" in t_low:
#                 df_out[col] = pd.to_datetime(s, errors="coerce")
#                 if verbose: print(f"{col} -> datetime64[ns]")

#             elif "bool" in t_low or "binary" in t_low:
#                 # try mapping common string tokens first, else coerce numeric
#                 mapped = s.astype("string").str.strip().str.lower().map(bool_map)
#                 if mapped.isna().all():
#                     # fallback to numeric then boolean
#                     num = pd.to_numeric(s, errors="coerce")
#                     df_out[col] = num.fillna(0).astype("boolean")
#                 else:
#                     df_out[col] = mapped.astype("boolean")
#                 if verbose: print(f"{col} -> boolean (nullable)")

#             elif "int" in t_low:
#                 num = pd.to_numeric(s, errors="coerce")
#                 df_out[col] = num.astype(pd.Int64Dtype())
#                 if verbose: print(f"{col} -> Int64 (nullable)")

#             elif "float" in t_low:
#                 num = pd.to_numeric(s, errors="coerce")
#                 df_out[col] = num.astype(pd.Float64Dtype())
#                 if verbose: print(f"{col} -> Float64 (nullable)")

#             elif "cat" in t_low or "string" in t_low or "text" in t_low:
#                 # prefer pandas nullable string dtype
#                 df_out[col] = s.astype(pd.StringDtype())
#                 if verbose: print(f"{col} -> StringDtype (nullable)")

#             else:
#                 # fallback: leave as object/string
#                 df_out[col] = s
#                 if verbose: print(f"{col} -> left as original dtype ({s.dtype})")
#         except Exception as e:
#             if verbose:
#                 print(f"conversion failed for {col}: {e} -- leaving original dtype")
#             df_out[col] = s

#     return df_out if not inplace else None

# apartment_rent_new_df = convert_dtypes(apartment_rent_df, var_types, inplace=False, verbose=True)

In [72]:
# apartment_rent_df

In [57]:
# # change the types in var_types to pandas dtypes:
# var_types_pd = {k: (pd.StringDtype() if v=="Categorical" else (pd.Int64Dtype() if v=="Integer" else (pd.Float64Dtype() if v=="Float" else pd.StringDtype))) for k,v in var_types.items()}

# # change dtypes according to var_types types:
# apartment_rent_df = apartment_rent_df.astype(var_types)

In [ ]:
apartment_rent_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(
    name="apartment_rent_classified", source="uci", df_type="pandas"
)
apartment_rent_df

/opt/miniconda3/envs/mixtabank/lib/python3.13/site-packages/ucimlrepo/fetch.py:97: DtypeWarning: Columns (0,5,6,12,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_url)

,category,title,body,amenities,bathrooms,bedrooms,currency,fee,has_photo,pets_allowed,...,price_display,price_type,square_feet,address,cityname,state,latitude,longitude,source,time
0,housing/rent/apartment,One BR 507 & 509 Esplanade,"This unit is located at 507 & 509 Esplanade, R...",NaN,1,1,USD,No,Thumbnail,Cats,...,2195,Monthly,542,507 509 Esplanade,Redondo Beach,CA,33.8520,-118.3759,RentLingo,1.577360e+09
1,housing/rent/apartment,Three BR 146 Lochview Drive,"This unit is located at 146 Lochview Drive, Ne...",NaN,1.5,3,USD,No,Thumbnail,"Cats,Dogs",...,1250,Monthly,1500,146 Lochview Dr,Newport News,VA,37.0867,-76.4941,RentLingo,1.577360e+09
2,housing/rent/apartment,Three BR 3101 Morningside Drive,This unit is located at 3101 Morningside Drive...,NaN,2,3,USD,No,Thumbnail,NaN,...,1395,Monthly,1650,3101 Morningside Dr,Raleigh,NC,35.8230,-78.6438,RentLingo,1.577360e+09
3,housing/rent/apartment,Two BR 209 Aegean Way,"This unit is located at 209 Aegean Way, Vacavi...",NaN,1,2,USD,No,Thumbnail,"Cats,Dogs",...,1600,Monthly,820,209 Aegean Way,Vacaville,CA,38.3622,-121.9712,RentLingo,1.577360e+09
4,housing/rent/apartment,One BR 4805 Marquette NE,"This unit is located at 4805 Marquette NE, Alb...",NaN,1,1,USD,No,Thumbnail,"Cats,Dogs",...,975,Monthly,624,4805 Marquette NE,Albuquerque,NM,35.1038,-106.6110,RentLingo,1.577360e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99821,housing/rent/apartment,Houston - superb Apartment nearby fine dining,"Redefining urban living, in southeast Houston,...","Gym,Parking,Patio/Deck,Playground,Storage,Wood...",1.0,1.0,USD,No,Yes,NaN,...,780,Monthly,605,NaN,Houston,TX,29.6151,-95.1998,RentDigs.com,1.544186e+09
99822,housing/rent/apartment,The Best of the Best in the City of Jacksonvil...,Courtney Manor Apartments offer the best of ev...,"AC,Cable or Satellite,Clubhouse,Dishwasher,Gym...",2.0,2.0,USD,No,Yes,"Cats,Dogs",...,813,Monthly,921,NaN,Jacksonville,FL,30.2254,-81.7579,RentDigs.com,1.544186e+09
99823,housing/rent/apartment,A great & large One BR apartment. Pet OK!,"Fully remodeled, new floor, kitchen cabinet, s...","Garbage Disposal,Refrigerator",1.0,1.0,USD,No,Yes,"Cats,Dogs",...,1325,Monthly,650,NaN,San Diego,CA,32.7379,-117.0914,RentDigs.com,1.544186e+09
99824,housing/rent/apartment,"The Crest offers studio, 1, 2 & Three BR homes...","Amenities include a fitness facilities, swimmi...","Gym,Pool",1.0,1.0,USD,No,Yes,"Cats,Dogs",...,931,Monthly,701,NaN,Huntersville,NC,35.4158,-80.8451,RentDigs.com,1.544186e+09
99825,housing/rent/apartment,Large Remodeled Two BR 1. Five BA Apartment Home,This is a brand new 2 Beds 1. five Bathrooms A...,"Gated,Parking,Wood Floors",1.5,2.0,USD,No,Yes,NaN,...,1595,Monthly,900,NaN,San Diego,CA,32.7379,-117.0914,RentDigs.com,1.544186e+09

Cleanup and preprocessing:

In [ ]:
apartment_rent_df["bathrooms"] = apartment_rent_df["bathrooms"].replace(
    [
        "No",
    ],
    0,
    inplace=False,
)
apartment_rent_df["bathrooms"] = apartment_rent_df["bathrooms"].replace(
    [
        "Thumbnail",
    ],
    np.nan,
    inplace=False,
)
apartment_rent_df["bathrooms"] = apartment_rent_df["bathrooms"].astype("Float64")

apartment_rent_df["bedrooms"] = apartment_rent_df["bedrooms"].replace(
    [
        "No",
    ],
    0,
    inplace=False,
)
apartment_rent_df["bedrooms"] = apartment_rent_df["bedrooms"].replace(["Thumbnail", "Cats,Dogs"], np.nan, inplace=False)
apartment_rent_df["bedrooms"] = apartment_rent_df["bedrooms"].astype("Float64").astype("Int64")

apartment_rent_df["square_feet"] = apartment_rent_df["square_feet"].replace(["NJ", "CA"], np.nan)
apartment_rent_df = apartment_rent_df.astype(
    {
        "square_feet": "Float64",
    }
).astype(
    {
        "square_feet": "Int64",
    }
)

apartment_rent_df["state"] = apartment_rent_df["state"].replace(["RentDigs.com"], np.nan)
apartment_rent_df = apartment_rent_df.astype(
    {
        "state": "object",
    }
)

cols_to_keep = [
    "category",
    "bathrooms",
    "bedrooms",
    "amenities",
    "currency",
    "fee",
    "has_photo",
    "pets_allowed",
    "price",
    "price_type",
    "square_feet",
    "cityname",
    "state",
    "source",
]
# removed: {'address', 'body', 'latitude', 'longitude', 'price_display', 'time', 'title'}
apartment_rent_new_df = apartment_rent_df[cols_to_keep]
apartment_rent_new_df

,category,bathrooms,bedrooms,amenities,currency,fee,has_photo,pets_allowed,price,price_type,square_feet,cityname,state,source
0,housing/rent/apartment,1.0,1,NaN,USD,No,Thumbnail,Cats,2195.0,Monthly,542,Redondo Beach,CA,RentLingo
1,housing/rent/apartment,1.5,3,NaN,USD,No,Thumbnail,"Cats,Dogs",1250.0,Monthly,1500,Newport News,VA,RentLingo
2,housing/rent/apartment,2.0,3,NaN,USD,No,Thumbnail,NaN,1395.0,Monthly,1650,Raleigh,NC,RentLingo
3,housing/rent/apartment,1.0,2,NaN,USD,No,Thumbnail,"Cats,Dogs",1600.0,Monthly,820,Vacaville,CA,RentLingo
4,housing/rent/apartment,1.0,1,NaN,USD,No,Thumbnail,"Cats,Dogs",975.0,Monthly,624,Albuquerque,NM,RentLingo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99821,housing/rent/apartment,1.0,1,"Gym,Parking,Patio/Deck,Playground,Storage,Wood...",USD,No,Yes,NaN,780.0,Monthly,605,Houston,TX,RentDigs.com
99822,housing/rent/apartment,2.0,2,"AC,Cable or Satellite,Clubhouse,Dishwasher,Gym...",USD,No,Yes,"Cats,Dogs",813.0,Monthly,921,Jacksonville,FL,RentDigs.com
99823,housing/rent/apartment,1.0,1,"Garbage Disposal,Refrigerator",USD,No,Yes,"Cats,Dogs",1325.0,Monthly,650,San Diego,CA,RentDigs.com
99824,housing/rent/apartment,1.0,1,"Gym,Pool",USD,No,Yes,"Cats,Dogs",931.0,Monthly,701,Huntersville,NC,RentDigs.com
99825,housing/rent/apartment,1.5,2,"Gated,Parking,Wood Floors",USD,No,Yes,NaN,1595.0,Monthly,900,San Diego,CA,RentDigs.com

In [9]:
# get_df_info_pd(apartment_rent_new_df.drop("amenities",axis=1))

### Covertype

In [ ]:
covertype_df, var_types, target_col_name, prediction_task, metadata = dataset_loader(
    name="covertype", source="uci", df_type="polars"
)
covertype_df

shape: (581_012, 55)
┌───────────┬────────┬───────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ Elevation ┆ Aspect ┆ Slope ┆ Horizontal_ ┆ … ┆ Wilderness ┆ Wilderness ┆ Wilderness ┆ Cover_Type │
│ ---       ┆ ---    ┆ ---   ┆ Distance_To ┆   ┆ _Area2     ┆ _Area3     ┆ _Area4     ┆ ---        │
│ i64       ┆ i64    ┆ i64   ┆ _Hydrolo…   ┆   ┆ ---        ┆ ---        ┆ ---        ┆ i64        │
│           ┆        ┆       ┆ ---         ┆   ┆ i64        ┆ i64        ┆ i64        ┆            │
│           ┆        ┆       ┆ i64         ┆   ┆            ┆            ┆            ┆            │
╞═══════════╪════════╪═══════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 2596      ┆ 51     ┆ 3     ┆ 258         ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 5          │
│ 2590      ┆ 56     ┆ 2     ┆ 212         ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 5          │
│ 2804      ┆ 139    ┆ 9     ┆ 268         ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 2          │
│ 2785      ┆ 155    ┆ 18    ┆ 242         ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 2          │
│ 2595      ┆ 45     ┆ 2     ┆ 153         ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 5          │
│ …         ┆ …      ┆ …     ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 2396      ┆ 153    ┆ 20    ┆ 85          ┆ … ┆ 0          ┆ 1          ┆ 0          ┆ 3          │
│ 2391      ┆ 152    ┆ 19    ┆ 67          ┆ … ┆ 0          ┆ 1          ┆ 0          ┆ 3          │
│ 2386      ┆ 159    ┆ 17    ┆ 60          ┆ … ┆ 0          ┆ 1          ┆ 0          ┆ 3          │
│ 2384      ┆ 170    ┆ 15    ┆ 60          ┆ … ┆ 0          ┆ 1          ┆ 0          ┆ 3          │
│ 2383      ┆ 165    ┆ 13    ┆ 60          ┆ … ┆ 0          ┆ 1          ┆ 0          ┆ 3          │
└───────────┴────────┴───────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [13]:
# get the number of unique values in each column:
covertype_df.select(pl.all().n_unique())

shape: (1, 55)
┌───────────┬────────┬───────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ Elevation ┆ Aspect ┆ Slope ┆ Horizontal_ ┆ … ┆ Wilderness ┆ Wilderness ┆ Wilderness ┆ Cover_Type │
│ ---       ┆ ---    ┆ ---   ┆ Distance_To ┆   ┆ _Area2     ┆ _Area3     ┆ _Area4     ┆ ---        │
│ u32       ┆ u32    ┆ u32   ┆ _Hydrolo…   ┆   ┆ ---        ┆ ---        ┆ ---        ┆ u32        │
│           ┆        ┆       ┆ ---         ┆   ┆ u32        ┆ u32        ┆ u32        ┆            │
│           ┆        ┆       ┆ u32         ┆   ┆            ┆            ┆            ┆            │
╞═══════════╪════════╪═══════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 1978      ┆ 361    ┆ 67    ┆ 551         ┆ … ┆ 2          ┆ 2          ┆ 2          ┆ 7          │
└───────────┴────────┴───────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [ ]:
catCols = [
    "Soil_Type1",
    "Soil_Type2",
    "Soil_Type3",
    "Soil_Type4",
    "Soil_Type5",
    "Soil_Type6",
    "Soil_Type7",
    "Soil_Type8",
    "Soil_Type9",
    "Soil_Type10",
    "Soil_Type11",
    "Soil_Type12",
    "Soil_Type13",
    "Soil_Type14",
    "Soil_Type15",
    "Soil_Type16",
    "Soil_Type17",
    "Soil_Type18",
    "Soil_Type19",
    "Soil_Type20",
    "Soil_Type21",
    "Soil_Type22",
    "Soil_Type23",
    "Soil_Type24",
    "Soil_Type25",
    "Soil_Type26",
    "Soil_Type27",
    "Soil_Type28",
    "Soil_Type29",
    "Soil_Type30",
    "Soil_Type31",
    "Soil_Type32",
    "Soil_Type33",
    "Soil_Type34",
    "Soil_Type35",
    "Soil_Type36",
    "Soil_Type37",
    "Soil_Type38",
    "Soil_Type39",
    "Soil_Type40",
    "Wilderness_Area2",
    "Wilderness_Area3",
    "Wilderness_Area4",
    "Cover_Type",
]

In [17]:
covertype_df = covertype_df.with_columns(pl.col(catCols).cast(pl.Utf8))

In [19]:
# get_df_info_pl(covertype_df)

In [179]:
# covertype["data"]["features"].nunique()
# covertype["data"]["features"].dtypes

### Beijing PM2.5

In [92]:
beijing, var_types, target_col_name, prediction_task, metadata = dataset_loader(
    name="beijing_pm25", source="uci", df_type="polars"
)
target_col_name = "pm2.5"

In [93]:
beijing = beijing.drop_nulls()
beijing

shape: (41_757, 12)
┌──────┬───────┬─────┬──────┬───┬────────┬─────┬─────┬───────┐
│ year ┆ month ┆ day ┆ hour ┆ … ┆ Iws    ┆ Is  ┆ Ir  ┆ pm2.5 │
│ ---  ┆ ---   ┆ --- ┆ ---  ┆   ┆ ---    ┆ --- ┆ --- ┆ ---   │
│ i64  ┆ i64   ┆ i64 ┆ i64  ┆   ┆ f64    ┆ i64 ┆ i64 ┆ f64   │
╞══════╪═══════╪═════╪══════╪═══╪════════╪═════╪═════╪═══════╡
│ 2010 ┆ 1     ┆ 2   ┆ 0    ┆ … ┆ 1.79   ┆ 0   ┆ 0   ┆ 129.0 │
│ 2010 ┆ 1     ┆ 2   ┆ 1    ┆ … ┆ 2.68   ┆ 0   ┆ 0   ┆ 148.0 │
│ 2010 ┆ 1     ┆ 2   ┆ 2    ┆ … ┆ 3.57   ┆ 0   ┆ 0   ┆ 159.0 │
│ 2010 ┆ 1     ┆ 2   ┆ 3    ┆ … ┆ 5.36   ┆ 1   ┆ 0   ┆ 181.0 │
│ 2010 ┆ 1     ┆ 2   ┆ 4    ┆ … ┆ 6.25   ┆ 2   ┆ 0   ┆ 138.0 │
│ …    ┆ …     ┆ …   ┆ …    ┆ … ┆ …      ┆ …   ┆ …   ┆ …     │
│ 2014 ┆ 12    ┆ 31  ┆ 19   ┆ … ┆ 231.97 ┆ 0   ┆ 0   ┆ 8.0   │
│ 2014 ┆ 12    ┆ 31  ┆ 20   ┆ … ┆ 237.78 ┆ 0   ┆ 0   ┆ 10.0  │
│ 2014 ┆ 12    ┆ 31  ┆ 21   ┆ … ┆ 242.7  ┆ 0   ┆ 0   ┆ 10.0  │
│ 2014 ┆ 12    ┆ 31  ┆ 22   ┆ … ┆ 246.72 ┆ 0   ┆ 0   ┆ 8.0   │
│ 2014 ┆ 12    ┆ 31  ┆ 23   ┆ … ┆ 249.85 ┆ 0   ┆ 0   ┆ 12.0  │
└──────┴───────┴─────┴──────┴───┴────────┴─────┴─────┴───────┘

In [94]:
var_types.pop("No")

'Integer'

In [95]:
intCols = [k for k, v in var_types.items() if v == "Integer"]
floatCols = [k for k, v in var_types.items() if v == "Continuous"]
catCols = [k for k, v in var_types.items() if v == "Categorical"]
numCols = intCols + floatCols
print("intCols: ", intCols)
print("floatCols: ", floatCols)
print("catCols: ", catCols)
print("numCols: ", numCols)

intCols:  ['year', 'month', 'day', 'hour', 'pm2.5', 'DEWP', 'TEMP', 'PRES', 'Is', 'Ir']
floatCols:  ['Iws']
catCols:  ['cbwd']
numCols:  ['year', 'month', 'day', 'hour', 'pm2.5', 'DEWP', 'TEMP', 'PRES', 'Is', 'Ir', 'Iws']

In [96]:
beijing = beijing.with_columns(pl.col(intCols).cast(pl.Int64))

In [97]:
tmp = get_df_info_pl(beijing)

DataFrame shape: (41757, 12)
Data types (according to dtypes):
Number of numerical columns: 11:
['year', 'month', 'day', 'hour', 'DEWP', 'TEMP', 'PRES', 'Iws', 'Is', 'Ir', 'pm2.5']
  - Integer columns: 10: ['year', 'month', 'day', 'hour', 'DEWP', 'TEMP', 'PRES', 'Is', 'Ir', 'pm2.5']
  - Float columns: 1: ['Iws']
Number of categorical columns: 1:
['cbwd']
  - Multiclass columns: 1: ['cbwd']
  - Binary columns: 0: []
  - Boolean columns: 0: []
Total categorical cardinality: 4
Total types count:
total numerical: 11 (int: 10, float: 1),
Total categorical: 1 (multi-class: 1, bin_cat: 0, bool_cat: 0):
Columns with missing values: 0

In [98]:
# Get metadata for Polars DataFrame
pl_metadata = get_pl_metadata(beijing)
# pp(pl_metadata)

# Retrieves column types from metadata
catCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "categorical"]
intCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "numerical" and v["subtype"] == "int"]
floatCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "numerical" and v["subtype"] == "float"]
binCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "categorical" and v["subtype"] == "binary"]
numCols = intCols + floatCols
print("catCols: ", catCols)
print("intCols: ", intCols)
print("floatCols: ", floatCols)
print("binCols: ", binCols)
print("numCols: ", numCols)
print("target_col: ", target_col_name)

catCols:  ['cbwd']
intCols:  ['year', 'month', 'day', 'hour', 'DEWP', 'TEMP', 'PRES', 'Is', 'Ir', 'pm2.5']
floatCols:  ['Iws']
binCols:  []
numCols:  ['year', 'month', 'day', 'hour', 'DEWP', 'TEMP', 'PRES', 'Is', 'Ir', 'pm2.5', 'Iws']
target_col:  pm2.5

In [99]:
catCols_noTarget = [j for j in catCols if j != target_col_name]
numCols_noTarget = [j for j in numCols if j != target_col_name]
print("numCols_noTarget: ", numCols_noTarget)  # catCols_noTarget

numCols_noTarget:  ['year', 'month', 'day', 'hour', 'DEWP', 'TEMP', 'PRES', 'Is', 'Ir', 'Iws']

In [100]:
beijing = beijing.select(catCols + numCols_noTarget + [target_col_name])
beijing

shape: (41_757, 12)
┌──────┬──────┬───────┬─────┬───┬─────┬─────┬────────┬───────┐
│ cbwd ┆ year ┆ month ┆ day ┆ … ┆ Is  ┆ Ir  ┆ Iws    ┆ pm2.5 │
│ ---  ┆ ---  ┆ ---   ┆ --- ┆   ┆ --- ┆ --- ┆ ---    ┆ ---   │
│ str  ┆ i64  ┆ i64   ┆ i64 ┆   ┆ i64 ┆ i64 ┆ f64    ┆ i64   │
╞══════╪══════╪═══════╪═════╪═══╪═════╪═════╪════════╪═══════╡
│ SE   ┆ 2010 ┆ 1     ┆ 2   ┆ … ┆ 0   ┆ 0   ┆ 1.79   ┆ 129   │
│ SE   ┆ 2010 ┆ 1     ┆ 2   ┆ … ┆ 0   ┆ 0   ┆ 2.68   ┆ 148   │
│ SE   ┆ 2010 ┆ 1     ┆ 2   ┆ … ┆ 0   ┆ 0   ┆ 3.57   ┆ 159   │
│ SE   ┆ 2010 ┆ 1     ┆ 2   ┆ … ┆ 1   ┆ 0   ┆ 5.36   ┆ 181   │
│ SE   ┆ 2010 ┆ 1     ┆ 2   ┆ … ┆ 2   ┆ 0   ┆ 6.25   ┆ 138   │
│ …    ┆ …    ┆ …     ┆ …   ┆ … ┆ …   ┆ …   ┆ …      ┆ …     │
│ NW   ┆ 2014 ┆ 12    ┆ 31  ┆ … ┆ 0   ┆ 0   ┆ 231.97 ┆ 8     │
│ NW   ┆ 2014 ┆ 12    ┆ 31  ┆ … ┆ 0   ┆ 0   ┆ 237.78 ┆ 10    │
│ NW   ┆ 2014 ┆ 12    ┆ 31  ┆ … ┆ 0   ┆ 0   ┆ 242.7  ┆ 10    │
│ NW   ┆ 2014 ┆ 12    ┆ 31  ┆ … ┆ 0   ┆ 0   ┆ 246.72 ┆ 8     │
│ NW   ┆ 2014 ┆ 12    ┆ 31  ┆ … ┆ 0   ┆ 0   ┆ 249.85 ┆ 12    │
└──────┴──────┴───────┴─────┴───┴─────┴─────┴────────┴───────┘

In [101]:
num_col_idx = [i for i, col in enumerate(beijing.columns) if col in numCols]
cat_col_idx = [i for i, col in enumerate(beijing.columns) if col in catCols_noTarget]
target_col_idx = beijing.columns.index(target_col_name)
cat_col_idx, num_col_idx, target_col_idx

([0], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], 11)

In [102]:
train, valid, test = pl_train_valid_test_split(beijing, splits=[0.7, 0.15, 0.15], seed=420)

print("Train shape:", train.shape, "Valid shape:", valid.shape, "Test shape:", test.shape)

Train shape: (29229, 12) Valid shape: (6264, 12) Test shape: (6264, 12)

In [103]:
#### save the datasets as parquet:
info = get_df_info_pl(beijing)

beijing_path = "/Users/leec/Documents/datasets/parquet/beijing/"
# make sure the output directory exists, and create it if it doesn't:
os.makedirs(beijing_path, exist_ok=True)

beijing_train_output_path = os.path.join(beijing_path, "beijing_train.parquet")
beijing_valid_output_path = os.path.join(beijing_path, "beijing_valid.parquet")
beijing_test_output_path = os.path.join(beijing_path, "beijing_test.parquet")

train.write_parquet(beijing_train_output_path)
valid.write_parquet(beijing_valid_output_path)
test.write_parquet(beijing_test_output_path)


# create an `info.json` file with the metadata information:
metadata = {
    "name": "beijing",
    "task_type": "regression", # binclass, multiclass, regression 
    "target_col_name": target_col_name,
    "train_size": train.shape[0],
    "val_size": valid.shape[0],
    "test_size": test.shape[0],
    "catCols": info["catCols"],
    "intCols": info["intCols"],
    "floatCols": info["floatCols"]   
}

metadata_output_path = os.path.join(beijing_path, "info.json")
with open(metadata_output_path, "w") as f:
    json.dump(metadata, f, indent=4)
    
metadata

DataFrame shape: (41757, 12)
Data types (according to dtypes):
Number of numerical columns: 11:
['year', 'month', 'day', 'hour', 'DEWP', 'TEMP', 'PRES', 'Is', 'Ir', 'Iws', 'pm2.5']
  - Integer columns: 10: ['year', 'month', 'day', 'hour', 'DEWP', 'TEMP', 'PRES', 'Is', 'Ir', 'pm2.5']
  - Float columns: 1: ['Iws']
Number of categorical columns: 1:
['cbwd']
  - Multiclass columns: 1: ['cbwd']
  - Binary columns: 0: []
  - Boolean columns: 0: []
Total categorical cardinality: 4
Total types count:
total numerical: 11 (int: 10, float: 1),
Total categorical: 1 (multi-class: 1, bin_cat: 0, bool_cat: 0):
Columns with missing values: 0

{'name': 'beijing',
 'task_type': 'regression',
 'target_col_name': 'pm2.5',
 'train_size': 29229,
 'val_size': 6264,
 'test_size': 6264,
 'catCols': ['cbwd'],
 'intCols': ['year',
  'month',
  'day',
  'hour',
  'DEWP',
  'TEMP',
  'PRES',
  'Is',
  'Ir',
  'pm2.5'],
 'floatCols': ['Iws']}

In [37]:
# save the datasets as pickle:
beijing_output_path = "/Users/leec/Documents/datasets/beijing/"
# make sure the output directory exists, and create it if it doesn't:
os.makedirs(beijing_output_path, exist_ok=True)

beijing_train_output_path = os.path.join(beijing_output_path, "beijing_train.pkl")
beijing_valid_output_path = os.path.join(beijing_output_path, "beijing_valid.pkl")
beijing_test_output_path = os.path.join(beijing_output_path, "beijing_test.pkl")

# pickle the datasets:
with open(beijing_train_output_path, "wb") as f:
    pickle.dump(train, f)
with open(beijing_valid_output_path, "wb") as f:
    pickle.dump(valid, f)
with open(beijing_test_output_path, "wb") as f:
    pickle.dump(test, f)


## also save as csv:

beijing_train_output_path = os.path.join(beijing_output_path, "beijing_train.csv")
beijing_valid_output_path = os.path.join(beijing_output_path, "beijing_valid.csv")
beijing_test_output_path = os.path.join(beijing_output_path, "beijing_test.csv")

train.write_csv(beijing_train_output_path)
valid.write_csv(beijing_valid_output_path)
test.write_csv(beijing_test_output_path)

In [ ]:
# beijing.write_parquet("/Users/leec/Documents/datasets/beijing/beijing_full.parquet")

### MAGIC GAMMA TELESCOPE

In [70]:
magic, var_types, target_col_name, prediction_task, metadata = dataset_loader(
    name="magic", source="uci", df_type="polars"
)
target_col_name = "class" # binary classification
magic

shape: (19_020, 11)
┌──────────┬─────────┬────────┬────────┬───┬──────────┬─────────┬──────────┬───────┐
│ fLength  ┆ fWidth  ┆ fSize  ┆ fConc  ┆ … ┆ fM3Trans ┆ fAlpha  ┆ fDist    ┆ class │
│ ---      ┆ ---     ┆ ---    ┆ ---    ┆   ┆ ---      ┆ ---     ┆ ---      ┆ ---   │
│ f64      ┆ f64     ┆ f64    ┆ f64    ┆   ┆ f64      ┆ f64     ┆ f64      ┆ str   │
╞══════════╪═════════╪════════╪════════╪═══╪══════════╪═════════╪══════════╪═══════╡
│ 28.7967  ┆ 16.0021 ┆ 2.6449 ┆ 0.3918 ┆ … ┆ -8.2027  ┆ 40.092  ┆ 81.8828  ┆ g     │
│ 31.6036  ┆ 11.7235 ┆ 2.5185 ┆ 0.5303 ┆ … ┆ -9.9574  ┆ 6.3609  ┆ 205.261  ┆ g     │
│ 162.052  ┆ 136.031 ┆ 4.0612 ┆ 0.0374 ┆ … ┆ -45.216  ┆ 76.96   ┆ 256.788  ┆ g     │
│ 23.8172  ┆ 9.5728  ┆ 2.3385 ┆ 0.6147 ┆ … ┆ -7.1513  ┆ 10.449  ┆ 116.737  ┆ g     │
│ 75.1362  ┆ 30.9205 ┆ 3.1611 ┆ 0.3168 ┆ … ┆ 21.8393  ┆ 4.648   ┆ 356.462  ┆ g     │
│ …        ┆ …       ┆ …      ┆ …      ┆ … ┆ …        ┆ …       ┆ …        ┆ …     │
│ 21.3846  ┆ 10.917  ┆ 2.6161 ┆ 0.5857 ┆ … ┆ 2.8766   ┆ 2.4229  ┆ 106.8258 ┆ h     │
│ 28.9452  ┆ 6.702   ┆ 2.2672 ┆ 0.5351 ┆ … ┆ -2.9632  ┆ 86.7975 ┆ 247.456  ┆ h     │
│ 75.4455  ┆ 47.5305 ┆ 3.4483 ┆ 0.1417 ┆ … ┆ -9.4662  ┆ 30.2987 ┆ 256.5166 ┆ h     │
│ 120.5135 ┆ 76.9018 ┆ 3.9939 ┆ 0.0944 ┆ … ┆ -63.8389 ┆ 84.6874 ┆ 408.3166 ┆ h     │
│ 187.1814 ┆ 53.0014 ┆ 3.2093 ┆ 0.2876 ┆ … ┆ 31.4755  ┆ 52.731  ┆ 272.3174 ┆ h     │
└──────────┴─────────┴────────┴────────┴───┴──────────┴─────────┴──────────┴───────┘

In [71]:
# Get metadata for Polars DataFrame
pl_metadata = get_pl_metadata(magic)
# pp(pl_metadata)

# Retrieves column types from metadata
catCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "categorical"]
intCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "numerical" and v["subtype"] == "int"]
floatCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "numerical" and v["subtype"] == "float"]
binCols = [(k) for k, v in pl_metadata["fields"].items() if v["type"] == "categorical" and v["subtype"] == "binary"]
numCols = intCols + floatCols
print("catCols: ", catCols)
print("intCols: ", intCols)
print("floatCols: ", floatCols)
print("binCols: ", binCols)
print("numCols: ", numCols)
print("target_col: ", target_col_name)

catCols:  ['class']
intCols:  []
floatCols:  ['fLength', 'fWidth', 'fSize', 'fConc', 'fConc1', 'fAsym', 'fM3Long', 'fM3Trans', 'fAlpha', 'fDist']
binCols:  ['class']
numCols:  ['fLength', 'fWidth', 'fSize', 'fConc', 'fConc1', 'fAsym', 'fM3Long', 'fM3Trans', 'fAlpha', 'fDist']
target_col:  class

In [72]:
catCols_noTarget = [j for j in catCols if j != target_col_name]
# numCols_noTarget = [j for j in numCols if j != target_col_name]
print("catCols_noTarget: ", catCols_noTarget)  # catCols_noTarget

catCols_noTarget:  []

In [73]:
magic = magic.select( numCols + [target_col_name])
magic

shape: (19_020, 11)
┌──────────┬─────────┬────────┬────────┬───┬──────────┬─────────┬──────────┬───────┐
│ fLength  ┆ fWidth  ┆ fSize  ┆ fConc  ┆ … ┆ fM3Trans ┆ fAlpha  ┆ fDist    ┆ class │
│ ---      ┆ ---     ┆ ---    ┆ ---    ┆   ┆ ---      ┆ ---     ┆ ---      ┆ ---   │
│ f64      ┆ f64     ┆ f64    ┆ f64    ┆   ┆ f64      ┆ f64     ┆ f64      ┆ str   │
╞══════════╪═════════╪════════╪════════╪═══╪══════════╪═════════╪══════════╪═══════╡
│ 28.7967  ┆ 16.0021 ┆ 2.6449 ┆ 0.3918 ┆ … ┆ -8.2027  ┆ 40.092  ┆ 81.8828  ┆ g     │
│ 31.6036  ┆ 11.7235 ┆ 2.5185 ┆ 0.5303 ┆ … ┆ -9.9574  ┆ 6.3609  ┆ 205.261  ┆ g     │
│ 162.052  ┆ 136.031 ┆ 4.0612 ┆ 0.0374 ┆ … ┆ -45.216  ┆ 76.96   ┆ 256.788  ┆ g     │
│ 23.8172  ┆ 9.5728  ┆ 2.3385 ┆ 0.6147 ┆ … ┆ -7.1513  ┆ 10.449  ┆ 116.737  ┆ g     │
│ 75.1362  ┆ 30.9205 ┆ 3.1611 ┆ 0.3168 ┆ … ┆ 21.8393  ┆ 4.648   ┆ 356.462  ┆ g     │
│ …        ┆ …       ┆ …      ┆ …      ┆ … ┆ …        ┆ …       ┆ …        ┆ …     │
│ 21.3846  ┆ 10.917  ┆ 2.6161 ┆ 0.5857 ┆ … ┆ 2.8766   ┆ 2.4229  ┆ 106.8258 ┆ h     │
│ 28.9452  ┆ 6.702   ┆ 2.2672 ┆ 0.5351 ┆ … ┆ -2.9632  ┆ 86.7975 ┆ 247.456  ┆ h     │
│ 75.4455  ┆ 47.5305 ┆ 3.4483 ┆ 0.1417 ┆ … ┆ -9.4662  ┆ 30.2987 ┆ 256.5166 ┆ h     │
│ 120.5135 ┆ 76.9018 ┆ 3.9939 ┆ 0.0944 ┆ … ┆ -63.8389 ┆ 84.6874 ┆ 408.3166 ┆ h     │
│ 187.1814 ┆ 53.0014 ┆ 3.2093 ┆ 0.2876 ┆ … ┆ 31.4755  ┆ 52.731  ┆ 272.3174 ┆ h     │
└──────────┴─────────┴────────┴────────┴───┴──────────┴─────────┴──────────┴───────┘

In [74]:
num_col_idx = [i for i, col in enumerate(magic.columns) if col in numCols]
cat_col_idx = [i for i, col in enumerate(magic.columns) if col in catCols_noTarget]
target_col_idx = magic.columns.index(target_col_name)
cat_col_idx, num_col_idx, target_col_idx

([], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 10)

In [75]:
train, valid, test = pl_train_valid_test_split(magic, splits=[0.7, 0.15, 0.15], seed=420)

print("Train shape:", train.shape, "Valid shape:", valid.shape, "Test shape:", test.shape)

Train shape: (13314, 11) Valid shape: (2853, 11) Test shape: (2853, 11)

In [76]:
#### save the datasets as parquet:
info = get_df_info_pl(magic)

magic_output_path = "/Users/leec/Documents/datasets/parquet/magic/"
# make sure the output directory exists, and create it if it doesn't:
os.makedirs(magic_output_path, exist_ok=True)

magic_train_output_path = os.path.join(magic_output_path, "magic_train.parquet")
magic_valid_output_path = os.path.join(magic_output_path, "magic_valid.parquet")
magic_test_output_path = os.path.join(magic_output_path, "magic_test.parquet")

train.write_parquet(magic_train_output_path)
valid.write_parquet(magic_valid_output_path)
test.write_parquet(magic_test_output_path)


# create an `info.json` file with the metadata information:
metadata = {
    "name": "magic",
    "task_type": "binclass", # binclass, multiclass, regression 
    "target_col_name": target_col_name,
    "train_size": train.shape[0],
    "val_size": valid.shape[0],
    "test_size": test.shape[0],
    "catCols": info["catCols"],
    "intCols": info["intCols"],
    "floatCols": info["floatCols"]   
}

metadata_output_path = os.path.join(magic_output_path, "info.json")
with open(metadata_output_path, "w") as f:
    json.dump(metadata, f, indent=4)
    
metadata

DataFrame shape: (19020, 11)
Data types (according to dtypes):
Number of numerical columns: 10:
['fLength', 'fWidth', 'fSize', 'fConc', 'fConc1', 'fAsym', 'fM3Long', 'fM3Trans', 'fAlpha', 'fDist']
  - Integer columns: 0: []
  - Float columns: 10: ['fLength', 'fWidth', 'fSize', 'fConc', 'fConc1', 'fAsym', 'fM3Long', 'fM3Trans', 'fAlpha', 'fDist']
Number of categorical columns: 1:
['class']
  - Multiclass columns: 0: []
  - Binary columns: 1: ['class']
  - Boolean columns: 0: []
Total categorical cardinality: 2
Total types count:
total numerical: 10 (int: 0, float: 10),
Total categorical: 1 (multi-class: 0, bin_cat: 1, bool_cat: 0):
Columns with missing values: 0

{'name': 'magic',
 'task_type': 'binclass',
 'target_col_name': 'class',
 'train_size': 13314,
 'val_size': 2853,
 'test_size': 2853,
 'catCols': ['class'],
 'intCols': [],
 'floatCols': ['fLength',
  'fWidth',
  'fSize',
  'fConc',
  'fConc1',
  'fAsym',
  'fM3Long',
  'fM3Trans',
  'fAlpha',
  'fDist']}

In [13]:
# save the datasets as pickle:
magic_output_path = "/Users/leec/Documents/datasets/magic/"
# make sure the output directory exists, and create it if it doesn't:
os.makedirs(magic_output_path, exist_ok=True)

magic_train_output_path = os.path.join(magic_output_path, "magic_train.pkl")
magic_valid_output_path = os.path.join(magic_output_path, "magic_valid.pkl")
magic_test_output_path = os.path.join(magic_output_path, "magic_test.pkl")

# pickle the datasets:
with open(magic_train_output_path, "wb") as f:
    pickle.dump(train, f)
with open(magic_valid_output_path, "wb") as f:
    pickle.dump(valid, f)
with open(magic_test_output_path, "wb") as f:
    pickle.dump(test, f)


## also save as csv:

magic_train_output_path = os.path.join(magic_output_path, "magic_train.csv")
magic_valid_output_path = os.path.join(magic_output_path, "magic_valid.csv")
magic_test_output_path = os.path.join(magic_output_path, "magic_test.csv")

train.write_csv(magic_train_output_path)
valid.write_csv(magic_valid_output_path)
test.write_csv(magic_test_output_path)

In [ ]:
# magic.write_parquet("/Users/leec/Documents/datasets/magic/magic_full.parquet")

## C'est fini